var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);function da(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}
function p(a){if(!(a instanceof Array)){a=da(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function q(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at
 http://polymer.github.io/LICENSE.txt The complete set of authors may be found
 at http://polymer.github.io/AUTHORS.txt The complete set of contributors may
 be found at http://polymer.github.io/CONTRIBUTORS.txt Code distributed by
 Google as part of the polymer project is also subject to an additional IP
 rights grant found at http://polymer.github.io/PATENTS.txt
*/
var ea=window.Document.prototype.createElement,fa=window.Document.prototype.createElementNS,ha=window.Document.prototype.importNode,ia=window.Document.prototype.prepend,ja=window.Document.prototype.append,ka=window.DocumentFragment.prototype.prepend,la=window.DocumentFragment.prototype.append,ma=window.Node.prototype.cloneNode,na=window.Node.prototype.appendChild,pa=window.Node.prototype.insertBefore,qa=window.Node.prototype.removeChild,ra=window.Node.prototype.replaceChild,sa=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),ta=window.Element.prototype.attachShadow,ua=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),va=window.Element.prototype.getAttribute,wa=window.Element.prototype.setAttribute,xa=window.Element.prototype.removeAttribute,ya=window.Element.prototype.getAttributeNS,za=window.Element.prototype.setAttributeNS,Aa=window.Element.prototype.removeAttributeNS,Ba=window.Element.prototype.insertAdjacentElement,Ca=window.Element.prototype.insertAdjacentHTML,Da=window.Element.prototype.prepend,
Ea=window.Element.prototype.append,Fa=window.Element.prototype.before,Ga=window.Element.prototype.after,Ha=window.Element.prototype.replaceWith,Ia=window.Element.prototype.remove,Ja=window.HTMLElement,Ka=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),La=window.HTMLElement.prototype.insertAdjacentElement,Ma=window.HTMLElement.prototype.insertAdjacentHTML;var Na=function(){var a=new Set;"annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" ").forEach(function(b){return a.add(b)});return a}();function Oa(a){var b=Na.has(a);a=/^[a-z][.0-9_a-z]*-[-.0-9_a-z]*$/.test(a);return!b&&a}var Pa=document.contains?document.contains.bind(document):document.documentElement.contains.bind(document.documentElement);
function r(a){var b=a.isConnected;if(void 0!==b)return b;if(Pa(a))return!0;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}function Qa(a){var b=a.children;if(b)return Array.prototype.slice.call(b);b=[];for(a=a.firstChild;a;a=a.nextSibling)a.nodeType===Node.ELEMENT_NODE&&b.push(a);return b}
function Ra(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function Sa(a,b,c){for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;void 0===c&&(c=new Set);if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)Sa(d,b,c);d=Ra(a,e);continue}else if("template"===f){d=Ra(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)Sa(e,b,c)}d=d.firstChild?d.firstChild:Ra(a,d)}};function Ta(){var a=!(null===u||void 0===u||!u.noDocumentConstructionObserver),b=!(null===u||void 0===u||!u.shadyDomFastWalk);this.S=[];this.ra=[];this.K=!1;this.shadyDomFastWalk=b;this.sc=!a}function Ua(a,b,c,d){var e=window.ShadyDOM;if(a.shadyDomFastWalk&&e&&e.inUse){if(b.nodeType===Node.ELEMENT_NODE&&c(b),b.querySelectorAll)for(a=e.nativeMethods.querySelectorAll.call(b,"*"),b=0;b<a.length;b++)c(a[b])}else Sa(b,c,d)}function Va(a,b){a.K=!0;a.S.push(b)}function Wa(a,b){a.K=!0;a.ra.push(b)}
function Xa(a,b){a.K&&Ua(a,b,function(c){return v(a,c)})}function v(a,b){if(a.K&&!b.__CE_patched){b.__CE_patched=!0;for(var c=0;c<a.S.length;c++)a.S[c](b);for(c=0;c<a.ra.length;c++)a.ra[c](b)}}function w(a,b){var c=[];Ua(a,b,function(e){return c.push(e)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):Ya(a,d)}}function x(a,b){var c=[];Ua(a,b,function(e){return c.push(e)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function y(a,b,c){c=void 0===c?{}:c;var d=c.tc,e=c.upgrade||function(g){return Ya(a,g)},f=[];Ua(a,b,function(g){a.K&&v(a,g);if("link"===g.localName&&"import"===g.getAttribute("rel")){var h=g.import;h instanceof Node&&(h.__CE_isImportDocument=!0,h.__CE_registry=document.__CE_registry);h&&"complete"===h.readyState?h.__CE_documentLoadHandled=!0:g.addEventListener("load",function(){var k=g.import;if(!k.__CE_documentLoadHandled){k.__CE_documentLoadHandled=!0;var m=new Set;d&&(d.forEach(function(n){return m.add(n)}),
m.delete(k));y(a,k,{tc:m,upgrade:e})}})}else f.push(g)},d);for(b=0;b<f.length;b++)e(f[b])}function Ya(a,b){try{var c=a.Eb(b.ownerDocument,b.localName);c&&a.Zb(b,c)}catch(d){z(d)}}l=Ta.prototype;
l.Zb=function(a,b){if(void 0===a.__CE_state){b.constructionStack.push(a);try{try{if(new b.constructorFunction!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback&&a.hasAttributes()){b=b.observedAttributes;for(var c=0;c<b.length;c++){var d=b[c],e=a.getAttribute(d);null!==e&&this.attributeChangedCallback(a,d,null,e,null)}}r(a)&&
this.connectedCallback(a)}};l.connectedCallback=function(a){var b=a.__CE_definition;if(b.connectedCallback)try{b.connectedCallback.call(a)}catch(c){z(c)}};l.disconnectedCallback=function(a){var b=a.__CE_definition;if(b.disconnectedCallback)try{b.disconnectedCallback.call(a)}catch(c){z(c)}};l.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;if(f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b))try{f.attributeChangedCallback.call(a,b,c,d,e)}catch(g){z(g)}};
l.Eb=function(a,b){var c=a.__CE_registry;if(c&&(a.defaultView||a.__CE_isImportDocument))return Za(c,b)};
function $a(a,b,c,d){var e=b.__CE_registry;if(e&&(null===d||"http://www.w3.org/1999/xhtml"===d)&&(e=Za(e,c)))try{var f=new e.constructorFunction;if(void 0===f.__CE_state||void 0===f.__CE_definition)throw Error("Failed to construct '"+c+"': The returned value was not constructed with the HTMLElement constructor.");if("http://www.w3.org/1999/xhtml"!==f.namespaceURI)throw Error("Failed to construct '"+c+"': The constructed element's namespace must be the HTML namespace.");if(f.hasAttributes())throw Error("Failed to construct '"+
c+"': The constructed element must not have any attributes.");if(null!==f.firstChild)throw Error("Failed to construct '"+c+"': The constructed element must not have any children.");if(null!==f.parentNode)throw Error("Failed to construct '"+c+"': The constructed element must not have a parent node.");if(f.ownerDocument!==b)throw Error("Failed to construct '"+c+"': The constructed element's owner document is incorrect.");if(f.localName!==c)throw Error("Failed to construct '"+c+"': The constructed element's local name is incorrect.");
return f}catch(g){return z(g),b=null===d?ea.call(b,c):fa.call(b,d,c),Object.setPrototypeOf(b,HTMLUnknownElement.prototype),b.__CE_state=2,b.__CE_definition=void 0,v(a,b),b}b=null===d?ea.call(b,c):fa.call(b,d,c);v(a,b);return b}
function z(a){var b=a.message,c=a.sourceURL||a.fileName||"",d=a.line||a.lineNumber||0,e=a.column||a.columnNumber||0,f=void 0;void 0===ErrorEvent.prototype.initErrorEvent?f=new ErrorEvent("error",{cancelable:!0,message:b,filename:c,lineno:d,colno:e,error:a}):(f=document.createEvent("ErrorEvent"),f.initErrorEvent("error",!1,!0,b,c,d),f.preventDefault=function(){Object.defineProperty(this,"defaultPrevented",{configurable:!0,get:function(){return!0}})});void 0===f.error&&Object.defineProperty(f,"error",
{configurable:!0,enumerable:!0,get:function(){return a}});window.dispatchEvent(f);f.defaultPrevented||console.error(a)};function ab(){var a=this;this.Xa=void 0;this.Qa=new Promise(function(b){a.Ob=b})}ab.prototype.resolve=function(a){if(this.Xa)throw Error("Already resolved.");this.Xa=a;this.Ob(a)};function bb(a){var b=document;this.L=void 0;this.D=a;this.Z=b;y(this.D,this.Z);"loading"===this.Z.readyState&&(this.L=new MutationObserver(this.Ab.bind(this)),this.L.observe(this.Z,{childList:!0,subtree:!0}))}bb.prototype.disconnect=function(){this.L&&this.L.disconnect()};bb.prototype.Ab=function(a){var b=this.Z.readyState;"interactive"!==b&&"complete"!==b||this.disconnect();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)y(this.D,c[d])};function A(a){this.ba=new Map;this.ca=new Map;this.Ea=new Map;this.oa=!1;this.wa=new Map;this.aa=function(b){return b()};this.J=!1;this.ga=[];this.D=a;this.Ga=a.sc?new bb(a):void 0}l=A.prototype;l.jc=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructor getters must be functions.");cb(this,a);this.ba.set(a,b);this.ga.push(a);this.J||(this.J=!0,this.aa(function(){return c.Ia()}))};
l.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");cb(this,a);db(this,a,b);this.ga.push(a);this.J||(this.J=!0,this.aa(function(){return c.Ia()}))};function cb(a,b){if(!Oa(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(Za(a,b))throw Error("A custom element with name '"+(b+"' has already been defined."));if(a.oa)throw Error("A custom element is already being defined.");}
function db(a,b,c){a.oa=!0;var d;try{var e=c.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=function(n){var t=e[n];if(void 0!==t&&!(t instanceof Function))throw Error("The '"+n+"' callback must be a function.");return t};var g=f("connectedCallback");var h=f("disconnectedCallback");var k=f("adoptedCallback");var m=(d=f("attributeChangedCallback"))&&c.observedAttributes||[]}catch(n){throw n;}finally{a.oa=!1}c={localName:b,
constructorFunction:c,connectedCallback:g,disconnectedCallback:h,adoptedCallback:k,attributeChangedCallback:d,observedAttributes:m,constructionStack:[]};a.ca.set(b,c);a.Ea.set(c.constructorFunction,c);return c}l.upgrade=function(a){y(this.D,a)};
l.Ia=function(){var a=this;if(!1!==this.J){this.J=!1;for(var b=[],c=this.ga,d=new Map,e=0;e<c.length;e++)d.set(c[e],[]);y(this.D,document,{upgrade:function(k){if(void 0===k.__CE_state){var m=k.localName,n=d.get(m);n?n.push(k):a.ca.has(m)&&b.push(k)}}});for(e=0;e<b.length;e++)Ya(this.D,b[e]);for(e=0;e<c.length;e++){for(var f=c[e],g=d.get(f),h=0;h<g.length;h++)Ya(this.D,g[h]);(f=this.wa.get(f))&&f.resolve(void 0)}c.length=0}};l.get=function(a){if(a=Za(this,a))return a.constructorFunction};
l.whenDefined=function(a){if(!Oa(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.wa.get(a);if(b)return b.Qa;b=new ab;this.wa.set(a,b);var c=this.ca.has(a)||this.ba.has(a);a=-1===this.ga.indexOf(a);c&&a&&b.resolve(void 0);return b.Qa};l.polyfillWrapFlushCallback=function(a){this.Ga&&this.Ga.disconnect();var b=this.aa;this.aa=function(c){return a(function(){return b(c)})}};
function Za(a,b){var c=a.ca.get(b);if(c)return c;if(c=a.ba.get(b)){a.ba.delete(b);try{return db(a,b,c())}catch(d){z(d)}}}window.CustomElementRegistry=A;A.prototype.define=A.prototype.define;A.prototype.upgrade=A.prototype.upgrade;A.prototype.get=A.prototype.get;A.prototype.whenDefined=A.prototype.whenDefined;A.prototype.polyfillDefineLazy=A.prototype.jc;A.prototype.polyfillWrapFlushCallback=A.prototype.polyfillWrapFlushCallback;function eb(a,b,c){function d(e){return function(){for(var f=q.apply(0,arguments),g=[],h=[],k=0;k<f.length;k++){var m=f[k];m instanceof Element&&r(m)&&h.push(m);if(m instanceof DocumentFragment)for(m=m.firstChild;m;m=m.nextSibling)g.push(m);else g.push(m)}e.apply(this,f);for(f=0;f<h.length;f++)x(a,h[f]);if(r(this))for(h=0;h<g.length;h++)f=g[h],f instanceof Element&&w(a,f)}}void 0!==c.prepend&&(b.prepend=d(c.prepend));void 0!==c.append&&(b.append=d(c.append))};function fb(a){Document.prototype.createElement=function(b){return $a(a,this,b,null)};Document.prototype.importNode=function(b,c){b=ha.call(this,b,!!c);this.__CE_registry?y(a,b):Xa(a,b);return b};Document.prototype.createElementNS=function(b,c){return $a(a,this,c,b)};eb(a,Document.prototype,{prepend:ia,append:ja})};function gb(a){function b(d){return function(){for(var e=q.apply(0,arguments),f=[],g=[],h=0;h<e.length;h++){var k=e[h];k instanceof Element&&r(k)&&g.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)f.push(k);else f.push(k)}d.apply(this,e);for(e=0;e<g.length;e++)x(a,g[e]);if(r(this))for(g=0;g<f.length;g++)e=f[g],e instanceof Element&&w(a,e)}}var c=Element.prototype;void 0!==Fa&&(c.before=b(Fa));void 0!==Ga&&(c.after=b(Ga));void 0!==Ha&&(c.replaceWith=function(){for(var d=
q.apply(0,arguments),e=[],f=[],g=0;g<d.length;g++){var h=d[g];h instanceof Element&&r(h)&&f.push(h);if(h instanceof DocumentFragment)for(h=h.firstChild;h;h=h.nextSibling)e.push(h);else e.push(h)}g=r(this);Ha.apply(this,d);for(d=0;d<f.length;d++)x(a,f[d]);if(g)for(x(a,this),f=0;f<e.length;f++)d=e[f],d instanceof Element&&w(a,d)});void 0!==Ia&&(c.remove=function(){var d=r(this);Ia.call(this);d&&x(a,this)})};function hb(a){function b(e,f){Object.defineProperty(e,"innerHTML",{enumerable:f.enumerable,configurable:!0,get:f.get,set:function(g){var h=this,k=void 0;r(this)&&(k=[],Ua(a,this,function(t){t!==h&&k.push(t)}));f.set.call(this,g);if(k)for(var m=0;m<k.length;m++){var n=k[m];1===n.__CE_state&&a.disconnectedCallback(n)}this.ownerDocument.__CE_registry?y(a,this):Xa(a,this);return g}})}function c(e,f){e.insertAdjacentElement=function(g,h){var k=r(h);g=f.call(this,g,h);k&&x(a,h);r(g)&&w(a,h);return g}}
function d(e,f){function g(h,k){for(var m=[];h!==k;h=h.nextSibling)m.push(h);for(k=0;k<m.length;k++)y(a,m[k])}e.insertAdjacentHTML=function(h,k){h=h.toLowerCase();if("beforebegin"===h){var m=this.previousSibling;f.call(this,h,k);g(m||this.parentNode.firstChild,this)}else if("afterbegin"===h)m=this.firstChild,f.call(this,h,k),g(this.firstChild,m);else if("beforeend"===h)m=this.lastChild,f.call(this,h,k),g(m||this.firstChild,null);else if("afterend"===h)m=this.nextSibling,f.call(this,h,k),g(this.nextSibling,
m);else throw new SyntaxError("The value provided ("+String(h)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");}}ta&&(Element.prototype.attachShadow=function(e){e=ta.call(this,e);if(a.K&&!e.__CE_patched){e.__CE_patched=!0;for(var f=0;f<a.S.length;f++)a.S[f](e)}return this.__CE_shadowRoot=e});ua&&ua.get?b(Element.prototype,ua):Ka&&Ka.get?b(HTMLElement.prototype,Ka):Wa(a,function(e){b(e,{enumerable:!0,configurable:!0,get:function(){return ma.call(this,!0).innerHTML},set:function(f){var g=
"template"===this.localName,h=g?this.content:this,k=fa.call(document,this.namespaceURI,this.localName);for(k.innerHTML=f;0<h.childNodes.length;)qa.call(h,h.childNodes[0]);for(f=g?k.content:k;0<f.childNodes.length;)na.call(h,f.childNodes[0])}})});Element.prototype.setAttribute=function(e,f){if(1!==this.__CE_state)return wa.call(this,e,f);var g=va.call(this,e);wa.call(this,e,f);f=va.call(this,e);a.attributeChangedCallback(this,e,g,f,null)};Element.prototype.setAttributeNS=function(e,f,g){if(1!==this.__CE_state)return za.call(this,
e,f,g);var h=ya.call(this,e,f);za.call(this,e,f,g);g=ya.call(this,e,f);a.attributeChangedCallback(this,f,h,g,e)};Element.prototype.removeAttribute=function(e){if(1!==this.__CE_state)return xa.call(this,e);var f=va.call(this,e);xa.call(this,e);null!==f&&a.attributeChangedCallback(this,e,f,null,null)};Element.prototype.removeAttributeNS=function(e,f){if(1!==this.__CE_state)return Aa.call(this,e,f);var g=ya.call(this,e,f);Aa.call(this,e,f);var h=ya.call(this,e,f);g!==h&&a.attributeChangedCallback(this,
f,g,h,e)};La?c(HTMLElement.prototype,La):Ba&&c(Element.prototype,Ba);Ma?d(HTMLElement.prototype,Ma):Ca&&d(Element.prototype,Ca);eb(a,Element.prototype,{prepend:Da,append:Ea});gb(a)};var ib={};function jb(a){function b(){var c=this.constructor;var d=document.__CE_registry.Ea.get(c);if(!d)throw Error("Failed to construct a custom element: The constructor was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=ea.call(document,d.localName),Object.setPrototypeOf(e,c.prototype),e.__CE_state=1,e.__CE_definition=d,v(a,e),e;var f=e.length-1,g=e[f];if(g===ib)throw Error("Failed to construct '"+d.localName+"': This element was already constructed.");e[f]=ib;
Object.setPrototypeOf(g,c.prototype);v(a,g);return g}b.prototype=Ja.prototype;Object.defineProperty(HTMLElement.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});window.HTMLElement=b};function kb(a){function b(c,d){Object.defineProperty(c,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(e){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,e);else{var f=void 0;if(this.firstChild){var g=this.childNodes,h=g.length;if(0<h&&r(this)){f=Array(h);for(var k=0;k<h;k++)f[k]=g[k]}}d.set.call(this,e);if(f)for(e=0;e<f.length;e++)x(a,f[e])}}})}Node.prototype.insertBefore=function(c,d){if(c instanceof DocumentFragment){var e=Qa(c);c=pa.call(this,c,d);if(r(this))for(d=
0;d<e.length;d++)w(a,e[d]);return c}e=c instanceof Element&&r(c);d=pa.call(this,c,d);e&&x(a,c);r(this)&&w(a,c);return d};Node.prototype.appendChild=function(c){if(c instanceof DocumentFragment){var d=Qa(c);c=na.call(this,c);if(r(this))for(var e=0;e<d.length;e++)w(a,d[e]);return c}d=c instanceof Element&&r(c);e=na.call(this,c);d&&x(a,c);r(this)&&w(a,c);return e};Node.prototype.cloneNode=function(c){c=ma.call(this,!!c);this.ownerDocument.__CE_registry?y(a,c):Xa(a,c);return c};Node.prototype.removeChild=
function(c){var d=c instanceof Element&&r(c),e=qa.call(this,c);d&&x(a,c);return e};Node.prototype.replaceChild=function(c,d){if(c instanceof DocumentFragment){var e=Qa(c);c=ra.call(this,c,d);if(r(this))for(x(a,d),d=0;d<e.length;d++)w(a,e[d]);return c}e=c instanceof Element&&r(c);var f=ra.call(this,c,d),g=r(this);g&&x(a,d);e&&x(a,c);g&&w(a,c);return f};sa&&sa.get?b(Node.prototype,sa):Va(a,function(c){b(c,{enumerable:!0,configurable:!0,get:function(){for(var d=[],e=this.firstChild;e;e=e.nextSibling)e.nodeType!==
Node.COMMENT_NODE&&d.push(e.textContent);return d.join("")},set:function(d){for(;this.firstChild;)qa.call(this,this.firstChild);null!=d&&""!==d&&na.call(this,document.createTextNode(d))}})})};var u=window.customElements;function lb(){var a=new Ta;jb(a);fb(a);eb(a,DocumentFragment.prototype,{prepend:ka,append:la});kb(a);hb(a);a=new A(a);document.__CE_registry=a;Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:a})}u&&!u.forcePolyfill&&"function"==typeof u.define&&"function"==typeof u.get||lb();window.__CE_installPolyfill=lb;/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function mb(){}mb.prototype.toJSON=function(){return{}};function B(a){a.__shady||(a.__shady=new mb);return a.__shady}function D(a){return a&&a.__shady};var E=window.ShadyDOM||{};E.dc=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var nb=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");E.j=!!(nb&&nb.configurable&&nb.get);E.inUse=E.force||!E.dc;E.noPatch=E.noPatch||!1;E.U=E.preferPerformance;E.za="on-demand"===E.noPatch;var ob=navigator.userAgent.match("Trident");E.cb=ob;function pb(){return Document.prototype.msElementsFromPoint?"msElementsFromPoint":"elementsFromPoint"}
function F(a){return(a=D(a))&&void 0!==a.firstChild}function G(a){return a instanceof ShadowRoot}function qb(a){return(a=(a=D(a))&&a.root)&&a.Ja()}var H=Element.prototype,rb=H.matches||H.matchesSelector||H.mozMatchesSelector||H.msMatchesSelector||H.oMatchesSelector||H.webkitMatchesSelector,sb=document.createTextNode(""),tb=0,ub=[];(new MutationObserver(function(){for(;ub.length;)try{ub.shift()()}catch(a){throw sb.textContent=tb++,a;}})).observe(sb,{characterData:!0});
function vb(a){ub.push(a);sb.textContent=tb++}var wb=document.contains?function(a,b){return a.__shady_native_contains(b)}:function(a,b){return a===b||a.documentElement&&a.documentElement.__shady_native_contains(b)};function xb(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function yb(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=da(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}function zb(a){var b=[];for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)b.push(a);return b}
function Ab(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b.push(a);return b}function Bb(a,b,c){c.configurable=!0;if(c.value)a[b]=c.value;else try{Object.defineProperty(a,b,c)}catch(d){}}function I(a,b,c,d){c=void 0===c?"":c;for(var e in b)d&&0<=d.indexOf(e)||Bb(a,c+e,b[e])}function Cb(a,b){for(var c in b)c in a&&Bb(a,c,b[c])}function J(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b}
function Db(a,b){for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length;d++)e=c[d],a[e]=b[e]}function Eb(a){return a instanceof Node?a:document.createTextNode(""+a)}function K(){var a=q.apply(0,arguments);if(1===a.length)return Eb(a[0]);var b=document.createDocumentFragment();a=da(a);for(var c=a.next();!c.done;c=a.next())b.appendChild(Eb(c.value));return b};var Fb=[],Gb;function Hb(a){Gb||(Gb=!0,vb(Ib));Fb.push(a)}function Ib(){Gb=!1;for(var a=!!Fb.length;Fb.length;)Fb.shift()();return a}Ib.list=Fb;function Jb(){this.ea=!1;this.addedNodes=[];this.removedNodes=[];this.ja=new Set}function Kb(a){a.ea||(a.ea=!0,vb(function(){a.flush()}))}Jb.prototype.flush=function(){if(this.ea){this.ea=!1;var a=this.takeRecords();a.length&&this.ja.forEach(function(b){b(a)})}};Jb.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Lb(a,b){var c=B(a);c.T||(c.T=new Jb);c.T.ja.add(b);var d=c.T;return{kb:b,L:d,Hb:a,takeRecords:function(){return d.takeRecords()}}}function Mb(a){var b=a&&a.L;b&&(b.ja.delete(a.kb),b.ja.size||(B(a.Hb).T=null))}
function Nb(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=[].slice.call(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Ob=/[&\u00A0"]/g,Pb=/[&\u00A0<>]/g;function Qb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Rb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Sb=Rb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Tb=Rb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ub(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var k=a,m=b;switch(h.nodeType){case Node.ELEMENT_NODE:k=h.localName;for(var n="<"+k,t=h.attributes,C=0,oa;oa=t[C];C++)n+=" "+oa.name+'="'+oa.value.replace(Ob,Qb)+'"';n+=">";h=Sb[k]?n:n+Ub(h,m)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&Tb[k.localName]?h:h.replace(Pb,Qb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var Vb=E.j,Wb={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},Xb={};function Yb(a){Xb[a]=function(b){return b["__shady_native_"+a]}}function Zb(a,b){I(a,b,"__shady_native_");for(var c in b)Yb(c)}function L(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Wb[d]||(Wb[d]=e.value):Yb(d))}}
var M=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),N=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),$b=document.implementation.createHTMLDocument("inert");function ac(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var bc=["firstElementChild","lastElementChild","children","childElementCount"],cc=["querySelector","querySelectorAll","append","prepend","replaceChildren"];
function dc(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?(L(window.EventTarget.prototype,a),void 0===window.__shady_native_addEventListener&&L(Window.prototype,a)):(L(Node.prototype,a),L(Window.prototype,a));Vb?L(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Zb(Node.prototype,{parentNode:{get:function(){M.currentNode=this;return M.parentNode()}},firstChild:{get:function(){M.currentNode=
this;return M.firstChild()}},lastChild:{get:function(){M.currentNode=this;return M.lastChild()}},previousSibling:{get:function(){M.currentNode=this;return M.previousSibling()}},nextSibling:{get:function(){M.currentNode=this;return M.nextSibling()}},childNodes:{get:function(){var b=[];M.currentNode=this;for(var c=M.firstChild();c;)b.push(c),c=M.nextSibling();return b}},parentElement:{get:function(){N.currentNode=this;return N.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=
document.createTreeWalker(this,NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:ac(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});L(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
L(HTMLElement.prototype,["parentElement","contains"]);a={firstElementChild:{get:function(){N.currentNode=this;return N.firstChild()}},lastElementChild:{get:function(){N.currentNode=this;return N.lastChild()}},children:{get:function(){var b=[];N.currentNode=this;for(var c=N.firstChild();c;)b.push(c),c=N.nextSibling();return yb(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Vb?(L(Element.prototype,bc),L(Element.prototype,["previousElementSibling","nextElementSibling",
"innerHTML","className"]),L(HTMLElement.prototype,["children","innerHTML","className"])):(Zb(Element.prototype,a),Zb(Element.prototype,{previousElementSibling:{get:function(){N.currentNode=this;return N.previousSibling()}},nextElementSibling:{get:function(){N.currentNode=this;return N.nextSibling()}},innerHTML:{get:function(){return Ub(this,zb)},set:function(b){var c="template"===this.localName?this.content:this;ac(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==$b.namespaceURI?
$b.createElementNS(this.namespaceURI,d):$b.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}},className:{get:function(){return this.getAttribute("class")||""},set:function(b){this.setAttribute("class",b)}}}));L(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));L(Element.prototype,cc);L(HTMLElement.prototype,["focus","blur"]);window.HTMLTemplateElement&&
L(window.HTMLTemplateElement.prototype,["innerHTML"]);Vb?L(DocumentFragment.prototype,bc):Zb(DocumentFragment.prototype,a);L(DocumentFragment.prototype,cc);Vb?(L(Document.prototype,bc),L(Document.prototype,["activeElement"])):Zb(Document.prototype,a);L(Document.prototype,["importNode","getElementById","elementFromPoint",pb()]);L(Document.prototype,cc)};var ec=J({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get shadowRoot(){return this.__shady_shadowRoot}}),fc=J({get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=
a},get innerHTML(){return this.__shady_innerHTML},set innerHTML(a){this.__shady_innerHTML=a}}),gc=J({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},set className(a){this.__shady_className=
a}});function hc(a){for(var b in a){var c=a[b];c&&(c.enumerable=!1)}}hc(ec);hc(fc);hc(gc);var ic=E.j||!0===E.noPatch,jc=ic?function(){}:function(a){var b=B(a);b.gb||(b.gb=!0,Cb(a,gc))},kc=ic?function(){}:function(a){var b=B(a);b.fb||(b.fb=!0,Cb(a,ec),window.customElements&&window.customElements.polyfillWrapFlushCallback&&!E.noPatch||Cb(a,fc))};var lc="__eventWrappers"+Date.now(),mc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),nc=function(){function a(){}var b=!1,c={get capture(){b=!0;return!1}};window.addEventListener("test",a,c);window.removeEventListener("test",a,c);return b}();function oc(a){if(null===a||"object"!==typeof a&&"function"!==typeof a){var b=!!a;var c=!1}else{b=!!a.capture;c=!!a.once;var d=a.H}return{$a:d,capture:b,once:c,Za:nc?a:b}}
var pc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,
drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},qc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};function rc(a){return a instanceof Node?a.__shady_getRootNode():a}
function sc(a,b){var c=[],d=a;for(a=rc(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function tc(a){a.__composedPath||(a.__composedPath=sc(a.target,!0));return a.__composedPath}function uc(a,b){if(!G)return a;a=sc(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=rc(d),f!==e&&(g=a.indexOf(f),e=f),!G(f)||-1<g)return d}
var vc={get composed(){void 0===this.__composed&&(mc?this.__composed="focusin"===this.type||"focusout"===this.type||mc(this):!1!==this.isTrusted&&(this.__composed=pc[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=sc(this.__target,this.composed));return this.__composedPath},get target(){return uc(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=sc(this.__relatedTarget,!0));return uc(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.ma=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.ma=this.__immediatePropagationStopped=!0}},wc=E.j&&Object.getOwnPropertyDescriptor(Event.prototype,"eventPhase");
wc&&(Object.defineProperty(vc,"eventPhase",{get:function(){return this.currentTarget===this.target?Event.AT_TARGET:this.__shady_native_eventPhase},enumerable:!0,configurable:!0}),Object.defineProperty(vc,"__shady_native_eventPhase",wc));function xc(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var yc={focus:!0,blur:!0};function zc(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}
function Ac(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!zc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function Bc(a){var b=a.composedPath(),c=b.map(function(k){return uc(k,b)}),d=a.bubbles;Object.defineProperty(a,"currentTarget",{configurable:!0,enumerable:!0,get:function(){return g}});var e=Event.CAPTURING_PHASE;Object.defineProperty(a,"eventPhase",{configurable:!0,enumerable:!0,get:function(){return e}});for(var f=b.length-1;0<=f;f--){var g=b[f];e=g===c[f]?Event.AT_TARGET:Event.CAPTURING_PHASE;Ac(a,g,"capture");if(a.ma)return}for(f=0;f<b.length;f++){g=b[f];var h=g===c[f];if(h||d)if(e=h?Event.AT_TARGET:
Event.BUBBLING_PHASE,Ac(a,g,"bubble"),a.ma)return}e=0;g=null}function Cc(a,b,c,d){for(var e=0;e<a.length;e++){var f=a[e],g=f.type,h=f.capture;if(b===f.node&&c===g&&d===h)return e}return-1}function Dc(a){Ib();return!E.U&&this instanceof Node&&!wb(document,this)?(a.__target||Ec(a,this),Bc(a)):this.__shady_native_dispatchEvent(a)}
function Fc(a,b,c){var d=this,e=oc(c),f=e.capture,g=e.once,h=e.$a;e=e.Za;if(b){var k=typeof b;if("function"===k||"object"===k)if("object"!==k||b.handleEvent&&"function"===typeof b.handleEvent){if(qc[a])return this.__shady_native_addEventListener(a,b,e);var m=h||this;if(h=b[lc]){if(-1<Cc(h,m,a,f))return}else b[lc]=[];h=function(n){g&&d.__shady_removeEventListener(a,b,c);n.__target||Ec(n);if(m!==d){var t=Object.getOwnPropertyDescriptor(n,"currentTarget");Object.defineProperty(n,"currentTarget",{get:function(){return m},
configurable:!0});var C=Object.getOwnPropertyDescriptor(n,"eventPhase");Object.defineProperty(n,"eventPhase",{configurable:!0,enumerable:!0,get:function(){return f?Event.CAPTURING_PHASE:Event.BUBBLING_PHASE}})}n.__previousCurrentTarget=n.currentTarget;if(!G(m)&&"slot"!==m.localName||-1!=n.composedPath().indexOf(m))if(n.composed||-1<n.composedPath().indexOf(m))if(zc(n)&&n.target===n.relatedTarget)n.eventPhase===Event.BUBBLING_PHASE&&n.stopImmediatePropagation();else if(n.eventPhase===Event.CAPTURING_PHASE||
n.bubbles||n.target===m||m instanceof Window){var oa="function"===k?b.call(m,n):b.handleEvent&&b.handleEvent(n);m!==d&&(t?(Object.defineProperty(n,"currentTarget",t),t=null):delete n.currentTarget,C?(Object.defineProperty(n,"eventPhase",C),C=null):delete n.eventPhase);return oa}};b[lc].push({node:m,type:a,capture:f,uc:h});this.__handlers=this.__handlers||{};this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]};this.__handlers[a][f?"capture":"bubble"].push(h);yc[a]||this.__shady_native_addEventListener(a,
h,e)}}}function Gc(a,b,c){if(b){var d=oc(c);c=d.capture;var e=d.$a;d=d.Za;if(qc[a])return this.__shady_native_removeEventListener(a,b,d);var f=e||this;e=void 0;var g=null;try{g=b[lc]}catch(h){}g&&(f=Cc(g,f,a,c),-1<f&&(e=g.splice(f,1)[0].uc,g.length||(b[lc]=void 0)));this.__shady_native_removeEventListener(a,e||b,d);e&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][c?"capture":"bubble"],b=a.indexOf(e),-1<b&&a.splice(b,1))}}
function Hc(){for(var a in yc)window.__shady_native_addEventListener(a,function(b){b.__target||(Ec(b),Bc(b))},!0)}var Ic=J(vc);function Ec(a,b){b=void 0===b?a.target:b;a.__target=b;a.__relatedTarget=a.relatedTarget;if(E.j){b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;I(c,Ic);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else I(a,Ic)}var Jc=xc(Event),Kc=xc(CustomEvent),Lc=xc(MouseEvent);
function Mc(){if(!mc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}
var Nc=Object.getOwnPropertyNames(Element.prototype).filter(function(a){return"on"===a.substring(0,2)}),Oc=Object.getOwnPropertyNames(HTMLElement.prototype).filter(function(a){return"on"===a.substring(0,2)});function Pc(a){return{set:function(b){var c=B(this),d=a.substring(2);c.G||(c.G={});c.G[a]&&this.removeEventListener(d,c.G[a]);this.__shady_addEventListener(d,b);c.G[a]=b},get:function(){var b=D(this);return b&&b.G&&b.G[a]},configurable:!0}};function Qc(a,b){return{index:a,V:[],ia:b}}
function Rc(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var m=c.length,n=0;n<k-g&&Sc(a[--h],c[--m]);)n++;h=n}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Qc(e,0);f<d;)b.V.push(c[f++]);return[b]}if(f==d)return[Qc(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(m=0;m<d;m++)b[m]=Array(h),b[m][0]=m;for(m=0;m<h;m++)b[0][m]=m;for(m=1;m<d;m++)for(n=1;n<h;n++)if(a[k+n-1]===c[g+m-1])b[m][n]=
b[m-1][n-1];else{var t=b[m-1][n]+1,C=b[m][n-1]+1;b[m][n]=t<C?t:C}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],m=b[k-1][g],n=b[k][g-1],t=m<n?m<h?m:h:n<h?n:h,t==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):t==m?(a.push(3),k--,d=m):(a.push(2),g--,d=n));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=Qc(e,0));b.ia++;e++;b.V.push(c[f]);f++;break;case 2:b||(b=Qc(e,
0));b.ia++;e++;break;case 3:b||(b=Qc(e,0)),b.V.push(c[f]),f++}b&&k.push(b);return k}function Sc(a,b){return a===b};var Tc=J({dispatchEvent:Dc,addEventListener:Fc,removeEventListener:Gc});var Uc=null;function O(){Uc||(Uc=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Uc||null}function Vc(a,b,c){var d=O();return d&&"class"===b?(d.setElementClass(a,c),!0):!1}function Wc(a,b){var c=O();c&&c.unscopeNode(a,b)}function Xc(a,b){var c=O();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)c=c&&Xc(a,b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}
function Yc(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=O();return b?b.currentScopeForNode(a):""}function Zc(a,b){if(a)for(a.nodeType===Node.ELEMENT_NODE&&b(a),a=a.__shady_firstChild;a;a=a.__shady_nextSibling)a.nodeType===Node.ELEMENT_NODE&&Zc(a,b)};var $c=window.document,ad=E.U,bd=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),cd=bd&&bd.get;function dd(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function ed(a){var b=D(a);if(b&&void 0!==b.la)for(b=a.__shady_firstChild;b;b=b.__shady_nextSibling)ed(b);if(a=D(a))a.la=void 0}function fd(a){var b=a;if(a&&"slot"===a.localName){var c=D(a);(c=c&&c.O)&&(b=c.length?c[0]:fd(a.__shady_nextSibling))}return b}
function gd(a,b,c){if(a=(a=D(a))&&a.T){if(b)if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(var d=0,e=b.childNodes.length;d<e;d++)a.addedNodes.push(b.childNodes[d]);else a.addedNodes.push(b);c&&a.removedNodes.push(c);Kb(a)}}
var kd=J({get parentNode(){var a=D(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=D(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=D(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=D(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=D(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(F(this)){var a=D(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=D(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if(cd&&cd.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(null===a||wb(a,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(G(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(F(this)){for(var a=[],b=this.__shady_firstChild;b;b=b.__shady_nextSibling)b.nodeType!==Node.COMMENT_NODE&&a.push(b.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!F(this)&&
E.j){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&dd(this);this.__shady_native_textContent=a}else dd(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==$c&&a.ownerDocument!==$c)return this.__shady_native_insertBefore(a,b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");
if(b){var c=D(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;gd(this,a);var d=[],e=(c=hd(this))?c.host.localName:Yc(this),f=a.__shady_parentNode;if(f){var g=Yc(a);var h=!!c||!hd(a)||ad&&void 0!==this.__noInsertionPoint;f.__shady_removeChild(a,h)}f=!0;var k=(!ad||void 0===a.__noInsertionPoint&&void 0===
this.__noInsertionPoint)&&!Xc(a,e),m=c&&!a.__noInsertionPoint&&(!ad||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(m||k)k&&(g=g||Yc(a)),Zc(a,function(n){m&&"slot"===n.localName&&d.push(n);if(k){var t=g;O()&&(t&&Wc(n,t),(t=O())&&t.scopeNode(n,e))}});d.length&&(c.Ca(d),c.s());F(this)&&(id(a,this,b),h=D(this),h.root?(f=!1,qb(this)&&h.root.s()):c&&"slot"===this.localName&&(f=!1,c.s()));f?(c=G(this)?this.host:this,b?(b=fd(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==
this.ownerDocument&&this.ownerDocument.adoptNode(a);return a},appendChild:function(a){if(this!=a||!G(a))return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==$c)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);gd(this,null,a);var c=hd(a),d=c&&c.Kb(a),e=D(this);if(F(this)&&(jd(a,this),qb(this))){e.root.s();var f=!0}if(O()&&!b&&c&&a.nodeType!==Node.TEXT_NODE){var g=
Yc(a);Zc(a,function(h){Wc(h,g)})}ed(a);c&&((b="slot"===this.localName)&&(f=!0),(d||b)&&c.s());f||(f=G(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=
this.__shady_firstChild;for(var c;a;a=a.__shady_nextSibling)c=a.__shady_cloneNode(!0),b.__shady_appendChild(c)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=B(this),c=b.la;void 0===c&&(G(this)?(c=this,b.la=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.la=c)));return c}},contains:function(a){return xb(this,a)}});var ld=J({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&a.da();return(a=D(this))&&a.assignedSlot||null}});function md(a,b,c){var d=[];nd(a,b,c,d);return d}function nd(a,b,c,d){for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling){var e;if(e=a.nodeType===Node.ELEMENT_NODE){e=a;var f=b,g=c,h=d,k=f(e);k&&h.push(e);g&&g(k)?e=k:(nd(e,f,g,h),e=void 0)}if(e)break}}
var od={get firstElementChild(){var a=D(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=D(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return F(this)?yb(Array.prototype.filter.call(Ab(this),function(a){return a.nodeType===
Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}},pd=J((od.append=function(){this.__shady_insertBefore(K.apply(null,p(q.apply(0,arguments))),null)},od.prepend=function(){this.__shady_insertBefore(K.apply(null,p(q.apply(0,arguments))),this.__shady_firstChild)},od.replaceChildren=function(){for(var a=q.apply(0,arguments),b;null!==(b=this.__shady_firstChild);)this.__shady_removeChild(b);this.__shady_insertBefore(K.apply(null,
p(a)),null)},od)),qd=J({querySelector:function(a){return md(this,function(b){return rb.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return yb(b.filter(function(d){return d.__shady_getRootNode()==c}))}return yb(md(this,function(d){return rb.call(d,a)}))}}),rd=E.U&&!E.noPatch?Db({},pd):pd;Db(pd,qd);/*

Copyright (c) 2020 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var sd=J({after:function(){var a=this.__shady_parentNode;if(null!==a){var b=this.__shady_nextSibling;a.__shady_insertBefore(K.apply(null,p(q.apply(0,arguments))),b)}},before:function(){var a=this.__shady_parentNode;null!==a&&a.__shady_insertBefore(K.apply(null,p(q.apply(0,arguments))),this)},remove:function(){var a=this.__shady_parentNode;null!==a&&a.__shady_removeChild(this)},replaceWith:function(){var a=q.apply(0,arguments),b=this.__shady_parentNode;if(null!==b){var c=this.__shady_nextSibling;b.__shady_removeChild(this);
b.__shady_insertBefore(K.apply(null,p(a)),c)}}});var td=window.document;function ud(a,b){"slot"===b?(a=a.__shady_parentNode,qb(a)&&D(a).root.s()):"slot"===a.localName&&"name"===b&&(b=hd(a))&&(b.Yb(a),b.s())}
var vd=J({get previousElementSibling(){var a=D(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=D(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){this.ownerDocument!==td?this.__shady_native_setAttribute(a,b):Vc(this,a,b)||(this.__shady_native_setAttribute(a,b),ud(this,a))},removeAttribute:function(a){this.ownerDocument!==td?this.__shady_native_removeAttribute(a):Vc(this,a,"")?""===this.getAttribute(a)&&this.__shady_native_removeAttribute(a):(this.__shady_native_removeAttribute(a),
ud(this,a))}});E.U||Nc.forEach(function(a){vd[a]=Pc(a)});
var zd=J({attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");if(a.shadyUpgradeFragment&&!E.cb){var b=a.shadyUpgradeFragment;b.__proto__=ShadowRoot.prototype;b.La(this,a);wd(b,b);a=b.__noInsertionPoint?null:b.querySelectorAll("slot");b.__noInsertionPoint=void 0;a&&a.length&&(b.Ca(a),b.s());b.host.__shady_native_appendChild(b)}else b=new xd(yd,this,a);return this.__CE_shadowRoot=b},get shadowRoot(){var a=D(this);return a&&a.kc||null}});
Db(vd,zd);var Ad=document.implementation.createHTMLDocument("inert"),Bd=J({get innerHTML(){return F(this)?Ub("template"===this.localName?this.content:this,Ab):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{dd(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==Ad.namespaceURI?Ad.createElementNS(this.namespaceURI,b):Ad.createElement(b);for(E.j?b.__shady_native_innerHTML=a:b.innerHTML=a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var Cd=J({blur:function(){var a=D(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});E.U||Oc.forEach(function(a){Cd[a]=Pc(a)});var Dd=J({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&G(b)&&b.da();return(b=D(this))?(a&&a.flatten?b.O:b.assignedNodes)||[]:[]}},addEventListener:function(a,b,c){if("slot"!==this.localName||"slotchange"===a)Fc.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.H=this;d.__shady_addEventListener(a,b,c)}},removeEventListener:function(a,
b,c){if("slot"!==this.localName||"slotchange"===a)Gc.call(this,a,b,c);else{"object"!==typeof c&&(c={capture:!!c});var d=this.__shady_parentNode;if(!d)throw Error("ShadyDOM cannot attach event to slot unless it has a `parentNode`");c.H=this;d.__shady_removeEventListener(a,b,c)}}});var Ed=J({getElementById:function(a){return""===a?null:md(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});function Fd(a,b){for(var c;b&&!a.has(c=b.__shady_getRootNode());)b=c.host;return b}function Gd(a){var b=new Set;for(b.add(a);G(a)&&a.host;)a=a.host.__shady_getRootNode(),b.add(a);return b}
var Hd="__shady_native_"+pb(),Id=J({get activeElement(){var a=E.j?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!G(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=hd(a);b&&b!==this;)a=b.host,b=hd(a);return this===document?b?null:a:b===this?a:null},elementsFromPoint:function(a,b){a=document[Hd](a,b);if(this===document&&E.useNativeDocumentEFP)return a;a=[].slice.call(a);b=Gd(this);for(var c=new Set,
d=0;d<a.length;d++)c.add(Fd(b,a[d]));var e=[];c.forEach(function(f){return e.push(f)});return e},elementFromPoint:function(a,b){return this===document&&E.useNativeDocumentEFP?this.__shady_native_elementFromPoint(a,b):this.__shady_elementsFromPoint(a,b)[0]||null}});var Jd=window.document,Kd=J({importNode:function(a,b){if(a.ownerDocument!==Jd||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b)for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)b=this.__shady_importNode(a,!0),c.__shady_appendChild(b);return c}});var Ld=J({dispatchEvent:Dc,addEventListener:Fc.bind(window),removeEventListener:Gc.bind(window)});var Md={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(Md.parentElement=kd.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(Md.contains=kd.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(Md.children=pd.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(Md.innerHTML=Bd.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(Md.className=vd.className);
var P={EventTarget:[Tc],Node:[kd,window.EventTarget?null:Tc],Text:[ld],Comment:[ld],CDATASection:[ld],ProcessingInstruction:[ld],Element:[vd,pd,sd,ld,!E.j||"innerHTML"in Element.prototype?Bd:null,window.HTMLSlotElement?null:Dd],HTMLElement:[Cd,Md],HTMLSlotElement:[Dd],DocumentFragment:[rd,Ed],Document:[Kd,rd,Ed,Id],Window:[Ld],CharacterData:[sd]},Nd=E.j?null:["innerHTML","textContent"];function Q(a,b,c,d){b.forEach(function(e){return a&&e&&I(a,e,c,d)})}
function Od(a){var b=a?null:Nd,c;for(c in P)Q(window[c]&&window[c].prototype,P[c],a,b)}["Text","Comment","CDATASection","ProcessingInstruction"].forEach(function(a){var b=window[a],c=Object.create(b.prototype);c.__shady_protoIsPatched=!0;Q(c,P.EventTarget);Q(c,P.Node);P[a]&&Q(c,P[a]);b.prototype.__shady_patchedProto=c});function Pd(a){a.__shady_protoIsPatched=!0;Q(a,P.EventTarget);Q(a,P.Node);Q(a,P.Element);Q(a,P.HTMLElement);Q(a,P.HTMLSlotElement);return a};var Qd=E.za,Rd=E.j;function Sd(a,b){if(Qd&&!a.__shady_protoIsPatched&&!G(a)){var c=Object.getPrototypeOf(a),d=c.hasOwnProperty("__shady_patchedProto")&&c.__shady_patchedProto;d||(d=Object.create(c),Pd(d),c.__shady_patchedProto=d);Object.setPrototypeOf(a,d)}Rd||(1===b?jc(a):2===b&&kc(a))}
function Td(a,b,c,d){Sd(a,1);d=d||null;var e=B(a),f=d?B(d):null;e.previousSibling=d?f.previousSibling:b.__shady_lastChild;if(f=D(e.previousSibling))f.nextSibling=a;if(f=D(e.nextSibling=d))f.previousSibling=a;e.parentNode=b;d?d===c.firstChild&&(c.firstChild=a):(c.lastChild=a,c.firstChild||(c.firstChild=a));c.childNodes=null}
function id(a,b,c){Sd(b,2);var d=B(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(a=a.__shady_native_firstChild;a;a=a.__shady_native_nextSibling)Td(a,b,d,c);else Td(a,b,d,c)}
function jd(a,b){var c=B(a);b=B(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(B(a).nextSibling=d);d&&(B(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function wd(a,b){var c=B(a);if(b||void 0===c.firstChild){c.childNodes=null;var d=c.firstChild=a.__shady_native_firstChild;c.lastChild=a.__shady_native_lastChild;Sd(a,2);c=d;for(d=void 0;c;c=c.__shady_native_nextSibling){var e=B(c);e.parentNode=b||a;e.nextSibling=c.__shady_native_nextSibling;e.previousSibling=d||null;d=c;Sd(c,1)}}};var Ud=J({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.H=c.H||this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.H=c.H||this;this.host.__shady_removeEventListener(a,b,c)}});function Vd(a,b){I(a,Ud,b);I(a,Id,b);I(a,Bd,b);I(a,pd,b);E.noPatch&&!b?(I(a,kd,b),I(a,Ed,b)):E.j||(I(a,gc),I(a,ec),I(a,fc))};var yd={},R=E.deferConnectionCallbacks&&"loading"===document.readyState,Wd;function Xd(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}function xd(a,b,c){if(a!==yd)throw new TypeError("Illegal constructor");this.g=null;this.La(b,c)}l=xd.prototype;
l.La=function(a,b){this.host=a;this.mode=b&&b.mode;wd(this.host);a=B(this.host);a.root=this;a.kc="closed"!==this.mode?this:null;a=B(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;if(E.preferPerformance)for(;a=this.host.__shady_native_firstChild;)this.host.__shady_native_removeChild(a);else this.s()};l.s=function(){var a=this;this.M||(this.M=!0,Hb(function(){return a.da()}))};l.yb=function(){for(var a,b=this;b;)b.M&&(a=b),b=b.xb();return a};
l.xb=function(){var a=this.host.__shady_getRootNode();if(G(a)){var b=D(this.host);if(b&&0<b.Y)return a}};l.da=function(){var a=this.M&&this.yb();a&&a._renderSelf()};l.tb=function(){!this.Ka&&this.M&&this.da()};
l._renderSelf=function(){var a=R;R=!0;this.M=!1;this.g&&(this.ob(),this.mb());if(!E.preferPerformance&&!this.Ka)for(var b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling){var c=D(b);b.__shady_native_parentNode!==this.host||"slot"!==b.localName&&c.assignedSlot||this.host.__shady_native_removeChild(b)}this.Ka=!0;R=a;Wd&&Wd()};
l.ob=function(){this.ha();for(var a=0,b;a<this.g.length;a++)b=this.g[a],this.lb(b);for(a=this.host.__shady_firstChild;a;a=a.__shady_nextSibling)this.Fa(a);for(a=0;a<this.g.length;a++){b=this.g[a];var c=D(b);if(!c.assignedNodes.length)for(var d=b.__shady_firstChild;d;d=d.__shady_nextSibling)this.Fa(d,b);(d=(d=D(b.__shady_parentNode))&&d.root)&&(d.Ja()||d.M)&&d._renderSelf();this.Ba(c.O,c.assignedNodes);if(d=c.Pa){for(var e=0;e<d.length;e++)D(d[e]).sa=null;c.Pa=null;d.length>c.assignedNodes.length&&
(c.xa=!0)}c.xa&&(c.xa=!1,this.Ha(b))}};l.Fa=function(a,b){var c=B(a),d=c.sa;c.sa=null;b||(b=(b=this.i[a.__shady_slot||"__catchall"])&&b[0]);b?(B(b).assignedNodes.push(a),c.assignedSlot=b):c.assignedSlot=void 0;d!==c.assignedSlot&&c.assignedSlot&&(B(c.assignedSlot).xa=!0)};l.lb=function(a){var b=D(a),c=b.assignedNodes;b.assignedNodes=[];b.O=[];if(b.Pa=c)for(b=0;b<c.length;b++){var d=D(c[b]);d.sa=d.assignedSlot;d.assignedSlot===a&&(d.assignedSlot=null)}};
l.Ba=function(a,b){for(var c=0,d=void 0;c<b.length&&(d=b[c]);c++)if("slot"==d.localName){var e=D(d).assignedNodes;e&&e.length&&this.Ba(a,e)}else a.push(b[c])};l.Ha=function(a){a.__shady_native_dispatchEvent(new Event("slotchange"));a=D(a);a.assignedSlot&&this.Ha(a.assignedSlot)};l.mb=function(){for(var a=this.g,b=[],c=0;c<a.length;c++){var d=a[c].__shady_parentNode,e=D(d);e&&e.root||!(0>b.indexOf(d))||b.push(d)}for(a=0;a<b.length;a++)c=b[a],this.Xb(c===this?this.host:c,this.nb(c))};
l.nb=function(a){var b=[];for(a=a.__shady_firstChild;a;a=a.__shady_nextSibling)if(this.Bb(a))for(var c=D(a).O,d=0;d<c.length;d++)b.push(c[d]);else b.push(a);return b};l.Bb=function(a){return"slot"==a.localName};
l.Xb=function(a,b){for(var c=zb(a),d=Rc(b,b.length,c,c.length),e=0,f=0,g=void 0;e<d.length&&(g=d[e]);e++){for(var h=0,k=void 0;h<g.V.length&&(k=g.V[h]);h++)k.__shady_native_parentNode===a&&a.__shady_native_removeChild(k),c.splice(g.index+f,1);f-=g.ia}e=0;for(f=void 0;e<d.length&&(f=d[e]);e++)for(g=c[f.index],h=f.index;h<f.index+f.ia;h++)k=b[h],a.__shady_native_insertBefore(k,g),c.splice(h,0,k)};l.sb=function(){this.F=this.F||[];this.g=this.g||[];this.i=this.i||{}};
l.Ca=function(a){this.sb();this.F.push.apply(this.F,p(a))};l.ha=function(){this.F&&this.F.length&&(this.Fb(this.F),this.F=[])};l.Fb=function(a){for(var b,c=0;c<a.length;c++){var d=a[c];wd(d);var e=d.__shady_parentNode;wd(e);e=D(e);e.Y=(e.Y||0)+1;e=this.Na(d);this.i[e]?(b=b||{},b[e]=!0,this.i[e].push(d)):this.i[e]=[d];this.g.push(d)}if(b)for(var f in b)this.i[f]=this.Sa(this.i[f])};l.Na=function(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.hb=b};
l.Sa=function(a){return a.sort(function(b,c){b=Xd(b);for(var d=Xd(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=Ab(c.__shady_parentNode),b.indexOf(c)-b.indexOf(f)}})};l.Kb=function(a){if(this.g){this.ha();var b=this.i,c;for(c in b)for(var d=b[c],e=0;e<d.length;e++){var f=d[e];if(xb(a,f)){d.splice(e,1);var g=this.g.indexOf(f);0<=g&&(this.g.splice(g,1),(g=D(f.__shady_parentNode))&&g.Y&&g.Y--);e--;this.Lb(f);g=!0}}return g}};
l.Yb=function(a){if(this.g){this.ha();var b=a.hb,c=this.Na(a);if(c!==b){b=this.i[b];var d=b.indexOf(a);0<=d&&b.splice(d,1);b=this.i[c]||(this.i[c]=[]);b.push(a);1<b.length&&(this.i[c]=this.Sa(b))}}};l.Lb=function(a){a=D(a);var b=a.O;if(b)for(var c=0;c<b.length;c++){var d=b[c],e=d.__shady_native_parentNode;e&&e.__shady_native_removeChild(d)}a.O=[];a.assignedNodes=[]};l.Ja=function(){this.ha();return!(!this.g||!this.g.length)};
(function(a){a.__proto__=DocumentFragment.prototype;Vd(a,"__shady_");Vd(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(xd.prototype);
if(window.customElements&&window.customElements.define&&E.inUse&&!E.preferPerformance){var Yd=new Map;Wd=function(){var a=[];Yd.forEach(function(d,e){a.push([e,d])});Yd.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.__shadydom_connectedCallback():c.__shadydom_disconnectedCallback()}};R&&document.addEventListener("readystatechange",function(){R=!1;Wd()},{once:!0});var Zd=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.__shadydom_connectedCallback=
function(){R?Yd.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.__shadydom_disconnectedCallback=function(){R?this.isConnected||Yd.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},$d=window.customElements.define,ae=function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;$d.call(window.customElements,a,Zd(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d};window.customElements.define=
ae;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:ae,configurable:!0})}function hd(a){a=a.__shady_getRootNode();if(G(a))return a};function be(a){this.node=a}l=be.prototype;l.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};l.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};l.appendChild=function(a){return this.node.__shady_appendChild(a)};l.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};l.removeChild=function(a){return this.node.__shady_removeChild(a)};l.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
l.cloneNode=function(a){return this.node.__shady_cloneNode(a)};l.getRootNode=function(a){return this.node.__shady_getRootNode(a)};l.contains=function(a){return this.node.__shady_contains(a)};l.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};l.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};l.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};l.hasAttribute=function(a){return this.node.__shady_native_hasAttribute(a)};l.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};
l.attachShadow=function(a){return this.node.__shady_attachShadow(a)};l.focus=function(){this.node.__shady_native_focus()};l.blur=function(){this.node.__shady_blur()};l.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};l.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};l.elementsFromPoint=function(a,b){return this.node.__shady_elementsFromPoint(a,b)};
l.elementFromPoint=function(a,b){return this.node.__shady_elementFromPoint(a,b)};l.querySelector=function(a){return this.node.__shady_querySelector(a)};l.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};l.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};l.append=function(){return this.node.__shady_append.apply(this.node,p(q.apply(0,arguments)))};
l.prepend=function(){return this.node.__shady_prepend.apply(this.node,p(q.apply(0,arguments)))};l.replaceChildren=function(){return this.node.__shady_replaceChildren.apply(this.node,p(q.apply(0,arguments)))};l.after=function(){return this.node.__shady_after.apply(this.node,p(q.apply(0,arguments)))};l.before=function(){return this.node.__shady_before.apply(this.node,p(q.apply(0,arguments)))};l.remove=function(){return this.node.__shady_remove()};
l.replaceWith=function(){return this.node.__shady_replaceWith.apply(this.node,p(q.apply(0,arguments)))};
ca.Object.defineProperties(be.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(G(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(G(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}},className:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_className},set:function(a){this.node.__shady_className=
a}}});function ce(a){Object.defineProperty(be.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})}Nc.forEach(function(a){return ce(a)});Oc.forEach(function(a){return ce(a)});var de=new WeakMap;function ee(a){if(G(a)||a instanceof be)return a;var b=de.get(a);b||(b=new be(a),de.set(a,b));return b};if(E.inUse){var fe=E.j?function(a){return a}:function(a){kc(a);jc(a);return a},ShadyDOM={inUse:E.inUse,patch:fe,isShadyRoot:G,enqueue:Hb,flush:Ib,flushInitial:function(a){a.tb()},settings:E,filterMutations:Nb,observeChildren:Lb,unobserveChildren:Mb,deferConnectionCallbacks:E.deferConnectionCallbacks,preferPerformance:E.preferPerformance,handlesDynamicScoping:!0,wrap:E.noPatch?ee:fe,wrapIfNeeded:!0===E.noPatch?ee:function(a){return a},Wrapper:be,composedPath:tc,noPatch:E.noPatch,patchOnDemand:E.za,
nativeMethods:Wb,nativeTree:Xb,patchElementProto:Pd};window.ShadyDOM=ShadyDOM;dc();Od("__shady_");Object.defineProperty(document,"_activeElement",Id.activeElement);I(Window.prototype,Ld,"__shady_");E.noPatch?E.za&&I(Element.prototype,zd):(Od(),Mc());Hc();window.Event=Jc;window.CustomEvent=Kc;window.MouseEvent=Lc;window.ShadowRoot=xd};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function ge(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function he(a){var b=a=a.replace(ie,"").replace(je,""),c=new ge;c.start=0;c.end=b.length;for(var d=c,e=0,f=b.length;e<f;e++)if("{"===b[e]){d.rules||(d.rules=[]);var g=d,h=g.rules[g.rules.length-1]||null;d=new ge;d.start=e+1;d.parent=g;d.previous=h;g.rules.push(d)}else"}"===b[e]&&(d.end=e+1,d=d.parent||c);return ke(c,a)}
function ke(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=_expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(c),c=c.replace(le," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=4:c.match(me)&&(a.type=7,a.keyframesName=a.selector.split(le).pop()):a.type=0===c.indexOf("--")?
1E3:1);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)ke(f,b);return a}function _expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function ne(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules;if(e&&!_hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(e))for(var f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=ne(h,b,d);else b?b=a.cssText:(b=a.cssText,b=b.replace(oe,"").replace(pe,""),b=b.replace(qe,"").replace(re,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
function _hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){a=a[0];return!!a&&!!a.selector&&0===a.selector.indexOf("--")}var ie=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,je=/@import[^;]*;/gim,oe=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,pe=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,qe=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,re=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,me=/^@[^\s]*keyframes/,le=/\s+/g;var S=!(window.ShadyDOM&&window.ShadyDOM.inUse),se;function te(a){se=a&&a.shimcssproperties?!1:S||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var ue;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(ue=window.ShadyCSS.cssBuild);var ve=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?se=window.ShadyCSS.nativeCss:window.ShadyCSS?(te(window.ShadyCSS),window.ShadyCSS=void 0):te(window.WebComponents&&window.WebComponents.flags);var T=se;var we=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,xe=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,ye=/(--[\w-]+)\s*([:,;)]|$)/gi,ze=/(animation\s*:)|(animation-name\s*:)/,Ae=/@media\s(.*)/,Be=/\{[^}]*\}/g;var Ce=new Set;function De(a,b){if(!a)return"";"string"===typeof a&&(a=he(a));b&&Ee(a,b);return ne(a,T)}function Fe(a){!a.__cssRules&&a.textContent&&(a.__cssRules=he(a.textContent));return a.__cssRules||null}function Ge(a){return!!a.parent&&7===a.parent.type}function Ee(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&4===f){var g=a.selector.match(Ae);g&&(window.matchMedia(g[1]).matches||(e=!0))}1===f?b(a):c&&7===f?c(a):1E3===f&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)Ee(g,b,c,d)}}
function He(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Ie(e,c,d);return e}var U=null;function Je(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(U?U.nextSibling:null)||b.firstChild);return U=a}function Ie(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);U?a.compareDocumentPosition(U)===Node.DOCUMENT_POSITION_PRECEDING&&(U=a):U=a}
function Ke(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function Le(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=Ke(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=Le(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Me(a,b){S?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var Ne=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function V(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,W:c}}function Oe(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=Ke(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function Pe(a){if(void 0!==ue)return ue;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function Qe(a){a=void 0===a?"":a;return""!==a&&T?S?"shadow"===a:"shady"===a:!1};function Re(){}function Se(a,b){var c=W;c.fa(a,function(d){c.element(d,b||"")})}l=Re.prototype;l.fa=function(a,b){a.nodeType===Node.ELEMENT_NODE&&b(a);if(a="template"===a.localName?(a.content||a._content||a).childNodes:a.children||a.childNodes)for(var c=0;c<a.length;c++)this.fa(a[c],b)};
l.element=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),Me(a,b)):Me(a,(d?d+" ":"")+"style-scope "+b)}};function Te(a,b,c){var d=W;d.fa(a,function(e){d.element(e,b,!0);d.element(e,c)})}function Ue(a,b){var c=W;c.fa(a,function(d){c.element(d,b||"",!0)})}
function Ve(a,b,c,d,e){var f=W;e=void 0===e?"":e;""===e&&(S||"shady"===(void 0===d?"":d)?e=De(b,c):(a=V(a),e=We(f,b,a.is,a.W,c)+"\n\n"));return e.trim()}function We(a,b,c,d,e){var f=a.na(c,d);c=a.Da(c);return De(b,function(g){g.hc||(a.Ta(g,a.ua,c,f),g.hc=!0);e&&e(g,c,f)})}l.Da=function(a){return a?"."+a:""};l.na=function(a,b){return b?"[is="+a+"]":a};l.Ta=function(a,b,c,d){a.selector=a.o=this.Ua(a,b,c,d)};
l.Ua=function(a,b,c,d){var e=Oe(a.selector);if(!Ge(a)){a=0;for(var f=e.length,g=void 0;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.filter(function(h){return!!h}).join(",")};l.Wa=function(a){return a.replace(Xe,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})};
l.Jb=function(a){for(var b=[],c;c=a.match(Ye);){var d=c.index,e=Ke(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{Aa:a,matches:b}};l.Nb=function(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])};
l.ua=function(a,b,c){var d=this,e=!1;a=a.trim();var f=Xe.test(a);f&&(a=a.replace(Xe,function(k,m,n){return":"+m+"("+n.replace(/\s/g,"")+")"}),a=this.Wa(a));var g=Ye.test(a);if(g){var h=this.Jb(a);a=h.Aa;h=h.matches}a=a.replace(Ze,":host $1");a=a.replace($e,function(k,m,n){e||(k=d.Ub(n,m,b,c),e=e||k.stop,m=k.ac,n=k.value);return m+n});g&&(a=this.Nb(a,h));f&&(a=this.Wa(a));return a=a.replace(af,function(k,m,n,t){return'[dir="'+n+'"] '+m+t+", "+m+'[dir="'+n+'"]'+t})};
l.Ub=function(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=this.Wb(a,d):0!==e&&(a=c?this.Va(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(bf,function(g,h){return" > "+h}))}return{value:a,ac:b,stop:f}};l.Va=function(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")};
l.Wb=function(a,b){var c=a.match(cf);return(c=c&&c[2].trim()||"")?c[0].match(df)?a.replace(cf,function(d,e,f){return b+f}):c.split(df)[0]===b?c:"should_not_match":a.replace(":host",b)};function ef(a){":root"===a.selector&&(a.selector="html")}l.Vb=function(a){return a.match(":host")?"":a.match("::slotted")?this.ua(a,":not(.style-scope)"):this.Va(a.trim(),":not(.style-scope)")};ca.Object.defineProperties(Re.prototype,{X:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Xe=/:(nth[-\w]+)\(([^)]+)\)/,$e=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,df=/[[.:#*]/,Ze=RegExp("^(::slotted)"),cf=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,bf=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,af=/(.*):dir\((?:(ltr|rtl))\)(.*)/,Ye=/:(?:matches|any|-(?:webkit|moz)-any)/,W=new Re;function ff(a,b,c,d,e){this.v=a||null;this.placeholder=b||null;this.ya=c||[];this.P=null;this.cssBuild=e||"";this.W=d||"";this.N=this.u=this.C=null}function X(a){return a?a.__styleInfo:null}function gf(a,b){return a.__styleInfo=b}ff.prototype.zb=function(){return this.v};ff.prototype._getStyleRules=ff.prototype.zb;function hf(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var jf=/:host\s*>\s*/,kf=navigator.userAgent.match("Trident");function lf(){}function mf(a){var b={},c=[],d=0;Ee(a,function(f){nf(f);f.index=d++;f=f.l.cssText;for(var g;g=ye.exec(f);){var h=g[1];":"!==g[2]&&(b[h]=!0)}},function(f){c.push(f)});a.Cb=c;a=[];for(var e in b)a.push(e);return a}
function nf(a){if(!a.l){var b={},c={};of(a,c)&&(b.B=c,a.rules=null);b.cssText=a.parsedCssText.replace(Be,"").replace(we,"");a.l=b}}function of(a,b){var c=a.l;if(c){if(c.B)return Object.assign(b,c.B),!0}else{c=a.parsedCssText;for(var d;a=we.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function pf(a,b,c){b&&(b=0<=b.indexOf(";")?qf(a,b,c):Le(b,function(d,e,f,g){if(!e)return d+g;(e=pf(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=pf(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function qf(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){xe.lastIndex=0;if(f=xe.exec(e))e=pf(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=pf(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function rf(a,b){var c={},d=[];Ee(a,function(e){e.l||nf(e);var f=e.o||e.parsedSelector;b&&e.l.B&&f&&hf.call(b,f)&&(of(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{B:c,key:d}}
function sf(a,b,c,d){b.l||nf(b);if(b.l.B){var e=V(a);a=e.is;e=e.W;e=a?W.na(a,e):"html";var f=b.parsedSelector;var g=!!f.match(jf)||"html"===e&&-1<f.indexOf("html");var h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.o||(b.o=W.Ua(b,W.ua,W.Da(a),e)),c=b.o||e),g&&"html"===e&&(c=b.o||b.wc),d({Aa:c,fc:h,vc:g})}}
function tf(a,b,c){var d={},e={};Ee(b,function(f){sf(a,f,c,function(g){hf.call(a._element||a,g.Aa)&&(g.fc?of(f,d):of(f,e))})},null,!0);return{lc:e,ec:d}}
function uf(a,b,c,d){var e=V(b),f=W.na(e.is,e.W),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=X(b);e=h.v;h=h.cssBuild;var k=a.pb(b,e,d);return Ve(b,e,function(m){var n="";m.l||nf(m);m.l.cssText&&(n=qf(a,m.l.cssText,c));m.cssText=n;if(!S&&!Ge(m)&&m.cssText){var t=n=m.cssText;null==m.Ya&&(m.Ya=ze.test(n));if(m.Ya)if(null==m.ka){m.ka=[];for(var C in k)t=k[C],t=t(n),n!==t&&(n=t,m.ka.push(C))}else{for(C=0;C<m.ka.length;++C)t=k[m.ka[C]],n=t(n);t=n}m.cssText=t;
a.Sb(m,g,f,d)}},h)}lf.prototype.pb=function(a,b,c){a=b.Cb;b={};if(!S&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.Rb(e,c),b[e.keyframesName]=this.Db(e);return b};lf.prototype.Db=function(a){return function(b){return b.replace(a.ic,a.bb)}};lf.prototype.Rb=function(a,b){a.ic=new RegExp("\\b"+a.keyframesName+"(?!\\B|-)","g");a.bb=a.keyframesName+"-"+b;a.o=a.o||a.selector;a.selector=a.o.replace(a.keyframesName,a.bb)};
lf.prototype.Sb=function(a,b,c,d){a.o=a.o||a.selector;d="."+d;for(var e=Oe(a.o),f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};function vf(a,b){var c=wf,d=Fe(a);a.textContent=De(d,function(e){var f=e.cssText=e.parsedCssText;e.l&&e.l.cssText&&(f=f.replace(oe,"").replace(pe,""),e.cssText=qf(c,f,b))})}ca.Object.defineProperties(lf.prototype,{eb:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var wf=new lf;var xf={},yf=window.customElements;if(yf&&!S&&!ve){var zf=yf.define;yf.define=function(a,b,c){xf[a]||(xf[a]=Je(a));zf.call(yf,a,b,c)}};function Af(){this.cache={};this.qc=100}Af.prototype.$b=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.B[e]!==b[e])return!1}return!0};Af.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({B:b,styleElement:c,u:d});e.length>this.qc&&e.shift();this.cache[a]=e};Af.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.$b(e,b,c))return e}};function Bf(){}var Cf=new RegExp(W.X+"\\s*([^\\s]*)");function Df(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Cf))?a[1]:""}function Ef(a){var b=Ne(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?V(a).is:""}
function Ff(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=Df(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===Pe(e)))Ue(e,g);else if(f instanceof ShadowRoot)for(f=Ef(e),f!==g&&Te(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+W.X+")"),g=0;g<e.length;g++){f=e[g];
var h=Ef(f);h&&W.element(f,h)}}}}}
if(!(S||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var Gf=new MutationObserver(Ff),Hf=function(a){Gf.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Hf(document);else{var If=function(){Hf(document.body)};window.HTMLImports?window.HTMLImports.whenReady(If):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){If();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else If()})}Bf=function(){Ff(Gf.takeRecords())}};var Jf={};var Kf=Promise.resolve();function Lf(a){if(a=Jf[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Mf(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Nf(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,Kf.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var Of={},Pf=new Af;function Y(){this.Ra={};this.I=document.documentElement;var a=new ge;a.rules=[];this.A=gf(this.I,new ff(a));this.pa=!1;this.h=this.m=null}l=Y.prototype;l.flush=function(){Bf()};l.vb=function(a){var b=this.Ra[a]=(this.Ra[a]||0)+1;return a+"-"+b};l.cc=function(a){return Fe(a)};l.pc=function(a){return De(a)};
l.ub=function(a){var b=[];a=a.content.querySelectorAll("style");for(var c=0;c<a.length;c++){var d=a[c];if(d.hasAttribute("shady-unscoped")){if(!S){var e=d.textContent;if(!Ce.has(e)){Ce.add(e);var f=document.createElement("style");f.setAttribute("shady-unscoped","");f.textContent=e;document.head.appendChild(f)}d.parentNode.removeChild(d)}}else b.push(d.textContent),d.parentNode.removeChild(d)}return b.join("").trim()};
l.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
l.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!ve){S||xf[b]||(xf[b]=Je(b));a._prepared=!0;a.name=b;a.extends=c;Jf[b]=a;var d=Pe(a),e=Qe(d);c={is:b,extends:c};var f=this.ub(a)+(Of[b]||"");this.R();if(!e){var g;if(g=!d)g=xe.test(f)||we.test(f),xe.lastIndex=0,we.lastIndex=0;var h=he(f);g&&T&&this.m&&this.m.transformRules(h,b);a._styleAst=h}g=[];T||(g=mf(a._styleAst));if(!g.length||T)b=this.wb(c,a._styleAst,S?a.content:null,xf[b]||null,d,e?f:""),a._style=b;a.Ib=g}};
l.prepareAdoptedCssText=function(a,b){Of[b]=a.join(" ")};l.prepareTemplateDom=function(a,b){if(!ve){var c=Pe(a);S||"shady"===c||a._domPrepared||(a._domPrepared=!0,Se(a.content,b))}};l.wb=function(a,b,c,d,e,f){f=Ve(a,b,null,e,f);return f.length?He(f,a.is,c,d):null};l.Oa=function(a){var b=V(a),c=b.is;b=b.W;var d=xf[c]||null,e=Jf[c];if(e){c=e._styleAst;var f=e.Ib;e=Pe(e);b=new ff(c,d,f,b,e);gf(a,b);return b}};
l.qb=function(){return!this.m&&window.ShadyCSS&&window.ShadyCSS.ApplyShim?(this.m=window.ShadyCSS.ApplyShim,this.m.invalidCallback=Lf,!0):!1};l.rb=function(){var a=this;!this.h&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.h=window.ShadyCSS.CustomStyleInterface,this.h.transformCallback=function(b){a.ab(b)},this.h.validateCallback=function(){requestAnimationFrame(function(){(a.h.enqueued||a.pa)&&a.flushCustomStyles()})})};l.R=function(){var a=this.qb();this.rb();return a};
l.flushCustomStyles=function(){if(!ve){var a=this.R();if(this.h){var b=this.h.processStyles();!a&&!this.h.enqueued||Qe(this.A.cssBuild)||(T?this.A.cssBuild||this.Qb(b):(this.Mb(b),this.va(this.I,this.A),this.ib(b),this.pa&&this.styleDocument()),this.h.enqueued=!1)}}};
l.Mb=function(a){var b=this;a=a.map(function(c){return b.h.getStyleForCustomStyle(c)}).filter(function(c){return!!c});a.sort(function(c,d){c=d.compareDocumentPosition(c);return c&Node.DOCUMENT_POSITION_FOLLOWING?1:c&Node.DOCUMENT_POSITION_PRECEDING?-1:0});this.A.v.rules=a.map(function(c){return Fe(c)})};
l.styleElement=function(a,b){if(ve){if(b){X(a)||gf(a,new ff(null));var c=X(a);this.Ma(c,b);Qf(this,a,c)}}else if(c=X(a)||this.Oa(a))this.qa(a)||(this.pa=!0),b&&this.Ma(c,b),T?Qf(this,a,c):(this.flush(),this.va(a,c),c.ya&&c.ya.length&&this.jb(a,c))};l.Ma=function(a,b){a.P=a.P||{};Object.assign(a.P,b)};
function Qf(a,b,c){var d=V(b).is;if(c.P){var e=c.P,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}if(((e=Jf[d])||a.qa(b))&&(!e||""===Pe(e))&&e&&e._style&&!Mf(e)){if(Mf(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)a.R(),a.m&&a.m.transformRules(e._styleAst,d),e._style.textContent=Ve(b,c.v),Nf(e);S&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=Ve(b,c.v));c.v=e._styleAst}}
l.ta=function(a){return(a=Ne(a).getRootNode().host)?X(a)||this.Oa(a)?a:this.ta(a):this.I};l.qa=function(a){return a===this.I};
l.jb=function(a,b){var c=V(a).is,d=Pf.fetch(c,b.C,b.ya),e=d?d.styleElement:null,f=b.u;b.u=d&&d.u||this.vb(c);var g=b.u;var h=wf;h=e?e.textContent||"":uf(h,a,b.C,g);var k=X(a),m=k.N;m&&!S&&m!==e&&(m._useCount--,0>=m._useCount&&m.parentNode&&m.parentNode.removeChild(m));S?k.N?(k.N.textContent=h,e=k.N):h&&(e=He(h,g,a.shadowRoot,k.placeholder)):e?e.parentNode||(kf&&-1<h.indexOf("@media")&&(e.textContent=h),Ie(e,null,k.placeholder)):h&&(e=He(h,g,null,k.placeholder));e&&(e._useCount=e._useCount||0,k.N!=
e&&e._useCount++,k.N=e);g=e;S||(e=b.u,k=h=a.getAttribute("class")||"",f&&(k=h.replace(new RegExp("\\s*x-scope\\s*"+f+"\\s*","g")," ")),k+=(k?" ":"")+"x-scope "+e,h!==k&&Me(a,k));d||Pf.store(c,b.C,g,b.u);return g};l.va=function(a,b){var c=this.ta(a),d=X(c),e=d.C;c===this.I||e||(this.va(c,d),e=d.C);c=Object.create(e||null);e=tf(a,b.v,b.cssBuild);a=rf(d.v,a).B;Object.assign(c,e.ec,a,e.lc);this.Gb(c,b.P);a=wf;d=Object.getOwnPropertyNames(c);e=0;for(var f;e<d.length;e++)f=d[e],c[f]=pf(a,c[f],c);b.C=c};
l.Gb=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};l.styleDocument=function(a){this.styleSubtree(this.I,a)};l.styleSubtree=function(a,b){var c=Ne(a),d=c.shadowRoot,e=this.qa(a);(d||e)&&this.styleElement(a,b);if(a=e?c:d)for(a=Array.from(a.querySelectorAll("*")).filter(function(f){return Ne(f).shadowRoot}),b=0;b<a.length;b++)this.styleSubtree(a[b])};l.Qb=function(a){for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);c&&this.Pb(c)}};
l.ib=function(a){for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);c&&vf(c,this.A.C)}};l.ab=function(a){var b=this,c=Pe(a);c!==this.A.cssBuild&&(this.A.cssBuild=c);if(!Qe(c)){var d=Fe(a);Ee(d,function(e){if(S)ef(e);else{var f=W;e.selector=e.parsedSelector;ef(e);f.Ta(e,f.Vb)}T&&""===c&&(b.R(),b.m&&b.m.transformRule(e))});T?a.textContent=De(d):this.A.v.rules.push(d)}};l.Pb=function(a){if(T&&this.m){var b=Fe(a);this.R();this.m.transformRules(b);a.textContent=De(b)}};
l.getComputedStyleValue=function(a,b){var c;T||(c=(X(a)||X(this.ta(a))).C[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};l.oc=function(a,b){var c=Ne(a).getRootNode();b=b?("string"===typeof b?b:String(b)).split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===W.X){c=d[e+1];break}}}c&&b.push(W.X,c);T||(c=X(a))&&c.u&&b.push(wf.eb,c.u);Me(a,b.join(" "))};l.Tb=function(a){return X(a)};
l.nc=function(a,b){W.element(a,b)};l.rc=function(a,b){W.element(a,b,!0)};l.mc=function(a){return Ef(a)};l.bc=function(a){return Df(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.oc;
Y.prototype._styleInfoForNode=Y.prototype.Tb;Y.prototype.transformCustomStyleForDocument=Y.prototype.ab;Y.prototype.getStyleAst=Y.prototype.cc;Y.prototype.styleAstToString=Y.prototype.pc;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Y.prototype.scopeNode=Y.prototype.nc;Y.prototype.unscopeNode=Y.prototype.rc;Y.prototype.scopeForNode=Y.prototype.mc;Y.prototype.currentScopeForNode=Y.prototype.bc;Y.prototype.prepareAdoptedCssText=Y.prototype.prepareAdoptedCssText;
Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return S}},nativeCss:{get:function(){return T}}});var Z=new Y,Rf,Sf;window.ShadyCSS&&(Rf=window.ShadyCSS.ApplyShim,Sf=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:T,nativeShadow:S,cssBuild:ue,disableRuntime:ve};Rf&&(window.ShadyCSS.ApplyShim=Rf);Sf&&(window.ShadyCSS.CustomStyleInterface=Sf);})();
//# sourceMappingURL=blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-ce-sd.js.sourcemap


}
/*
     FILE ARCHIVED ON 00:33:23 Mar 01, 2022 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 19:11:41 Dec 11, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 70.464
  exclusion.robots: 0.07
  exclusion.robots.policy: 0.061
  cdx.remote: 0.054
  esindex: 0.009
  LoadShardBlock: 43.74 (3)
  PetaboxLoader3.datanode: 84.968 (5)
  load_resource: 210.866 (2)
  PetaboxLoader3.resolve: 86.862 (2)
*/