var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(d,g,v){d.execute(function(){d.when("A").register("sg-jsutil",function(e){var l=e.$;return{safeCall:function(e,f){return l.isFunction(e)?e(f):f}}});d.when("A").register("dombinder",function(e){function l(c,b){for(var f=0,b=b.split("."),e=b.length;f<e;f++)c=c&&c[b[f]];return c}function d(j){return f.map(f(j).data("bind").split(","),function(b){var b=b.split(":"),e=f.trim(b[0]),l=f.trim(b[1]),d=c[e];if(d)return d.init&&d.init(j,l),function(b){d.update(j,l,b)}})}var f=e.$,c={text:{update:function(c,
b,e){f(c).text(l(e,b)||"")}},html:{update:function(c,b,e){f(c).html(l(e,b)||"")}},href:{update:function(c,b,e){f(c).attr("href",l(e,b)||"")}},trimText:{update:function(c,b){var e=f(c),l=e.text();if(l.length>b){for(var d=b-4;d>=0&&"[.,-/#!$%^&*;:{}=-_`~()] ".indexOf(l[d])>0;)d--;e.text(l.substring(0,d>=0?d+1:b-3)+"...")}}},value:{update:function(c,b,e){f(c).val(l(e,b)||"")}},visible:{update:function(c,b,e){var d=!1;b.charAt(0)==="!"&&(d=!0,b=b.substring(1));b=!!l(e,b);d!==b?f(c).show():f(c).hide()}},
css:{init:function(c,b){var e=f(c),l=e.data("dombcss")||[];l[b]="";e.data("dombcss",l)},update:function(c,b,e){var c=f(c),d=c.data("dombcss"),i=d[b],e=l(e,b);i!==e&&(d[b]=e,i&&c.removeClass(i),e&&c.addClass(e))}},attr:{init:function(c,b){var e=f(c),l=e.data("dombattr")||[];l[b]={};e.data("dombattr",l)},update:function(c,b,e){var d=f(c),c=d.data("dombattr"),i=c[b],e=l(e,b);i!==e&&(c[b]=e,i&&f.each(i,function(b){d.removeAttr(b)}),e&&f.each(e,function(b,a){d.attr(b,a)}))}}};return{init:function(c){var b=
{$root:c,bindings:[]};c.find("[data-bind]").each(function(){f.each(d(this),function(c,f){b.bindings.push(f)})});return b},update:function(c,b){f.each(c.bindings,function(c,f){f(b)})}}});d.when("A").register("gwAjax",function(e){return function(l,d){function f(f,e,j){typeof g.ue==="object"&&typeof g.ue.count==="function"&&c(d.errorCounter||"gwAjaxError");typeof g.ueLogError==="function"&&g.ueLogError({logLevel:"WARN",attribution:"gwAjax-"+(d.id||l),message:"gwAjax call failed "+(JSON&&JSON.stringify?
JSON.stringify({url:l,"params-data":d.params||d.data}):"")});typeof b==="function"&&b(f,e,j)}function c(b){typeof g.ue==="object"&&typeof g.ue.count==="function"&&g.ue.count(b,(g.ue.count(b)||0)+1)}var d=e.copy(d),j=d.success,b=d.error;d.success=function(b,c,e){b.error?f(b,c,e):typeof j==="function"&&j(b,c,e)};d.error=f;d.data=d.params?d.params:d.data;c("gwAjaxCall");d.ajaxCounter&&c(d.ajaxCounter);return e.$.ajax(l,d)}});d.when("A","sg-jsutil","a-modal","gw-productdb","productdb-binding-helper",
"sg-media-builder","gw-sims","gw-popover-data").register("gw-popover",function(e,l,i,f,c,j,b,r){function p(a,h){g.uet&&g.uet(a,h,{wb:1})}function u(a){if(g.ue&&typeof g.ue.count==="function")return g.ue.count(a)||0}function q(a){g.ue&&typeof g.ue.count==="function"&&g.ue.count(a,(g.ue.count(a)||0)+1)}function a(a){return a.closest("*[data-sgproduct]").data("sgproduct")}function s(a,b){h[a.asin]&&h[a.asin].isResolved()?w.resetSimData():(h[a.asin]=m.Deferred(),a&&a.asin&&b?w.fetch(a,b,h[a.asin]):h[a.asin].reject())}
var m=e.$,o={},h={};if(!m("html").hasClass("a-touch")){var l=m('<span style="display: none" />').appendTo("body"),n=m("#gw-popover-wrapper"),x=new c(f,n),k=i.create(l,{name:"gw-asin-popover",width:"90%","max-width":900,height:590,popoverLabel:r.popoverLabel,closeButton:!1}),w=new b(x),z=m("#gw-quick-look-btn");m("#a-page").delegate("li[data-sgproduct]","mouseenter",function(a){m(a.currentTarget).append(z);m(a.currentTarget).find("[title]").removeAttr("title");z.addClass("active")});z.mouseenter(function(){var h=
m(this),b=a(h),h=h.siblings().children("a").attr("href");s(b,h)});m(".bestsellers .listRow a").mouseenter(function(){var h=m(this),b=a(h),h=h.attr("href");s(b,h);if(b&&b.asin&&(!o[b.asin]||!o[b.asin].isResolved()))if(h=f.get(b.asin))o[b.asin]=m.Deferred(),o[b.asin].resolve(h)});d.when("gwAjax").execute(function(a){var h={};m("#a-page").delegate(".fresh-shoveler li[data-sgproduct]","mouseenter mousemove",function(b){var b=m(b.currentTarget),k=b.data("sgproduct").asin;if(!o[k]||!o[k].isResolved()){var c=
[];b.add(b.prev("li[data-sgproduct]")).add(b.next("li[data-sgproduct]")).each(function(){var a=m(this).data("sgproduct");if(a&&a.asin){var b=f.get(a.asin),k=(b=!(!h[a.asin]&&b&&b.loading))&&e.now()-h[a.asin]>1500;if(!b||k)c.push(a.asin),h[a.asin]=e.now()}});o[k]=m.Deferred();c.length?(a("/gp/gw/ajax/pdb.html",{id:"quicklook-pdb",data:{swn:"productdb-ajax",sa:'{"asins": ["'+c.join('","')+'"]}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:g.ue_id}}).done(function(a){f._add(a);for(var b=0;b<c.length;b++)h[c[b]]=
Infinity;o[k].resolve(a)}).fail(o[k].reject),q("freshHoverCount")):o[k].resolve()}})});m("#a-page").delegate("li[data-sgproduct]","mouseleave",function(){z.removeClass("active")});var B="#a-popover-"+k.attrs("id")+" ",i=m.map([".a-popover-header { display: none; }",".a-popover-inner { padding: 0px !important; margin: 0px !important; overflow: hidden !important; height: 100% !important; }"],function(a){return B+a}).join(" ");m("head").append("<style>"+i+"</style>");e.on("a:popover:hide:gw-asin-popover",
function(){g.history.state&&g.history.state.popup&&g.history.back();x.clear()});m(g).bind("popstate",function(){k.hide()});return{show:function(a,b){q("freshPopOverOn");p("bb","popoverLatency"+u("freshPopOverOn"));g.history&&g.history.pushState&&g.history.pushState({popup:1},"");x.setAsin(a,{beforeUpdate:function(k){if(k.loading)return q("freshPopOverLoading"),k;var c=(new j(k.images[0])).autoCrop().scaleXY(500,400).build(),c={url:b,image:c,actionUrl:{action:"/gp/product/handle-buy-box/"+b.substring(b.indexOf("/ref=")+
1,b.length)}};k.reviews&&(c.reviews=m.extend({},k.reviews,{url:b+"#customerReviews"}));m.when(h[a],o[a]).done(function(h){w.showSims(a,h)});h[a].fail(w.setNoSimView);p("cf","popoverLatency"+u("freshPopOverOn"));return m.extend({},k,c)}});k.show()},hide:function(){k.hide()}}}});d.when("A","sg-media-builder","gw-productdb").register("gw-sims",function(e,l,i){var f=e.$;return function(c){function e(a,h){g.uet&&g.uet(a,h,{wb:1})}function b(a){if(g.ue&&typeof g.ue.count==="function")return g.ue.count(a)||
0}function r(a){g.ue&&typeof g.ue.count==="function"&&g.ue.count(a,(g.ue.count(a)||0)+1)}function p(){if(!B){B=!0;F.hide();A.show();G.animate({height:"100%"},300);var a=0,h=0,k=0,c=parseInt(A.css("width"),10),n=A.find(".sims-img-link");n.each(function(b,e){a+=e.clientWidth;c<a?f(e).hide():(h=a,k+=1)});var d=c-h;d>0&&(d=Math.floor(20+d/k-1),d>20&&n.css({"padding-right":d/2+"px","padding-left":d/2+"px"}));n="popoverLatency"+b("freshPopOverOn");e("be",n);g.uex&&g.uex("ld",n,{wb:1})}}function u(){--x===
0&&p()}function q(a,h){var b=f("<a>"),k=f("<div>");b.attr("class","sims-img-link");k.addClass("sims-img-border");h&&b.addClass("selected");b.click(function(){r("freshPopOverSimsClick");A.find(".sims-img-link").removeClass("selected");f(this).addClass("selected");c.clear();c.setAsin(a.asin,{beforeUpdate:function(){var h;h=f.extend(!0,{},a);var b=a.url;if(h.loading)r("freshPopOverLoading");else{var k=(new l(h.images[0])).autoCrop().scaleXY(500,400).build(),k={url:b,image:k,actionUrl:{action:"/gp/product/handle-buy-box/"+
s(b)}};h.reviews&&(k.reviews=f.extend({},h.reviews,{url:b+"#customerReviews"}));h=f.extend({},h,k)}return h}})});return b.append(k)}function a(){f.each(k,function(a,h){h.url=h.url.replace(/ref=gw_pdb_pdt-[\d]+/,s(w)+"&gw_sims-"+a)})}function s(a){return a.indexOf("redirect.html?")>=0?a.replace(/.*redirect.html|(token|location)=.*?&/g,""):a.substring(a.indexOf("/ref=")+1,a.length)}function m(){B=!1;a();var h=[];x=k.length>x?x:k.length;f(k).each(function(a,b){b.loading=!1;if(b.images[0].src){var k=
(new l(b.images[0])).autoCrop().scaleXY(130,100).build().src,c=f("<img>");c.attr("src",k);c.attr("class","sims-img");c.load(u);k=f("<div>");k.attr("class","sims-img-container");var e=f("<div>");e.addClass("sims-img-overlay");f(k).append(e);k.append(c);c=q(b,a===0);c.append(k);h.push(c)}return a<x-1});x=h.length;f(h).each(function(a,h){A.append(h)});setTimeout(p,z)}function o(){d.when("gw-popover").execute(function(a){a.hide()})}function h(){F.hide();G.addClass("hidden");D.bind("click",o)}function n(){A.empty();
G.add(F).removeAttr("style");G.removeClass("hidden");D.unbind("click",o);F.show();A.hide();x=8;k=[]}var x,k,w,z=1E4,B=!1,D=f("#sims-section"),G=D.find(".sims-wrapper"),F=D.find(".sims-loading"),A=D.find(".sims-details");f("#gw-asin-popover");return{fetch:function(a,h,c){e("af","popoverLatency"+b("freshPopOverOn"));n();w=h;a.url=w;k.push(a);h=i.get(a.asin);setTimeout(c.reject,z);h.sims?c.resolve(h.sims):d.when("gwAjax").execute(function(h){h("/gp/gw/ajax/pdb.html",{id:"quicklook-sims-pdb",data:{swn:"productdb-ajax",
sa:'{"asins": [], "entityId":"'+a.asin+'","datasetId": "purchase"}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:g.ue_id}}).done(function(h){if(h&&h.p&&h.p.length>0){var b=a.asin,k=h.p;k&&(i.get(b).sims||i.addSims(b,k));return c.resolve(h.p)}return c.reject()}).fail(c.reject)});return c},setNoSimView:h,showSims:function(a,b){var c=i.get(a);c.loading?r("freshPopOverSimLoadBeforePrimeAsin"):k=c.sims?f.merge([c],c.sims):f.merge([c],b);k.length>4?m():(r("simsLessThanThreshold"),h())},resetSimData:n}}});
d.when("A").execute(function(e){var l=e.$,i,f;if(!e.$("html").hasClass("a-touch"))if(g.cvox)g.ue&&g.ue.tag&&g.ue.tag("screenReaderOn");else{l("#a-page").delegate("*[data-sgproduct] #gw-quick-look-btn","click",function(f){c(f)});l("#a-page").delegate(".bestseller-list *[data-sgproduct]","click",function(f){c(f)});d.when("gw-popover").execute(function(c){i=c;l("#gw-popover-close").click(function(){i.hide()});f&&i.show.apply(i,f)});var c=function(c){if(!(c.which>1||c.shiftKey||c.altKey||c.metaKey||c.ctrlKey)){var b,
e;l(c.target).parents(".bestseller-list").length?(b=l(c.currentTarget).data("sgproduct"),e=l(c.target).closest("a").attr("href")):(b=l("#gw-quick-look-btn").closest("*[data-sgproduct]").data("sgproduct"),e=l("#gw-quick-look-btn").siblings().children("a").attr("href"));var d=[b.asin,e];b.asin&&e&&(c.preventDefault(),i?i.show.apply(i,d):f=d)}}}});d.when("A","sg-jsutil","dombinder").register("productdb-binding-helper",function(e,d,i){return function(f,c){function e(b,c){i.update(a,p(c.beforeUpdate,b));
b.loading||p(c.load,b)}function b(a){r();q=function(){a(g)};g.pdb_observe(q)}function r(){g&&q&&(g.pdb_unobserve(q),q=null)}var p=d.safeCall,g=null,q=null,a=i.init(c);this.setAsin=function(a,c){c=c||{};r();g=f.get(a);e(g,c);g.loading&&b(function(a){e(a,c)});return g};this.clear=function(){r();g={};i.update(a,g)}}});d.register("sg-media-builder",function(){return function(e){var d=this,i=e.src,f=[];d.build=function(){var c=f.join("_");return{src:i.replace(/\.([^.]+)$/,"._"+c+"_.$1"),alt:e.alt}};d.autoCrop=
function(){f.push("AC");return d};d.scaleX=function(c){f.push("SX"+c);return d};d.scaleY=function(c){f.push("SY"+c);return d};d.upScaleX=function(c){f.push("UX"+c);return d};d.upScaleY=function(c){f.push("UY"+c);return d};d.scaleXY=function(c,f){return d.upScaleX(c).scaleY(f)}}});d.when("A","gwAjax").register("shogunProductDB",function(e,d){function i(f){var b=[];c[f]={loading:!0,pdb_observe:function(c){b.push(c)},pdb_unobserve:function(c){b=e.$.grep(b,function(b){return b!==c})},_trigger:function(){e.$.each(b,
function(){this.call(c[f])})}};return c[f]}function f(f,b){this.ajaxUrl=f;this.experienceStr=b;this._add=function(b){b.p&&e.$.each(b.p,function(b,f){if(f.asin){var d=c[f.asin]||i(f.asin);e.$.extend(d,f,{loading:!1,error:!1});d._trigger(f)}})};this.addSims=function(b,f){if(f){var d=c[b]||i(b);e.$.extend(d,{sims:f});d._trigger(b)}};this._ajax=function(c,i){var u=e.$.extend(!0,{},f,{params:{sa:JSON.stringify(c),oe:b}});g.ue_sid&&(u.url+="/"+g.ue_sid);if(g.ue_id)u.params.rrid=g.ue_id;return d(u.url,{method:u.method,
params:u.params,success:i.success,error:i.error,id:"gw-jslibs-"+i.id})};this.get=function(b){return b in c?c[b]:i(b)}}var c={};return function(c,b){return new f(c,b)}});d.when("A").register("component-feed-carousel",function(e){var d=e.$,i=function(f,c,e){this.init(f,c,e)};i.prototype={init:function(f,c,j){var b=this;e.$("html").hasClass("a-touch")&&f.addClass("feed-carousel-touch");b.adjustMarginOnChange=!0;b.defaultCssRightMargin=null;b.minItems=c||10;b.imgClass=".product-image";b.$carousel=f;b.cfMinItems=
j||6;b.cfFired=!1;b.shovelerReadyFired=!1;b.slotId=b.getSlotId();b.touch=b.$carousel.hasClass("feed-carousel-touch");b.ajaxSource=b.$carousel.parent().hasClass("ajaxSource");b.$shelf=b.$carousel.find(".feed-carousel-shelf");b.$viewport=b.$carousel.find(".feed-carousel-viewport");b.$spinner=b.$carousel.find(".spinner");b.$left=d(".feed-carousel-control.feed-left",f);b.$right=d(".feed-carousel-control.feed-right",f);b.$buttons=d(".feed-carousel-control",f);b.$thumb=d(".feed-scrollbar-thumb",f);b.shelfLeft=
-1*parseInt(b.$shelf.css("left"),10);b.calcWidth=d("html").hasClass("a-lt-ie9");b.noOpacity=d("html").hasClass("a-lt-ie9");b.$left.attr("aria-hidden",!0);b.$right.attr("aria-hidden",!0);b.bindEvents();b.$carousel.data("Carousel",b);b.$carousel.trigger("change");b.token=!1;b.lock=function(){b.token=!0};b.unlock=function(){b.token=!1};b.locked=function(){return b.token}},getSlotId:function(){var f=this.$carousel.closest(".gw-widget-instrument");return f.length>0?d(f[0]).attr("id"):null},bindEvents:function(){function f(b){return e.capabilities.pointerPrefix&&
d.inArray(b.originalEvent.pointerType,[2,"touch"])>-1||e.capabilities.actionMode==="touch"}var c=this,j=d("body");c.$buttons.ready(function(){if(!c.shovelerReadyFired){if(c.slotId){var b=c.slotId.toString()+"-active";g.GWI&&g.GWI.recordLatency(b);g.GWI&&g.GWI.register(b)}c.shovelerReadyFired=!0}});c.$carousel.change(function(){c.updateItems();c.updateSpinner();c.updateShelf();c.updateControls();if(c.defaultCssRightMargin===null&&c.$shelf.children("li").first())c.defaultCssRightMargin=parseInt(c.$shelf.children("li").first().css("margin-right"),
10);c.adjustMarginOnChange&&c.adjustCardMargin()});c.$left.click(function(b){b.preventDefault();c.changePage(-1);c.slotId&&c.logCounter("gw-"+c.slotId.toString()+"-left")});c.$right.click(function(b){b.preventDefault();c.changePage(1);c.slotId&&c.logCounter("gw-"+c.slotId.toString()+"-right")});c.bindImageLoadEvents(c.$shelf);var b;d(g).resize(function(){clearTimeout(b);b=setTimeout(function(){var b=c.getDimensions(),b=Math.max(Math.min(b.shelfLeft,b.maxLeft),0);c.moveShelf(b)},100)});c.$thumb.mousedown(function(b){var f=
b.clientX;b.which===1&&(b.preventDefault(),c.$carousel.addClass("scrolling"),j.bind("mousemove.feed-carousel",function(b){var e=c.getDimensions(),e=Math.max(Math.min(e.shelfLeft+1/e.pageRatio*(b.clientX-f),e.maxLeft),0);f=b.clientX;c.moveShelf(e)}),d(document).bind("selectstart.feed-carousel",function(){return!1}))});j.add(g).mouseup(function(){c.$carousel.removeClass("scrolling");c.$carousel.hasClass("hovering")||c.hideControls();j.unbind("mousemove.feed-carousel");d(document).unbind("selectstart.feed-carousel")});
c.$carousel.hover(function(){c.$carousel.addClass("hovering");clearTimeout(c.hoverTimer);c.hoverTimer=setTimeout(function(){c.$carousel.hasClass("hovering")&&!c.$carousel.hasClass("touching")?c.showControls():c.$carousel.removeClass("touching")},300)},function(){c.$carousel.removeClass("hovering touching");clearTimeout(c.hoverTimer);if(!c.$carousel.hasClass("scrolling"))c.hoverTimer=setTimeout(function(){c.$carousel.hasClass("hovering")||c.hideControls()},600)});c.$carousel.bind(e.action.start,function(b){if(f(b))c.$carousel.addClass("touching"),
clearTimeout(c.touchTimer),c.touchTimer=setTimeout(function(){c.$carousel.removeClass("touching")},5E3)});c.$carousel.bind(e.action.end,function(b){f(b)&&(c.$carousel.removeClass("touching"),clearTimeout(c.touchTimer),clearTimeout(c.hoverTimer))});c.$viewport.scroll(function(){c.shelfLeft=c.$viewport.scrollLeft();c.updateControls()})},bindImageLoadEvents:function(f){var c=this;d(c.imgClass,f).one("load",function(){c.$carousel.trigger("change")})},getDimensions:function(){var f=this.$shelf.width(),
c=this.shelfLeft,e=this.$carousel.width();return{pageWidth:e,shelfWidth:f,shelfLeft:c,pageRatio:e/f,leftRatio:c/f,maxLeft:f-e}},updateItems:function(){var f=this,c=f.$shelf.find(".feed-carousel-card"),e=function(b){return b.css("display")==="none"};c.each(function(b,c){var i=d(c);if(!e(i))return!0;i.attr("aria-setsize",f.$shelf.find(".feed-carousel-card").size());i.attr("aria-posinset",b+1);i.attr("aria-hidden",!1);i.attr("role","listitem");if(i.find(f.imgClass).filter(function(){return!this.complete}).length<=
0){i.css("display","inline-block");if(b>=f.cfMinItems&&!f.cfFired)f.slotId&&(i=f.slotId.toString()+"-visible",g.GWI&&g.GWI.recordLatency(i),g.GWI&&g.GWI.register(i)),f.cfFired=!0;return!0}else return!1});f.$items=c.filter(function(){return!e(d(this))})},updateShelf:function(){var f=0;this.calcWidth&&(this.$shelf.children().each(function(){f+=d(this).outerWidth(!0)}),this.$shelf.width(f));this.touch&&this.$carousel.not(".fresh-shoveler-tablet-app .feed-carousel").height(this.$shelf.outerHeight(!0))},
updateSpinner:function(){this.size()<this.minItems&&this.ajaxSource?this.$spinner.show():(this.size()<this.minItems&&typeof g.ue==="object"&&typeof g.ue.count==="function"&&g.ue.count("shovelerNotEnoughItem",(g.ue.count("shovelerNotEnoughItem")||0)+1),this.$spinner.hide())},updateControls:function(){this.updateArrows();this.updateScrollThumb()},showControls:function(f){this.$thumb.add(this.$buttons).stop(!0,!0).fadeIn({duration:300,complete:f,queue:!1})},hideControls:function(f){var c=this.$thumb;
if(!this.$carousel.hasClass("first-carousel")||this.touch)c=c.add(this.$buttons);c.stop(!0,!0).fadeOut({duration:300,complete:f,queue:!1})},appendCards:function(f){this.$shelf.append(f);this.bindImageLoadEvents(f);this.$carousel.trigger("change")},updateArrows:function(){var f=this,c=f.getDimensions();d.each([{$e:f.$left,enabled:c.shelfLeft>0},{$e:f.$right,enabled:c.shelfLeft<c.maxLeft}],function(c,b){var e=b.$e;b.enabled?e.removeClass("feed-control-disabled"):e.addClass("feed-control-disabled");
f.noOpacity&&(b.enabled?e.css("opacity","1"):e.css("opacity","0.5"))})},updateScrollThumb:function(){var f=this.getDimensions(),c=f.leftRatio*f.pageWidth;this.$thumb.width(Math.min(f.pageRatio*f.pageWidth,f.pageWidth)).each(function(){d(this).animate({left:c},0)})},logCounter:function(f){typeof g.ue==="object"&&typeof g.ue.count==="function"&&(g.ue.count(f,(g.ue.count(f)||0)+1),g.ue.count("gw-shoveler-click",1))},changePage:function(f){var c=this.getDimensions(),e=this.alignWithItem(c.shelfLeft+f*
c.pageWidth),e=Math.min(f<0?e.right:e.left,c.maxLeft);this.locked()||(this.lock(),c.shelfLeft===e?(this.bounce(this.$shelf,-30*f),this.bounce(this.$thumb,6*f)):this.moveShelf(e,400))},moveShelf:function(f,c){function e(){b.updateArrows();b.unlock()}var b=this,c=c||0;b.shelfLeft=f;if(b.touch)b.$viewport.animate({scrollLeft:f},c,"swing",e);else{var d=b.getDimensions(),d=f/d.shelfWidth*d.pageWidth;b.$shelf.animate({left:-f},c,"swing",e);b.$thumb.animate({left:d},c,"swing",function(){b.updateScrollThumb();
b.unlock()})}},getItems:function(){return this.$items},size:function(){return this.getItems().length},alignWithItem:function(f){if(f<0)return{left:0,right:0};var c=this,e=c.getItems(),b=e.map(function(){var b=c.cardPosition(d(this));if(f>=b.left&&f<=b.right)return b}).get(0);return b?b:c.cardPosition(e.last())},cardPosition:function(f){var c=f.position().left,f=c+f.outerWidth(!0);return{left:c,right:f}},bounce:function(f,c){function e(c){var f={};f[b.touch?"left":"marginLeft"]=c;return f}var b=this;
f.each(function(){var f=d(this);f.animate(e(c),400,"swing",function(){f.animate(e(0),100,"swing",b.unlock)})})},setCardMargin:function(f){this.$shelf.children("li").first()&&this.$shelf.children("li").first().css("margin-right")!==f+"px"&&(this.$shelf.children("li").css("margin-right",f+"px"),this.updateShelf())},adjustCardMargin:function(f){f=f===v||f===null?this.defaultCssRightMargin:f;this.setCardMargin(f);var c=this.getDimensions(),c=c.maxLeft<0?Math.ceil(-c.maxLeft/this.size()):f;this.setCardMargin(c<
f?f:c)}};return{createCarousel:function(f,c,j){d(f).each(function(b,f){var d=e.$(f);new i(d,c,j)})}}})})})(function(){var d=window.AmazonUIPageJS||window.P,g=d._namespace||d.attributeErrors;return g?g("AmazonGatewayAuiAssets"):d}(),window);

}
/*
     FILE ARCHIVED ON 19:26:02 Jul 31, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 21:26:24 Dec 11, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 185.225
  exclusion.robots: 0.138
  exclusion.robots.policy: 0.118
  cdx.remote: 0.088
  esindex: 0.013
  LoadShardBlock: 144.811 (3)
  PetaboxLoader3.datanode: 846.669 (5)
  load_resource: 993.346 (2)
  PetaboxLoader3.resolve: 263.779 (2)
*/