var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(m){var h=window.AmazonUIPageJS||window.P,r=h._namespace||h.attributeErrors,g=r?r("AmazonGatewayAuiAssets"):h;g.guardFatal?g.guardFatal(m)(g,window):g.execute(function(){m(g,window)})})(function(m,h,r){m.when("A").register("sg-jsutil",function(g){var k=g.$;return{safeCall:function(g,f){return k.isFunction(g)?g(f):f}}});m.when("A").register("dombinder",function(g){function k(b,a){var c=0;a=a.split(".");for(var d=a.length;c<d;c++)b=b&&b[a[c]];return b}function n(b){return f.map(f(b).data("bind").split(","),
function(a){a=a.split(":");var c=f.trim(a[0]),d=f.trim(a[1]),g=e[c];if(g)return g.init&&g.init(b,d),function(a){g.update(b,d,a)}})}var f=g.$,e={text:{update:function(b,a,c){f(b).text(k(c,a)||"")}},html:{update:function(b,a,c){f(b).html(k(c,a)||"")}},href:{update:function(b,a,c){f(b).attr("href",k(c,a)||"")}},trimText:{update:function(b,a,c){b=f(b);c=b.text();if(c.length>a){for(var d=a-4;0<=d&&0<"[.,-/#!$%^&*;:{}=-_`~()] ".indexOf(c[d]);)d--;b.text(c.substring(0,0<=d?d+1:a-3)+"...")}}},value:{update:function(b,
a,c){f(b).val(k(c,a)||"")}},visible:{update:function(b,a,c){var d=!1;"!"===a.charAt(0)&&(d=!0,a=a.substring(1));a=!!k(c,a);d!==a?f(b).show():f(b).hide()}},css:{init:function(b,a){var c=f(b),d=c.data("dombcss")||[];d[a]="";c.data("dombcss",d)},update:function(b,a,c){b=f(b);var d=b.data("dombcss"),e=d[a];c=k(c,a);e!==c&&(d[a]=c,e&&b.removeClass(e),c&&b.addClass(c))}},attr:{init:function(b,a){var c=f(b),d=c.data("dombattr")||[];d[a]={};c.data("dombattr",d)},update:function(b,a,c){var d=f(b);b=d.data("dombattr");
var e=b[a];c=k(c,a);e!==c&&(b[a]=c,e&&f.each(e,function(a,c){d.removeAttr(a)}),c&&f.each(c,function(a,c){d.attr(a,c)}))}}};return{init:function(b){var a={$root:b,bindings:[]};b.find("[data-bind]").each(function(){f.each(n(this),function(c,b){a.bindings.push(b)})});return a},update:function(b,a){f.each(b.bindings,function(c,b){b(a)})}}});m.when("jQuery").register("gwAjax",function(g){return function(k,n){function f(c,b,f){"object"===typeof h.ue&&"function"===typeof h.ue.count&&e(n.errorCounter||
"gwAjaxError");"function"===typeof h.ueLogError&&h.ueLogError({logLevel:"WARN",attribution:"gwAjax-"+(n.id||k),message:"gwAjax call failed "+(JSON&&JSON.stringify?JSON.stringify({url:k,"params-data":n.params||n.data}):"")});"function"===typeof a&&a(c,b,f)}function e(a){"object"===typeof h.ue&&"function"===typeof h.ue.count&&h.ue.count(a,(h.ue.count(a)||0)+1)}n=g.extend(!0,{},n);var b=n.success,a=n.error;n.success=function(a,d,e){a.error?f(a,d,e):"function"===typeof b&&b(a,d,e)};n.error=f;n.data=n.params?
n.params:n.data;e("gwAjaxCall");n.ajaxCounter&&e(n.ajaxCounter);return g.ajax(k,n)}});m.when("jQuery","gw-hud-punt").execute("gw-hud-sidekick",function(g){g("#gw-hud-grid").css({display:"none"})});m.when("A","sg-jsutil","a-modal","gw-productdb","productdb-binding-helper","sg-media-builder","gw-sims","gw-popover-data").register("gw-popover",function(g,k,n,f,e,b,a,c){function d(a,c){h.uet&&h.uet(a,c,{wb:1})}function B(a){if(h.ue&&"function"===typeof h.ue.count)return h.ue.count(a)||
0}function z(a){h.ue&&"function"===typeof h.ue.count&&h.ue.count(a,(h.ue.count(a)||0)+1)}function l(a){return a.closest("*[data-sgproduct]").data("sgproduct")}function x(a,c){u[a.asin]&&u[a.asin].isResolved()?y.resetSimData():(u[a.asin]=p.Deferred(),a&&a.asin&&c?y.fetch(a,c,u[a.asin]):u[a.asin].reject())}var p=g.$,t={},u={};if(!p("html").hasClass("a-touch")){k=p('<span style="display: none" />').appendTo("body");var w=p("#gw-popover-wrapper"),q=new e(f,w),v=n.create(k,{name:"gw-asin-popover",width:"90%",
"max-width":900,height:590,popoverLabel:c.popoverLabel,closeButton:!1}),y=new a(q),A=p("#gw-quick-look-btn");p("#a-page").delegate("li[data-sgproduct]","mouseenter",function(a){p(a.currentTarget).append(A);p(a.currentTarget).find("[title]").removeAttr("title");A.addClass("active")});A.mouseenter(function(){var a=p(this),c=l(a),a=a.siblings().children("a").attr("href");x(c,a)});p(".bestsellers .listRow a").mouseenter(function(){var a=p(this),c=l(a),a=a.attr("href");x(c,a);!c||!c.asin||t[c.asin]&&t[c.asin].isResolved()||
!(a=f.get(c.asin))||(t[c.asin]=p.Deferred(),t[c.asin].resolve(a))});m.when("gwAjax").execute(function(a){var c={};p("#a-page").delegate(".fresh-shoveler li[data-sgproduct]","mouseenter mousemove",function(b){b=p(b.currentTarget);var d=b.data("sgproduct").asin;if(!t[d]||!t[d].isResolved()){var e=[];b.add(b.prev("li[data-sgproduct]")).add(b.next("li[data-sgproduct]")).each(function(){var a=p(this).data("sgproduct");if(a&&a.asin){var b=f.get(a.asin),d=(b=!(!c[a.asin]&&b&&b.loading))&&1500<g.now()-c[a.asin];
if(!b||d)e.push(a.asin),c[a.asin]=g.now()}});t[d]=p.Deferred();e.length?(a("/gp/gw/ajax/pdb.html",{id:"quicklook-pdb",data:{swn:"productdb-ajax",sa:'{"asins": ["'+e.join('","')+'"]}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:h.ue_id}}).done(function(a){f._add(a);for(var b=0;b<e.length;b++)c[e[b]]=Infinity;t[d].resolve(a)}).fail(t[d].reject),z("freshHoverCount")):t[d].resolve()}})});p("#a-page").delegate("li[data-sgproduct]","mouseleave",function(a){A.removeClass("active")});var C="#a-popover-"+
v.attrs("id")+" ";n=p.map([".a-popover-header { display: none; }",".a-popover-inner { padding: 0px !important; margin: 0px !important; overflow: hidden !important; height: 100% !important; }"],function(a){return C+a}).join(" ");p("head").append("<style>"+n+"</style>");g.on("a:popover:hide:gw-asin-popover",function(a){h.history.state&&h.history.state.popup&&h.history.back();q.clear()});p(h).bind("popstate",function(){v.hide()});return{show:function(a,c){z("freshPopOverOn");d("bb","popoverLatency"+
B("freshPopOverOn"));h.history&&h.history.pushState&&h.history.pushState({popup:1},"");q.setAsin(a,{beforeUpdate:function(f){if(f.loading)return z("freshPopOverLoading"),f;var e=(new b(f.images[0])).autoCrop().scaleXY(500,400).build(),e={url:c,image:e,actionUrl:{action:"/gp/product/handle-buy-box/"+function(a){return a.substring(a.indexOf("/ref=")+1,a.length)}(c)}};f.reviews&&(e.reviews=p.extend({},f.reviews,{url:c+"#customerReviews"}));p.when(u[a],t[a]).done(function(c,b){y.showSims(a,c)});u[a].fail(y.setNoSimView);
d("cf","popoverLatency"+B("freshPopOverOn"));return p.extend({},f,e)}});v.show()},hide:function(){v.hide()}}}});m.when("A","sg-media-builder","gw-productdb").register("gw-sims",function(g,k,n){var f=g.$;return function(e){function b(a,c){h.uet&&h.uet(a,c,{wb:1})}function a(a){if(h.ue&&"function"===typeof h.ue.count)return h.ue.count(a)||0}function c(a){h.ue&&"function"===typeof h.ue.count&&h.ue.count(a,(h.ue.count(a)||0)+1)}function d(){if(!C){C=!0;D.hide();G.show();F.animate({height:"100%"},
300);var c=0,d=0,e=0,g=parseInt(G.css("width"),10),l=G.find(".sims-img-link");l.each(function(a,b){c+=b.clientWidth;g<c?f(b).hide():(d=c,e+=1)});var k=g-d;0<k&&(k=Math.floor(20+k/e-1),20<k&&l.css({"padding-right":k/2+"px","padding-left":k/2+"px"}));l="popoverLatency"+a("freshPopOverOn");b("be",l);h.uex&&h.uex("ld",l,{wb:1})}}function g(){0===--q&&d()}function z(a,b){var d=f("<a>"),g=f("<div>");d.attr("class","sims-img-link");g.addClass("sims-img-border");b&&d.addClass("selected");d.click(function(){c("freshPopOverSimsClick");
G.find(".sims-img-link").removeClass("selected");f(this).addClass("selected");e.clear();e.setAsin(a.asin,{beforeUpdate:function(b){b=f.extend(!0,{},a);var d=a.url;if(b.loading)c("freshPopOverLoading");else{var e=(new k(b.images[0])).autoCrop().scaleXY(500,400).build(),e={url:d,image:e,actionUrl:{action:"/gp/product/handle-buy-box/"+x(d)}};b.reviews&&(e.reviews=f.extend({},b.reviews,{url:d+"#customerReviews"}));b=f.extend({},b,e)}return b}})});return d.append(g)}function l(){f.each(v,function(a,c){c.url=
c.url.replace(/ref=gw_pdb_pdt-[\d]+/,x(y)+"&gw_sims-"+a)})}function x(a){return 0<=a.indexOf("redirect.html?")?a.replace(/.*redirect.html|(token|location)=.*?&/g,""):a.substring(a.indexOf("/ref=")+1,a.length)}function p(){C=!1;l();var a=[];q=v.length>q?q:v.length;f(v).each(function(c,b){b.loading=!1;if(b.images[0].src){var d=(new k(b.images[0])).autoCrop().scaleXY(130,100).build().src,e=f("<img>");e.attr("src",d);e.attr("class","sims-img");e.load(g);d=f("<div>");d.attr("class","sims-img-container");
var l=f("<div>");l.addClass("sims-img-overlay");f(d).append(l);d.append(e);e=z(b,0===c);e.append(d);a.push(e)}return c<q-1});q=a.length;f(a).each(function(a,c){G.append(c)});setTimeout(d,A)}function t(){m.when("gw-popover").execute(function(a){a.hide()})}function u(){D.hide();F.addClass("hidden");E.bind("click",t)}function w(){G.empty();F.add(D).removeAttr("style");F.removeClass("hidden");E.unbind("click",t);D.show();G.hide();q=8;v=[]}var q,v,y,A=1E4,C=!1,E=f("#sims-section"),F=E.find(".sims-wrapper"),
D=E.find(".sims-loading"),G=E.find(".sims-details");f("#gw-asin-popover");return{fetch:function(c,d,f){b("af","popoverLatency"+a("freshPopOverOn"));w();y=d;c.url=y;v.push(c);d=n.get(c.asin);setTimeout(f.reject,A);d.sims?f.resolve(d.sims):m.when("gwAjax").execute(function(a){a("/gp/gw/ajax/pdb.html",{id:"quicklook-sims-pdb",data:{swn:"productdb-ajax",sa:'{"asins": [], "entityId":"'+c.asin+'","datasetId": "purchase"}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:h.ue_id}}).done(function(a){if(a&&
a.p&&0<a.p.length){var b=c.asin,d=a.p;d&&(n.get(b).sims||n.addSims(b,d));return f.resolve(a.p)}return f.reject()}).fail(f.reject)});return f},setNoSimView:u,showSims:function(a,b){var d=n.get(a);d.loading?c("freshPopOverSimLoadBeforePrimeAsin"):v=d.sims?f.merge([d],d.sims):f.merge([d],b);4<v.length?p():(c("simsLessThanThreshold"),u())},resetSimData:w,setWaitPeriod:function(a){A=a}}}});m.when("A").execute(function(g){var k=g.$,n,f;if(!g.$("html").hasClass("a-touch"))if(h.cvox)h.ue&&h.ue.tag&&
h.ue.tag("screenReaderOn");else{k("#a-page").delegate("*[data-sgproduct] #gw-quick-look-btn","click",function(b){e(b)});k("#a-page").delegate(".bestseller-list *[data-sgproduct]","click",function(b){e(b)});m.when("gw-popover").execute(function(b){n=b;k("#gw-popover-close").click(function(){n.hide()});f&&n.show.apply(n,f)});var e=function(b){if(!(1<b.which||b.shiftKey||b.altKey||b.metaKey||b.ctrlKey)){var a,c;k(b.target).parents(".bestseller-list").length?(a=k(b.currentTarget).data("sgproduct"),c=
k(b.target).closest("a").attr("href")):(a=k("#gw-quick-look-btn").closest("*[data-sgproduct]").data("sgproduct"),c=k("#gw-quick-look-btn").siblings().children("a").attr("href"));var d=[a.asin,c];a.asin&&c&&(b.preventDefault(),n?n.show.apply(n,d):f=d)}}}});m.when("A","sg-jsutil","dombinder").register("productdb-binding-helper",function(g,k,n){return function(f,e){function b(a,c){n.update(l,d(c.beforeUpdate,a));a.loading||d(c.load,a)}function a(a){c();h=function(){a(g)};g.pdb_observe(h)}
function c(){g&&h&&(g.pdb_unobserve(h),h=null)}var d=k.safeCall,g=null,h=null,l=n.init(e);this.setAsin=function(d,e){e=e||{};c();g=f.get(d);b(g,e);g.loading&&a(function(a){b(a,e)});return g};this.clear=function(){c();g={};n.update(l,g)}}});h.P&&m.when("jQuery","afterLoad").register("gw-resource-logger",function(g){return{instrumentResources:function(k){var n;n=!1;if(g.isArray(k)&&!g.isEmptyObject(k)){n=!0;for(var f=0;f<k.length;f++){var e=k[f];if("id"in e&&"regex"in e&&"initiator"in e){if(!("string"===
typeof e.id&&"string"===typeof e.initiator&&e.regex instanceof RegExp)){n=!1;break}}else{n=!1;break}}}f=h.performance&&"function"===typeof h.performance.getEntriesByType&&"undefined"!==typeof h.performance.getEntriesByType("resource")&&"undefined"!==typeof h.ue;if(n&&f){n=Array(k.length);for(f=0;f<n.length;f++)n[f]=!1;for(e=f=0;e<h.performance.getEntriesByType("resource").length&&f<k.length;e++)for(var b=h.performance.getEntriesByType("resource")[e],a=b.name,c=b.initiatorType,d=0;d<k.length;d++)if(!n[d]){var m=
k[d].regex;if(c===k[d].initiator&&m.test(a)){a=k[d].id;c=b;b=c.duration;h.ue.count&&(h.ue.count(a+":duration",b),h.ue.count(a+":startTime",c.startTime));h.ue.tag&&(c=void 0,c=50>b?a+":cached":a+":notCached",h.ue.tag(c));n[d]=!0;f++;break}}}}}});m.register("sg-media-builder",function(){return function(g){var k=this,n=g.src,f=[];k.build=function(){var e=f.join("_");return{src:n.replace(/\.([^.]+)$/,"._"+e+"_.$1"),alt:g.alt}};k.autoCrop=function(){f.push("AC");return k};k.scaleX=function(e){f.push("SX"+
e);return k};k.scaleY=function(e){f.push("SY"+e);return k};k.upScaleX=function(e){f.push("UX"+e);return k};k.upScaleY=function(e){f.push("UY"+e);return k};k.scaleXY=function(f,b){return k.upScaleX(f).scaleY(b)}}});m.when("A","gwAjax").register("shogunProductDB",function(g,k){function n(b){var a=[];e[b]={loading:!0,pdb_observe:function(c){a.push(c)},pdb_unobserve:function(c){a=g.$.grep(a,function(a){return a!==c})},_trigger:function(){g.$.each(a,function(){this.call(e[b])})}};return e[b]}
function f(b,a){this.ajaxUrl=b;this.experienceStr=a;this._add=function(a){a.p&&g.$.each(a.p,function(a,c){if(c.asin){var b=e[c.asin]||n(c.asin);g.$.extend(b,c,{loading:!1,error:!1});b._trigger(c)}})};this.addSims=function(a,b){if(b){var f=e[a]||n(a);g.$.extend(f,{sims:b});f._trigger(a)}};this._ajax=function(c,d){var f=g.$.extend(!0,{},b,{params:{sa:JSON.stringify(c),oe:a}});h.ue_sid&&(f.url+="/"+h.ue_sid);h.ue_id&&(f.params.rrid=h.ue_id);return k(f.url,{method:f.method,params:f.params,success:d.success,
error:d.error,id:"gw-jslibs-"+d.id})};this.get=function(a){return a in e?e[a]:n(a)}}var e={};return function(b,a){return new f(b,a)}});m.when("jQuery","p-detect").register("component-feed-carousel",function(g,k){var n=g.extend(!0,{},k);g.each({pointerPrefix:function(){return"onmspointerup"in document||"onpointerup"in document?"onpointerup"in document?"pointer":"MSPointer":!1},actionMode:function(){var b=n.capabilities.pointerPrefix;return b?b:n.capabilities.touch?"touch":"mouse"}},function(b,
a){n.capabilities[b]=a()});var f={};g.each({start:{mouse:"down",touch:"start",pointer:"down",MSPointer:"Down"},end:{mouse:"up",touch:"end",pointer:"up",MSPointer:"Up"}},function(b,a){var c=n.capabilities.actionMode,d="string"===typeof a?a:a[c];f[b]=d?c+d:a.mouse===r?"":"mouse"+a.mouse});n.action=f;var e=function(b,a,c){this.init(b,a,c)};e.prototype={init:function(b,a,c){var d=this;g("html").hasClass("a-touch")&&b.addClass("feed-carousel-touch");d.adjustMarginOnChange=!0;d.defaultCssRightMargin=null;
d.minItems=a||10;d.imgClass=".product-image";d.$carousel=b;d.cfMinItems=c||6;d.cfFired=!1;d.shovelerReadyFired=!1;d.slotId=d.getSlotId();d.touch=d.$carousel.hasClass("feed-carousel-touch");d.ajaxSource=d.$carousel.parent().hasClass("ajaxSource");d.$shelf=d.$carousel.find(".feed-carousel-shelf");d.$viewport=d.$carousel.find(".feed-carousel-viewport");d.$spinner=d.$carousel.find(".spinner");d.$left=g(".feed-carousel-control.feed-left",b);d.$right=g(".feed-carousel-control.feed-right",b);d.$buttons=
g(".feed-carousel-control",b);d.$thumb=g(".feed-scrollbar-thumb",b);d.shelfLeft=-1*parseInt(d.$shelf.css("left"),10);d.calcWidth=g("html").hasClass("a-lt-ie9");d.noOpacity=g("html").hasClass("a-lt-ie9");d.$left.attr("aria-hidden",!0);d.$right.attr("aria-hidden",!0);d.bindEvents();d.$carousel.data("Carousel",d);d.$carousel.trigger("change");d.token=!1;d.lock=function(){d.token=!0};d.unlock=function(){d.token=!1};d.locked=function(){return d.token};m.when("gw-first-carousel").execute(function(){d.first=
d.$carousel.hasClass("first-carousel");d.shouldControlsOn()?d.showControls():d.hideControls()})},getSlotId:function(){var b=this.$carousel.closest(".gw-widget-instrument");return 0<b.length?g(b[0]).attr("id"):null},bindEvents:function(){function b(a){return n.capabilities.pointerPrefix&&-1<g.inArray(a.originalEvent.pointerType,[2,"touch"])||"touch"===n.capabilities.actionMode}var a=this,c=g("body");a.$buttons.ready(function(c){a.shovelerReadyFired||(a.slotId&&(c=a.slotId.toString()+"-active",h.GWI&&
h.GWI.recordLatency(c),h.GWI&&h.GWI.register(c)),a.shovelerReadyFired=!0)});a.$carousel.change(function(c){a.updateItems();a.updateSpinner();a.updateShelf();a.updateControls();null===a.defaultCssRightMargin&&a.$shelf.children("li").first()&&(a.defaultCssRightMargin=parseInt(a.$shelf.children("li").first().css("margin-right"),10));a.adjustMarginOnChange&&a.adjustCardMargin()});a.$left.click(function(c){c.preventDefault();a.changePage(-1);a.slotId&&a.logCounter("gw-"+a.slotId.toString()+"-left")});
a.$right.click(function(c){c.preventDefault();a.changePage(1);a.slotId&&a.logCounter("gw-"+a.slotId.toString()+"-right")});a.bindImageLoadEvents(a.$shelf);var d;g(h).resize(function(){clearTimeout(d);d=setTimeout(function(){var c=a.getDimensions(),c=Math.max(Math.min(c.shelfLeft,c.maxLeft),0);a.moveShelf(c)},100)});a.$thumb.mousedown(function(b){var d=b.clientX;1===b.which&&(b.preventDefault(),a.$carousel.addClass("scrolling"),c.bind("mousemove.feed-carousel",function(c){var b=a.getDimensions(),b=
Math.max(Math.min(b.shelfLeft+1/b.pageRatio*(c.clientX-d),b.maxLeft),0);d=c.clientX;a.moveShelf(b)}),g(document).bind("selectstart.feed-carousel",function(){return!1}))});c.add(h).mouseup(function(b){a.$carousel.removeClass("scrolling");a.$carousel.hasClass("hovering")||a.hideControls();c.unbind("mousemove.feed-carousel");g(document).unbind("selectstart.feed-carousel")});a.$carousel.hover(function(){a.$carousel.addClass("hovering");clearTimeout(a.hoverTimer);a.hoverTimer=setTimeout(function(){a.$carousel.hasClass("hovering")&&
!a.$carousel.hasClass("touching")?a.showControls():a.$carousel.removeClass("touching")},300)},function(){a.$carousel.removeClass("hovering touching");clearTimeout(a.hoverTimer);a.$carousel.hasClass("scrolling")||(a.hoverTimer=setTimeout(function(){a.$carousel.hasClass("hovering")||a.hideControls()},600))});a.$carousel.bind(n.action.start,function(c){b(c)&&(a.$carousel.addClass("touching"),clearTimeout(a.touchTimer),a.touchTimer=setTimeout(function(){a.$carousel.removeClass("touching")},5E3))});a.$carousel.bind(n.action.end,
function(c){b(c)&&(a.$carousel.removeClass("touching"),clearTimeout(a.touchTimer),clearTimeout(a.hoverTimer))});a.$viewport.scroll(function(){a.shelfLeft=a.$viewport.scrollLeft();a.updateControls()})},bindImageLoadEvents:function(b){var a=this;g(a.imgClass,b).one("load",function(){a.$carousel.trigger("change")})},getDimensions:function(){var b=this.$shelf.width(),a=this.shelfLeft,c=this.$carousel.width();return{pageWidth:c,shelfWidth:b,shelfLeft:a,pageRatio:c/b,leftRatio:a/b,maxLeft:b-c}},updateItems:function(){var b=
this,a=b.$shelf.find(".feed-carousel-card"),c=function(a){return"none"===a.css("display")};a.each(function(a,f){var e=g(f);if(!c(e))return!0;e.attr("aria-setsize",b.$shelf.find(".feed-carousel-card").size());e.attr("aria-posinset",a+1);e.attr("aria-hidden",!1);e.attr("role","listitem");return 0>=e.find(b.imgClass).filter(function(){return!this.complete}).length?(e.css("display","inline-block"),a+1>=b.cfMinItems&&!b.cfFired&&(b.slotId&&(e=b.slotId.toString()+"-visible",h.GWI&&h.GWI.recordLatency(e),
h.GWI&&h.GWI.register(e)),b.cfFired=!0),!0):!1});b.$items=a.filter(function(){return!c(g(this))})},updateShelf:function(){var b=0;this.calcWidth&&(this.$shelf.children().each(function(){b+=g(this).outerWidth(!0)}),this.$shelf.width(b));this.touch&&this.$carousel.not(".fresh-shoveler-tablet-app .feed-carousel").height(this.$shelf.outerHeight(!0))},updateSpinner:function(){this.size()<this.minItems&&this.ajaxSource?this.$spinner.show():(this.size()<this.minItems&&"object"===typeof h.ue&&"function"===
typeof h.ue.count&&h.ue.count("shovelerNotEnoughItem",(h.ue.count("shovelerNotEnoughItem")||0)+1),this.$spinner.hide())},updateControls:function(){this.updateArrows();this.updateScrollThumb()},shouldControlsOn:function(){return this.first&&!this.touch},showControls:function(b){this.$thumb.add(this.$buttons).stop(!0,!0).fadeIn({duration:300,complete:b,queue:!1})},hideControls:function(b){var a=this.$thumb;this.shouldControlsOn()||(a=a.add(this.$buttons));a.stop(!0,!0).fadeOut({duration:300,complete:b,
queue:!1})},appendCards:function(b){this.$shelf.append(b);this.bindImageLoadEvents(b);this.$carousel.trigger("change")},updateArrows:function(){var b=this,a=b.getDimensions();g.each([{$e:b.$left,enabled:0<a.shelfLeft},{$e:b.$right,enabled:a.shelfLeft<a.maxLeft}],function(a,d){var f=d.$e;d.enabled?f.removeClass("feed-control-disabled"):f.addClass("feed-control-disabled");b.noOpacity&&(d.enabled?f.css("opacity","1"):f.css("opacity","0.5"))})},updateScrollThumb:function(){var b=this.getDimensions(),
a=b.leftRatio*b.pageWidth,b=Math.min(b.pageRatio*b.pageWidth,b.pageWidth);this.$thumb.width(b).each(function(){g(this).animate({left:a},0)})},logCounter:function(b){"object"===typeof h.ue&&"function"===typeof h.ue.count&&(h.ue.count(b,(h.ue.count(b)||0)+1),h.ue.count("gw-shoveler-click",1))},changePage:function(b){var a=this.getDimensions(),c=this.alignWithItem(a.shelfLeft+b*a.pageWidth),c=Math.min(0>b?c.right:c.left,a.maxLeft);this.locked()||(this.lock(),a.shelfLeft===c?(this.bounce(this.$shelf,
-30*b),this.bounce(this.$thumb,6*b)):this.moveShelf(c,400))},moveShelf:function(b,a){function c(){d.updateArrows();d.unlock()}var d=this;a=a||0;d.shelfLeft=b;if(d.touch)d.$viewport.animate({scrollLeft:b},a,"swing",c);else{var f=d.getDimensions(),f=b/f.shelfWidth*f.pageWidth;d.$shelf.animate({left:-b},a,"swing",c);d.$thumb.animate({left:f},a,"swing",function(){d.updateScrollThumb();d.unlock()})}},getItems:function(){return this.$items},size:function(){return this.getItems().length},alignWithItem:function(b){if(0>
b)return{left:0,right:0};var a=this,c=a.getItems(),d=c.map(function(){var c=a.cardPosition(g(this));if(b>=c.left&&b<=c.right)return c}).get(0);return d?d:a.cardPosition(c.last())},cardPosition:function(b){var a=b.position().left;b=a+b.outerWidth(!0);return{left:a,right:b}},bounce:function(b,a){function c(a){var c={};c[d.touch?"left":"marginLeft"]=a;return c}var d=this;b.each(function(){var b=g(this);b.animate(c(a),400,"swing",function(){b.animate(c(0),100,"swing",d.unlock)})})},setCardMargin:function(b){this.$shelf.children("li").first()&&
this.$shelf.children("li").first().css("margin-right")!==b+"px"&&(this.$shelf.children("li").css("margin-right",b+"px"),this.updateShelf())},adjustCardMargin:function(b){b=b===r||null===b?this.defaultCssRightMargin:b;this.setCardMargin(b);var a=this.getDimensions(),a=0>a.maxLeft?Math.ceil(-a.maxLeft/this.size()):b;this.setCardMargin(a<b?b:a)}};return{createCarousel:function(b,a,c){g(b).each(function(b,f){var k=g(f);new e(k,a,c)})}}});m.register("billboard-widget",function(){return function(g,
k){m.when("gwi-util").execute(function(n){function f(){for(var c=0;c<a.length;++c)if(!a[c].complete)return;n.logScope(b.visible);n.logScope(b.active)}k=k||[];var e;e=n.getParent(g);var b=n.gwiData(e),a=[];for(e=0;e<k.length;++e)(function(c){var b=new Image;b.onload=f;b.src=k[c];a[c]=b})(e);f()})}});m.register("gwi-util",function(){return{logScope:function(g){var k=h.GWI;g&&k&&(k.recordLatency(g),k.register(g))},getParent:function(g){return(g=document.getElementById(g))&&g.parentElement},
gwiData:function(g){var k;if(k=g)g=g.getAttribute("data-gwi"),k=h.JSON&&JSON.parse&&JSON.parse(g);return k||{}}}})});

}
/*
     FILE ARCHIVED ON 16:45:41 Dec 31, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 21:35:41 Dec 11, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 129.508
  exclusion.robots: 0.077
  exclusion.robots.policy: 0.068
  cdx.remote: 0.055
  esindex: 0.009
  LoadShardBlock: 32.446 (3)
  PetaboxLoader3.datanode: 46.308 (4)
  load_resource: 76.527
  PetaboxLoader3.resolve: 60.174
*/