var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

var _yt_www={};(function(m){var window=this;m.ba=function(a){return function(){return m.ca[a].apply(this,arguments)}};m.l=function(a,b){for(var c=a.split("."),d=b||m.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.ea=function(){};
m.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ga=function(a){return"array"==(0,m.fa)(a)};m.n=function(a){return"string"==typeof a};m.ha=function(a){return"function"==(0,m.fa)(a)};var ia=function(a,b,c){return a.call.apply(a.bind,arguments)};
var ja=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return m.q.apply(null,arguments)};m.ka=function(a,b){for(var c in b)a[c]=b[c]};
m.r=function(a,b){var c=a.split("."),d=m.da;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b};m.s=function(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.RJ=function(a,c,g){var h=Array.prototype.slice.call(arguments,2);return b.prototype[c].apply(a,h)}};m.la=function(a,b){var c=(0,m.ma)(a,b),d;(d=0<=c)&&(0,m.na)(a,c);return d};
m.na=function(a,b){m.oa.splice.call(a,b,1)};m.qa=function(a,b,c){return 2>=arguments.length?m.oa.slice.call(a,b):m.oa.slice.call(a,b,c)};m.ra=function(){};m.sa=function(){this.b=[];this.Yc={}};m.ta=function(a){ua(m.va,arguments)};m.t=function(a,b){return a in m.va?m.va[a]:b};m.wa=function(a){ua(m.xa,arguments)};
m.u=function(a,b){if((0,m.ha)(a)&&(0,m.l)("ytsched.enableSetTimeout")){var c=(0,m.l)("yt.scheduler.instance.addJob");if(c)return c(a,0,b);(0,m.r)("ytsched.enableSetTimeout",!1)}(0,m.ha)(a)&&(a=(0,m.ya)(a));return window.setTimeout(a,b)};m.w=function(a){(0,m.l)("ytsched.enableSetTimeout")?(0,m.l)("yt.scheduler.instance.cancelJob")(a):window.clearTimeout(a)};m.ya=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw(0,m.za)(b),b;}}:a};
m.za=function(a,b){if(window&&window.yterr){var c=(0,m.l)("yt.www.errors.log");c?c(a,b):(c=(0,m.t)("ERRORS")||[],c.push(a),(0,m.ta)("ERRORS",c))}};m.Aa=function(a){ua(m.Ba,arguments)};m.Ca=function(a){return a in m.Ba};var ua=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.Da=function(){return(0,m.l)("yt.scheduler.instance")&&!(0,m.l)("ytsched.enableSetTimeout")};
m.Ea=function(a,b,c){void 0===c&&(c=window.NaN);var d=(0,m.l)("yt.scheduler.instance.addJob");if(d)return(0,window.isNaN)(c)&&(c=0),d(a,b,c);if((0,window.isNaN)(c))a();else return(0,m.u)(a,c||0)};m.Fa=function(a,b){return(0,m.Ea)(a,0,b)};m.Ga=function(a,b){return(0,m.Ea)(a,1,b)};m.x=function(a,b,c){var d=Ha();return d?d.subscribe(a,function(){function d(){b.apply(c||window,g)}var g=arguments;try{Ia[a]?d():(0,m.Da)()?(0,m.Fa)(d):(0,m.u)(d,0)}catch(h){(0,m.za)(h)}},c):0};
m.Ja=function(a){var b=Ha();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.y)(a,function(a){b.unsubscribeByKey(a)}))};m.A=function(a,b){var c=Ha();return c?c.publish.apply(c,arguments):!1};var Ka=function(a,b){Ia[a]=!0;var c=Ha();c&&c.publish.apply(c,arguments);Ia[a]=!1};var Ha=function(){return(0,m.l)("yt.pubsub.instance_")};m.La=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.D=(0,m.ya)(d||null);this.k=(0,m.ya)(e||null);this.j=[]};
m.Ma=function(a){a.name in Na&&Oa(a.name);Na[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.y)(a.deps,function(b){if(!(b in Na))throw Error("Module "+b+" required by "+a.name);Na[b].reqs.push(a.name)});(0,m.Da)()?(0,m.Ga)((0,m.q)(a.enable,a)):a.enable()};var Oa=function(a){if(a in Na){var b=Na[a];(0,m.y)(b.reqs,function(a){Oa(a)});try{b.disable()}catch(c){}delete Na[a]}};m.Pa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
m.Qa=function(a,b){var c=a.match(Ra);window.spf.scripts.load(a,b,c?c[1]:"")};m.Sa=function(a){a&&((0,m.n)(a)?(0,m.Qa)(a):(0,m.ga)(a)?(0,m.y)(a,function(a){(0,m.Sa)(a)}):(0,m.Pa)(a,function(a,c){(0,m.Qa)(c,function(){(0,m.Sa)(a)})}))};m.Ta=function(a,b){if(a){var c=new window.Image,d=""+Ua++;Va[d]=c;c.onload=c.onerror=function(){b&&Va[d]&&b();delete Va[d]};c.src=a;c=eval("null")}};m.Wa=function(a,b,c){(0,m.Xa)(c)[a]=b||(0,m.B)()};var Ya=function(a){return Math.max(0,a.responseStart-a.navigationStart)};
m.Za=function(a,b){var c=(0,m.Xa)(a),d=$a(a).span,e=(0,m.ab)(a),g=b||(0,m.l)("yt.timing.reportbuilder_");if(g){if(g=g.apply(null,[c,d,e,a]))bb(g),(0,m.cb)(a)}else{var g={v:2,s:"youtube",action:(0,m.t)("TIMING_ACTION")},h=(0,m.t)("TIMING_INFO")||{},k;for(k in h)e[k]=h[k];k=e.srt;delete e.srt;if(!k&&0!==k)try{k=Ya((window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance).timing)}catch(p){e.pt&&(k=e.pt)}if(k||0===k)e.srt=k;c.aft||(c.aft=c.vr&&c.cl&&c.cl>c.vr?c.cl:c.vr?
c.vr:c.ol);c.vr&&c.gv&&(d.vl=Math.round(c.vr-c.gv));for(var v in e)"_"!=v.charAt(0)&&(g[v]=e[v]);e={};v=[];k=c._start;for(var z in c)"_"!=z.charAt(0)&&(h=Math.max(Math.round(c[z]-k),0),e[z]=h,v.push(z+"."+h));g.rt=v.join(",");c={};z=[];for(var I in d)"_"!=I.charAt(0)&&(c[I]=d[I],z.push(I+"."+d[I]));g.it=z.join(",");bb(g);(d=(0,m.l)("ytdebug.logTiming"))&&d(g,e,c);(0,m.cb)(a)}};
var db=function(){var a=(0,m.t)("TIMING_ACTION"),b=!!(0,m.t)("TIMING_WFF"),c=(0,m.Xa)(void 0);a&&c._start&&(b&&c.vr?(0,m.Za)(void 0):b||!c.ol&&!c.aft||(0,m.Za)(void 0))};var bb=function(a){var b="https:"==window.location.protocol?"https://web.archive.org/web/20131201000838/https://gg.google.com/csi":"https://web.archive.org/web/20131201000838/http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];(0,m.Ta)(b+"?"+c.substring(1))};m.Xa=function(a){return $a(a).tick};m.ab=function(a){return $a(a).info};var $a=function(a){return(0,m.l)("ytcsi."+(a||"")+"data_")||(0,m.cb)(a)};
m.cb=function(a){var b={tick:{},span:{},info:{}};(0,m.r)("ytcsi."+(a||"")+"data_",b);return b};var eb=function(){(0,m.Wa)("ol");(0,m.A)("init");var a=(0,m.t)("PAGE_NAME");a&&(0,m.A)("init-"+a);db()};var fb=function(){var a=(0,m.t)("PAGE_NAME");a&&Ka("dispose-"+a);Ka("dispose")};var gb=function(){eb()};var hb=function(){fb()};
var ib=function(a,b,c){for(var d=window.document.getElementsByTagName("script"),e=!1,g=0,h=d.length;g<h;g++)if(0<d[g].src.indexOf("/debug-")){e=!0;break}e&&(d=Error(),d.message=a,d.fileName=b,d.lineNumber=c,(0,m.za)(d))};var jb=function(){kb=1;(0,m.cb)(void 0);lb(mb);Ka("navigate")};var nb=function(a,b){var c=1==kb;kb=2;c?(lb(ob),pb()):lb(qb);b.swfcfg&&rb(b.swfcfg)};var sb=function(){};
var tb=function(a,b){var c=1==kb;kb=3;(0,m.Wa)("_start",b.timing.responseStart);var d=Ya(b.timing);(0,m.ab)(void 0).srt=d;var d=b.timing.responseStart-b.timing.fetchStart,e=$a(void 0).span,g=(0,m.Xa)(void 0);"number"==typeof d?e.req=d:d in g&&(e.req=(0,m.B)()-g[d]);c&&(lb(ub),pb());b.swfcfg&&rb(b.swfcfg)};var vb=function(a){lb(wb);if(a.timing){var b={spfProcessCss:"cl",spfProcessHtml:"hr",spfProcessJs:"jl"},c;for(c in b)a.timing[c]&&(0,m.Wa)(b[c],a.timing[c])}eb();kb=0};var xb=function(a,b){(0,m.za)(b)};
var yb=function(){zb()};var Ab=function(){};var pb=function(){var a=(0,m.l)("ytbin.qoe.getInstance");a&&(a=a(),a.reset(),a.start());window.scroll(0,0);fb();for(var b in m.va)delete m.va[b];(b=(0,m.l)("yt.www.watch.player.dispose"))&&b()};var rb=function(a){(0,m.r)("ytplayer.config",null);var b=(0,m.l)("yt.player.cancelAll");b&&b();a=a||null;b=(0,m.l)("yt.player.embed");a&&b&&(b("player-api",a),a=(0,m.Bb)(a),a.loaded=!0);(0,m.r)("ytplayer.config",a)};
var lb=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.innerHTML="<dt><dd>",window.document.body.appendChild(b));(0,m.u)(function(){var c=a[0],d=a[1],e=a[2];b.className="";var g=b.style;g.transitionDuration=g.webkitTransitionDuration=c+"ms";g.width=d+"%";(0,m.w)(Cb);Cb=(0,m.u)(function(){b.className=e},c)},0)};
var zb=function(){var a=wb[0]+50;(0,m.w)(Cb);Cb=(0,m.u)(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var Db=function(){m.La.call(this,"www/base");this.b=0};var Eb=function(a,b){var c;(c=(c=b.match(Fb))?c[1]+"/"+c[2]:"")&&Oa(c)};m.ca=[];m.Gb=m.Gb||{};m.da=this;m.Hb="closure_uid_"+(1E9*Math.random()>>>0);m.B=Date.now||function(){return+new Date};
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};m.oa=Array.prototype;m.ma=m.oa.indexOf?function(a,b,c){return m.oa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if((0,m.n)(a))return(0,m.n)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};m.y=m.oa.forEach?function(a,b,c){m.oa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.n)(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
m.Ib=m.oa.filter?function(a,b,c){return m.oa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,h=(0,m.n)(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var p=h[k];b.call(c,p,k,a)&&(e[g++]=p)}return e};m.Jb=m.oa.map?function(a,b,c){return m.oa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=(0,m.n)(a)?a.split(""):a,h=0;h<d;h++)h in g&&(e[h]=b.call(c,g[h],h,a));return e};
m.Kb=m.oa.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.oa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.y)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Lb=m.oa.some?function(a,b,c){return m.oa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.n)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return!0;return!1};
m.Mb=m.oa.every?function(a,b,c){return m.oa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.n)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&!b.call(c,e[g],g,a))return!1;return!0};m.ra.prototype.ie=!1;m.ra.prototype.va=(0,m.ba)(14);m.ra.prototype.dispose=function(){this.ie||(this.ie=!0,this.Q())};m.ra.prototype.Q=function(){if(this.Tb)for(;this.Tb.length;)this.Tb.shift()()};(0,m.s)(m.sa,m.ra);m.f=m.sa.prototype;m.f.Su=1;m.f.Gl=0;m.f.R=function(a,b,c){var d=this.Yc[a];d||(d=this.Yc[a]=[]);var e=this.Su;this.b[e]=a;this.b[e+1]=b;this.b[e+2]=c;this.Su=e+3;d.push(e);return e};m.f.ra=(0,m.ba)(5);m.f.qe=function(a){if(0!=this.Gl)return this.j||(this.j=[]),this.j.push(a),!1;var b=this.b[a];if(b){var c=this.Yc[b];c&&(0,m.la)(c,a);delete this.b[a];delete this.b[a+1];delete this.b[a+2]}return!!b};
m.f.O=function(a,b){var c=this.Yc[a];if(c){this.Gl++;for(var d=(0,m.qa)(arguments,1),e=0,g=c.length;e<g;e++){var h=c[e];this.b[h+1].apply(this.b[h+2],d)}this.Gl--;if(this.j&&0==this.Gl)for(;c=this.j.pop();)this.qe(c);return 0!=e}return!1};m.f.clear=function(a){if(a){var b=this.Yc[a];b&&((0,m.y)(b,this.qe,this),delete this.Yc[a])}else this.b.length=0,this.Yc={}};m.f.fb=(0,m.ba)(4);m.f.Q=function(){m.sa.L.Q.call(this);delete this.b;delete this.Yc;delete this.j};m.va=window.yt&&window.yt.config_||{};(0,m.r)("yt.config_",m.va);m.xa=window.yt&&window.yt.tokens_||{};(0,m.r)("yt.tokens_",m.xa);m.Ba=window.yt&&window.yt.msgs_||{};(0,m.r)("yt.msgs_",m.Ba);m.Nb="Microsoft Internet Explorer"==window.navigator.appName;m.Ob=(0,m.l)("yt.scheduler.instance.cancelJob")||m.ea;var Pb=(0,m.l)("yt.pubsub.instance_")||new m.sa;m.sa.prototype.subscribe=m.sa.prototype.R;m.sa.prototype.unsubscribeByKey=m.sa.prototype.qe;m.sa.prototype.publish=m.sa.prototype.O;m.sa.prototype.clear=m.sa.prototype.clear;(0,m.r)("yt.pubsub.instance_",Pb);var Ia={};m.f=m.La.prototype;m.f.enable=function(){(0,m.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.R("init-"+a,this.init,this),this.R("dispose-"+a,this.dispose,this),(0,m.t)("PAGE_NAME")==a&&this.init())},this)};m.f.init=function(){this.D&&this.D()};m.f.dispose=function(){this.k&&this.k()};m.f.disable=function(){this.dispose();this.clear()};m.f.R=function(a,b,c){a=(0,m.x)(a,b,c);this.j.push(a);return a};m.f.clear=function(){(0,m.Ja)(this.j);this.j=[]};var Na=(0,m.l)("yt.modules.registry_")||{};(0,m.r)("yt.modules.registry_",Na);var Ra=/jsbin\/(?:[a-zA-Z0-9_-]+\/)*(?:debug-)?([a-zA-Z0-9_-]+?)(?:-vfl|.js)/,Fb=/^([a-z]+)_(\w+)_mod$/;var Va={},Ua=0;var kb,Cb,mb=[900,60,"waiting"],ub=[500,99,"waiting"],ob=[300,60,"waiting"],qb=[400,99,"waiting"],wb=[300,101,"done"];window.yt=window.yt||{};(0,m.r)("yt.setConfig",m.ta);(0,m.r)("yt.getConfig",m.t);(0,m.r)("yt.hasMsg",m.Ca);(0,m.r)("yt.setMsg",m.Aa);(0,m.r)("yt.setGoogMsg",function(a){ua(m.Ba,arguments)});(0,m.r)("yt.setAjaxToken",m.wa);(0,m.r)("reportTimingMaps",function(a,b){for(var c in a)(0,m.Wa)(c,a[c]);for(var d in b){c=d;var e=b[d];(0,m.ab)(void 0)[c]=e}db()});(0,m.s)(Db,m.La);
Db.prototype.enable=function(){window.onload=gb;window.onunload=hb;window.onerror=ib;var a=window.ytspf||{};a.enabled?(a.config=a.config||{},(0,m.ka)(a.config,{"navigate-requested-callback":jb,"navigate-part-received-callback":nb,"navigate-part-processed-callback":sb,"navigate-received-callback":tb,"navigate-processed-callback":vb,"navigate-error-callback":xb,"script-loading-callback":Eb}),a.enabled=window.spf.init(a.config),this.R("init",yb),this.R("dispose",Ab)):window.spf.dispose();this.R("init",
this.init,this);this.R("dispose",this.dispose,this)};Db.prototype.init=function(){(window.ytspf||{}).enabled||window.spf.dispose();var a,b;!window.ytPageFrameLoaded&&(0,m.t)("PAGEFRAME_JS")&&(a=(0,m.t)("PAGEFRAME_JS"),b=function(){(0,m.l)("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0});var c={};c[(0,m.t)("JS_COMMON_MODULE")]=(0,m.t)("JS_PAGE_MODULES");var d=(0,m.t)("JS_DELAY_LOAD");0<d?((0,m.w)(this.b),this.b=(0,m.u)(function(){a&&(0,m.Qa)(a,b);(0,m.Sa)(c)},d)):(a&&(0,m.Qa)(a,b),(0,m.Sa)(c))};
Db.prototype.dispose=function(){(0,m.w)(this.b);var a=(0,m.l)("ytbin.www.pageframe.cancelSetup");a&&a()};Db.prototype.disable=function(){Db.L.disable.call(this);window.spf.dispose();window.onload=null;window.onunload=null;window.onerror=null};(0,m.Ma)(new Db);})(_yt_www);


}
/*
     FILE ARCHIVED ON 00:08:38 Dec 01, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:41:44 Dec 07, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 130.569
  exclusion.robots: 0.091
  exclusion.robots.policy: 0.082
  cdx.remote: 0.059
  esindex: 0.009
  LoadShardBlock: 86.164 (3)
  PetaboxLoader3.datanode: 98.577 (5)
  load_resource: 124.098 (2)
  PetaboxLoader3.resolve: 52.284 (2)
*/