var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

var _yt_www={};(function(m){var window=this;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.l=function(a,b){for(var c=a.split("."),d=b||m.n,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
m.ca=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ea=function(a){return"array"==(0,m.ca)(a)};m.p=function(a){return"string"==typeof a};m.fa=function(a){return"function"==(0,m.ca)(a)};var ga=function(a,b,c){return a.call.apply(a.bind,arguments)};
var ha=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return m.q.apply(null,arguments)};m.ia=function(a,b){for(var c in b)a[c]=b[c]};
m.s=function(a,b){var c=a.split("."),d=m.n;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c};m.ja=function(a,b){var c=(0,m.ka)(a,b),d;(d=0<=c)&&(0,m.la)(a,c);return d};m.la=function(a,b){m.ma.splice.call(a,b,1)};m.na=function(a,b,c){return 2>=arguments.length?m.ma.slice.call(a,b):m.ma.slice.call(a,b,c)};m.u=function(){};
m.oa=function(){this.b=[];this.Ja={}};m.pa=function(a){qa(m.ra,arguments)};m.v=function(a,b){return a in m.ra?m.ra[a]:b};m.sa=function(a){qa(m.ta,arguments)};m.x=function(a,b){(0,m.fa)(a)&&(a=(0,m.ua)(a));var c=window.setTimeout(a,b);va.push(c);return c};m.y=function(a){window.clearTimeout(a)};m.ua=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw wa(b),b;}}:a};
var wa=function(a){if(window&&window.yterr){var b=(0,m.l)("yt.www.errors.log");b?b(a):(b=(0,m.v)("ERRORS")||[],b.push(a),(0,m.pa)("ERRORS",b))}};m.ya=function(a){qa(m.za,arguments)};m.Aa=function(a){return a in m.za};var qa=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.z=function(a,b,c){var d=Ba();return d?d.subscribe(a,function(){var a=arguments;try{(0,m.x)(function(){b.apply(c||m.n,a)},0)}catch(d){wa(d)}},c):0};
m.Ca=function(a){var b=Ba();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.A)(a,function(a){b.unsubscribeByKey(a)}))};m.B=function(a,b){var c=Ba();return c?c.publish.apply(c,arguments):!1};var Ba=function(){return(0,m.l)("yt.pubsub.instance_")};m.Da=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.j=(0,m.ua)(d||null);this.i=(0,m.ua)(e||null);this.g=[]};
m.Ea=function(a){a.name in Fa&&Ga(a.name);Fa[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.A)(a.deps,function(b){if(!(b in Fa))throw Error("Module "+b+" required by "+a.name);Fa[b].reqs.push(a.name)});a.enable()};var Ga=function(a){if(a in Fa){var b=Fa[a];(0,m.A)(b.reqs,function(a){Ga(a)});try{b.disable()}catch(c){}delete Fa[a]}};m.Ha=function(a,b){for(var c in a)b.call(void 0,a[c],c,a)};m.Ia=function(a,b){var c=a.match(Ja);return window.spf.scripts.load(a,b,c?c[1]:"")};
m.Ka=function(a){a&&((0,m.p)(a)?(0,m.Ia)(a):(0,m.ea)(a)?(0,m.A)(a,function(a){(0,m.Ka)(a)}):(0,m.Ha)(a,function(a,c){(0,m.Ia)(c,function(){(0,m.Ka)(a)})}))};m.La=function(a,b){if(a){var c=new window.Image,d=""+Ma++;Na[d]=c;c.onload=c.onerror=function(){b&&Na[d]&&b();delete Na[d]};c.src=a;c=eval("null")}};m.Oa=function(a,b){Pa().tick[a]=b||(0,m.C)()};var Qa=function(a){return a.responseStart-a.navigationStart};
var Ra=function(){var a=Pa().tick,b=Pa().span,c=Pa().info,d=(0,m.l)("yt.timing.reportbuilder_");if(d){if(d=d.apply(null,[a,b,c,void 0]))Sa(d),Ta()}else{var d={v:2,s:"youtube",action:(0,m.v)("TIMING_ACTION")},e=(0,m.v)("TIMING_INFO")||{},g;for(g in e)c[g]=e[g];g=c.srt;delete c.srt;if(!g&&0!==g)try{g=Qa((window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance).timing)}catch(h){c.pt&&(g=c.pt)}if(g||0===g)c.srt=g;a.aft||(a.aft=a.vr&&a.cl&&a.cl>a.vr?a.cl:a.vr?a.vr:a.ol);
a.aft&&a.plev&&(a.aft=Math.min(a.aft,a.plev));a.vr&&a.gv&&(b.vl=Math.round(a.vr-a.gv));for(var k in c)"_"!=k.charAt(0)&&(d[k]=c[k]);c={};k=[];g=a._start;for(var r in a)"_"!=r.charAt(0)&&(e=Math.max(Math.round(a[r]-g),0),c[r]=e,k.push(r+"."+e));d.rt=k.join(",");a={};r=[];for(var w in b)"_"!=w.charAt(0)&&(a[w]=b[w],r.push(w+"."+b[w]));d.it=r.join(",");Sa(d);(b=(0,m.l)("ytdebug.logTiming"))&&b(d,c,a);Ta()}};
var Ua=function(){var a=(0,m.v)("TIMING_ACTION"),b=!!(0,m.v)("TIMING_WFF"),c=Pa().tick;a&&c._start&&(b&&c.vr?Ra():b||!c.ol&&!c.aft||Ra())};var Sa=function(a){var b="https:"==window.location.protocol?"https://web.archive.org/web/20130801001305/https://gg.google.com/csi":"https://web.archive.org/web/20130801001305/http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];(0,m.La)(b+"?"+c.substring(1))};var Pa=function(){return(0,m.l)("ytcsi.data_")||Ta()};var Ta=function(){var a={tick:{},span:{},info:{}};(0,m.s)("ytcsi.data_",a);return a};
var Va=function(){(0,m.Oa)("ol");(0,m.B)("init");var a=(0,m.v)("PAGE_NAME");a&&(0,m.B)("init-"+a);Ua()};var Wa=function(a){(a=a||(0,m.v)("PAGE_NAME"))&&(0,m.B)("dispose-"+a);(0,m.B)("dispose")};var Xa=function(){Va()};var Ya=function(){Wa()};var Za=function(a,b,c){for(var d=window.document.getElementsByTagName("script"),e=!1,g=0,h=d.length;g<h;g++)if(0<d[g].src.indexOf("/debug-")){e=!0;break}e&&(d=Error(),d.message=a,d.fileName=b,d.lineNumber=c,wa(d))};
var $a=function(){Ta();var a=window.document.getElementById("progress");a||(a=window.document.createElement("div"),a.id="progress",a.innerHTML="<dt><dd>",window.document.body.appendChild(a));ab(60,900);(0,m.B)("navigate")};
var bb=function(a,b){(0,m.Oa)("_start");var c=Qa(b.timing);Pa().info.srt=c;ab(90,500);window.scroll(0,0);var c=(0,m.v)("PAGE_NAME"),d;for(d in m.ra)delete m.ra[d];(0,m.s)("ytplayer.config",null);(d=(0,m.l)("yt.www.watch.player.dispose"))&&d();(d=(0,m.l)("yt.player.cancelAll"))&&d();d=b.swfcfg||null;var e=(0,m.l)("yt.player.embed");d&&e&&(e("player-api",d),d=(0,m.cb)(d),d.loaded=!0);(0,m.s)("ytplayer.config",d);Wa(c)};var db=function(){ab(101,25);Va()};var eb=function(a,b){wa(b)};var fb=function(){gb()};
var hb=function(){};var gb=function(){if(window.document.getElementById("progress")){var a=function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)};(0,m.x)(function(){var b=window.document.getElementById("progress");b&&(b.className="done",b=b.style,b.transitionDuration=b.MozTransitionDuration=b.b=b.g=b.webkitTransitionDuration="",(0,m.x)(a,450))},500)}};
var ab=function(a,b){var c=b||500,d=window.document.getElementById("progress");if(d){d.className="";var e=d.style;e.transitionDuration=e.MozTransitionDuration=e.b=e.g=e.webkitTransitionDuration=c+"ms";(0,m.x)(function(){e.width=a+"%";(0,m.x)(function(){d.className="waiting"},c)},0)}};var ib=function(){m.Da.call(this,"www/base");this.b=0};var jb=function(a,b){var c;(c=(c=b.match(kb))?c[1]+"/"+c[2]:"")&&Ga(c)};m.ba=[];m.lb=m.lb||{};m.n=this;m.mb="closure_uid_"+(1E9*Math.random()>>>0);
m.C=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};m.ma=Array.prototype;m.ka=m.ma.indexOf?function(a,b,c){return m.ma.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if((0,m.p)(a))return(0,m.p)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};m.A=m.ma.forEach?function(a,b,c){m.ma.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.p)(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
m.ob=m.ma.filter?function(a,b,c){return m.ma.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,h=(0,m.p)(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var r=h[k];b.call(c,r,k,a)&&(e[g++]=r)}return e};m.pb=m.ma.map?function(a,b,c){return m.ma.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=(0,m.p)(a)?a.split(""):a,h=0;h<d;h++)h in g&&(e[h]=b.call(c,g[h],h,a));return e};
m.qb=m.ma.some?function(a,b,c){return m.ma.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.p)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return!0;return!1};m.rb=m.ma.every?function(a,b,c){return m.ma.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.p)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&!b.call(c,e[g],g,a))return!1;return!0};m.u.prototype.ea=!1;m.u.prototype.ya=(0,m.aa)(4);m.u.prototype.dispose=function(){this.ea||(this.ea=!0,this.H())};m.u.prototype.H=function(){if(this.X)for(;this.X.length;)this.X.shift()()};(0,m.t)(m.oa,m.u);m.f=m.oa.prototype;m.f.fi=1;m.f.Ce=0;m.f.ba=function(a,b,c){var d=this.Ja[a];d||(d=this.Ja[a]=[]);var e=this.fi;this.b[e]=a;this.b[e+1]=b;this.b[e+2]=c;this.fi=e+3;d.push(e);return e};m.f.lb=(0,m.aa)(6);m.f.Qb=function(a){if(0!=this.Ce)return this.g||(this.g=[]),this.g.push(a),!1;var b=this.b[a];if(b){var c=this.Ja[b];c&&(0,m.ja)(c,a);delete this.b[a];delete this.b[a+1];delete this.b[a+2]}return!!b};
m.f.aa=function(a,b){var c=this.Ja[a];if(c){this.Ce++;for(var d=(0,m.na)(arguments,1),e=0,g=c.length;e<g;e++){var h=c[e];this.b[h+1].apply(this.b[h+2],d)}this.Ce--;if(this.g&&0==this.Ce)for(;c=this.g.pop();)this.Qb(c);return 0!=e}return!1};m.f.clear=function(a){if(a){var b=this.Ja[a];b&&((0,m.A)(b,this.Qb,this),delete this.Ja[a])}else this.b.length=0,this.Ja={}};m.f.Ta=(0,m.aa)(5);m.f.H=function(){m.oa.C.H.call(this);delete this.b;delete this.Ja;delete this.g};m.ra=window.yt&&window.yt.config_||{};(0,m.s)("yt.config_",m.ra);m.ta=window.yt&&window.yt.tokens_||{};(0,m.s)("yt.tokens_",m.ta);m.sb=window.yt&&window.yt.globals_||{};(0,m.s)("yt.globals_",m.sb);m.za=window.yt&&window.yt.msgs_||{};(0,m.s)("yt.msgs_",m.za);var va=window.yt&&window.yt.timeouts_||[];(0,m.s)("yt.timeouts_",va);m.ub=window.yt&&window.yt.intervals_||[];(0,m.s)("yt.intervals_",m.ub);m.vb="Microsoft Internet Explorer"==window.navigator.appName;var wb=(0,m.l)("yt.pubsub.instance_")||new m.oa;m.oa.prototype.subscribe=m.oa.prototype.ba;m.oa.prototype.unsubscribeByKey=m.oa.prototype.Qb;m.oa.prototype.publish=m.oa.prototype.aa;m.oa.prototype.clear=m.oa.prototype.clear;(0,m.s)("yt.pubsub.instance_",wb);m.f=m.Da.prototype;m.f.enable=function(){(0,m.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.ba("init-"+a,this.init,this),this.ba("dispose-"+a,this.dispose,this),(0,m.v)("PAGE_NAME")==a&&this.init())},this)};m.f.init=function(){this.j&&this.j()};m.f.dispose=function(){this.i&&this.i()};m.f.disable=function(){this.dispose();this.clear()};m.f.ba=function(a,b,c){a=(0,m.z)(a,b,c);this.g.push(a);return a};m.f.clear=function(){(0,m.Ca)(this.g);this.g.length=0};var Fa=(0,m.l)("yt.modules.registry_")||{};(0,m.s)("yt.modules.registry_",Fa);var Ja=/jsbin\/(?:[a-zA-Z0-9_-]+\/)*(?:debug-)?([a-zA-Z0-9_-]+?)(?:-vfl|.js)/,kb=/^([a-z]+)_(\w+)_mod$/;var Na={},Ma=0;window.yt=window.yt||{};(0,m.s)("yt.setConfig",m.pa);(0,m.s)("yt.getConfig",m.v);(0,m.s)("yt.hasMsg",m.Aa);(0,m.s)("yt.setMsg",m.ya);(0,m.s)("yt.setGoogMsg",function(a){qa(m.za,arguments)});(0,m.s)("yt.setAjaxToken",m.sa);(0,m.s)("reportTimingMaps",function(a,b){for(var c in a)(0,m.Oa)(c,a[c]);for(var d in b){c=d;var e=b[d];Pa().info[c]=e}Ua()});(0,m.t)(ib,m.Da);
ib.prototype.enable=function(){window.onload=Xa;window.onunload=Ya;window.onerror=Za;var a=window.ytspf||{};a.enabled?(a.config=a.config||{},(0,m.ia)(a.config,{"navigate-requested-callback":$a,"navigate-received-callback":bb,"navigate-processed-callback":db,"navigate-error-callback":eb,"script-loading-callback":jb}),window.spf.init(a.config),this.ba("init",fb),this.ba("dispose",hb)):window.spf.dispose();this.ba("init",this.init,this);this.ba("dispose",this.dispose,this)};
ib.prototype.init=function(){(window.ytspf||{}).enabled||window.spf.dispose();var a,b;!window.ytMastheadLoaded&&(0,m.v)("MASTHEAD_JS")&&(a=(0,m.v)("MASTHEAD_JS"),b=function(){(0,m.l)("ytbin.www.masthead.setup")();window.ytMastheadLoaded=!0});var c={};c[(0,m.v)("JS_COMMON_MODULE")]=(0,m.v)("JS_PAGE_MODULES");var d=(0,m.v)("JS_DELAY_LOAD");0<d?((0,m.y)(this.b),this.b=(0,m.x)(function(){a&&(0,m.Ia)(a,b);(0,m.Ka)(c)},d)):(a&&(0,m.Ia)(a,b),(0,m.Ka)(c))};ib.prototype.dispose=function(){(0,m.y)(this.b)};
ib.prototype.disable=function(){ib.C.disable.call(this);window.spf.dispose();window.onload=null;window.onunload=null;window.onerror=null};(0,m.Ea)(new ib);})(_yt_www);


}
/*
     FILE ARCHIVED ON 00:13:05 Aug 01, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:42:17 Dec 07, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 70.787
  exclusion.robots: 0.063
  exclusion.robots.policy: 0.054
  cdx.remote: 0.049
  esindex: 0.008
  LoadShardBlock: 45.866 (3)
  PetaboxLoader3.datanode: 85.894 (5)
  load_resource: 141.34 (2)
  PetaboxLoader3.resolve: 81.779 (2)
*/