var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(d){var c=window.AmazonUIPageJS||window.P,k=c._namespace||c.attributeErrors,a=k?k("AmazonGatewayAuiAssets"):c;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,c,k){d.when("A").register("sg-jsutil",function(a){var c=a.$;return{safeCall:function(a,d){return c.isFunction(a)?a(d):d}}});d.when("A","load").execute("ah-inst-img-size",function(a){function m(b){if(!b)return null;var f=g(b).attr("src");b=g(b).data("a-hires");return f===b?null:f}function n(b){"object"===
typeof l.ue&&"function"===typeof l.ue.count&&l.ue&&l.ue.count(b,(l.ue.count(b)||0)+1)}function h(b,f){n("gw-img-size-invoke");g.ajax({type:"HEAD",async:!0,url:b,success:function(b,g,p){n("gw-img-size-success");a.trigger(f,parseInt(p.getResponseHeader("Content-Length"),10))},error:function(b,g,f){n("gw-img-size-error")}})}function e(b,f){0<b.length&&(t[f]={count:b.length,totalSize:0,images:b},g(t[f].images).each(function(b,g){var p=f+"_"+b;a.on(p,function(b){isNaN(b)||(--t[f].count,t[f].totalSize+=
b,0===t[f].count&&l.ue&&l.ue.count(f,t[f].totalSize))});h(g,p)}))}function p(b,g){var p=a.$(b);(p=0>=p.length?null:m(p[0]))&&e([p],g)}function b(b,f){f=f||b.length;var a=[];g(b.slice(0,f)).each(function(b,g){var f=m(g);if(!f)return[];a.push(f)});return a}var g=a.$,l=c,t=[];d.execute("inst-cf-img",function(){n("gw-inst-img");p(".gw-critical-content img","gw-cf-img-size")});d.when("x1").execute("inst-x1-img",function(){d.execute("inst-x1-rec-img",function(){var a=1;g("#gw-content-grid .feed-carousel .feed-carousel-shelf").slice(0,
2).each(function(f,p){if(2>=a){var l="gw-shoveler-img-size-"+a++,c=g(p).find("img");6<=c.length&&(c=b(c,6),e(c,l))}})});d.execute("inst-x1-unrec-img",function(){var g=a.$("#desktop-unrec-col-2 img"),g=b(g);e(g,"gw-dpt-img-size");p("#desktop-unrec-col-3 .image-map-before img","gw-slate-img-size");p("#desktop-unrec-sidekick #dotd-image img","gw-dotd-img-size")})})});d.when("A").register("dombinder",function(a){function c(a,b){var g=0;b=b.split(".");for(var l=b.length;g<l;g++)a=a&&a[b[g]];
return a}function d(a){return h.map(h(a).data("bind").split(","),function(b){b=b.split(":");var g=h.trim(b[0]),l=h.trim(b[1]),c=e[g];if(c)return c.init&&c.init(a,l),function(b){c.update(a,l,b)}})}var h=a.$,e={text:{update:function(a,b,g){h(a).text(c(g,b)||"")}},html:{update:function(a,b,g){h(a).html(c(g,b)||"")}},href:{update:function(a,b,g){h(a).attr("href",c(g,b)||"")}},trimText:{update:function(a,b,g){a=h(a);g=a.text();if(g.length>b){for(var l=b-4;0<=l&&0<"[.,-/#!$%^&*;:{}=-_`~()] ".indexOf(g[l]);)l--;
a.text(g.substring(0,0<=l?l+1:b-3)+"...")}}},value:{update:function(a,b,g){h(a).val(c(g,b)||"")}},visible:{update:function(a,b,g){var l=!1;"!"===b.charAt(0)&&(l=!0,b=b.substring(1));b=!!c(g,b);l!==b?h(a).show():h(a).hide()}},css:{init:function(a,b){var g=h(a),l=g.data("dombcss")||[];l[b]="";g.data("dombcss",l)},update:function(a,b,g){a=h(a);var l=a.data("dombcss"),e=l[b];g=c(g,b);e!==g&&(l[b]=g,e&&a.removeClass(e),g&&a.addClass(g))}},attr:{init:function(a,b){var g=h(a),l=g.data("dombattr")||[];l[b]=
{};g.data("dombattr",l)},update:function(a,b,g){var l=h(a);a=l.data("dombattr");var e=a[b];g=c(g,b);e!==g&&(a[b]=g,e&&h.each(e,function(b,g){l.removeAttr(b)}),g&&h.each(g,function(b,g){l.attr(b,g)}))}}};return{init:function(a){var b={$root:a,bindings:[]};a.find("[data-bind]").each(function(){h.each(d(this),function(g,a){b.bindings.push(a)})});return b},update:function(a,b){h.each(a.bindings,function(g,a){a(b)})}}});d.when("jQuery").register("gwAjax",function(a){return function(d,n){function h(g,
a,p){"object"===typeof c.ue&&"function"===typeof c.ue.count&&(e(n.errorCounter||"gwAjaxError"),n.id&&e("gwAjaxError:"+n.id));"function"===typeof c.ueLogError&&c.ueLogError({logLevel:"WARN",attribution:"gwAjax-"+(n.id||d),message:"gwAjax call failed "+(JSON&&JSON.stringify?JSON.stringify({url:d,"params-data":n.params||n.data}):"")});"function"===typeof b&&b(g,a,p)}function e(b){"object"===typeof c.ue&&"function"===typeof c.ue.count&&c.ue.count(b,(c.ue.count(b)||0)+1)}n=a.extend(!0,{},n);var p=n.success,
b=n.error;n.success=function(b,a,c){b.error?h(b,a,c):"function"===typeof p&&p(b,a,c)};n.error=h;n.data=n.params?n.params:n.data;e("gwAjaxCall");n.ajaxCounter&&e(n.ajaxCounter);return a.ajax(d,n)}});d.when("jQuery","gw-hud-punt").execute("gw-hud-sidekick",function(a){a("#gw-hud-grid").css({display:"none"})});d.when("A","sg-jsutil","a-modal","gw-productdb","productdb-binding-helper","sg-media-builder","gw-sims","gw-popover-data").register("gw-popover",function(a,m,n,h,e,p,
b,g){function l(b,g){c.uet&&c.uet(b,g,{wb:1})}function t(b){if(c.ue&&"function"===typeof c.ue.count)return c.ue.count(b)||0}function k(b){c.ue&&"function"===typeof c.ue.count&&c.ue.count(b,(c.ue.count(b)||0)+1)}function f(b){return b.closest("*[data-sgproduct]").data("sgproduct")}function u(b,g){z[b.asin]&&z[b.asin].isResolved()?A.resetSimData():(z[b.asin]=q.Deferred(),b&&b.asin&&g?A.fetch(b,g,z[b.asin]):z[b.asin].reject())}var q=a.$,y={},z={};if(!q("html").hasClass("a-touch")){m=q('<span style="display: none" />').appendTo("body");
var x=q("#gw-popover-wrapper"),r=new e(h,x),B=n.create(m,{name:"gw-asin-popover",width:"90%","max-width":900,height:590,popoverLabel:g.popoverLabel,closeButton:!1}),A=new b(r),D=q("#gw-quick-look-btn");q("#a-page").delegate("li[data-sgproduct]","mouseenter",function(b){q(b.currentTarget).append(D);q(b.currentTarget).find("[title]").removeAttr("title");D.addClass("active")});D.mouseenter(function(){var b=q(this),g=f(b),b=b.siblings().children("a").attr("href");u(g,b)});q(".bestsellers .listRow a").mouseenter(function(){var b=
q(this),g=f(b),b=b.attr("href");u(g,b);!g||!g.asin||y[g.asin]&&y[g.asin].isResolved()||!(b=h.get(g.asin))||(y[g.asin]=q.Deferred(),y[g.asin].resolve(b))});d.when("gwAjax").execute(function(b){var g={};q("#a-page").delegate(".fresh-shoveler li[data-sgproduct]","mouseenter mousemove",function(f){f=q(f.currentTarget);var l=f.data("sgproduct").asin;if(!y[l]||!y[l].isResolved()){var p=[];f.add(f.prev("li[data-sgproduct]")).add(f.next("li[data-sgproduct]")).each(function(){var b=q(this).data("sgproduct");
if(b&&b.asin){var f=h.get(b.asin),l=(f=!(!g[b.asin]&&f&&f.loading))&&1500<a.now()-g[b.asin];if(!f||l)p.push(b.asin),g[b.asin]=a.now()}});y[l]=q.Deferred();p.length?(b("/gp/gw/ajax/pdb.html",{id:"quicklook-pdb",data:{swn:"productdb-ajax",sa:'{"asins": ["'+p.join('","')+'"]}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:c.ue_id}}).done(function(b){h._add(b);for(var f=0;f<p.length;f++)g[p[f]]=Infinity;y[l].resolve(b)}).fail(y[l].reject),k("freshHoverCount")):y[l].resolve()}})});q("#a-page").delegate("li[data-sgproduct]",
"mouseleave",function(b){D.removeClass("active")});var C="#a-popover-"+B.attrs("id")+" ";n=q.map([".a-popover-header { display: none; }",".a-popover-inner { padding: 0px !important; margin: 0px !important; overflow: hidden !important; height: 100% !important; }"],function(b){return C+b}).join(" ");q("head").append("<style>"+n+"</style>");a.on("a:popover:hide:gw-asin-popover",function(b){c.history.state&&c.history.state.popup&&c.history.back();r.clear()});q(c).bind("popstate",function(){B.hide()});
return{show:function(b,g){k("freshPopOverOn");l("bb","popoverLatency"+t("freshPopOverOn"));c.history&&c.history.pushState&&c.history.pushState({popup:1},"");r.setAsin(b,{beforeUpdate:function(f){if(f.loading)return k("freshPopOverLoading"),f;var a=(new p(f.images[0])).autoCrop().scaleXY(500,400).build(),a={url:g,image:a,actionUrl:{action:"/gp/product/handle-buy-box/"+function(b){return b.substring(b.indexOf("/ref=")+1,b.length)}(g)}};f.reviews&&(a.reviews=q.extend({},f.reviews,{url:g+"#customerReviews"}));
q.when(z[b],y[b]).done(function(g,f){A.showSims(b,g)});z[b].fail(A.setNoSimView);l("cf","popoverLatency"+t("freshPopOverOn"));return q.extend({},f,a)}});B.show()},hide:function(){B.hide()}}}});d.when("A","sg-media-builder","gw-productdb").register("gw-sims",function(a,m,n){var h=a.$;return function(a){function p(b,g){c.uet&&c.uet(b,g,{wb:1})}function b(b){if(c.ue&&"function"===typeof c.ue.count)return c.ue.count(b)||0}function g(b){c.ue&&"function"===typeof c.ue.count&&c.ue.count(b,(c.ue.count(b)||
0)+1)}function l(){if(!C){C=!0;I.hide();v.show();H.animate({height:"100%"},300);var g=0,f=0,a=0,l=parseInt(v.css("width"),10),r=v.find(".sims-img-link");r.each(function(b,p){g+=p.clientWidth;l<g?h(p).hide():(f=g,a+=1)});var e=l-f;0<e&&(e=Math.floor(20+e/a-1),20<e&&r.css({"padding-right":e/2+"px","padding-left":e/2+"px"}));r="popoverLatency"+b("freshPopOverOn");p("be",r);c.uex&&c.uex("ld",r,{wb:1})}}function t(){0===--r&&l()}function k(b,f){var l=h("<a>"),p=h("<div>");l.attr("class","sims-img-link");
p.addClass("sims-img-border");f&&l.addClass("selected");l.click(function(){g("freshPopOverSimsClick");v.find(".sims-img-link").removeClass("selected");h(this).addClass("selected");a.clear();a.setAsin(b.asin,{beforeUpdate:function(f){f=h.extend(!0,{},b);var a=b.url;if(f.loading)g("freshPopOverLoading");else{var l=(new m(f.images[0])).autoCrop().scaleXY(500,400).build(),l={url:a,image:l,actionUrl:{action:"/gp/product/handle-buy-box/"+u(a)}};f.reviews&&(l.reviews=h.extend({},f.reviews,{url:a+"#customerReviews"}));
f=h.extend({},f,l)}return f}})});return l.append(p)}function f(){h.each(B,function(b,g){g.url=g.url.replace(/ref=gw_pdb_pdt-[\d]+/,u(A)+"&gw_sims-"+b)})}function u(b){return 0<=b.indexOf("redirect.html?")?b.replace(/.*redirect.html|(token|location)=.*?&/g,""):b.substring(b.indexOf("/ref=")+1,b.length)}function q(){C=!1;f();var b=[];r=B.length>r?r:B.length;h(B).each(function(g,f){f.loading=!1;if(f.images[0].src){var a=(new m(f.images[0])).autoCrop().scaleXY(130,100).build().src,l=h("<img>");l.attr("src",
a);l.attr("class","sims-img");l.load(t);a=h("<div>");a.attr("class","sims-img-container");var p=h("<div>");p.addClass("sims-img-overlay");h(a).append(p);a.append(l);l=k(f,0===g);l.append(a);b.push(l)}return g<r-1});r=b.length;h(b).each(function(b,g){v.append(g)});setTimeout(l,D)}function y(){d.when("gw-popover").execute(function(b){b.hide()})}function z(){I.hide();H.addClass("hidden");E.bind("click",y)}function x(){v.empty();H.add(I).removeAttr("style");H.removeClass("hidden");E.unbind("click",y);
I.show();v.hide();r=8;B=[]}var r,B,A,D=1E4,C=!1,E=h("#sims-section"),H=E.find(".sims-wrapper"),I=E.find(".sims-loading"),v=E.find(".sims-details");h("#gw-asin-popover");return{fetch:function(g,f,a){p("af","popoverLatency"+b("freshPopOverOn"));x();A=f;g.url=A;B.push(g);f=n.get(g.asin);setTimeout(a.reject,D);f.sims?a.resolve(f.sims):d.when("gwAjax").execute(function(b){b("/gp/gw/ajax/pdb.html",{id:"quicklook-sims-pdb",data:{swn:"productdb-ajax",sa:'{"asins": [], "entityId":"'+g.asin+'","datasetId": "purchase"}',
oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:c.ue_id}}).done(function(b){if(b&&b.p&&0<b.p.length){var f=g.asin,l=b.p;l&&(n.get(f).sims||n.addSims(f,l));return a.resolve(b.p)}return a.reject()}).fail(a.reject)});return a},setNoSimView:z,showSims:function(b,f){var a=n.get(b);a.loading?g("freshPopOverSimLoadBeforePrimeAsin"):B=a.sims?h.merge([a],a.sims):h.merge([a],f);4<B.length?q():(g("simsLessThanThreshold"),z())},resetSimData:x,setWaitPeriod:function(b){D=b}}}});d.when("A").execute(function(a){var m=
a.$,n,h;if(!a.$("html").hasClass("a-touch"))if(c.cvox)c.ue&&c.ue.tag&&c.ue.tag("screenReaderOn");else{m("#a-page").delegate("*[data-sgproduct] #gw-quick-look-btn","click",function(a){e(a)});m("#a-page").delegate(".bestseller-list *[data-sgproduct]","click",function(a){e(a)});d.when("gw-popover").execute(function(a){n=a;m("#gw-popover-close").click(function(){n.hide()});h&&n.show.apply(n,h)});var e=function(a){if(!(1<a.which||a.shiftKey||a.altKey||a.metaKey||a.ctrlKey)){var b,g;m(a.target).parents(".bestseller-list").length?
(b=m(a.currentTarget).data("sgproduct"),g=m(a.target).closest("a").attr("href")):(b=m("#gw-quick-look-btn").closest("*[data-sgproduct]").data("sgproduct"),g=m("#gw-quick-look-btn").siblings().children("a").attr("href"));var l=[b.asin,g];b.asin&&g&&(a.preventDefault(),n?n.show.apply(n,l):h=l)}}}});d.when("A","sg-jsutil","dombinder").register("productdb-binding-helper",function(a,c,d){return function(a,e){function p(b,g){d.update(f,l(g.beforeUpdate,b));b.loading||l(g.load,b)}function b(b){g();
k=function(){b(t)};t.pdb_observe(k)}function g(){t&&k&&(t.pdb_unobserve(k),k=null)}var l=c.safeCall,t=null,k=null,f=d.init(e);this.setAsin=function(f,l){l=l||{};g();t=a.get(f);p(t,l);t.loading&&b(function(b){p(b,l)});return t};this.clear=function(){g();t={};d.update(f,t)}}});c.P&&d.when("jQuery","afterLoad").register("gw-resource-logger",function(a){return{instrumentResources:function(d){var n;n=!1;if(a.isArray(d)&&!a.isEmptyObject(d)){n=!0;for(var h=0;h<d.length;h++){var e=d[h];if("id"in e&&"regex"in
e&&"initiator"in e){if(!("string"===typeof e.id&&"string"===typeof e.initiator&&e.regex instanceof RegExp)){n=!1;break}}else{n=!1;break}}}h=c.performance&&"function"===typeof c.performance.getEntriesByType&&"undefined"!==typeof c.performance.getEntriesByType("resource")&&"undefined"!==typeof c.ue;if(n&&h){n=Array(d.length);for(h=0;h<n.length;h++)n[h]=!1;for(e=h=0;e<c.performance.getEntriesByType("resource").length&&h<d.length;e++)for(var p=c.performance.getEntriesByType("resource")[e],b=p.name,g=
p.initiatorType,l=0;l<d.length;l++)if(!n[l]){var t=d[l].regex;if(g===d[l].initiator&&t.test(b)){b=d[l].id;g=p;p=g.duration;c.ue.count&&(c.ue.count(b+":duration",p),c.ue.count(b+":startTime",g.startTime));c.ue.tag&&(g=void 0,g=50>p?b+":cached":b+":notCached",c.ue.tag(g));n[l]=!0;h++;break}}}}}});d.register("sg-media-builder",function(){return function(a){var c=this,d=a.src,h=[];c.build=function(){var c=h.join("_");return{src:d.replace(/\.([^.]+)$/,"._"+c+"_.$1"),alt:a.alt}};c.autoCrop=
function(){h.push("AC");return c};c.scaleX=function(a){h.push("SX"+a);return c};c.scaleY=function(a){h.push("SY"+a);return c};c.upScaleX=function(a){h.push("UX"+a);return c};c.upScaleY=function(a){h.push("UY"+a);return c};c.scaleXY=function(a,p){return c.upScaleX(a).scaleY(p)}}});d.when("A","gwAjax").register("shogunProductDB",function(a,d){function n(c){var b=[];e[c]={loading:!0,pdb_observe:function(g){b.push(g)},pdb_unobserve:function(g){b=a.$.grep(b,function(b){return b!==g})},_trigger:function(){a.$.each(b,
function(){this.call(e[c])})}};return e[c]}function h(p,b){this.ajaxUrl=p;this.experienceStr=b;this._add=function(b){b.p&&a.$.each(b.p,function(b,g){if(g.asin){var c=e[g.asin]||n(g.asin);a.$.extend(c,g,{loading:!1,error:!1});c._trigger(g)}})};this.addSims=function(b,l){if(l){var c=e[b]||n(b);a.$.extend(c,{sims:l});c._trigger(b)}};this._ajax=function(g,l){var e=a.$.extend(!0,{},p,{params:{sa:JSON.stringify(g),oe:b}});c.ue_sid&&(e.url+="/"+c.ue_sid);c.ue_id&&(e.params.rrid=c.ue_id);return d(e.url,{method:e.method,
params:e.params,success:l.success,error:l.error,id:"gw-jslibs-"+l.id})};this.get=function(b){return b in e?e[b]:n(b)}}var e={};return function(a,b){return new h(a,b)}});d.when("jQuery","p-detect").register("component-feed-carousel",function(a,m){var n=a.extend(!0,{},m);a.each({pointerPrefix:function(){return"onmspointerup"in document||"onpointerup"in document?"onpointerup"in document?"pointer":"MSPointer":!1},actionMode:function(){var a=n.capabilities.pointerPrefix;return a?a:n.capabilities.touch?
"touch":"mouse"}},function(a,b){n.capabilities[a]=b()});var h={};a.each({start:{mouse:"down",touch:"start",pointer:"down",MSPointer:"Down"},end:{mouse:"up",touch:"end",pointer:"up",MSPointer:"Up"}},function(a,b){var g=n.capabilities.actionMode,l="string"===typeof b?b:b[g];h[a]=l?g+l:b.mouse===k?"":"mouse"+b.mouse});n.action=h;var e=function(a,b,g,l){this.init(a,b,g,l)};e.prototype={init:function(p,b,g,l){var e=this;a("html").hasClass("a-touch")&&p.addClass("feed-carousel-touch");e.adjustMarginOnChange=
!0;e.defaultCssRightMargin=null;e.minItems=b||10;e.imgClass=".product-image";e.config=l||{};e.$carousel=p;e.cfMinItems=g||6;e.cfFired=!1;e.shovelerReadyFired=!1;e.slotId=e.getSlotId();e.touch=e.$carousel.hasClass("feed-carousel-touch");e.ajaxSource=e.$carousel.parent().hasClass("ajaxSource");e.$shelf=e.$carousel.find(".feed-carousel-shelf");e.$viewport=e.$carousel.find(".feed-carousel-viewport");e.$spinner=e.$carousel.find(".spinner");e.$left=a(".feed-carousel-control.feed-left",p);e.$right=a(".feed-carousel-control.feed-right",
p);e.$buttons=a(".feed-carousel-control",p);e.$thumb=a(".feed-scrollbar-thumb",p);e.shelfLeft=-1*parseInt(e.$shelf.css("left"),10);e.calcWidth=a("html").hasClass("a-lt-ie9");e.noOpacity=a("html").hasClass("a-lt-ie9");e.uniqueId=e.getUniqueId();e.$left.attr("aria-hidden",!0);e.$right.attr("aria-hidden",!0);e.bindEvents();e.$carousel.data("Carousel",e);e.$carousel.trigger("change");e.token=!1;e.lock=function(){e.token=!0};e.unlock=function(){e.token=!1};e.locked=function(){return e.token};d.when("gw-first-carousel").execute(function(){e.first=
e.$carousel.hasClass("first-carousel");e.shouldControlsOn()?e.showControls():e.hideControls()});e.uniqueId&&d.when(e.uniqueId).execute(function(b){e.appendCards(b.cards);if(b.cards&&e.slotId&&"object"===typeof c.ue&&"function"===typeof c.ue.count){var g="gw-"+e.slotId.toString()+"-lazy-cards",a="gw-"+e.slotId.toString()+"-lazy";c.ue.count(g,(c.ue.count(g)||0)+b.cards.length);c.ue.count(a,(c.ue.count(a)||0)+1)}})},getUniqueId:function(){if(this.$viewport){var e=this.$viewport.closest(".shogun-widget");
return 0<e.length?a(e[0]).attr("id"):null}},getSlotId:function(){var e=this.$carousel.closest(".gw-widget-instrument");return 0<e.length?a(e[0]).attr("id"):null},bindEvents:function(){function e(b){return n.capabilities.pointerPrefix&&-1<a.inArray(b.originalEvent.pointerType,[2,"touch"])||"touch"===n.capabilities.actionMode}var b=this,g=a("body");b.$buttons.ready(function(g){b.shovelerReadyFired||(b.slotId&&(g=b.slotId.toString()+"-active",c.GWI&&c.GWI.recordLatency(g),c.GWI&&c.GWI.register(g)),b.shovelerReadyFired=
!0)});b.$carousel.change(function(g){b.updateItems();b.updateSpinner();b.updateShelf();b.updateControls();null===b.defaultCssRightMargin&&b.$shelf.children("li").first()&&(b.defaultCssRightMargin=parseInt(b.$shelf.children("li").first().css("margin-right"),10));b.adjustMarginOnChange&&b.adjustCardMargin()});b.$left.click(function(g){g.preventDefault();b.changePage(-1);b.slotId&&b.logCounter("gw-"+b.slotId.toString()+"-left")});b.$right.click(function(g){g.preventDefault();b.changePage(1);b.slotId&&
b.logCounter("gw-"+b.slotId.toString()+"-right")});b.bindImageLoadEvents(b.$shelf);var l;a(c).resize(function(){clearTimeout(l);l=setTimeout(function(){var g=b.getDimensions(),g=Math.max(Math.min(g.shelfLeft,g.maxLeft),0);b.moveShelf(g)},100)});b.$thumb.mousedown(function(l){var e=l.clientX;1===l.which&&(l.preventDefault(),b.$carousel.addClass("scrolling"),g.bind("mousemove.feed-carousel",function(g){var a=b.getDimensions(),a=Math.max(Math.min(a.shelfLeft+1/a.pageRatio*(g.clientX-e),a.maxLeft),0);
e=g.clientX;b.moveShelf(a)}),a(document).bind("selectstart.feed-carousel",function(){return!1}))});g.add(c).mouseup(function(l){b.$carousel.removeClass("scrolling");b.$carousel.hasClass("hovering")||b.hideControls();g.unbind("mousemove.feed-carousel");a(document).unbind("selectstart.feed-carousel")});b.$carousel.hover(function(){b.$carousel.addClass("hovering");clearTimeout(b.hoverTimer);b.hoverTimer=setTimeout(function(){b.$carousel.hasClass("hovering")&&!b.$carousel.hasClass("touching")?b.showControls():
b.$carousel.removeClass("touching")},300)},function(){b.$carousel.removeClass("hovering touching");clearTimeout(b.hoverTimer);b.$carousel.hasClass("scrolling")||(b.hoverTimer=setTimeout(function(){b.$carousel.hasClass("hovering")||b.hideControls()},600))});b.$carousel.bind(n.action.start,function(g){e(g)&&(b.$carousel.addClass("touching"),clearTimeout(b.touchTimer),b.touchTimer=setTimeout(function(){b.$carousel.removeClass("touching")},5E3))});b.$carousel.bind(n.action.end,function(g){e(g)&&(b.$carousel.removeClass("touching"),
clearTimeout(b.touchTimer),clearTimeout(b.hoverTimer))});b.$viewport.scroll(function(){b.shelfLeft=b.$viewport.scrollLeft();b.updateControls()})},bindImageLoadEvents:function(e){var b=this;a(b.imgClass,e).one("load",function(){b.$carousel.trigger("change")})},getDimensions:function(){var a=this.$shelf.width(),b=this.shelfLeft,g=this.$carousel.width();return{pageWidth:g,shelfWidth:a,shelfLeft:b,pageRatio:g/a,leftRatio:b/a,maxLeft:a-g}},updateItems:function(){var e=this,b=e.$shelf.find(".feed-carousel-card"),
g=function(b){return"none"===b.css("display")};b.each(function(b,d){var h=a(d);if(!g(h)&&!e.config.visibleBeforeLoad)return!0;h.attr("aria-posinset",b+1);h.attr("aria-hidden",!1);h.attr("role","listitem");return 0>=h.find(e.imgClass).filter(function(){return!this.complete}).length?(h.css("display","inline-block"),b+1>=e.cfMinItems&&!e.cfFired&&(e.slotId&&(h=e.slotId.toString()+"-visible",c.GWI&&c.GWI.recordLatency(h),c.GWI&&c.GWI.register(h)),e.cfFired=!0),!0):!1});b.attr("aria-setsize",b.size());
e.$items=b.filter(function(){return!g(a(this))})},updateShelf:function(){var e=0;this.calcWidth&&(this.$shelf.children().each(function(){e+=a(this).outerWidth(!0)}),this.$shelf.width(e));this.touch&&this.$carousel.not(".fresh-shoveler-tablet-app .feed-carousel").height(this.$shelf.outerHeight(!0))},updateSpinner:function(){this.size()<this.minItems&&this.ajaxSource?this.$spinner.show():(this.size()<this.minItems&&"object"===typeof c.ue&&"function"===typeof c.ue.count&&c.ue.count("shovelerNotEnoughItem",
(c.ue.count("shovelerNotEnoughItem")||0)+1),this.$spinner.hide())},updateControls:function(){this.updateArrows();this.updateScrollThumb()},shouldControlsOn:function(){return this.first&&!this.touch},showControls:function(a){this.$thumb.add(this.$buttons).stop(!0,!0).fadeIn({duration:300,complete:a,queue:!1})},hideControls:function(a){var b=this.$thumb;this.shouldControlsOn()||(b=b.add(this.$buttons));b.stop(!0,!0).fadeOut({duration:300,complete:a,queue:!1})},appendCards:function(a){this.$shelf.append(a);
this.bindImageLoadEvents(a);this.$carousel.trigger("change")},updateArrows:function(){var e=this,b=e.getDimensions();a.each([{$e:e.$left,enabled:0<b.shelfLeft},{$e:e.$right,enabled:b.shelfLeft<b.maxLeft}],function(b,a){var c=a.$e;a.enabled?c.removeClass("feed-control-disabled"):c.addClass("feed-control-disabled");e.noOpacity&&(a.enabled?c.css("opacity","1"):c.css("opacity","0.5"))})},updateScrollThumb:function(){var e=this.getDimensions(),b=e.leftRatio*e.pageWidth,e=Math.min(e.pageRatio*e.pageWidth,
e.pageWidth);this.$thumb.width(e).each(function(){a(this).animate({left:b},0)})},logCounter:function(a){"object"===typeof c.ue&&"function"===typeof c.ue.count&&(c.ue.count(a,(c.ue.count(a)||0)+1),c.ue.count("gw-shoveler-click",1))},changePage:function(a){var b=this.getDimensions(),g=this.alignWithItem(b.shelfLeft+a*b.pageWidth),g=Math.min(0>a?g.right:g.left,b.maxLeft);this.locked()||(this.lock(),b.shelfLeft===g?(this.bounce(this.$shelf,-30*a),this.bounce(this.$thumb,6*a)):this.moveShelf(g,400))},
moveShelf:function(a,b){function g(){e.updateArrows();e.unlock()}var e=this;b=b||0;e.shelfLeft=a;if(e.touch)e.$viewport.animate({scrollLeft:a},b,"swing",g);else{var c=e.getDimensions(),c=a/c.shelfWidth*c.pageWidth;e.$shelf.animate({left:-a},b,"swing",g);e.$thumb.animate({left:c},b,"swing",function(){e.updateScrollThumb();e.unlock()})}},getItems:function(){return this.$items},size:function(){return this.getItems().length},alignWithItem:function(e){if(0>e)return{left:0,right:0};var b=this,g=b.getItems(),
l=g.map(function(){var g=b.cardPosition(a(this));if(e>=g.left&&e<=g.right)return g}).get(0);return l?l:b.cardPosition(g.last())},cardPosition:function(a){var b=(a.position()||{left:0,right:0}).left;a=b+a.outerWidth(!0);return{left:b,right:a}},bounce:function(e,b){function g(b){var g={};g[l.touch?"left":"marginLeft"]=b;return g}var l=this;e.each(function(){var e=a(this);e.animate(g(b),400,"swing",function(){e.animate(g(0),100,"swing",l.unlock)})})},setCardMargin:function(a){this.$shelf.children("li").first()&&
this.$shelf.children("li").first().css("margin-right")!==a+"px"&&(this.$shelf.children("li").css("margin-right",a+"px"),this.updateShelf())},adjustCardMargin:function(a){a=a===k||null===a?this.defaultCssRightMargin:a;this.setCardMargin(a);var b=this.getDimensions(),b=0>b.maxLeft?Math.ceil(-b.maxLeft/this.size()):a;this.setCardMargin(b<a?a:b)}};return{createCarousel:function(c,b,g,l){a(c).each(function(c,d){var f=a(d);new e(f,b,g,l)})}}});d.register("SafeP",function(){var a={};return{register:function(c,
n){"string"===typeof c&&"function"===typeof n&&(a[c]||(a[c]=function(c,e){d.register(c,e);a[c]=function(){}}),a[c]&&a[c](c,n))}}});d.when("jQuery","SafeP").execute("shoveler-lazy-non-visible-images",function(a,m){function n(a){"object"===typeof e.ue&&"function"===typeof e.ue.count&&e.ue.count(a,(e.ue.count(a)||0)+1)}function h(){e.GWData&&a.each(e.GWData,function(e,b){if(e&&b&&b.data&&!1===b.loaded){b.loaded=!0;n("gw-lazy-load-all");var g=[];a.each(b.data,function(b,e){g.push(a(e)[0])});g&&0<g.length&&
n("gw-lazy-load-non-empty");m&&m.register(e,function(){return{cards:g}})}})}var e=c;d.when("x1").execute(function(){h()});d.when("ready").execute(function(){h()});d.when("load").execute(function(){h()})});d.register("billboard-widget",function(){if(c.GWI)return c.GWI.BillboardWidget});d.register("gwi-util",function(){if(c.GWI)return c.GWI.util});d.when("A").register("resizeable-inline-video",function(a){function m(a,b){"function"===typeof e.uet&&b&&e.uet(a,b,
{wb:1})}function n(a,b){"function"===typeof e.uex&&b&&e.uex(a,b,{wb:1})}var h=a.$,e=c;return function(c,b,g){function l(){D.removeClass("player-uncommenced viewport-loaded").addClass("viewport-loading player-loading");x.css("z-index",1).css("opacity",1);m("tc","airyInlineVideoLoadingMonitor");m("tc",g.loadingScope);m("bb","airyInlineVideoPlaybackMonitor");m("bb",g.playbackScope)}function t(b){b=b||{};return{play:b.play||C,stop:b.stop||C,resize:b.resize||C,airyReady:b.airyReady||C}}function k(){return new t({airyReady:function(b){l();
E=new u(b);E.play()},stop:function(){var b;b=C;z.removeClass("viewport-loading").addClass("viewport-loaded");x.css("z-index",-1).css("opacity",0);B.length&&r.hide();b()}})}function f(b){return new t({play:function(){E=new u(b);r.fadeOut(1E3,function(){r.css("display","block");r.css("visibility","hidden");l();E.play()})}})}function u(b){return new t({play:function(){A.removeClass("viewport-loading").addClass("viewport-loaded");D.removeClass("player-loading");m("be","airyInlineVideoLoadingMonitor");
m("be",g.loadingScope);n("ld","airyInlineVideoLoadingMonitor");n("ld",g.loadingScope);E=new q(b)}})}function q(b){return new t({stop:function(){E=new y(b);b.pause()}})}function y(b){return new t({})}var z=h(c),x=z.find(".airy-video-container"),r=z.find(".image-map-before"),B=z.find(".image-map-after"),A=z.find(".airy-video-viewport-in"),D=z.add(A),C=function(){},E;g=g||{};m("bb","airyInlineVideoLoadingMonitor");m("bb",g.loadingScope);E=new function(a){function c(a){function f(b){"object"===typeof e.ue&&
"function"===typeof e.ue.count&&e.ue.count(b,(e.ue.count(b)||0)+1)}b.bindings={loadedmetadata:function(b,a){E.airyReady(l);m("cf","airyInlineVideoLoadingMonitor");m("cf",g.loadingScope)},videounsupportederror:function(b,g){f("airyResizableInlineVideoUnsupportedError")},decodeerror:function(b,g){f("airyResizableInlineVideoDecodeError")},networkerror:function(b,g){f("airyResizableInlineVideoNetworkError")},undefinederror:function(b,g){f("airyResizableInlineVideoUndefinedError")},beganplaying:function(){E.play()},
ended:function(){m("af","airyInlineVideoPlaybackMonitor");m("af",g.playbackScope);E.stop()}};var l=a.embed(b);g.autoPlay&&l.play({isAsync:!0})}a=a||{};d.load.js(a.js||"");d.load.css(a.css||"");D.addClass("player-uncommenced");g.whenReady?d.when("Airy","ready").execute(c):d.when("Airy").execute(c);return new t({airyReady:function(b){E=new f(b);E.play()},play:function(){E=new k}})}(g.airyAssetUrls);(function(){a.on("resize",function(){E.resize()})})()}})});

}
/*
     FILE ARCHIVED ON 00:11:05 Jun 01, 2017 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 21:36:11 Dec 11, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 215.697
  exclusion.robots: 0.077
  exclusion.robots.policy: 0.068
  cdx.remote: 0.054
  esindex: 0.007
  LoadShardBlock: 145.73 (3)
  PetaboxLoader3.datanode: 172.798 (5)
  load_resource: 312.86 (2)
  PetaboxLoader3.resolve: 73.507 (2)
*/