var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(m){var k=window.AmazonUIPageJS||window.P,r=k._namespace||k.attributeErrors,f=r?r("AmazonGatewayAuiAssets"):k;f.guardFatal?f.guardFatal(m)(f,window):f.execute(function(){m(f,window)})})(function(m,k,r){m.when("A").register("sg-jsutil",function(f){var l=f.$;return{safeCall:function(f,g){return l.isFunction(f)?f(g):g}}});m.when("A").register("dombinder",function(f){function l(b,a){var c=0;a=a.split(".");for(var h=a.length;c<h;c++)b=b&&b[a[c]];return b}function n(b){return g.map(g(b).data("bind").split(","),
function(a){a=a.split(":");var c=g.trim(a[0]),h=g.trim(a[1]),f=e[c];if(f)return f.init&&f.init(b,h),function(a){f.update(b,h,a)}})}var g=f.$,e={text:{update:function(b,a,c){g(b).text(l(c,a)||"")}},html:{update:function(b,a,c){g(b).html(l(c,a)||"")}},href:{update:function(b,a,c){g(b).attr("href",l(c,a)||"")}},trimText:{update:function(b,a,c){b=g(b);c=b.text();if(c.length>a){for(var h=a-4;0<=h&&0<"[.,-/#!$%^&*;:{}=-_`~()] ".indexOf(c[h]);)h--;b.text(c.substring(0,0<=h?h+1:a-3)+"...")}}},value:{update:function(b,
a,c){g(b).val(l(c,a)||"")}},visible:{update:function(b,a,c){var h=!1;"!"===a.charAt(0)&&(h=!0,a=a.substring(1));a=!!l(c,a);h!==a?g(b).show():g(b).hide()}},css:{init:function(b,a){var c=g(b),h=c.data("dombcss")||[];h[a]="";c.data("dombcss",h)},update:function(b,a,c){b=g(b);var h=b.data("dombcss"),e=h[a];c=l(c,a);e!==c&&(h[a]=c,e&&b.removeClass(e),c&&b.addClass(c))}},attr:{init:function(b,a){var c=g(b),h=c.data("dombattr")||[];h[a]={};c.data("dombattr",h)},update:function(b,a,c){var h=g(b);b=h.data("dombattr");
var e=b[a];c=l(c,a);e!==c&&(b[a]=c,e&&g.each(e,function(a,c){h.removeAttr(a)}),c&&g.each(c,function(a,c){h.attr(a,c)}))}}};return{init:function(b){var a={$root:b,bindings:[]};b.find("[data-bind]").each(function(){g.each(n(this),function(c,b){a.bindings.push(b)})});return a},update:function(b,a){g.each(b.bindings,function(c,b){b(a)})}}});m.when("A").register("gwAjax",function(f){return function(l,n){function g(c,b,g){"object"===typeof k.ue&&"function"===typeof k.ue.count&&e(n.errorCounter||
"gwAjaxError");"function"===typeof k.ueLogError&&k.ueLogError({logLevel:"WARN",attribution:"gwAjax-"+(n.id||l),message:"gwAjax call failed "+(JSON&&JSON.stringify?JSON.stringify({url:l,"params-data":n.params||n.data}):"")});"function"===typeof a&&a(c,b,g)}function e(a){"object"===typeof k.ue&&"function"===typeof k.ue.count&&k.ue.count(a,(k.ue.count(a)||0)+1)}n=f.copy(n);var b=n.success,a=n.error;n.success=function(a,h,e){a.error?g(a,h,e):"function"===typeof b&&b(a,h,e)};n.error=g;n.data=n.params?
n.params:n.data;e("gwAjaxCall");n.ajaxCounter&&e(n.ajaxCounter);return f.$.ajax(l,n)}});m.when("jQuery","gw-hud-punt").execute("gw-hud-sidekick",function(f){f("#gw-hud-grid").css({display:"none"})});m.when("A","sg-jsutil","a-modal","gw-productdb","productdb-binding-helper","sg-media-builder","gw-sims","gw-popover-data").register("gw-popover",function(f,l,n,g,e,b,a,c){function h(a,c){k.uet&&k.uet(a,c,{wb:1})}function D(a){if(k.ue&&"function"===typeof k.ue.count)return k.ue.count(a)||
0}function A(a){k.ue&&"function"===typeof k.ue.count&&k.ue.count(a,(k.ue.count(a)||0)+1)}function d(a){return a.closest("*[data-sgproduct]").data("sgproduct")}function x(a,c){u[a.asin]&&u[a.asin].isResolved()?y.resetSimData():(u[a.asin]=q.Deferred(),a&&a.asin&&c?y.fetch(a,c,u[a.asin]):u[a.asin].reject())}var q=f.$,v={},u={};if(!q("html").hasClass("a-touch")){l=q('<span style="display: none" />').appendTo("body");var t=q("#gw-popover-wrapper"),p=new e(g,t),w=n.create(l,{name:"gw-asin-popover",width:"90%",
"max-width":900,height:590,popoverLabel:c.popoverLabel,closeButton:!1}),y=new a(p),B=q("#gw-quick-look-btn");q("#a-page").delegate("li[data-sgproduct]","mouseenter",function(a){q(a.currentTarget).append(B);q(a.currentTarget).find("[title]").removeAttr("title");B.addClass("active")});B.mouseenter(function(){var a=q(this),c=d(a),a=a.siblings().children("a").attr("href");x(c,a)});q(".bestsellers .listRow a").mouseenter(function(){var a=q(this),c=d(a),a=a.attr("href");x(c,a);!c||!c.asin||v[c.asin]&&v[c.asin].isResolved()||
!(a=g.get(c.asin))||(v[c.asin]=q.Deferred(),v[c.asin].resolve(a))});m.when("gwAjax").execute(function(a){var c={};q("#a-page").delegate(".fresh-shoveler li[data-sgproduct]","mouseenter mousemove",function(d){d=q(d.currentTarget);var b=d.data("sgproduct").asin;if(!v[b]||!v[b].isResolved()){var h=[];d.add(d.prev("li[data-sgproduct]")).add(d.next("li[data-sgproduct]")).each(function(){var a=q(this).data("sgproduct");if(a&&a.asin){var d=g.get(a.asin),b=(d=!(!c[a.asin]&&d&&d.loading))&&1500<f.now()-c[a.asin];
if(!d||b)h.push(a.asin),c[a.asin]=f.now()}});v[b]=q.Deferred();h.length?(a("/gp/gw/ajax/pdb.html",{id:"quicklook-pdb",data:{swn:"productdb-ajax",sa:'{"asins": ["'+h.join('","')+'"]}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:k.ue_id}}).done(function(a){g._add(a);for(var d=0;d<h.length;d++)c[h[d]]=Infinity;v[b].resolve(a)}).fail(v[b].reject),A("freshHoverCount")):v[b].resolve()}})});q("#a-page").delegate("li[data-sgproduct]","mouseleave",function(a){B.removeClass("active")});var z="#a-popover-"+
w.attrs("id")+" ";n=q.map([".a-popover-header { display: none; }",".a-popover-inner { padding: 0px !important; margin: 0px !important; overflow: hidden !important; height: 100% !important; }"],function(a){return z+a}).join(" ");q("head").append("<style>"+n+"</style>");f.on("a:popover:hide:gw-asin-popover",function(a){k.history.state&&k.history.state.popup&&k.history.back();p.clear()});q(k).bind("popstate",function(){w.hide()});return{show:function(a,c){A("freshPopOverOn");h("bb","popoverLatency"+
D("freshPopOverOn"));k.history&&k.history.pushState&&k.history.pushState({popup:1},"");p.setAsin(a,{beforeUpdate:function(d){if(d.loading)return A("freshPopOverLoading"),d;var e=(new b(d.images[0])).autoCrop().scaleXY(500,400).build(),e={url:c,image:e,actionUrl:{action:"/gp/product/handle-buy-box/"+function(a){return a.substring(a.indexOf("/ref=")+1,a.length)}(c)}};d.reviews&&(e.reviews=q.extend({},d.reviews,{url:c+"#customerReviews"}));q.when(u[a],v[a]).done(function(c,d){y.showSims(a,c)});u[a].fail(y.setNoSimView);
h("cf","popoverLatency"+D("freshPopOverOn"));return q.extend({},d,e)}});w.show()},hide:function(){w.hide()}}}});m.when("A","sg-media-builder","gw-productdb").register("gw-sims",function(f,l,n){var g=f.$;return function(e){function b(a,c){k.uet&&k.uet(a,c,{wb:1})}function a(a){if(k.ue&&"function"===typeof k.ue.count)return k.ue.count(a)||0}function c(a){k.ue&&"function"===typeof k.ue.count&&k.ue.count(a,(k.ue.count(a)||0)+1)}function h(){if(!z){z=!0;C.hide();I.show();G.animate({height:"100%"},
300);var c=0,d=0,h=0,e=parseInt(I.css("width"),10),p=I.find(".sims-img-link");p.each(function(a,b){c+=b.clientWidth;e<c?g(b).hide():(d=c,h+=1)});var t=e-d;0<t&&(t=Math.floor(20+t/h-1),20<t&&p.css({"padding-right":t/2+"px","padding-left":t/2+"px"}));p="popoverLatency"+a("freshPopOverOn");b("be",p);k.uex&&k.uex("ld",p,{wb:1})}}function f(){0===--p&&h()}function A(a,d){var b=g("<a>"),h=g("<div>");b.attr("class","sims-img-link");h.addClass("sims-img-border");d&&b.addClass("selected");b.click(function(){c("freshPopOverSimsClick");
I.find(".sims-img-link").removeClass("selected");g(this).addClass("selected");e.clear();e.setAsin(a.asin,{beforeUpdate:function(d){d=g.extend(!0,{},a);var b=a.url;if(d.loading)c("freshPopOverLoading");else{var h=(new l(d.images[0])).autoCrop().scaleXY(500,400).build(),h={url:b,image:h,actionUrl:{action:"/gp/product/handle-buy-box/"+x(b)}};d.reviews&&(h.reviews=g.extend({},d.reviews,{url:b+"#customerReviews"}));d=g.extend({},d,h)}return d}})});return b.append(h)}function d(){g.each(w,function(a,c){c.url=
c.url.replace(/ref=gw_pdb_pdt-[\d]+/,x(y)+"&gw_sims-"+a)})}function x(a){return 0<=a.indexOf("redirect.html?")?a.replace(/.*redirect.html|(token|location)=.*?&/g,""):a.substring(a.indexOf("/ref=")+1,a.length)}function q(){z=!1;d();var a=[];p=w.length>p?p:w.length;g(w).each(function(c,d){d.loading=!1;if(d.images[0].src){var b=(new l(d.images[0])).autoCrop().scaleXY(130,100).build().src,h=g("<img>");h.attr("src",b);h.attr("class","sims-img");h.load(f);b=g("<div>");b.attr("class","sims-img-container");
var e=g("<div>");e.addClass("sims-img-overlay");g(b).append(e);b.append(h);h=A(d,0===c);h.append(b);a.push(h)}return c<p-1});p=a.length;g(a).each(function(a,c){I.append(c)});setTimeout(h,B)}function v(){m.when("gw-popover").execute(function(a){a.hide()})}function u(){C.hide();G.addClass("hidden");E.bind("click",v)}function t(){I.empty();G.add(C).removeAttr("style");G.removeClass("hidden");E.unbind("click",v);C.show();I.hide();p=8;w=[]}var p,w,y,B=1E4,z=!1,E=g("#sims-section"),G=E.find(".sims-wrapper"),
C=E.find(".sims-loading"),I=E.find(".sims-details");g("#gw-asin-popover");return{fetch:function(c,d,h){b("af","popoverLatency"+a("freshPopOverOn"));t();y=d;c.url=y;w.push(c);d=n.get(c.asin);setTimeout(h.reject,B);d.sims?h.resolve(d.sims):m.when("gwAjax").execute(function(a){a("/gp/gw/ajax/pdb.html",{id:"quicklook-sims-pdb",data:{swn:"productdb-ajax",sa:'{"asins": [], "entityId":"'+c.asin+'","datasetId": "purchase"}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:k.ue_id}}).done(function(a){if(a&&
a.p&&0<a.p.length){var d=c.asin,b=a.p;b&&(n.get(d).sims||n.addSims(d,b));return h.resolve(a.p)}return h.reject()}).fail(h.reject)});return h},setNoSimView:u,showSims:function(a,d){var b=n.get(a);b.loading?c("freshPopOverSimLoadBeforePrimeAsin"):w=b.sims?g.merge([b],b.sims):g.merge([b],d);4<w.length?q():(c("simsLessThanThreshold"),u())},resetSimData:t,setWaitPeriod:function(a){B=a}}}});m.when("A").execute(function(f){var l=f.$,n,g;if(!f.$("html").hasClass("a-touch"))if(k.cvox)k.ue&&k.ue.tag&&
k.ue.tag("screenReaderOn");else{l("#a-page").delegate("*[data-sgproduct] #gw-quick-look-btn","click",function(b){e(b)});l("#a-page").delegate(".bestseller-list *[data-sgproduct]","click",function(b){e(b)});m.when("gw-popover").execute(function(b){n=b;l("#gw-popover-close").click(function(){n.hide()});g&&n.show.apply(n,g)});var e=function(b){if(!(1<b.which||b.shiftKey||b.altKey||b.metaKey||b.ctrlKey)){var a,c;l(b.target).parents(".bestseller-list").length?(a=l(b.currentTarget).data("sgproduct"),c=
l(b.target).closest("a").attr("href")):(a=l("#gw-quick-look-btn").closest("*[data-sgproduct]").data("sgproduct"),c=l("#gw-quick-look-btn").siblings().children("a").attr("href"));var h=[a.asin,c];a.asin&&c&&(b.preventDefault(),n?n.show.apply(n,h):g=h)}}}});m.when("A","sg-jsutil","dombinder").register("productdb-binding-helper",function(f,l,n){return function(g,e){function b(a,c){n.update(d,h(c.beforeUpdate,a));a.loading||h(c.load,a)}function a(a){c();k=function(){a(f)};f.pdb_observe(k)}
function c(){f&&k&&(f.pdb_unobserve(k),k=null)}var h=l.safeCall,f=null,k=null,d=n.init(e);this.setAsin=function(d,h){h=h||{};c();f=g.get(d);b(f,h);f.loading&&a(function(a){b(a,h)});return f};this.clear=function(){c();f={};n.update(d,f)}}});k.P&&m.when("jQuery","afterLoad").register("gw-resource-logger",function(f){return{instrumentResources:function(l){var n;n=!1;if(f.isArray(l)&&!f.isEmptyObject(l)){n=!0;for(var g=0;g<l.length;g++){var e=l[g];if("id"in e&&"regex"in e&&"initiator"in e){if(!("string"===
typeof e.id&&"string"===typeof e.initiator&&e.regex instanceof RegExp)){n=!1;break}}else{n=!1;break}}}g=k.performance&&"function"===typeof k.performance.getEntriesByType&&"undefined"!==typeof k.performance.getEntriesByType("resource")&&"undefined"!==typeof k.ue;if(n&&g){n=Array(l.length);for(g=0;g<n.length;g++)n[g]=!1;for(e=g=0;e<k.performance.getEntriesByType("resource").length&&g<l.length;e++)for(var b=k.performance.getEntriesByType("resource")[e],a=b.name,c=b.initiatorType,h=0;h<l.length;h++)if(!n[h]){var m=
l[h].regex;if(c===l[h].initiator&&m.test(a)){a=l[h].id;c=b;b=c.duration;k.ue.count&&(k.ue.count(a+":duration",b),k.ue.count(a+":startTime",c.startTime));k.ue.tag&&(c=void 0,c=50>b?a+":cached":a+":notCached",k.ue.tag(c));n[h]=!0;g++;break}}}}}});m.register("sg-media-builder",function(){return function(f){var l=this,n=f.src,g=[];l.build=function(){var e=g.join("_");return{src:n.replace(/\.([^.]+)$/,"._"+e+"_.$1"),alt:f.alt}};l.autoCrop=function(){g.push("AC");return l};l.scaleX=function(e){g.push("SX"+
e);return l};l.scaleY=function(e){g.push("SY"+e);return l};l.upScaleX=function(e){g.push("UX"+e);return l};l.upScaleY=function(e){g.push("UY"+e);return l};l.scaleXY=function(e,b){return l.upScaleX(e).scaleY(b)}}});m.when("A","gwAjax").register("shogunProductDB",function(f,l){function n(b){var a=[];e[b]={loading:!0,pdb_observe:function(c){a.push(c)},pdb_unobserve:function(c){a=f.$.grep(a,function(a){return a!==c})},_trigger:function(){f.$.each(a,function(){this.call(e[b])})}};return e[b]}
function g(b,a){this.ajaxUrl=b;this.experienceStr=a;this._add=function(a){a.p&&f.$.each(a.p,function(a,c){if(c.asin){var b=e[c.asin]||n(c.asin);f.$.extend(b,c,{loading:!1,error:!1});b._trigger(c)}})};this.addSims=function(a,b){if(b){var g=e[a]||n(a);f.$.extend(g,{sims:b});g._trigger(a)}};this._ajax=function(c,h){var e=f.$.extend(!0,{},b,{params:{sa:JSON.stringify(c),oe:a}});k.ue_sid&&(e.url+="/"+k.ue_sid);k.ue_id&&(e.params.rrid=k.ue_id);return l(e.url,{method:e.method,params:e.params,success:h.success,
error:h.error,id:"gw-jslibs-"+h.id})};this.get=function(a){return a in e?e[a]:n(a)}}var e={};return function(b,a){return new g(b,a)}});m.when("jQuery","p-detect").register("component-feed-carousel",function(f,l){var n=f.extend(!0,{},l);f.each({pointerPrefix:function(){return"onmspointerup"in document||"onpointerup"in document?"onpointerup"in document?"pointer":"MSPointer":!1},actionMode:function(){var b=n.capabilities.pointerPrefix;return b?b:n.capabilities.touch?"touch":"mouse"}},function(b,
a){n.capabilities[b]=a()});var g={};f.each({start:{mouse:"down",touch:"start",pointer:"down",MSPointer:"Down"},end:{mouse:"up",touch:"end",pointer:"up",MSPointer:"Up"}},function(b,a){var c=n.capabilities.actionMode,h="string"===typeof a?a:a[c];g[b]=h?c+h:a.mouse===r?"":"mouse"+a.mouse});n.action=g;var e=function(b,a,c){this.init(b,a,c)};e.prototype={init:function(b,a,c){var h=this;f("html").hasClass("a-touch")&&b.addClass("feed-carousel-touch");h.adjustMarginOnChange=!0;h.defaultCssRightMargin=null;
h.minItems=a||10;h.imgClass=".product-image";h.$carousel=b;h.cfMinItems=c||6;h.cfFired=!1;h.shovelerReadyFired=!1;h.slotId=h.getSlotId();h.touch=h.$carousel.hasClass("feed-carousel-touch");h.ajaxSource=h.$carousel.parent().hasClass("ajaxSource");h.$shelf=h.$carousel.find(".feed-carousel-shelf");h.$viewport=h.$carousel.find(".feed-carousel-viewport");h.$spinner=h.$carousel.find(".spinner");h.$left=f(".feed-carousel-control.feed-left",b);h.$right=f(".feed-carousel-control.feed-right",b);h.$buttons=
f(".feed-carousel-control",b);h.$thumb=f(".feed-scrollbar-thumb",b);h.shelfLeft=-1*parseInt(h.$shelf.css("left"),10);h.calcWidth=f("html").hasClass("a-lt-ie9");h.noOpacity=f("html").hasClass("a-lt-ie9");h.$left.attr("aria-hidden",!0);h.$right.attr("aria-hidden",!0);h.bindEvents();h.$carousel.data("Carousel",h);h.$carousel.trigger("change");h.token=!1;h.lock=function(){h.token=!0};h.unlock=function(){h.token=!1};h.locked=function(){return h.token};m.when("gw-first-carousel").execute(function(){h.first=
h.$carousel.hasClass("first-carousel");h.shouldControlsOn()?h.showControls():h.hideControls()})},getSlotId:function(){var b=this.$carousel.closest(".gw-widget-instrument");return 0<b.length?f(b[0]).attr("id"):null},bindEvents:function(){function b(a){return n.capabilities.pointerPrefix&&-1<f.inArray(a.originalEvent.pointerType,[2,"touch"])||"touch"===n.capabilities.actionMode}var a=this,c=f("body");a.$buttons.ready(function(c){a.shovelerReadyFired||(a.slotId&&(c=a.slotId.toString()+"-active",k.GWI&&
k.GWI.recordLatency(c),k.GWI&&k.GWI.register(c)),a.shovelerReadyFired=!0)});a.$carousel.change(function(c){a.updateItems();a.updateSpinner();a.updateShelf();a.updateControls();null===a.defaultCssRightMargin&&a.$shelf.children("li").first()&&(a.defaultCssRightMargin=parseInt(a.$shelf.children("li").first().css("margin-right"),10));a.adjustMarginOnChange&&a.adjustCardMargin()});a.$left.click(function(c){c.preventDefault();a.changePage(-1);a.slotId&&a.logCounter("gw-"+a.slotId.toString()+"-left")});
a.$right.click(function(c){c.preventDefault();a.changePage(1);a.slotId&&a.logCounter("gw-"+a.slotId.toString()+"-right")});a.bindImageLoadEvents(a.$shelf);var h;f(k).resize(function(){clearTimeout(h);h=setTimeout(function(){var c=a.getDimensions(),c=Math.max(Math.min(c.shelfLeft,c.maxLeft),0);a.moveShelf(c)},100)});a.$thumb.mousedown(function(b){var h=b.clientX;1===b.which&&(b.preventDefault(),a.$carousel.addClass("scrolling"),c.bind("mousemove.feed-carousel",function(c){var b=a.getDimensions(),b=
Math.max(Math.min(b.shelfLeft+1/b.pageRatio*(c.clientX-h),b.maxLeft),0);h=c.clientX;a.moveShelf(b)}),f(document).bind("selectstart.feed-carousel",function(){return!1}))});c.add(k).mouseup(function(b){a.$carousel.removeClass("scrolling");a.$carousel.hasClass("hovering")||a.hideControls();c.unbind("mousemove.feed-carousel");f(document).unbind("selectstart.feed-carousel")});a.$carousel.hover(function(){a.$carousel.addClass("hovering");clearTimeout(a.hoverTimer);a.hoverTimer=setTimeout(function(){a.$carousel.hasClass("hovering")&&
!a.$carousel.hasClass("touching")?a.showControls():a.$carousel.removeClass("touching")},300)},function(){a.$carousel.removeClass("hovering touching");clearTimeout(a.hoverTimer);a.$carousel.hasClass("scrolling")||(a.hoverTimer=setTimeout(function(){a.$carousel.hasClass("hovering")||a.hideControls()},600))});a.$carousel.bind(n.action.start,function(c){b(c)&&(a.$carousel.addClass("touching"),clearTimeout(a.touchTimer),a.touchTimer=setTimeout(function(){a.$carousel.removeClass("touching")},5E3))});a.$carousel.bind(n.action.end,
function(c){b(c)&&(a.$carousel.removeClass("touching"),clearTimeout(a.touchTimer),clearTimeout(a.hoverTimer))});a.$viewport.scroll(function(){a.shelfLeft=a.$viewport.scrollLeft();a.updateControls()})},bindImageLoadEvents:function(b){var a=this;f(a.imgClass,b).one("load",function(){a.$carousel.trigger("change")})},getDimensions:function(){var b=this.$shelf.width(),a=this.shelfLeft,c=this.$carousel.width();return{pageWidth:c,shelfWidth:b,shelfLeft:a,pageRatio:c/b,leftRatio:a/b,maxLeft:b-c}},updateItems:function(){var b=
this,a=b.$shelf.find(".feed-carousel-card"),c=function(a){return"none"===a.css("display")};a.each(function(a,e){var g=f(e);if(!c(g))return!0;g.attr("aria-setsize",b.$shelf.find(".feed-carousel-card").size());g.attr("aria-posinset",a+1);g.attr("aria-hidden",!1);g.attr("role","listitem");return 0>=g.find(b.imgClass).filter(function(){return!this.complete}).length?(g.css("display","inline-block"),a+1>=b.cfMinItems&&!b.cfFired&&(b.slotId&&(g=b.slotId.toString()+"-visible",k.GWI&&k.GWI.recordLatency(g),
k.GWI&&k.GWI.register(g)),b.cfFired=!0),!0):!1});b.$items=a.filter(function(){return!c(f(this))})},updateShelf:function(){var b=0;this.calcWidth&&(this.$shelf.children().each(function(){b+=f(this).outerWidth(!0)}),this.$shelf.width(b));this.touch&&this.$carousel.not(".fresh-shoveler-tablet-app .feed-carousel").height(this.$shelf.outerHeight(!0))},updateSpinner:function(){this.size()<this.minItems&&this.ajaxSource?this.$spinner.show():(this.size()<this.minItems&&"object"===typeof k.ue&&"function"===
typeof k.ue.count&&k.ue.count("shovelerNotEnoughItem",(k.ue.count("shovelerNotEnoughItem")||0)+1),this.$spinner.hide())},updateControls:function(){this.updateArrows();this.updateScrollThumb()},shouldControlsOn:function(){return this.first&&!this.touch},showControls:function(b){this.$thumb.add(this.$buttons).stop(!0,!0).fadeIn({duration:300,complete:b,queue:!1})},hideControls:function(b){var a=this.$thumb;this.shouldControlsOn()||(a=a.add(this.$buttons));a.stop(!0,!0).fadeOut({duration:300,complete:b,
queue:!1})},appendCards:function(b){this.$shelf.append(b);this.bindImageLoadEvents(b);this.$carousel.trigger("change")},updateArrows:function(){var b=this,a=b.getDimensions();f.each([{$e:b.$left,enabled:0<a.shelfLeft},{$e:b.$right,enabled:a.shelfLeft<a.maxLeft}],function(a,h){var e=h.$e;h.enabled?e.removeClass("feed-control-disabled"):e.addClass("feed-control-disabled");b.noOpacity&&(h.enabled?e.css("opacity","1"):e.css("opacity","0.5"))})},updateScrollThumb:function(){var b=this.getDimensions(),
a=b.leftRatio*b.pageWidth,b=Math.min(b.pageRatio*b.pageWidth,b.pageWidth);this.$thumb.width(b).each(function(){f(this).animate({left:a},0)})},logCounter:function(b){"object"===typeof k.ue&&"function"===typeof k.ue.count&&(k.ue.count(b,(k.ue.count(b)||0)+1),k.ue.count("gw-shoveler-click",1))},changePage:function(b){var a=this.getDimensions(),c=this.alignWithItem(a.shelfLeft+b*a.pageWidth),c=Math.min(0>b?c.right:c.left,a.maxLeft);this.locked()||(this.lock(),a.shelfLeft===c?(this.bounce(this.$shelf,
-30*b),this.bounce(this.$thumb,6*b)):this.moveShelf(c,400))},moveShelf:function(b,a){function c(){h.updateArrows();h.unlock()}var h=this;a=a||0;h.shelfLeft=b;if(h.touch)h.$viewport.animate({scrollLeft:b},a,"swing",c);else{var e=h.getDimensions(),e=b/e.shelfWidth*e.pageWidth;h.$shelf.animate({left:-b},a,"swing",c);h.$thumb.animate({left:e},a,"swing",function(){h.updateScrollThumb();h.unlock()})}},getItems:function(){return this.$items},size:function(){return this.getItems().length},alignWithItem:function(b){if(0>
b)return{left:0,right:0};var a=this,c=a.getItems(),h=c.map(function(){var c=a.cardPosition(f(this));if(b>=c.left&&b<=c.right)return c}).get(0);return h?h:a.cardPosition(c.last())},cardPosition:function(b){var a=b.position().left;b=a+b.outerWidth(!0);return{left:a,right:b}},bounce:function(b,a){function c(a){var c={};c[h.touch?"left":"marginLeft"]=a;return c}var h=this;b.each(function(){var b=f(this);b.animate(c(a),400,"swing",function(){b.animate(c(0),100,"swing",h.unlock)})})},setCardMargin:function(b){this.$shelf.children("li").first()&&
this.$shelf.children("li").first().css("margin-right")!==b+"px"&&(this.$shelf.children("li").css("margin-right",b+"px"),this.updateShelf())},adjustCardMargin:function(b){b=b===r||null===b?this.defaultCssRightMargin:b;this.setCardMargin(b);var a=this.getDimensions(),a=0>a.maxLeft?Math.ceil(-a.maxLeft/this.size()):b;this.setCardMargin(a<b?b:a)}};return{createCarousel:function(b,a,c){f(b).each(function(b,g){var l=f(g);new e(l,a,c)})}}})});

}
/*
     FILE ARCHIVED ON 04:13:01 Dec 01, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 21:34:31 Dec 11, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 186.768
  exclusion.robots: 0.09
  exclusion.robots.policy: 0.078
  cdx.remote: 0.058
  esindex: 0.008
  LoadShardBlock: 134.53 (3)
  PetaboxLoader3.datanode: 62.918 (5)
  load_resource: 221.832 (2)
  PetaboxLoader3.resolve: 172.386 (2)
*/