var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(u){var r=window.AmazonUIPageJS||window.P,t=r._namespace||r.attributeErrors,b=t?t("CardJsRuntimeBuzzCopyBuild",""):r;b.guardFatal?b.guardFatal(u)(b,window):b.execute(function(){u(b,window)})})(function(u,r,t){xcp_d("@amzn/mix.client-runtime",["exports","tslib"],function(b,a){function d(c,a){return new Promise(function(b,d){setTimeout(function(){return d("Timed out while loading "+c)},a)})}function c(c,a){if(a)return{promise:Promise.resolve(a),resolve:n};var b=n;a=new Promise(function(c){b=
c});return{promise:Promise.race([a,d(c,1E3)]),resolve:b}}function e(c,b){return a.__awaiter(this,void 0,void 0,function(){return a.__generator(this,function(a){return[2,Promise.all(b.map(c))]})})}function m(b,d,f){var q=this;void 0===f&&(f={});return e(function(b){return a.__awaiter(q,void 0,void 0,function(){var p,q,e,n,h,y;return a.__generator(this,function(a){switch(a.label){case 0:if(f[b])return[2,f[b]];a=g[b]?g[b].promise:(g[b]=c(b)).promise;return[4,a];case 1:p=a.sent();q=p.capabilities;e=p.cardModuleFactory;
if(0!==q.length)return[3,2];h=e([]);return[3,4];case 2:return y=e,[4,m(q,d,f)];case 3:h=y.apply(void 0,[a.sent()]),a.label=4;case 4:return n=h,f[b]||(f[b]=n,d.push(n)),[2,n]}})})},b)}function h(a){var c="#"===a[0]?a.slice(1):a;if(c=document.getElementById(c))if(c=-1!==c.className.indexOf("mix-slot")?c.firstElementChild:c)if(c=c.dataset.model)try{return JSON.parse(c)}catch(b){throw Error("Unable to inflate seed ViewModel. Unable to parse the model. \nSelector: "+a+". \nValue: "+c);}else return t;else throw Error("Unable to inflate seed ViewModel. No card is rendered inside of: "+
a);else throw Error("Unable to inflate seed ViewModel. No element found for selector: "+a);}var g={},n=function(){};b.registerCapabilityModule=function(a,b){g[a]?g[a].resolve(b):g[a]=c(a,b)};b.registerCardFactory=function(c,b){return a.__awaiter(this,void 0,void 0,function(){var d,q,e,g,n,w,x;return a.__generator(this,function(a){switch(a.label){case 0:return d=b.capabilities,q=b.cardModuleFactory,e=[],[4,m(d,e)];case 1:return g=a.sent(),n=q(g),w=n.P,x=h(c),e.forEach(function(a){return a.initialize(c,
x,n,w)}),w.execute(function(){n.card(x)}),[2]}})})};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/dom",["exports"],function(b){var a,d,c={get cardRoot(){return d},get container(){return a}};b.default=c;b.initialize=function(c,b,h){b="#"===c[0]?c.slice(1):c;d=document.getElementById(b);if(!d)throw Error("No node found for selector: "+c);a=d.parentNode;if(d.classList.contains("mix-slot")&&(a=d,d=d.children[0],!d))throw Error("No card root found within mix-slot");};b.unscope=function(a){return null!==
a&&a.__unscope__?a.__unscope__(c):a};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/guard",["exports","@c/logger"],function(b,a){a=a&&a.hasOwnProperty("default")?a["default"]:a;var d,c=function(a,c){return d.guardFatal(a,c)},e=function(a,c){return d.guardError(a,c)},m=function(a){return d.guardCurrent(a)},h=function(c){return c.catch(function(c){a.log(c.message);throw c;})},g={asFatal:c,asError:e,current:m,promise:h};b.asError=e;b.asFatal=c;b.current=m;b.default=g;b.initialize=function(a,
c,b,e){d=e};b.promise=h;Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/logger",["exports"],function(b){var a,d=function(c,b,d){return a.log(c,b,d)};b.default={log:d};b.initialize=function(c,b,d,h){a=h};b.log=d;Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/remote-operations",["exports","@c/dom","@c/guard","@c/scoped-dom"],function(b,a,d,c){function e(a){return function(c){return n(p,a,c,l)}}function m(a,c){0<c.length&&c.forEach(function(c){a[c]=e(c)})}a=a&&a.hasOwnProperty("default")?
a["default"]:a;d=d&&d.hasOwnProperty("default")?d["default"]:d;c=c&&c.hasOwnProperty("default")?c["default"]:c;var h={post:function(c){var a=new r.XMLHttpRequest,b=new Promise(function(c,b){a.onabort=function(){b(Error("XMLHttpRequest aborted"))}}),d=new Promise(function(a,b){0<c.timeout&&r.setTimeout(function(){b(Error("XMLHttpRequest timeout"))},c.timeout)}),e=new Promise(function(b,d){var e=c.headers||{},p=function(){var z;z=1223===a.status?204:a.status;var D=a.response||"{}";if(0===z)d(Error("Internal XMLHttpRequest Error"));
else if(200!==z)d({statusCode:z,response:D});else{var e=c.uri,B;a:{var A=a.getAllResponseHeaders();B="NO-CONTENT-TYPE-FOUND";if(A)for(var A=A.trim().split("\n"),p=A.length,l=0;l<p;l++){var k=A[l].split(":"),f=1<=k.length?k[0].trim():"";if(2===k.length&&/content-type/i.test(f)&&(k=k[1].trim().split(";"),1<=k.length)){B=k[0];break a}}}b({body:D,statusCode:z,method:"POST",url:e,rawRequest:a,contentType:B})}},f=function(a){a instanceof Error?d(a):d(Error(""+(a||"Unknown XMLHttpRequest Error")))};a.onreadystatechange=
function(){4===a.readyState&&setTimeout(p,0)};a.onload=p;a.onerror=f;a.onprogress=function(){};a.ontimeout=f;a.open("POST",c.uri,!0);if(a.setRequestHeader)for(var l in e)e.hasOwnProperty(l)&&a.setRequestHeader(l,e[l]);a.send(c.body||null)});return Promise.race([b,d,e])}},g=JSON.stringify({}),n=function(a,b,e,p){e=e?JSON.stringify(e):g;a=h.post({body:e,uri:a+b,timeout:1E3,headers:{Accept:"text/html, application/json","Content-Type":"application/json","x-amz-acp-params":p}});return d.promise(a.then(function(a){var b=
a.body;if("application/json"===a.contentType)try{return JSON.parse(b)}catch(d){throw Error("Parsing error encountered when parsing json response: "+d);}else if("text/html"===a.contentType)try{var e=(new DOMParser).parseFromString(b,"text/html");return c.proxify(e.querySelector("body").firstElementChild)}catch(d){throw Error("Error encountered when parsing html response"+d);}else throw Error("Unexpected content-type found when parsing response: "+a.contentType);}))},p,l,f={};b.default={setup:function(a){void 0===
a&&(a=[]);m(f,a);return f}};b.initialize=function(c,b,d){if((c=a.cardRoot)&&c.hasAttribute("data-acp-path")&&c.hasAttribute("data-acp-params")){p=c.getAttribute("data-acp-path")||"";b=c.getAttribute("data-acp-params")||"";try{var e=document.createElement("textarea");e.innerHTML=b;l=0===e.childNodes.length?"":e.childNodes[0].nodeValue||""}catch(g){throw Error("Issue encountered while parsing card attributes when setting up RemoteOperations, error: "+g);}c.removeAttribute("data-acp-path");c.removeAttribute("data-acp-params")}else throw Error("Remote Operation capability requires card root node to exist and have attribute: data-acp-path \x26 data-acp-params");
d._operationNames&&m(f,d._operationNames)};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/scoped-dom",["exports","tslib","@c/dom"],function(b,a,d){function c(a,c){return"undefined"!==typeof Proxy&&"undefined"!==typeof Reflect?(a.__proxified||(a.__proxified=new Proxy(a,c)),a.__proxified):a}var e="default"in d?d["default"]:d,m=["before","after","replaceWith","append","prepend"],h=["appendChild","replaceChild","insertBefore","insertAdjacentElement"],g={get:function(b,l){var f=Reflect.get(b,
l);return"__proxified"===l?Reflect.get(b,l):"ownerDocument"===l?t:"parentElement"===l||"parentNode"===l?null!==f&&f!==e.container?c(f,g):null:"__unscope__"===l?function(a){return a===e?b:null}:f instanceof HTMLElement||f instanceof Node||f instanceof EventTarget?c(f,g):f instanceof HTMLCollection?c(f,n):"function"===typeof f?"addEventListener"===l?function(d,e,l){var h;h="function"===typeof e?function(a){return e.call(c(this,g),c(a,g))}:a.__assign(a.__assign({},e),{handleEvent:function(a){return e.handleEvent.call(this,
c(a,g))}});e.__proxy=h;return f.call(b,d,h,l)}:"removeEventListener"===l?function(a,c,d){f.call(b,a,c.__proxy,d)}:"closest"===l?function(a){a=f.call(b,a);return e.cardRoot.contains(a)?a:null}:-1<m.indexOf(l)?function(){for(var c=[],e=0;e<arguments.length;e++)c[e]=arguments[e];c=c.map(function(a){return d.unscope(a)});f.call.apply(f,a.__spread([b],c))}:-1<h.indexOf(l)?function(a,e){a=d.unscope(a);e&&(e=d.unscope(e));return c(e?f.call(b,a,e):f.call(b,a),g)}:function(){for(var a=[],d=0;d<arguments.length;d++)a[d]=
arguments[d];a=f.apply(b,a);return a instanceof HTMLElement||a instanceof Node?c(a,g):a instanceof HTMLCollection?c(a,n):a}:f},set:function(a,b,d){"string"===typeof b&&b.startsWith("on")&&"function"===typeof d?Reflect.set(a,b,function(a){d.call(c(this,g),c(a,g))}):Reflect.set(a,b,d);return!0}},n={get:function(a,b){return"number"===typeof b||"string"===typeof b&&Number.isInteger(Number.parseInt(b,10))?c(Reflect.get(a,b),g):Reflect.get(a,b)}};b.default={get cardRoot(){return c(e.cardRoot,g)},proxify:function(a){return c(a,
g)}};b.initialize=function(a,c,b){};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/sudo",["exports"],function(b){b.default={get cardRoot(){return null}};b.initialize=function(a,b,c){};b.sudo={};Object.defineProperty(b,"__esModule",{value:!0})});(function(){var b=function(a,c,b){xcp_d(a,c,b)};b.amd=!0;var a,d,c,e,m,h,g,n,p,l,f,q,r,v,t,w,x,u,y,C;(function(a){function c(a,b){a!==d&&("function"===typeof Object.create?Object.defineProperty(a,"__esModule",{value:!0}):a.__esModule=!0);return function(c,
d){return a[c]=b?b(c,d):d}}var d="object"===typeof global?global:"object"===typeof self?self:"object"===typeof this?this:{};"function"===typeof b&&b.amd?b("tslib",["exports"],function(b){a(c(d,c(b)))}):"object"===typeof module&&"object"===typeof module.exports?a(c(d,c(module.exports))):a(c(d))})(function(b){var E=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};a=function(a,b){function c(){this.constructor=
a}E(a,b);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)};d=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++){b=arguments[c];for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(a[e]=b[e])}return a};c=function(a,b){var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&0>b.indexOf(d)&&(c[d]=a[d]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var e=0;for(d=Object.getOwnPropertySymbols(a);e<d.length;e++)0>b.indexOf(d[e])&&Object.prototype.propertyIsEnumerable.call(a,
d[e])&&(c[d[e]]=a[d[e]])}return c};e=function(a,b,c,d){var e=arguments.length,g=3>e?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d,f;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)g=Reflect.decorate(a,b,c,d);else for(var k=a.length-1;0<=k;k--)if(f=a[k])g=(3>e?f(g):3<e?f(b,c,g):f(b,c))||g;return 3<e&&g&&Object.defineProperty(b,c,g),g};m=function(a,b){return function(c,d){b(c,d,a)}};h=function(a,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(a,
b)};g=function(a,b,c,d){return new (c||(c=Promise))(function(e,g){function f(a){try{h(d.next(a))}catch(b){g(b)}}function k(a){try{h(d["throw"](a))}catch(b){g(b)}}function h(a){a.done?e(a.value):(new c(function(b){b(a.value)})).then(f,k)}h((d=d.apply(a,b||[])).next())})};n=function(a,b){function c(a){return function(b){return d([a,b])}}function d(c){if(g)throw new TypeError("Generator is already executing.");for(;e;)try{if(g=1,f&&(k=c[0]&2?f["return"]:c[0]?f["throw"]||((k=f["return"])&&k.call(f),0):
f.next)&&!(k=k.call(f,c[1])).done)return k;if(f=0,k)c=[c[0]&2,k.value];switch(c[0]){case 0:case 1:k=c;break;case 4:return e.label++,{value:c[1],done:!1};case 5:e.label++;f=c[1];c=[0];continue;case 7:c=e.ops.pop();e.trys.pop();continue;default:if(!(k=e.trys,k=0<k.length&&k[k.length-1])&&(6===c[0]||2===c[0])){e=0;continue}if(3===c[0]&&(!k||c[1]>k[0]&&c[1]<k[3]))e.label=c[1];else if(6===c[0]&&e.label<k[1])e.label=k[1],k=c;else if(k&&e.label<k[2])e.label=k[2],e.ops.push(c);else{k[2]&&e.ops.pop();e.trys.pop();
continue}}c=b.call(a,e)}catch(h){c=[6,h],f=0}finally{g=k=0}if(c[0]&5)throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}var e={label:0,sent:function(){if(k[0]&1)throw k[1];return k[1]},trys:[],ops:[]},g,f,k,h;return h={next:c(0),"throw":c(1),"return":c(2)},"function"===typeof Symbol&&(h[Symbol.iterator]=function(){return this}),h};p=function(a,c){for(var b in a)c.hasOwnProperty(b)||(c[b]=a[b])};l=function(a){var c="function"===typeof Symbol&&a[Symbol.iterator],b=0;return c?c.call(a):{next:function(){a&&
b>=a.length&&(a=void 0);return{value:a&&a[b++],done:!a}}}};f=function(a,c){var b="function"===typeof Symbol&&a[Symbol.iterator];if(!b)return a;a=b.call(a);var d,e=[],f;try{for(;(void 0===c||0<c--)&&!(d=a.next()).done;)e.push(d.value)}catch(g){f={error:g}}finally{try{d&&!d.done&&(b=a["return"])&&b.call(a)}finally{if(f)throw f.error;}}return e};q=function(){for(var a=[],c=0;c<arguments.length;c++)a=a.concat(f(arguments[c]));return a};r=function(){for(var a=0,c=0,b=arguments.length;c<b;c++)a+=arguments[c].length;
for(var a=Array(a),d=0,c=0;c<b;c++)for(var e=arguments[c],f=0,g=e.length;f<g;f++,d++)a[d]=e[f];return a};v=function(a){return this instanceof v?(this.v=a,this):new v(a)};t=function(a,c,b){function d(a){l[a]&&(n[a]=function(c){return new Promise(function(b,d){1<m.push([a,c,b,d])||e(a,c)})})}function e(a,c){try{var b=l[a](c);b.value instanceof v?Promise.resolve(b.value.v).then(f,g):h(m[0][2],b)}catch(d){h(m[0][3],d)}}function f(a){e("next",a)}function g(a){e("throw",a)}function h(a,c){(a(c),m.shift(),
m.length)&&e(m[0][0],m[0][1])}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var l=b.apply(a,c||[]),n,m=[];return n={},d("next"),d("throw"),d("return"),n[Symbol.asyncIterator]=function(){return this},n};w=function(a){function c(e,f){b[e]=a[e]?function(c){return(d=!d)?{value:v(a[e](c)),done:"return"===e}:f?f(c):c}:f}var b,d;return b={},c("next"),c("throw",function(a){throw a;}),c("return"),b[Symbol.iterator]=function(){return this},b};x=function(a){function c(d){e[d]=
a[d]&&function(c){return new Promise(function(e,f){c=a[d](c);b(e,f,c.done,c.value)})}}function b(a,c,d,e){Promise.resolve(e).then(function(c){a({value:c,done:d})},c)}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var d=a[Symbol.asyncIterator],e;return d?d.call(a):(a="function"===typeof l?l(a):a[Symbol.iterator](),e={},c("next"),c("throw"),c("return"),e[Symbol.asyncIterator]=function(){return this},e)};u=function(a,c){Object.defineProperty?Object.defineProperty(a,
"raw",{value:c}):a.raw=c;return a};y=function(a){if(a&&a.__esModule)return a;var c={};if(null!=a)for(var b in a)Object.hasOwnProperty.call(a,b)&&(c[b]=a[b]);c["default"]=a;return c};C=function(a){return a&&a.__esModule?a:{"default":a}};b("__extends",a);b("__assign",d);b("__rest",c);b("__decorate",e);b("__param",m);b("__metadata",h);b("__awaiter",g);b("__generator",n);b("__exportStar",p);b("__values",l);b("__read",f);b("__spread",q);b("__spreadArrays",r);b("__await",v);b("__asyncGenerator",t);b("__asyncDelegator",
w);b("__asyncValues",x);b("__makeTemplateObject",u);b("__importStar",y);b("__importDefault",C)})})();xcp_d("@c/aui-card",["exports","@p/a-cardui","@p/a-cardui-deck"],function(b,a,d){a=a&&a.hasOwnProperty("default")?a["default"]:a;d=d&&d.hasOwnProperty("default")?d["default"]:d;b.default={getCard:function(c){var b=a.get(c);return{isExpanded:function(){return b.isExpanded()},toggle:function(){return b.toggle()}}},getCardDeck:function(a){var b=d.get(a);return{initializeAllCards:function(){return b.initializeAllCards()}}}};
b.initialize=function(a,b,d){};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/aui-carousel",["exports","tslib","@c/dom","@p/a-carousel-framework"],function(b,a,d,c){function e(c){var b=this;return function(d,e){return a.__awaiter(b,void 0,void 0,function(){var b;return a.__generator(this,function(a){switch(a.label){case 0:return[4,c({indexes:d,ids:e})];case 1:b=a.sent();"string"===typeof b&&(b=(new DOMParser).parseFromString(b,"text/html").body.children[0]);if(!b.classList.contains("a-carousel-content-fragment"))throw Error("CarouselRemoteOperation did not return a ContentFragment"+
b.innerHTML);return[2,b.querySelectorAll(".a-carousel-card-fragment")]}})})}}c=c&&c.hasOwnProperty("default")?c["default"]:c;b.default={getCarousel:function(a){var b=c.getCarousel(d.unscope(a)),g=b.getAttr("name");return{gotoPage:function(){return b.gotoPage()},gotoPrevPage:function(){return b.gotoPrevPage()},gotoNextPage:function(){return b.gotoNextPage()},get initialized(){return new Promise(function(a){return c.onInit(g,function(){return a()})})},attachRemoteOperation:function(a){if(b.getAttr("async_provider"))throw Error("Carousel already has attached remoteOperation");
b.setAttr("async_provider",e(a))}}}};b.initialize=function(a,c,b){};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/aui-truncate",["exports","@c/dom","@p/a-truncate"],function(b,a,d){a=a&&a.hasOwnProperty("default")?a["default"]:a;d=d&&d.hasOwnProperty("default")?d["default"]:d;var c;b.default={updateAll:function(){Array.prototype.slice.call(c).forEach(function(a){return d.get(a).update()})}};b.initialize=function(b,d,h){c=a.cardRoot.getElementsByClassName("a-truncate")};Object.defineProperty(b,
"__esModule",{value:!0})});xcp_d("@c/aui-utils",["exports","@p/A","@c/dom"],function(b,a,d){a=a&&a.hasOwnProperty("default")?a["default"]:a;b.default={hide:function(c){a.hide(d.unscope(c))},show:function(c){a.show(d.unscope(c))},onScreen:function(c,b){return a.onScreen(d.unscope(c),b)},objectIsEmpty:function(c){return a.objectIsEmpty(c)},equals:function(c,b){return a.equals(c,b)},diff:function(c,b){return a.diff(c,b)},throttle:function(c,b,d){return a.throttle(c,b,d)},debounce:function(c,b,d){return a.debounce(c,
b,d)},defer:function(c){a.defer(c)},interval:function(c,b){return a.interval(c,b)},animationFrameDelay:function(c){return a.animationFrameDelay(c)},delay:function(c,b){return a.delay(c,b)},once:function(c){return a.once(c)},attributionChain:function(c){return a.attributionChain(d.unscope(c))}};b.initialize=function(a,b,d){};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/error-handling",["exports"],function(b){var a,d=function(b,d,m,h){a.error(b,d,m,h)};b.default={error:d};b.error=d;
b.initialize=function(b,d,m,h){a=h};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/metrics",["exports"],function(b){var a=function(a,b,d){return r.ue.count(a,b,d)},d={count:a};b.count=a;b.default=d;b.initialize=function(a,b,d){};Object.defineProperty(b,"__esModule",{value:!0})});xcp_d("@c/pagemarker",["exports","@p/A","@c/dom","@c/guard"],function(b,a,d,c){function e(b){var d;return function(){return c.promise(d=d||new Promise(function(c){return a.on(b,function(){return c()})}))}}a=
a&&a.hasOwnProperty("default")?a["default"]:a;d=d&&d.hasOwnProperty("default")?d["default"]:d;c=c&&c.hasOwnProperty("default")?c["default"]:c;var m=e("ready"),h=e("load");b.default={get pageReady(){return m()},get pageLoad(){return h()},visible:function(b){void 0===b&&(b=0);var c,e=new Promise(function(a){return c=a}),h=function(){a.onScreen(d.container,b)&&(a.off("scroll resize ready",h),c())};a.on("scroll resize ready",h);h();return e}};b.initialize=function(a,b,c){};Object.defineProperty(b,"__esModule",
{value:!0})});xcp_d("@c/x-sample-capability-card-scoped",["exports"],function(b){b.default={};b.initialize=function(a,b,c){};Object.defineProperty(b,"__esModule",{value:!0})})});

}
/*
     FILE ARCHIVED ON 00:35:41 Nov 01, 2019 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 22:48:45 Dec 11, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 403.922
  exclusion.robots: 0.06
  exclusion.robots.policy: 0.052
  cdx.remote: 0.046
  esindex: 0.008
  LoadShardBlock: 187.211 (3)
  PetaboxLoader3.datanode: 71.259 (4)
  load_resource: 105.752
  PetaboxLoader3.resolve: 77.472
*/