var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(e,h,w){e.execute(function(){e.when("A").register("sg-jsutil",function(d){var j=d.$;return{safeCall:function(d,f){return j.isFunction(d)?d(f):f}}});e.when("A").register("dombinder",function(d){function j(b,c){for(var f=0,c=c.split("."),d=c.length;f<d;f++)b=b&&b[c[f]];return b}function e(d){return f.map(f(d).data("bind").split(","),function(c){var c=c.split(":"),j=f.trim(c[0]),e=f.trim(c[1]),g=b[j];if(g)return g.init&&g.init(d,e),function(b){g.update(d,e,b)}})}var f=d.$,b={text:{update:function(b,
c,d){f(b).text(j(d,c)||"")}},html:{update:function(b,c,d){f(b).html(j(d,c)||"")}},href:{update:function(b,c,d){f(b).attr("href",j(d,c)||"")}},trimText:{update:function(b,c){var d=f(b),j=d.text();if(j.length>c){for(var e=c-4;e>=0&&"[.,-/#!$%^&*;:{}=-_`~()] ".indexOf(j[e])>0;)e--;d.text(j.substring(0,e>=0?e+1:c-3)+"...")}}},value:{update:function(b,c,d){f(b).val(j(d,c)||"")}},visible:{update:function(b,c,d){var e=!1;c.charAt(0)==="!"&&(e=!0,c=c.substring(1));c=!!j(d,c);e!==c?f(b).show():f(b).hide()}},
css:{init:function(b,c){var d=f(b),e=d.data("dombcss")||[];e[c]="";d.data("dombcss",e)},update:function(b,c,d){var b=f(b),e=b.data("dombcss"),g=e[c],d=j(d,c);g!==d&&(e[c]=d,g&&b.removeClass(g),d&&b.addClass(d))}},attr:{init:function(b,c){var d=f(b),e=d.data("dombattr")||[];e[c]={};d.data("dombattr",e)},update:function(b,c,d){var e=f(b),b=e.data("dombattr"),g=b[c],d=j(d,c);g!==d&&(b[c]=d,g&&f.each(g,function(b){e.removeAttr(b)}),d&&f.each(d,function(b,a){e.attr(b,a)}))}}};return{init:function(b){var c=
{$root:b,bindings:[]};b.find("[data-bind]").each(function(){f.each(e(this),function(b,f){c.bindings.push(f)})});return c},update:function(b,c){f.each(b.bindings,function(b,f){f(c)})}}});e.when("A").register("gwAjax",function(d){return function(e,g){function f(b,f,d){typeof h.ue==="object"&&typeof h.ue.count==="function"&&(g.errorCounter?h.ue.count(g.errorCounter,(h.ue.count(g.errCounter)||0)+1):h.ue.count("gwAjaxError",(h.ue.count("gwAjaxError")||0)+1));typeof h.ueLogError==="function"&&h.ueLogError({logLevel:"WARN",
attribution:"gwAjax-"+(g.id||e),message:"gwAjax call failed "+(JSON&&JSON.stringify?JSON.stringify({url:e,"params-data":g.params||g.data}):"")});typeof k==="function"&&k(b,f,d)}var g=d.copy(g),b=g.success,k=g.error;g.success=function(c,d,e){c.error?f(c,d,e):typeof b==="function"&&b(c,d,e)};g.error=f;g.data=g.params?g.params:g.data;typeof h.ue==="object"&&typeof h.ue.count==="function"&&h.ue.count("gwAjaxCall",(h.ue.count("gwAjaxCall")||0)+1);return d.$.ajax(e,g)}});e.when("A","sg-jsutil","a-modal",
"gw-productdb","productdb-binding-helper","sg-media-builder","gw-sims","gw-popover-data").register("gw-popover",function(d,j,g,f,b,k,c,u){function q(a,b){h.uet&&h.uet(a,b,{wb:1})}function t(a){if(h.ue&&typeof h.ue.count==="function")return h.ue.count(a)||0}function r(a){h.ue&&typeof h.ue.count==="function"&&h.ue.count(a,(h.ue.count(a)||0)+1)}function a(a){return a.closest("*[data-sgproduct]").data("sgproduct")}function v(a,b){m[a.asin]&&m[a.asin].isResolved()?C.resetSimData():(m[a.asin]=n.Deferred(),
a&&a.asin&&b?C.fetch(a,b,m[a.asin]):m[a.asin].reject())}var n=d.$,s={},m={};if(!n("html").hasClass("a-touch")){var j=n('<span style="display: none" />').appendTo("body"),o=n("#gw-popover-wrapper"),y=new b(f,o),l=g.create(j,{name:"gw-asin-popover",width:"90%","max-width":900,height:590,popoverLabel:u.popoverLabel,closeButton:!1}),C=new c(y),x=n("#gw-quick-look-btn");n("#a-page").delegate("li[data-sgproduct]","mouseenter",function(a){n(a.currentTarget).append(x);n(a.currentTarget).find("[title]").removeAttr("title");
x.addClass("active")});x.mouseenter(function(){var b=n(this),c=a(b),b=b.siblings().children("a").attr("href");v(c,b)});n(".bestsellers .listRow a").mouseenter(function(){var b=n(this),c=a(b),b=b.attr("href");v(c,b);if(c&&c.asin&&(!s[c.asin]||!s[c.asin].isResolved()))if(b=f.get(c.asin))s[c.asin]=n.Deferred(),s[c.asin].resolve(b)});e.when("gwAjax").execute(function(a){var b={};n("#a-page").delegate(".fresh-shoveler li[data-sgproduct]","mouseenter mousemove",function(c){var c=n(c.currentTarget),m=c.data("sgproduct").asin;
if(!s[m]||!s[m].isResolved()){var l=[];c.add(c.prev("li[data-sgproduct]")).add(c.next("li[data-sgproduct]")).each(function(){var a=n(this).data("sgproduct");if(a&&a.asin){var c=f.get(a.asin),m=(c=!(!b[a.asin]&&c&&c.loading))&&d.now()-b[a.asin]>1500;if(!c||m)l.push(a.asin),b[a.asin]=d.now()}});s[m]=n.Deferred();l.length?(a("/gp/gw/ajax/pdb.html",{id:"quicklook-pdb",data:{swn:"productdb-ajax",sa:'{"asins": ["'+l.join('","')+'"]}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:h.ue_id}}).done(function(a){f._add(a);
for(var c=0;c<l.length;c++)b[l[c]]=Infinity;s[m].resolve(a)}).fail(s[m].reject),r("freshHoverCount")):s[m].resolve()}})});n("#a-page").delegate("li[data-sgproduct]","mouseleave",function(){x.removeClass("active")});var z="#a-popover-"+l.attrs("id")+" ",g=n.map([".a-popover-header { display: none; }",".a-popover-inner { padding: 0px !important; margin: 0px !important; overflow: hidden !important; height: 100% !important; }"],function(a){return z+a}).join(" ");n("head").append("<style>"+g+"</style>");
d.on("a:popover:hide:gw-asin-popover",function(){h.history.state&&h.history.state.popup&&h.history.back();y.clear()});n(h).bind("popstate",function(){l.hide()});return{show:function(a,b){r("freshPopOverOn");q("bb","popoverLatency"+t("freshPopOverOn"));h.history&&h.history.pushState&&h.history.pushState({popup:1},"");y.setAsin(a,{beforeUpdate:function(c){if(c.loading)return r("freshPopOverLoading"),c;var f=(new k(c.images[0])).autoCrop().scaleXY(500,400).build(),f={url:b,image:f,actionUrl:{action:"/gp/product/handle-buy-box/"+
b.substring(b.indexOf("/ref=")+1,b.length)}};c.reviews&&(f.reviews=n.extend({},c.reviews,{url:b+"#customerReviews"}));n.when(m[a],s[a]).done(function(b){C.showSims(a,b)});m[a].fail(C.setNoSimView);q("cf","popoverLatency"+t("freshPopOverOn"));return n.extend({},c,f)}});l.show()},hide:function(){l.hide()}}}});e.when("A","sg-media-builder","gw-productdb").register("gw-sims",function(d,j,g){var f=d.$;return function(b){function d(a,b){h.uet&&h.uet(a,b,{wb:1})}function c(a){if(h.ue&&typeof h.ue.count===
"function")return h.ue.count(a)||0}function u(a){h.ue&&typeof h.ue.count==="function"&&h.ue.count(a,(h.ue.count(a)||0)+1)}function q(){if(!z){z=!0;D.hide();p.show();A.animate({height:"100%"},300);var a=0,b=0,m=0,l=parseInt(p.css("width"),10),o=p.find(".sims-img-link");o.each(function(c,d){a+=d.clientWidth;l<a?f(d).hide():(b=a,m+=1)});var e=l-b;e>0&&(e=Math.floor(20+e/m-1),e>20&&o.css({"padding-right":e/2+"px","padding-left":e/2+"px"}));o="popoverLatency"+c("freshPopOverOn");d("be",o);h.uex&&h.uex("ld",
o,{wb:1})}}function t(){--y===0&&q()}function r(a,c){var m=f("<a>"),l=f("<div>");m.attr("class","sims-img-link");l.addClass("sims-img-border");c&&m.addClass("selected");m.click(function(){u("freshPopOverSimsClick");p.find(".sims-img-link").removeClass("selected");f(this).addClass("selected");b.clear();b.setAsin(a.asin,{beforeUpdate:function(){var b;b=f.extend(!0,{},a);var c=a.url;if(b.loading)u("freshPopOverLoading");else{var m=(new j(b.images[0])).autoCrop().scaleXY(500,400).build(),m={url:c,image:m,
actionUrl:{action:"/gp/product/handle-buy-box/"+v(c)}};b.reviews&&(m.reviews=f.extend({},b.reviews,{url:c+"#customerReviews"}));b=f.extend({},b,m)}return b}})});return m.append(l)}function a(){f.each(l,function(a,b){b.url=b.url.replace(/ref=gw_pdb_pdt-[\d]+/,v(C)+"&gw_sims-"+a)})}function v(a){return a.indexOf("redirect.html?")>=0?a.replace(/.*redirect.html|(token|location)=.*?&/g,""):a.substring(a.indexOf("/ref=")+1,a.length)}function n(){z=!1;a();var b=[];y=l.length>y?y:l.length;f(l).each(function(a,
c){c.loading=!1;if(c.images[0].src){var m=(new j(c.images[0])).autoCrop().scaleXY(130,100).build().src,l=f("<img>");l.attr("src",m);l.attr("class","sims-img");l.load(t);m=f("<div>");m.attr("class","sims-img-container");var d=f("<div>");d.addClass("sims-img-overlay");f(m).append(d);m.append(l);l=r(c,a===0);l.append(m);b.push(l)}return a<y-1});y=b.length;f(b).each(function(a,b){p.append(b)});setTimeout(q,x)}function s(){e.when("gw-popover").execute(function(a){a.hide()})}function m(){D.hide();A.addClass("hidden");
B.bind("click",s)}function o(){p.empty();A.add(D).removeAttr("style");A.removeClass("hidden");B.unbind("click",s);D.show();p.hide();y=8;l=[]}var y,l,C,x=1E4,z=!1,B=f("#sims-section"),A=B.find(".sims-wrapper"),D=B.find(".sims-loading"),p=B.find(".sims-details");f("#gw-asin-popover");return{fetch:function(a,b,m){d("af","popoverLatency"+c("freshPopOverOn"));o();C=b;a.url=C;l.push(a);b=g.get(a.asin);setTimeout(m.reject,x);b.sims?m.resolve(b.sims):e.when("gwAjax").execute(function(b){b("/gp/gw/ajax/pdb.html",
{id:"quicklook-sims-pdb",data:{swn:"productdb-ajax",sa:'{"asins": [], "entityId":"'+a.asin+'","datasetId": "purchase"}',oe:'{"isDesktop":1,"isTablet":0,"isMobile":0}',rrid:h.ue_id}}).done(function(b){if(b&&b.p&&b.p.length>0){var c=a.asin,f=b.p;f&&(g.get(c).sims||g.addSims(c,f));return m.resolve(b.p)}return m.reject()}).fail(m.reject)});return m},setNoSimView:m,showSims:function(a,b){var c=g.get(a);c.loading?u("freshPopOverSimLoadBeforePrimeAsin"):l=c.sims?f.merge([c],c.sims):f.merge([c],b);l.length>
4?n():(u("simsLessThanThreshold"),m())},resetSimData:o}}});e.when("A").execute(function(d){var j=d.$,g,f;if(!d.$("html").hasClass("a-touch"))if(h.cvox)h.ue&&h.ue.tag&&h.ue.tag("screenReaderOn");else{j("#a-page").delegate("*[data-sgproduct] #gw-quick-look-btn","click",function(f){b(f)});j("#a-page").delegate(".bestseller-list *[data-sgproduct]","click",function(f){b(f)});e.when("gw-popover").execute(function(b){g=b;j("#gw-popover-close").click(function(){g.hide()});f&&g.show.apply(g,f)});var b=function(b){if(!(b.which>
1||b.shiftKey||b.altKey||b.metaKey||b.ctrlKey)){var c,d;j(b.target).parents(".bestseller-list").length?(c=j(b.currentTarget).data("sgproduct"),d=j(b.target).closest("a").attr("href")):(c=j("#gw-quick-look-btn").closest("*[data-sgproduct]").data("sgproduct"),d=j("#gw-quick-look-btn").siblings().children("a").attr("href"));var e=[c.asin,d];c.asin&&d&&(b.preventDefault(),g?g.show.apply(g,e):f=e)}}}});e.when("A","sg-jsutil","dombinder").register("productdb-binding-helper",function(d,e,g){return function(f,
b){function d(b,c){g.update(a,q(c.beforeUpdate,b));b.loading||q(c.load,b)}function c(a){h();r=function(){a(t)};t.pdb_observe(r)}function h(){t&&r&&(t.pdb_unobserve(r),r=null)}var q=e.safeCall,t=null,r=null,a=g.init(b);this.setAsin=function(a,b){b=b||{};h();t=f.get(a);d(t,b);t.loading&&c(function(a){d(a,b)});return t};this.clear=function(){h();t={};g.update(a,t)}}});e.register("sg-media-builder",function(){return function(d){var e=this,g=d.src,f=[];e.build=function(){var b=f.join("_");return{src:g.replace(/\.([^.]+)$/,
"._"+b+"_.$1"),alt:d.alt}};e.autoCrop=function(){f.push("AC");return e};e.scaleX=function(b){f.push("SX"+b);return e};e.scaleY=function(b){f.push("SY"+b);return e};e.upScaleX=function(b){f.push("UX"+b);return e};e.upScaleY=function(b){f.push("UY"+b);return e};e.scaleXY=function(b,f){return e.upScaleX(b).scaleY(f)}}});e.when("A","gwAjax").register("shogunProductDB",function(d,e){function g(f){var c=[];b[f]={loading:!0,pdb_observe:function(b){c.push(b)},pdb_unobserve:function(b){c=d.$.grep(c,function(c){return c!==
b})},_trigger:function(){d.$.each(c,function(){this.call(b[f])})}};return b[f]}function f(f,c){this.ajaxUrl=f;this.experienceStr=c;this._add=function(c){c.p&&d.$.each(c.p,function(c,f){if(f.asin){var e=b[f.asin]||g(f.asin);d.$.extend(e,f,{loading:!1,error:!1});e._trigger(f)}})};this.addSims=function(c,f){if(f){var e=b[c]||g(c);d.$.extend(e,{sims:f});e._trigger(c)}};this._ajax=function(b,g){var t=d.$.extend(!0,{},f,{params:{sa:JSON.stringify(b),oe:c}});h.ue_sid&&(t.url+="/"+h.ue_sid);if(h.ue_id)t.params.rrid=
h.ue_id;return e(t.url,{method:t.method,params:t.params,success:g.success,error:g.error,id:"gw-jslibs-"+g.id})};this.get=function(c){return c in b?b[c]:g(c)}}var b={};return function(b,c){return new f(b,c)}});e.when("A").register("component-feed-carousel",function(d){var e=d.$,g=function(f,b,d){this.init(f,b,d)};g.prototype={init:function(f,b,g){d.$("html").hasClass("a-touch")&&f.addClass("feed-carousel-touch");this.adjustMarginOnChange=!0;this.defaultCssRightMargin=null;this.minItems=b||10;this.imgClass=
".product-image";this.$carousel=f;this.cfMinItems=g||6;this.shovelerReadyFired=this.cfFired=!1;this.slotId=this.getSlotId();this.touch=this.$carousel.hasClass("feed-carousel-touch");this.ajaxSource=this.$carousel.parent().hasClass("ajaxSource");this.$shelf=this.$carousel.find(".feed-carousel-shelf");this.$viewport=this.$carousel.find(".feed-carousel-viewport");this.$spinner=this.$carousel.find(".spinner");this.$left=e(".feed-carousel-control.feed-left",f);this.$right=e(".feed-carousel-control.feed-right",
f);this.$buttons=e(".feed-carousel-control",f);this.$thumb=e(".feed-scrollbar-thumb",f);this.shelfLeft=-1*parseInt(this.$shelf.css("left"),10);this.calcWidth=e("html").hasClass("a-lt-ie9");this.noOpacity=e("html").hasClass("a-lt-ie9");this.$left.attr("aria-hidden",!0);this.$right.attr("aria-hidden",!0);this.bindEvents();this.$carousel.data("Carousel",this);this.$carousel.trigger("change")},getSlotId:function(){var f=this.$carousel.closest(".gw-widget-instrument");return f.length>0?e(f[0]).attr("id"):
null},bindEvents:function(){function f(b){return d.capabilities.pointerPrefix&&e.inArray(b.originalEvent.pointerType,[2,"touch"])>-1||d.capabilities.actionMode==="touch"}var b=this,g=e("body");b.$buttons.ready(function(){if(!b.shovelerReadyFired){if(b.slotId){var c=b.slotId.toString()+"-active";h.GWI&&h.GWI.recordLatency(c);h.GWI&&h.GWI.register(c)}b.shovelerReadyFired=!0}});b.$carousel.change(function(){b.updateItems();b.updateSpinner();b.updateShelf();b.updateControls();if(b.defaultCssRightMargin===
null&&b.$shelf.children("li").first())b.defaultCssRightMargin=parseInt(b.$shelf.children("li").first().css("margin-right"),10);b.adjustMarginOnChange&&b.adjustCardMargin()});b.$left.click(function(c){c.preventDefault();b.changePage(-1)});b.$right.click(function(c){c.preventDefault();b.changePage(1)});b.bindImageLoadEvents(b.$shelf);var c;e(h).resize(function(){clearTimeout(c);c=setTimeout(function(){var c=b.getDimensions(),c=Math.max(Math.min(c.shelfLeft,c.maxLeft),0);b.moveShelf(c)},100)});b.$thumb.mousedown(function(c){var f=
c.clientX;c.which===1&&(c.preventDefault(),b.$carousel.addClass("scrolling"),g.bind("mousemove.feed-carousel",function(c){var d=b.getDimensions(),d=Math.max(Math.min(d.shelfLeft+1/d.pageRatio*(c.clientX-f),d.maxLeft),0);f=c.clientX;b.moveShelf(d)}),e(document).bind("selectstart.feed-carousel",function(){return!1}))});g.add(h).mouseup(function(){b.$carousel.removeClass("scrolling");b.$carousel.hasClass("hovering")||b.hideControls();g.unbind("mousemove.feed-carousel");e(document).unbind("selectstart.feed-carousel")});
b.$carousel.hover(function(){b.$carousel.addClass("hovering");clearTimeout(b.hoverTimer);b.hoverTimer=setTimeout(function(){b.$carousel.hasClass("hovering")&&!b.$carousel.hasClass("touching")?b.showControls():b.$carousel.removeClass("touching")},300)},function(){b.$carousel.removeClass("hovering touching");clearTimeout(b.hoverTimer);if(!b.$carousel.hasClass("scrolling"))b.hoverTimer=setTimeout(function(){b.$carousel.hasClass("hovering")||b.hideControls()},600)});b.$carousel.bind(d.action.start,function(c){if(f(c))b.$carousel.addClass("touching"),
clearTimeout(b.touchTimer),b.touchTimer=setTimeout(function(){b.$carousel.removeClass("touching")},5E3)});b.$carousel.bind(d.action.end,function(c){f(c)&&(b.$carousel.removeClass("touching"),clearTimeout(b.touchTimer),clearTimeout(b.hoverTimer))});b.$viewport.scroll(function(){b.shelfLeft=b.$viewport.scrollLeft();b.updateControls()})},bindImageLoadEvents:function(f){var b=this;e(b.imgClass,f).one("load",function(){b.$carousel.trigger("change")})},getDimensions:function(){var f=this.$shelf.width(),
b=this.shelfLeft,d=this.$carousel.width();return{pageWidth:d,shelfWidth:f,shelfLeft:b,pageRatio:d/f,leftRatio:b/f,maxLeft:f-d}},updateItems:function(){var f=this,b=f.$shelf.find(".feed-carousel-card"),d=function(b){return b.css("display")==="none"};b.each(function(b,g){var q=e(g);if(!d(q))return!0;q.attr("aria-setsize",f.$shelf.find(".feed-carousel-card").size());q.attr("aria-posinset",b+1);q.attr("aria-hidden",!1);q.attr("role","listitem");if(q.find(f.imgClass).filter(function(){return!this.complete}).length<=
0){q.css("display","inline-block");if(b>=f.cfMinItems&&!f.cfFired)f.slotId&&(q=f.slotId.toString()+"-visible",h.GWI&&h.GWI.recordLatency(q),h.GWI&&h.GWI.register(q)),f.cfFired=!0;return!0}else return!1});f.$items=b.filter(function(){return!d(e(this))})},updateShelf:function(){var f=0;this.calcWidth&&(this.$shelf.children().each(function(){f+=e(this).outerWidth(!0)}),this.$shelf.width(f));this.touch&&this.$carousel.not(".fresh-shoveler-tablet-app .feed-carousel").height(this.$shelf.outerHeight(!0))},
updateSpinner:function(){this.size()<this.minItems&&this.ajaxSource?this.$spinner.show():(this.size()<this.minItems&&typeof h.ue==="object"&&typeof h.ue.count==="function"&&h.ue.count("shovelerNotEnoughItem",(h.ue.count("shovelerNotEnoughItem")||0)+1),this.$spinner.hide())},updateControls:function(){this.updateArrows();this.updateScrollThumb()},showControls:function(f){this.$thumb.add(this.$buttons).stop(!0,!0).fadeIn({duration:300,complete:f,queue:!1})},hideControls:function(f){var b=this.$thumb;
if(!this.$carousel.hasClass("first-carousel")||this.touch)b=b.add(this.$buttons);b.stop(!0,!0).fadeOut({duration:300,complete:f,queue:!1})},appendCards:function(f){this.$shelf.append(f);this.bindImageLoadEvents(f);this.$carousel.trigger("change")},updateArrows:function(){var f=this,b=f.getDimensions();e.each([{$e:f.$left,enabled:b.shelfLeft>0},{$e:f.$right,enabled:b.shelfLeft<b.maxLeft}],function(b,c){var d=c.$e;c.enabled?d.removeClass("feed-control-disabled"):d.addClass("feed-control-disabled");
f.noOpacity&&(c.enabled?d.css("opacity","1"):d.css("opacity","0.5"))})},updateScrollThumb:function(){var f=this.getDimensions(),b=f.leftRatio*f.pageWidth;this.$thumb.width(Math.min(f.pageRatio*f.pageWidth,f.pageWidth)).each(function(){e(this).animate({left:b},0)})},changePage:function(f){var b=this.getDimensions(),d=this.alignWithItem(b.shelfLeft+f*b.pageWidth),d=Math.min(f<0?d.right:d.left,b.maxLeft);b.shelfLeft===d?(this.bounce(this.$shelf,-30*f),this.bounce(this.$thumb,6*f)):this.moveShelf(d,400)},
moveShelf:function(f,b){var d=this,b=b||0;d.shelfLeft=f;if(d.touch)d.$viewport.animate({scrollLeft:f},b,"swing",function(){d.updateArrows()});else{var c=d.getDimensions(),c=f/c.shelfWidth*c.pageWidth;d.$shelf.animate({left:-f},b,"swing",function(){d.updateArrows()});d.$thumb.animate({left:c},b,"swing",function(){d.updateScrollThumb()})}},getItems:function(){return this.$items},size:function(){return this.getItems().length},alignWithItem:function(f){if(f<0)return{left:0,right:0};var b=this,d=b.getItems(),
c=d.map(function(){var c=b.cardPosition(e(this));if(f>=c.left&&f<=c.right)return c}).get(0);return c?c:b.cardPosition(d.last())},cardPosition:function(f){var b=f.position().left,f=b+f.outerWidth(!0);return{left:b,right:f}},bounce:function(f,b){function d(b){var f={};f[c.touch?"left":"marginLeft"]=b;return f}var c=this;f.each(function(){var c=e(this);c.animate(d(b),400,"swing",function(){c.animate(d(0),100)})})},setCardMargin:function(f){this.$shelf.children("li").first()&&this.$shelf.children("li").first().css("margin-right")!==
f+"px"&&(this.$shelf.children("li").css("margin-right",f+"px"),this.updateShelf())},adjustCardMargin:function(f){f=f===w||f===null?this.defaultCssRightMargin:f;this.setCardMargin(f);var b=this.getDimensions(),b=b.maxLeft<0?Math.ceil(-b.maxLeft/this.size()):f;this.setCardMargin(b<f?f:b)}};return{createCarousel:function(f,b){e(f).each(function(f,c){var e=d.$(c);new g(e,b)})}}})})})(function(){var e=window.AmazonUIPageJS||window.P,h=e._namespace||e.attributeErrors;return h?h("AmazonGatewayAuiAssets"):
e}(),window);

}
/*
     FILE ARCHIVED ON 23:43:11 Feb 22, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:39:05 Dec 11, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 134.018
  exclusion.robots: 0.081
  exclusion.robots.policy: 0.071
  cdx.remote: 0.063
  esindex: 0.011
  LoadShardBlock: 101.272 (3)
  PetaboxLoader3.datanode: 147.879 (5)
  load_resource: 167.682 (2)
  PetaboxLoader3.resolve: 82.994 (2)
*/