var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(m){var window=this;var lF=function(a,b){if("FORM"==a.tagName)for(var c=a.elements,d=0;a=c[d];d++)lF(a,b);else!0==b&&a.blur(),a.disabled=b};var mF=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};var nF=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);(0,m.Cd)(a)}};
var oF=function(a,b){this.j=a;this.D=b;this.b=null;this.k=(0,m.N)("page");this.b=(0,m.S)((0,m.N)("premium-yva-close"),"click",(0,m.r)(this.xh,this));m.Re.getInstance().get("HIDDEN_MASTHEAD_ID")==this.j||(0,m.J)(this.k,"masthead-ad-expanded")};var pF=function(a){var b=m.Re.getInstance();b.set("HIDDEN_MASTHEAD_ID",a);b.save()};
var qF=function(a,b){this.M="session_token="+a;(this.b=window.document.location.protocol+"//"+window.document.location.hostname)&&"/"!=this.b.charAt(this.b.length-1)&&(this.b+="/");this.k=b;this.D=null;this.H=[];this.F=[];this.J={}};var rF=function(){return(0,m.O)("feed-item-checkbox",sF)};var tF=function(a){uF(a.currentTarget.checked)};var vF=function(a){a="false"!=(0,m.C)(a.currentTarget,"enabled");(0,m.vo)(wF,a);uF(a)};var uF=function(a){(0,m.z)(rF(),function(b){(0,m.vo)(b,a)});xF()};var yF=function(){xF()};
var xF=function(){var a=[],b=!0,c=rF();(0,m.z)(c,function(c){c.checked&&(a.push(c.value),b=!1)});(0,m.D)(zF,"video-ids",a.join(","));lF(zF,b);lF(AF,b);lF(BF,b);CF&&lF(CF,0==c.length)};
var DF=function(){var a=(0,m.C)(zF,"video-ids"),b={};switch(EF){case "history":b.action_remove_history_entries=1;break;case "watch_later":b.action_remove_watch_later_entries=1;break;case "favorites":b.action_remove_favorites_entries=1;break;default:throw Error("Unsupported feed name: "+EF);}(0,m.X)("/feed_change_ajax",{method:"POST",Q:b,R:{session_token:(0,m.F)("feed_change_ajax"),video_ids:a},N:FF,onError:GF})};
var FF=function(){var a=0;(0,m.z)(rF(),function(b){b.checked&&((0,m.Cd)((0,m.Xd)(b,"li")),a+=1)});if(HF){var b=(0,window.parseInt)(HF.innerHTML.replace(/[^\d\.\ ]/g,""),10);HF.innerHTML=b-a}xF();(0,m.vo)(wF,!1);(0,m.Eq)(sF)};var GF=function(){m.R.hide(IF);m.R.show(JF)};var KF=function(){(0,m.X)("/feed_change_ajax",{method:"POST",Q:{action_pause_history:1},R:{session_token:(0,m.F)("feed_change_ajax")},N:LF,onError:GF})};var LF=function(){MF((0,m.E)("HISTORY_FEED_PAUSED"))};
var NF=function(){(0,m.X)("/feed_change_ajax",{method:"POST",Q:{action_resume_history:1},R:{session_token:(0,m.F)("feed_change_ajax")},N:OF,onError:GF})};var OF=function(){MF((0,m.E)("HISTORY_FEED_RESUMED"))};var MF=function(a){PF(a);m.R.toggle((0,m.N)("watch-history-pause-container"),(0,m.N)("watch-history-resume-container"))};var PF=function(a){(0,m.P)("yt-alert-content",IF).innerHTML=a;m.R.show(IF);m.R.hide(JF)};
var QF=function(){(0,m.X)("/feed_change_ajax",{method:"POST",Q:{action_clear_history:1},R:{session_token:(0,m.F)("feed_change_ajax")},N:RF,onError:GF})};var RF=function(){PF((0,m.E)("HISTORY_FEED_CLEARED"));var a=rF();0!=a.length&&((0,m.Xd)(a[0],"ul").innerHTML="",xF())};var SF=function(a){TF(a.currentTarget)};
var TF=function(a){a=(0,m.Q)(a,"feed-container");var b=(0,m.Q)(a,"individual-feed"),c=(0,m.C)(b,"feed-name")||null,b=(0,m.C)(b,"feed-type")||null,d=(0,m.C)(a,"filter-type")||null;(0,m.C)(a,"view-type");var e=(0,m.C)(a,"paging")||null;UF(a,c,b,d,e)};
var UF=function(a,b,c,d,e){c=VF(b,c,d,e);b=c.url;c=c.Q;var g=(0,m.P)("feed-load-more-container",a);(0,m.J)(g,"loading");(0,m.X)(b,{Q:c,format:"JSON",N:function(b,c){var d=(0,m.bg)(c.feed_html);if(d){var e=(0,m.P)("last",a);e&&(0,m.L)(e,"last");(0,m.zd)(d,g);(0,m.Eq)(d);m.fw.getInstance().wb();(0,m.L)(g,"loading");c.paging?(0,m.D)(a,"paging",c.paging):m.R.hide(g);m.R.hide(WF)}else(0,m.L)(g,"loading")},onError:function(){(0,m.L)(g,"loading");m.R.show(WF)}})};
var XF=function(a){a=a.getServiceInfo();for(var b in a){var c=(0,m.N)(b+"-connected");if(c){var d=a[b],e=(0,m.N)(b+"-not-connected"),g=(0,m.N)(b+"-display-name"),h=d.is_connected;m.R.Za(c,h);m.R.Za(e,!h);(0,m.Pd)(g,d.connected_as||"")}}};var YF=function(){m.R.hide("mep-container");(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_dismiss_music_promo:"1"},R:{session_token:(0,m.F)("engagement_wizard_ajax")}})};var ZF=function(a){return(0,m.Q)(a.currentTarget,"mep-artist-lockup")};
var $F=function(a){var b=ZF(a),c=(0,m.P)("mep-artist-thumb",b);a=(0,m.C)(c,"artist-id");(0,m.J)(b,"removed");(0,m.L)(b,"subbed");(0,m.L)(c,"yt-uix-tooltip");c=aG.shift();(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_dismiss_item_mep1:"1"},R:{session_token:(0,m.F)("engagement_wizard_ajax"),dismissed_channel:a,next_channel:c},N:function(a,c){(0,m.Fv)(b,{duration:0.5,ca:function(){b.innerHTML=c.html_content;nF(b);m.R.hide(b);(0,m.Ev)(b,0,1,{duration:0.5})}})}})};
var bG=function(a){var b=(0,m.N)("mep-container"),c=(0,m.N)("mep-player-container"),d=ZF(a);a=(0,m.C)((0,m.P)("mep-artist-thumb",ZF(a)),"artist-id");if(!(0,m.M)(b,"working")&&!(0,m.M)(d,"removed")){(0,m.J)(b,"open");(0,m.J)(b,"working");(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_select_artist:"1"},R:{channel_id:a,setting_type:"SUBSCRIPTIONS",session_token:(0,m.F)("engagement_wizard_ajax")},N:function(a,e){m.R.show(c);(0,m.L)(b,"working");(0,m.J)(d,"subbed");c.innerHTML=e.html_content;
(0,m.Eq)(c)}});var e=(0,m.C)(d,"sessionlink");(0,m.A)("subscription-subscribe",a,null,null,e)}};var cG=function(a){var b=(0,m.N)("mep-container");if(null!=b)for(var b=(0,m.O)("yt-uix-subscription-button",b),c=0;c<b.length;c++)if((0,m.C)(b[c],"channel-external-id")==a){a=(0,m.Q)(b[c],"music-promo-item");dG(a);(0,m.J)(a,"subscribed");break}};
var eG=function(a){var b=(0,m.Q)(a.currentTarget,"music-promo-item");a=(0,m.C)(b,"external-id");var c=(0,m.M)(b,"last")?1:0,d=aG.shift();(0,m.X)("/engagement_wizard_ajax",{method:"POST",Q:{action_dismiss_item_mep2:"1"},R:{session_token:(0,m.F)("engagement_wizard_ajax"),dismissed_channel:a,next_channel:d,is_last_item:c,column_name:(0,m.v)("MEP_COLUMN_NAME")},ca:function(a,c){(0,m.Fv)(b,{duration:0.5,ca:function(){var a=c.html_content;m.R.hide(b);a&&(b.innerHTML=a,nF(b),(0,m.Ev)(b,0,1,{duration:0.5}));
if(0==aG.length)for(var a=(0,m.O)("mep2-dismiss-button"),d=0;d<a.length;d++)m.R.setVisible(a[d],!1)}})}})};var fG=function(a){a=(0,m.Q)(a.currentTarget,"music-promo-item");var b=(0,m.M)(a,"collapsed"),c=(0,m.M)(a,"subscribed");b&&c&&dG(a)};var dG=function(a){if(!(0,m.M)(a,"expanded")){var b=(0,m.N)("mep-container");null!=b&&((b=(0,m.P)("expanded",b))&&(0,m.Yc)(b,"expanded","collapsed"),(0,m.Yc)(a,"collapsed","expanded"))}};
var gG=function(a){mF(a);a=(0,m.Q)(a.currentTarget,"feed-item-collapsed-container");(0,m.Zc)(a,"collapsed","expanded");(0,m.qp)()};var hG=function(a){mF(a);a=(0,m.Q)(a.currentTarget,"feed-item-collapsed-container");(0,m.Zc)(a,"expanded","collapsed");(0,m.qp)()};
var iG=function(a){mF(a);var b=(0,m.Q)(a.currentTarget,"context-data-item");a=(0,m.Q)(a.currentTarget,"feed-item-container");b=(0,m.C)(b,"context-item-id");a.parentNode.innerHTML='<iframe type="text/html" width="640" height="390" src="https://web.archive.org/web/20130901013415/http://www.youtube.com/embed/__VID__?autoplay=1" frameborder="0"/>'.replace("__VID__",b)};
var VF=function(a,b,c,d){var e="",g={};"personal"==b?(e="/feed_ajax?action_load_personal_feed=1",g={feed_name:a}):"social"==b?(e="/feed_ajax?action_load_social_feed=1",g={feed_name:a}):"system"==b?(e="/feed_ajax?action_load_system_feed=1",g={feed_name:a}):"main"==b?e="/feed_ajax?action_load_main_feed=1":"user"==b?(e="/feed_ajax?action_load_user_feed=1",g={user_id:a}):"collection"==b&&(e="/feed_ajax?action_load_collection_feed=1",g={collection_id:a});c&&(g.filter_type=c);d&&(g.paging=d);(0,m.v)("FEED_DEBUG")&&
(g.debug=(0,m.v)("FEED_DEBUG"));return{url:e,Q:g}};var jG=function(){var a=(0,m.v)("PYV_IFRAME_CONTENT"),b=(0,m.N)((0,m.v)("PYV_IFRAME_ID"));b&&(b=b.contentDocument||b.contentWindow.document,b.open(),b.write("<!DOCTYPE html><html><head></head><body>"+a+"</body></html>"),m.I||b.close())};var kG=function(){var a=(0,m.N)("destination-moments-promo");if(a){var b=(0,m.C)(a,"column-name")||"";lG=(0,m.V)(a,"click",(0,m.Bb)(mG,b),"destination-moments-promo-close")}};
var mG=function(a){var b=m.Re.getInstance();(0,m.Xe)(0,m.Qf.oq,!0);b.save();m.R.hide((0,m.N)("destination-moments-promo"));(new m.pw(a)).write("write_reject")};var nG=function(){(0,m.T)(oG);(0,m.Da)(pG);(0,m.z)(qG,function(a){(0,m.x)(a)})};var rG=function(a){a.preventDefault();a=(0,m.Q)(a.currentTarget,"branded-page-related-channels-item");sG(a,!0)};var tG=function(a){(0,m.Fv)(a,{duration:0.3,ca:function(){(0,m.Cd)(a)}})};
var uG=function(a){var b=(0,m.O)("branded-page-related-channels-item"),c=(0,m.Ab)(b,function(b){return(0,m.C)(b,"external-id")==a});c&&qG.push((0,m.w)(function(){sG(c,!1)},2E3))};
var sG=function(a,b){var c=window.document.getElementById("channels_you_may_know"),c=c&&(0,m.Od)(c,a),d=!!(0,m.P)("branded-page-related-channels-featured-badge",a),e=(0,m.C)(a,"external-id"),g=(0,m.Xd)(a,"ul"),g=(0,m.O)("branded-page-related-channels-item",g),g=(0,m.qb)(g,function(a){return(0,m.C)(a,"external-id")}),h={};d&&(h.featured=1);c&&(h.channels_you_may_know=1);(0,m.X)("/guide_ajax?action_reload_channel=1",{method:"POST",Q:h,R:{session_token:(0,m.F)("guide_ajax"),dismissed_id:e,shown_ids:g.join(),
dismiss_old_channel:b},N:function(b,c){var d=c.new_suggested_html;d?(d=(0,m.bg)(d),(0,m.Dd)(d,a),(0,m.Eq)(d),(0,m.Ev)(d,0,1,{duration:0.3})):tG(a)},onError:function(){tG(a)}})};
var vG=function(){"DELAYED_EMBEDED"in m.sa&&(0,m.z)((0,m.v)("DELAYED_EMBEDED"),function(a){(0,m.Kf)(a.container,a.swf_config)});"MASTHEAD_ENCRYPTED_ID"in m.sa&&(window.masthead=new oF((0,m.v)("MASTHEAD_ENCRYPTED_ID"),(0,m.v)("MASTHEAD_IS_BRANDED")));"PYV_IFRAME_ID"in m.sa&&jG();kG();oG=(0,m.V)(window.document.body,"click",rG,"branded-page-related-channels-item-close");pG.push((0,m.y)("subscription-subscribe-loaded",uG));(0,m.uw)();var a=(0,m.N)("chrome-feed-promo");a&&(a={hl:(0,m.C)(a,"hl")||""},
(0,m.mn)("chrome-feed-promo-show",(0,m.tf)(a)));if(a=(0,m.N)("destination-moments-promo"))a={"impression-count":(0,m.C)(a,"impression-count")||""},(0,m.mn)("destination-moments-promo-show",(0,m.tf)(a))};var wG=function(a){this.j=a;this.ga=(0,m.N)("shared-addto-menu");this.D=(0,m.C)(this.j,"feature")||"";this.Xc=(0,m.C)(this.j,"video-ids")||"";(0,m.Wb)(xG)||(xG=(0,m.xn)(this.ga,"lightweight-panel"));(a=(0,m.P)("sign-in",this.ga))?(0,m.S)(a,"click",(0,m.r)(this.ho,this)):this.Wc()};
var yG=function(a){var b=[];(0,m.jc)(b,(0,m.O)("playlist-name",a.b.list));(0,m.z)(b,function(a){(0,m.Zf)(a)&&(a=(0,m.Q)(a,"yt-uix-button-menu-item"),a.title=(0,m.C)(a,"possible-tooltip"))})};var zG=function(a,b,c){var d=(0,m.P)("addto-title",a.b.cc);(0,m.yd)(d);(0,m.wd)(d,AG(b,c));BG(a,a.b.cc,!0);b=(0,m.P)("close-note",a.ga);m.R.show(b);var e=(0,m.N)("addto-note");(0,m.S)(e,"keydown",(0,m.r)(a.xi,a));(0,m.S)(e,"paste",(0,m.r)(a.xi,a));CG(a.b.cc,function(){e.focus()})};
var AG=function(a,b){var c=window.document.createElement("a");c.href=b;c.innerHTML=a;return c};var CG=function(a,b){if(b){var c=m.nd?"webkitTransitionEnd":m.he?"oTransitionEnd":m.ge?"transitionend":m.I&&(0,m.Qc)(10)?"MSTransitionEnd":null;c?(0,m.lg)(a,c,function(){b()}):b()}};
var BG=function(a,b,c){c=c?"slide":"fade";var d=["fade","slide"];(0,m.Nx)(a.k,d);(0,m.W)(a.k,c);(0,m.Nx)(b,d);(0,m.W)(b,c);xG&&b==a.b.list&&(0,m.W)(a.ga,"lightweight-panel");(0,m.xn)(b,"dismissed-panel")?((0,m.Bg)(b,"dismissed-panel"),(0,m.Bg)(a.k,"active-panel")):(c=a.k,(0,m.xn)(c,"active-panel")&&((0,m.Bg)(c,"active-panel"),(0,m.W)(c,"dismissed-panel")));(0,m.W)(b,"active-panel");a.k=b};
var DG=function(a){BG(a,a.b.Qb,!0);EG(a);(0,m.Yb)(a.ga,"video-ids");var b=(0,m.N)("addto-create-playlist");(0,m.S)(b,"keydown",(0,m.r)(a.lg,a));(0,m.S)(b,"paste",(0,m.r)(a.lg,a));CG(a.b.Qb,function(){b.focus()});var c=(0,m.P)("addto-create-cancel-button",a.b.Qb);(0,m.S)(c,"click",(0,m.r)(function(){FG(this)},a));c=(0,m.P)("create-playlist-button",a.b.Qb);(0,m.S)(c,"click",(0,m.r)(a.Tn,a))};
var EG=function(a){a.M=(0,m.P)("addto-create-playlist",a.b.Qb);a.P=(0,m.P)("addto-create-playlist-label",a.b.Qb);a.Z=(0,m.P)("create-playlist-button",a.b.Qb);a.G=(0,m.P)("privacy-form",a.b.Qb);(0,m.V)(a.G,"click",(0,m.r)(a.lg,a),"playlist-privacy-option")};var FG=function(a){var b=m.Ln.getInstance(),c=(0,m.Yn)(b,a.ga);c&&(0,m.C)(c,"video-ids")==a.Xc&&(0,m.On)(b,c)};
var GG=function(a,b,c,d,e){var g=!(d||"FL"==b||"WL"==b);d={La:a.Xc,Bh:b,Wf:d,Ch:g?c:null,privacy:e,Yf:a.D,N:(0,m.Bb)(a.am,c,b),onError:(0,m.Bb)(a.$l,g),V:a};BG(a,a.b.$k);(0,m.Js)(d);(0,m.Yb)(a.ga,"video-ids");d="";switch(b){case "PL":d=c?"new_pl":"pl";break;case "FL":d="fav";break;case "WL":d="wl"}b={list:d,feature:a.D};(a=(0,m.Xd)(a.j,"a",null))&&a.href&&(a=(0,m.rf)(a.href),b.link_feature=a.feature||"");a=(0,m.tf)(b);(0,m.nn)("addto",a,void 0)};
var HG=function(){this.ga=(0,m.N)("tag-editing-menu");this.km=(0,m.P)("yt-combobox-menu-content",this.ga);this.b=(0,m.P)("yt-combobox-search-input",this.ga);this.j=(0,m.P)("tag-resource-container");this.Pa()};var IG=function(a){a.Ye?a.mg=!0:a.Wc()};
var JG=function(a,b){a.k=(0,m.P)("add-new-tag");a.Si=(0,m.P)("apply-tag-changes");if(b){var c=(0,m.fd)("input","tag-checkbox",void 0);(0,m.z)(c,function(a){var c=b[a.value];(0,m.D)(a,"initial-tag-membership",c);(0,m.D)(a,"current-tag-membership",c);"ALL"==c?a.checked=!0:"SOME"==c&&(0,m.zo)(a,!0)},a)}KG(a)};
var KG=function(a){for(var b=(0,m.fd)("input","tag-checkbox",void 0),c=!1,d=0;d<b.length;d++)if(!LG(b[d])){c=!0;break}c?(a=a.ga,(0,m.Bg)(a,"show-new"),(0,m.W)(a,"show-apply")):(a=a.ga,(0,m.Bg)(a,"show-apply"),(0,m.W)(a,"show-new"))};var LG=function(a){switch((0,m.C)(a,"initial-tag-membership")){case "SOME":if(a.Bf)return!0;break;case "NONE":if(!a.checked)return!0;break;case "ALL":if(a.checked)return!0}return!1};
var MG=function(a,b){if(b){var c=b.error;if(c){var d=(0,m.P)("error-small-template",a.ga),d=(0,m.Wf)(d);NG(a,"yt-alert-error",c,d,8E3)}}};var OG=function(a,b){if(b){var c=b.success_msg;if(c){var d=(0,m.P)("success-small-template",a.ga),d=(0,m.Wf)(d);NG(a,"yt-alert-success",c,d,3E3)}}};var NG=function(a,b,c,d,e){var g=(0,m.P)("tag-menu-notifications",a.ga);(0,m.sq)(b,c,d,g);(0,m.w)((0,m.r)(function(){(new m.Lu(d,750)).pa()},a),e)};
var PG=function(a){a=(0,m.fd)("input",a,void 0);for(var b=[],c=[],d=0;d<a.length;d++){var e=a[d];e.Bf||(e.checked?b.push(e.value):c.push(e.value))}return{checked_values:b,unchecked_values:c}};var QG=function(){m.Ea.call(this,"www/feed",["www/common"],["feed","index"],RG,SG)};
var RG=function(){m.vp.getInstance().wb();m.fw.getInstance().wb();vG();var a=(0,m.N)("feed");TG.push((0,m.V)(a,"click",SF,"feed-load-more"));TG.push((0,m.V)(a,"click",gG,"feed-item-expander-button"));TG.push((0,m.V)(a,"click",hG,"feed-item-collapser-button"));(0,m.v)("WATCH_FROM_FEED")&&(TG.push((0,m.V)(a,"click",iG,"feed-item-thumb")),TG.push((0,m.V)(a,"click",iG,"feed-video-title")));var b=(0,m.P)("individual-feed"),c=!1;b&&(UG=(0,m.C)(b,"feed-name"),c="user"==(0,m.C)(b,"feed-type"));if("history"==
UG||"watch_later"==UG||"favorites"==UG)EF=b=UG,sF=a,wF=(0,m.N)("feed-item-select-all-checkbox"),IF=(0,m.N)("managed-feed-success"),JF=(0,m.N)("managed-feed-error"),VG=(0,m.P)("branded-page-v2-primary-col-header-container"),zF=(0,m.P)("addto-button",VG),AF=(0,m.N)("feed-item-remove-videos"),BF=(0,m.N)("tag-menu-button"),CF=(0,m.N)("managed-toolbar-play-all-button"),HF=(0,m.N)("feed-title-count"),WG.push((0,m.S)(wF,"click",tF)),WG.push((0,m.V)(window.document.body,"click",vF,"feed-item-selection-action")),
WG.push((0,m.V)(window.document.body,"click",yF,"feed-item-checkbox")),WG.push((0,m.S)(AF,"click",DF)),"history"==b&&(WG.push((0,m.S)((0,m.N)("watch-history-pause-button"),"click",KF)),WG.push((0,m.S)((0,m.N)("watch-history-resume-button"),"click",NF)),WG.push((0,m.V)(window.document.body,"click",QF,"watch-history-clear-button")));(0,m.gw)({"feed-load-more":TF});if((0,m.v)("INIT_AUTOSHARE")){b=new qF((0,m.F)("autoshare"));b.addServiceChangedCallback(XF);var d=(0,m.N)("facebook-connect-button");d&&
b.registerConnectDialogLauncher(d,"facebook",!0);(d=(0,m.N)("twitter-connect-button"))&&b.registerConnectDialogLauncher(d,"twitter",!0);(d=(0,m.N)("orkut-connect-button"))&&b.registerConnectDialogLauncher(d,"orkut",!0);window.autoshare=b}"music-promo-1"==(0,m.v)("MUSIC_PROMO_TYPE")?(b=(0,m.N)("music-engagement-promo"),TG.push((0,m.V)(b,"click",YF,"mep-dismiss-button")),TG.push((0,m.V)(b,"click",$F,"mep-dismiss-artist-button")),TG.push((0,m.V)(b,"click",bG,"mep-artist-thumb")),aG=(0,m.C)((0,m.N)("mep-container"),
"ids-for-replacement").split(",")):"music-promo-2"==(0,m.v)("MUSIC_PROMO_TYPE")&&(b=(0,m.N)("mep-container"),XG.push((0,m.y)("subscription-subscribe-success",cG)),TG.push((0,m.V)(b,"click",eG,"mep2-dismiss-button")),TG.push((0,m.V)(b,"click",fG,"channel-lockup")),aG=(0,m.C)(b,"ids-for-replacement").split(","));(0,m.vw)(a,c);(0,m.Tv)(0);(0,m.Uv)()};
var SG=function(){(0,m.qa)("DELAYED_EMBEDED",[]);window.masthead&&window.masthead.dispose();lG&&((0,m.T)(lG),lG=null);nG();(0,m.nq)(m.tw);WF=null;(0,m.T)(TG);(0,m.Da)(XG);if("history"==UG||"watch_later"==UG||"favorites"==UG)(0,m.T)(WG),WG=[],BF=IF=JF=wF=HF=CF=AF=zF=VG=sF=null};var UG,WF;(0,m.t)(oF,m.oa);m.f=oF.prototype;m.f.O=function(){oF.L.O.call(this);(0,m.T)(this.b);this.b=null};
m.f.Dq=function(){m.R.hide("ad_creative_1");(0,m.A)("ads-masthead-hide");(0,m.Gq)((0,m.N)("page"),!0);this.D&&m.R.hide("ad_creative_collapse_btn_1");m.R.show("ad_creative_expand_btn_1");(0,m.L)(this.k,"masthead-ad-expanded");pF(this.j);(0,m.nn)("homepage_collapse_masthead_ad",void 0,void 0)};m.f.xh=function(){m.R.show("ad_creative_expand_btn_1");(0,m.Cd)((0,m.N)("premium-yva"));(0,m.Cd)((0,m.N)("video-masthead"));pF(this.j)};
m.f.Aq=function(){(0,m.Zc)(window.document.getElementById("premium-yva"),"premium-yva-unexpanded","premium-yva-expanded")};m.f.Bq=function(){(0,m.Zc)(window.document.getElementById("premium-yva"),"premium-yva-expanded","premium-yva-unexpanded")};m.f.sq=function(){m.R.hide("premium-yva");(0,m.L)((0,m.N)("premium-yva"),"premium-yva-unexpanded")};m.f.Eq=function(){var a=m.Re.getInstance();a.set("HIDDEN_MASTHEAD_ID",!1);a.save();(0,m.nn)("homepage_expand_masthead_ad",void 0,void 0);(0,m.Xp)(window.document.location.href)};(0,m.s)("yt.sharing.AutoShare",qF);qF.prototype.lb=function(a,b,c,d){(0,m.S)(a,"click",(0,m.r)(this.P,this));if(a.id)this.J[a.id]={serviceName:b,connectOnly:c},d&&(this.J[a.id].connectOnlyCallback=d);else throw"Connect dialog launch buttons must have an id.";};qF.prototype.registerConnectDialogLauncher=qF.prototype.lb;qF.prototype.P=function(a){if(a=this.J[a.currentTarget.id]){var b=a.connectOnly;a.connectOnlyCallback&&(b=(0,a.connectOnlyCallback)());this.G(a.serviceName,b)}};
qF.prototype.handleConnectService=qF.prototype.P;qF.prototype.na=function(){this.j()};qF.prototype.doOnLoad=qF.prototype.na;qF.prototype.fa=function(a){this.H.push(a)};qF.prototype.addServiceChangedCallback=qF.prototype.fa;qF.prototype.$=function(a){this.F.push(a)};qF.prototype.addCanConnectCallback=qF.prototype.$;qF.prototype.wa=function(){return this.k};qF.prototype.getServiceInfo=qF.prototype.wa;
qF.prototype.G=function(a,b){for(var c in this.F)if(!(0,this.F[c])(this,a,b))return;(0,m.X)(this.b+"autoshare",{Q:{action_ajax_stats_ping:"1",stat:"connect_has_google",service:a}});c=this.b+"autoshare?action_popup_auth=1&service="+a+"&connect_only="+(b?"True":"False")+"&root_url="+(0,window.encodeURIComponent)(this.b);"facebook"==a&&(c+="&permissions="+(0,window.encodeURIComponent)("read_stream,offline_access,manage_pages,user_likes,publish_stream"));this.Y(c,{height:500,width:860})};
qF.prototype.connectService=qF.prototype.G;qF.prototype.oa=function(a,b){var c=(0,m.r)(function(a,c){this.k=(0,m.xh)(c.html_content);this.j();b&&b()},this),d=(0,m.r)(function(){b&&b();this.j()},this),e={action_ajax_connect_service:1};e.return_url=a;(0,m.X)(this.b+"autoshare?ajax_connect_service",{format:"XML",method:"POST",yb:(0,m.tf)(e)+"&"+this.M,N:c,onError:d})};qF.prototype.connectServiceDone=qF.prototype.oa;qF.prototype.ja=function(a){this.Z(a)};qF.prototype.disconnectService=qF.prototype.ja;
qF.prototype.Wb=function(a,b){var c=(0,m.r)(function(a,b){this.k=(0,m.xh)(b.html_content);this.j()},this),d=(0,m.r)(function(){this.j()},this),e={action_ajax_set_connect_only:1};e.service=a;e.connect_only=b?"True":"False";(0,m.X)(this.b+"autoshare?ajax_set_connect_only",{format:"XML",method:"POST",yb:(0,m.tf)(e)+"&"+this.M,N:c,onError:d})};qF.prototype.setConnectOnly=qF.prototype.Wb;
qF.prototype.Z=function(a){var b=(0,m.r)(function(a,b){this.k=(0,m.xh)(b.html_content);this.j()},this),c=(0,m.r)(function(){this.j()},this),d={action_ajax_disconnect_service:1};d.service=a;(0,m.X)(this.b+"autoshare?ajax_disconnect_service",{format:"XML",method:"POST",yb:(0,m.tf)(d)+"&"+this.M,N:b,onError:c})};qF.prototype.j=function(){for(var a in this.H)(0,this.H[a])(this)};qF.prototype.Y=function(a,b){if(this.D)try{this.D.close()}catch(c){this.D=null}this.D=!(0,m.$p)(a,b)};
qF.prototype.ud=function(){this.G("facebook",!this.k.facebook.is_autosharing)};var EF,sF,VG,zF,AF,CF,HF,wF,JF,IF,BF,WG=[];var TG=[],XG=[],aG=[];var lG;var oG,pG=[],qG=[];var YG,ZG,xG;m.f=wG.prototype;
m.f.Wc=function(){var a=(0,m.C)(this.j,"hide-watch-later"),b={action_get_dropdown:"1",hide_favorites:(0,m.C)(this.j,"hide-favorites"),hide_watch_later:a,video_ids:this.Xc};this.D&&(b.feature=this.D);(0,m.X)("/addto_ajax",{Of:!0,format:"XML",method:"GET",V:this,Q:b,N:function(b,d){this.ga.innerHTML=d.html_content||"";(0,m.Ag)(this.ga,"no-watch-later",!!a);(0,m.Ag)(this.ga,"ie",m.I);var e=(0,m.O)("contains-selected-videos",this.ga),g=[];e&&(0,m.z)(e,function(a){g.push({id:(0,m.C)(a,"item-id"),name:(0,m.C)(a,
"item-name")})});(0,m.A)("addto-menu-loaded",{videoIds:this.Xc,selectedPlaylists:g});this.Pa();yG(this)}})};
m.f.Pa=function(){this.b={};this.b.list=(0,m.N)("addto-list-panel");this.b.$k=(0,m.N)("addto-list-saving-panel");this.b.Lf=(0,m.N)("addto-list-saved-panel");this.b.Te=(0,m.N)("addto-list-error-panel");this.b.cc=(0,m.N)("addto-note-input-panel");this.b.Ih=(0,m.N)("addto-note-saving-panel");this.b.Yh=(0,m.N)("addto-note-saved-panel");this.b.jg=(0,m.N)("addto-note-error-panel");this.b.Qb=(0,m.N)("addto-create-panel");this.k=this.b.list;(0,m.V)(this.b.list,"click",(0,m.r)(this.Ym,this),"yt-uix-button-menu-item");
this.F=(0,m.P)("playlist-save-note",this.b.cc);(0,m.S)(this.F,"click",(0,m.r)(this.Zm,this));var a=(0,m.P)("close-button",this.ga);(0,m.S)(a,"click",(0,m.r)(this.Xm,this))};m.f.Ym=function(a){a.stopPropagation();var b=a.currentTarget;(0,m.Jp)(m.Dp.getInstance(),b);a=(0,m.C)(b,"list-action");var c=(0,m.C)(b,"item-id")||"",b=(0,m.C)(b,"item-name")||"",d;switch(a){case "create-playlist":DG(this);return;case "favorites":d="FL";break;case "watch-later":d="WL";break;case "playlist":d="PL"}GG(this,d,b,c)};
m.f.xi=function(a){var b=a.target,c=(0,m.P)("addto-note-label",this.b.cc);(0,m.w)((0,m.r)(function(){var a=(0,m.Rb)(b.value);a?m.R.show(c):m.R.hide(c);!a&&this.J&&this.H?(0,m.Yf)(this.F,!0):(0,m.Yf)(this.F,!1)},this),0)};m.f.Tn=function(){var a=this.M.value,b=(0,m.Wl)(this.G,"privacy");GG(this,"PL",a,null,b)};
m.f.lg=function(){(0,m.w)((0,m.r)(function(){var a=(0,m.Rb)(this.M.value);a?m.R.show(this.P):m.R.hide(this.P);var b=(0,m.Wl)(this.G,"privacy");a||!b?(0,m.Yf)(this.Z,!1):(0,m.Yf)(this.Z,!0)},this),0)};m.f.Xm=function(){FG(this)};
m.f.am=function(a,b,c,d){this.J=d.list_id||"";this.H=d.setvideo_id||"";c=d.list_url||"";d="True"==d.show_private_video_warning;this.J&&this.H&&((0,m.Rb)((0,m.N)("addto-note").value)||(0,m.Yf)(this.F,!0),d&&(d=(0,m.O)("private-video-warning",this.ga))&&m.R.show.apply(m.R,d),d=this.Xc.split(","),b="FL"==b,(0,m.C)(this.j,"reload-menu-after-save")?this.Wc():b||1<d.length?(b=(0,m.P)("addto-title",this.b.Lf),(0,m.yd)(b),a=AG(a,c),b.appendChild(a),(0,m.Bg)(this.ga,"lightweight-panel"),BG(this,this.b.Lf,
!0),a=(0,m.P)("close-note",this.ga),m.R.show(a)):zG(this,a,c))};
m.f.$l=function(a,b,c){if(b=c&&c.error_message){(0,m.P)("error-details",this.b.Te).innerHTML=b;b=(0,m.P)("show-menu-link",this.b.Te);var d=(0,m.S)(b,"click",(0,m.r)(function(b){b.preventDefault();(0,m.T)(d);(0,m.Nx)(this.b.cc,["dismissed-panel","fade","slide"]);(0,m.Nx)(this.b.Lf,["dismissed-panel","fade","slide"]);b=(0,m.P)("close-note",this.ga);m.R.hide(b);a?BG(this,this.b.Qb,!0):BG(this,this.b.list,!0)},this));if(b=(0,m.N)("addto-create-name"))b.disabled=!1;(0,m.Nx)(this.b.Te,["dismissed-panel",
"fade","slide"]);BG(this,this.b.Te)}else FG(this)};m.f.Zm=function(){(0,m.X)("/playlist_bar_ajax",{method:"POST",Of:!0,Q:{action_set_playlist_item_annotation:1},R:{annotation:(0,m.N)("addto-note").value,playlist_id:this.J,setvideo_id:this.H,session_token:(0,m.F)("playlist_bar_ajax")},N:this.jn,onError:this.hn,V:this});BG(this,this.b.Ih)};
m.f.jn=function(){var a=(0,m.P)("addto-title",this.b.cc),b=(0,m.Vf)(a);(0,m.W)(b,"yt-uix-tooltip-reverse");(0,m.P)("panel-content",this.b.Yh).appendChild(b);BG(this,this.b.Yh);(0,m.w)((0,m.r)(function(){(0,m.Jp)(m.Dp.getInstance(),b);FG(this)},this),3E3)};
m.f.hn=function(a,b){var c=b&&b.errors;if(c){var d=(0,m.P)("error-details",this.b.jg);(0,m.yd)(d);(0,m.z)(c,function(a){var b=window.document.createElement("li");b.innerHTML=a;d.appendChild(b)});var c=(0,m.P)("add-note-link",this.b.jg),e=(0,m.S)(c,"click",(0,m.r)(function(a){a.preventDefault();(0,m.T)(e);(0,m.Bg)(this.b.Ih,"dismissed-panel");BG(this,this.b.cc)},this));BG(this,this.b.jg)}else FG(this)};
m.f.ho=function(){var a=(0,m.vf)("/addto_ajax",{action_redirect_to_signin_with_add:1,list_type:"WL",video_ids:this.Xc,next_url:window.document.location}),b=(0,m.ud)("form");b.action=a;b.method="POST";a=(0,m.ud)("input");a.type="hidden";a.name="session_token";a.value=(0,m.F)("addto_ajax_logged_out");b.appendChild(a);window.document.body.appendChild(b);b.submit()};(0,m.Ic)(HG);m.f=HG.prototype;m.f.Ye=!1;m.f.mg=!1;
m.f.Wc=function(){var a={},b=this.b.value;(0,m.Rb)(b)||(a.search=b);var b=[],c=[],b=PG("tag-video-checkbox").checked_values,c=PG("tag-playlist-checkbox").checked_values;this.Ye=!0;this.mg=!1;(0,m.X)("/labels_ajax?action_tag_menu_dropdown=1",{method:"POST",V:this,Q:a,R:{video_ids:b,playlist_ids:c},N:function(a,b){var c=b.tag_membership;this.km.innerHTML=b.html_content||"";JG(this,c);this.Ye=!1;(0,m.Bg)(this.ga,"loading");(0,m.wo)();this.mg&&this.Wc()},onError:function(a){this.Ye=!1;(0,m.Bg)(this.ga,
"loading");MG(this,(0,m.wh)(a.response))}})};
m.f.Pa=function(){(0,m.S)(this.b,"keydown",(0,m.r)(this.Uh,this));(0,m.S)(this.b,"paste",(0,m.r)(this.Uh,this));(0,m.V)(this.ga,"click",(0,m.r)(this.Om,this),"tag-checkbox");(0,m.V)(this.ga,"click",(0,m.r)(this.Nm,this),"add-new-tag");(0,m.V)(this.ga,"click",(0,m.r)(this.Mm,this),"apply-tag-changes");this.j&&((0,m.V)(this.j,"click",(0,m.r)(this.ig,this),"tag-video-checkbox"),(0,m.V)(this.j,"click",(0,m.r)(this.ig,this),"tag-playlist-checkbox"));(0,m.V)(window.document.body,"click",(0,m.r)(this.ig,
this),"tag-refresh")};m.f.Uh=function(){(0,m.w)((0,m.r)(function(){IG(this)},this),0)};m.f.Om=function(a){a=a.target;switch((0,m.C)(a,"current-tag-membership")){case "SOME":a.Bf=!1;(0,m.D)(a,"current-tag-membership","NONE");break;case "NONE":(0,m.D)(a,"current-tag-membership","ALL");break;case "ALL":"SOME"==(0,m.C)(a,"initial-tag-membership")?((0,m.zo)(a,!0),(0,m.D)(a,"current-tag-membership","SOME")):(0,m.D)(a,"current-tag-membership","NONE")}KG(this)};m.f.ig=function(){(0,m.W)(this.ga,"loading")};
m.f.Nm=function(){this.k.disabled=!0;var a=this.b.value,b=PG("tag-video-checkbox").checked_values,c=PG("tag-playlist-checkbox").checked_values,a={title:a,video_ids:b,playlist_ids:c},a={method:"POST",Q:{session_token:(0,m.C)(this.ga,"ajax-token")},R:a,N:function(a,b){OG(this,b);IG(this)},onError:function(a){MG(this,(0,m.wh)(a.response));IG(this)},V:this};(0,m.X)("/labels_ajax?action_create_and_apply_tag=1",a)};
m.f.Mm=function(){this.Si.disabled=!0;var a=PG("tag-video-checkbox").checked_values,b=PG("tag-playlist-checkbox").checked_values,c=PG("tag-checkbox"),d=(0,m.fd)("input","tag-checkbox",void 0).length;(0,m.X)("/labels_ajax?action_update_membership=1",{V:this,method:"POST",Q:{session_token:(0,m.C)(this.ga,"ajax-token")},R:{video_ids:a,playlist_ids:b,tags_to_add:c.checked_values,tags_to_remove:c.unchecked_values,num_tags:d},N:function(a,b){OG(this,b);IG(this)},onError:function(a){this.Si.disabled=!1;
MG(this,(0,m.wh)(a.response))}})};(0,m.s)("yt.flash.embed",m.Kf);(0,m.s)("yt.www.ads.pyv.pyvHomeAfcCallback",m.dw);(0,m.s)("yt.www.ads.MastheadAd",oF);
(0,m.s)("yt.www.lists.addto.toggleMenu",function(a,b){var c=m.Dp.getInstance(),d=(0,m.Y)(c),e=(0,m.N)("shared-addto-menu");if(b){var g=(0,m.P)("addto-menu",e);(0,m.Jp)(c,a);ZG=(0,m.Bg)(a,d);YG||(YG=g.innerHTML);c=(0,m.C)(e,"video-ids");d=(0,m.C)(a,"video-ids");xG&&(0,m.W)(e,"lightweight-panel");(0,m.xn)(a,"flip")&&(0,m.W)(e,"flip");d&&c!=d&&((0,m.D)(e,"video-ids",d),g.innerHTML=YG,new wG(a))}else ZG&&(0,m.W)(a,d),(0,m.Bg)(e,"flip")});
(0,m.s)("yt.www.TagEditingMenu.toggleTagMenu",function(a,b){if(b){var c=(0,m.N)("tag-editing-menu");(0,m.xn)(c,"loading")?HG.getInstance().Wc():(HG.getInstance(),(0,m.wo)());c=(0,m.P)("yt-combobox-search-input",c);(0,m.w)((0,m.r)(c.focus,c),0)}});oF.prototype.autoCollapsePremiumYva=oF.prototype.sq;oF.prototype.collapse_ad=oF.prototype.Dq;oF.prototype.expand_ad=oF.prototype.Eq;oF.prototype.userCollapsePremiumYva=oF.prototype.xh;oF.prototype.userExpandPremiumYva=oF.prototype.Aq;
oF.prototype.userUnexpandPremiumYva=oF.prototype.Bq;(0,m.t)(QG,m.Ea);QG.prototype.enable=function(){QG.L.enable.call(this);(0,m.Fn)(m.dp);(0,m.Fn)(m.fw)};QG.prototype.disable=function(){QG.L.disable.call(this);(0,m.Hn)(m.dp);(0,m.Hn)(m.fw)};(0,m.Fa)(new QG);})(_yt_www);


}
/*
     FILE ARCHIVED ON 01:34:15 Sep 01, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:42:46 Dec 07, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 194.939 (2)
  exclusion.robots: 0.17 (2)
  exclusion.robots.policy: 0.15 (2)
  cdx.remote: 0.13 (2)
  esindex: 0.021 (2)
  LoadShardBlock: 129.513 (6)
  PetaboxLoader3.datanode: 118.755 (8)
  load_resource: 236.383 (2)
  PetaboxLoader3.resolve: 177.687 (2)
*/