var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

var _yt_www={};(function(m){var window=this;var oa;var na;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.l=function(a,b,c){a=a.split(".");c=c||m.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]?c=c[d]:c=c[d]={}:c[d]=b};m.p=function(a,b){for(var c=a.split("."),d=b||m.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.ea=function(){};m.fa=function(a){a.getInstance=function(){return a.uo?a.uo:a.uo=new a}};
m.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.q=function(a){return void 0!==a};m.ha=function(a){return"array"==(0,m.ga)(a)};m.ia=function(a){var b=(0,m.ga)(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.r=function(a){return"string"==typeof a};m.ja=function(a){return"number"==typeof a};m.ka=function(a){return"function"==(0,m.ga)(a)};m.la=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.ma=function(a){return a[na]||(a[na]=++oa)};
var qa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.s=function(a,b,c){m.s=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?qa:ra;return m.s.apply(null,arguments)};
m.t=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.sa=function(a,b){for(var c in b)a[c]=b[c]};m.v=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.gK=function(a,c,g){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};m.ta=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};m.ua=function(a){return(0,window.encodeURIComponent)(String(a))};
m.va=function(a,b){for(var c=0,d=(0,m.ta)(String(a)).split("."),e=(0,m.ta)(String(b)).split("."),g=Math.max(d.length,e.length),h=0;0==c&&h<g;h++){var k=d[h]||"",n=e[h]||"",u=RegExp("(\\d*)(\\D*)","g"),y=RegExp("(\\d*)(\\D*)","g");do{var F=u.exec(k)||["","",""],N=y.exec(n)||["","",""];if(0==F[0].length&&0==N[0].length)break;c=wa(0==F[1].length?0:(0,window.parseInt)(F[1],10),0==N[1].length?0:(0,window.parseInt)(N[1],10))||wa(0==F[2].length,0==N[2].length)||wa(F[2],N[2])}while(0==c)}return c};
var wa=function(a,b){return a<b?-1:a>b?1:0};var xa=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var ya=function(a){var b=(0,m.r)(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.za=function(a,b,c){b=(0,m.Aa)(a,b,c);return 0>b?null:(0,m.r)(a)?a.charAt(b):a[b]};
m.Aa=function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return g;return-1};m.Ba=function(a,b){return 0<=(0,m.Ca)(a,b)};m.Da=function(a,b){var c=(0,m.Ca)(a,b),d;(d=0<=c)&&(0,m.Ea)(a,c);return d};m.Ea=function(a,b){m.Fa.splice.call(a,b,1)};m.Ga=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.Ha=function(a,b,c){return 2>=arguments.length?m.Fa.slice.call(a,b):m.Fa.slice.call(a,b,c)};m.Ia=function(){};
m.w=function(a,b){(0,m.Ja)(a,(0,m.t)(m.Ka,b))};m.Ja=function(a,b){a.Pd||(a.Pd=[]);a.Pd.push((0,m.s)(b,void 0))};m.Ka=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.La=function(){this.b=[];this.Nc={}};m.Ma=function(a){Na(m.Oa,arguments)};m.x=function(a,b){return a in m.Oa?m.Oa[a]:b};m.Pa=function(a){Na(m.Qa,arguments)};
m.z=function(a,b){if((0,m.ka)(a)&&(0,m.p)("ytsched.enableSetTimeout")){var c=(0,m.p)("yt.scheduler.instance.addJob");if(c)return c(a,0,b);(0,m.l)("ytsched.enableSetTimeout",!1,void 0)}(0,m.ka)(a)&&(a=(0,m.Ra)(a));return window.setTimeout(a,b)};m.A=function(a){(0,m.p)("ytsched.enableSetTimeout")?(0,m.p)("yt.scheduler.instance.cancelJob")(a):window.clearTimeout(a)};m.Ra=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw(0,m.Sa)(b),b;}}:a};
m.Sa=function(a,b){if(window&&window.yterr){var c=(0,m.p)("yt.www.errors.log");c?c(a,b):(c=(0,m.x)("ERRORS")||[],c.push(a),(0,m.Ma)("ERRORS",c))}};m.Ta=function(a){Na(m.Ua,arguments)};m.Va=function(a){return a in m.Ua};m.Wa=function(a,b,c){var d=b||{};if(a=a in m.Ua?m.Ua[a]:c)for(var e in d)a=a.replace(RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var Na=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
m.Xa=function(){return(0,m.p)("yt.scheduler.instance")&&!(0,m.p)("ytsched.enableSetTimeout")};m.Ya=function(a,b,c){void 0===c&&(c=window.NaN);var d=(0,m.p)("yt.scheduler.instance.addJob");if(d)return(0,window.isNaN)(c)&&(c=0),d(a,b,c);if((0,window.isNaN)(c))a();else return(0,m.z)(a,c||0)};m.Za=function(a,b){return(0,m.Ya)(a,0,b)};m.$a=function(a){return(0,m.Ya)(a,1,void 0)};
m.B=function(a,b,c){var d=ab();if(d){var e=d.subscribe(a,function(){if(!m.bb||m.bb!=e){var d=arguments,h=function(){cb[e]&&b.apply(c||window,d)};try{db[a]?h():(0,m.Xa)()?(0,m.Za)(h):(0,m.z)(h,0)}catch(k){(0,m.Sa)(k)}}},c);cb[e]=!0;eb[a]||(eb[a]=[]);eb[a].push(e);return e}return 0};m.fb=function(a){var b=ab();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.C)(a,function(a){b.unsubscribeByKey(a);delete cb[a]}))};
m.D=function(a,b){var c=ab();return c?c.publish.apply(c,arguments):!1};var gb=function(a,b){db[a]=!0;var c=ab();c&&c.publish.apply(c,arguments);db[a]=!1};var ab=function(){return(0,m.p)("yt.pubsub.instance_")};m.hb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.j=(0,m.Ra)(d||null);this.i=(0,m.Ra)(e||null);this.g=[]};
m.ib=function(a){a.name in jb&&kb(a.name);jb[a.name]={reqs:[],disable:(0,m.s)(a.disable,a)};(0,m.C)(a.deps,function(b){if(!(b in jb))throw Error("Module "+b+" required by "+a.name);jb[b].reqs.push(a.name)});(0,m.Xa)()?(0,m.$a)((0,m.s)(a.enable,a)):a.enable()};var kb=function(a){if(a in jb){var b=jb[a];(0,m.C)(b.reqs,function(a){kb(a)});try{b.disable()}catch(c){}delete jb[a]}};m.lb=function(a){return a&&"readyState"in a?a.readyState:0};
var mb=function(){if((0,m.x)("SCHEDULE_AJAX")&&window.XMLHttpRequest&&!nb){ob=(0,m.x)("SCHEDULER_BUFFER_LENGTH");var a=window.XMLHttpRequest;pb=a.prototype.abort;qb=a.prototype.open;nb=a.prototype.send;a.prototype.abort=rb;a.prototype.open=sb;a.prototype.send=tb}};var rb=function(){ub(!0);pb.call(this)};var sb=function(){this.url=arguments[1];qb.apply(this,arguments)};
var tb=function(){var a=this,b=arguments;a.url&&-1!=a.url.indexOf("spf=navigate")&&nb.apply(a,b);if("onloadend"in a)a.addEventListener("loadend",function(){4==(0,m.lb)(a)&&ub(!0)},!1);else{var c=a.onreadystatechange;a.onreadystatechange=function(){4==(0,m.lb)(a)&&ub(!0);c&&c.apply(this,arguments)}}vb.push(function(){nb.apply(a,b)});ub()};
var ub=function(a){a&&(wb=!1,(0,m.A)(xb));if(!wb&&vb.length){if(a=ob){a=ob;var b=(0,m.x)("PLAYER_REFERENCE"),c=(0,m.x)("ADS_DATA");a=!(b&&(!c||!c.show_instream)&&b.getVideoLoadedFraction&&b.getDuration&&b.getCurrentTime?b.getVideoLoadedFraction()*b.getDuration()-b.getCurrentTime()>a||0.5<b.getVideoLoadedFraction():1)}if(a)(0,m.A)(zb),zb=(0,m.z)(ub,100);else{wb=!0;a=vb.shift();try{a()}catch(d){ub(!0)}xb=(0,m.z)((0,m.t)(ub,!0),5E3)}}};m.Ab=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
m.Bb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.Cb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.Db=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.Eb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<Fb.length;g++)c=Fb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};m.Gb=function(a,b,c){a.dataset?a.dataset[(0,m.Hb)(b)]=c:a.setAttribute("data-"+b,c)};
m.E=function(a,b){return a.dataset?a.dataset[(0,m.Hb)(b)]:a.getAttribute("data-"+b)};m.Ib=function(a,b){return a.dataset?(0,m.Hb)(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b)};m.Hb=function(a){return Jb[a]||(Jb[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.Kb=function(a,b){var c=a.match(Lb);window.spf.scripts.load(a,b,c?c[1]:"")};
m.Mb=function(a){a&&((0,m.r)(a)?(0,m.Kb)(a):(0,m.ha)(a)?(0,m.C)(a,function(a){(0,m.Mb)(a)}):(0,m.Ab)(a,function(a,c){(0,m.Kb)(c,function(){(0,m.Mb)(a)})}))};m.Nb=function(a,b){a&&Ob(a,b)};var Ob=function(a,b){var c=new window.Image,d=""+Pb++;Qb[d]=c;c.onload=c.onerror=function(){b&&Qb[d]&&b();delete Qb[d]};c.src=a;c=eval("null")};m.Rb=function(a,b,c){Sb(c)[a]=b||(0,m.G)();b||Tb(a)};m.Ub=function(a){var b=Sb(void 0);return a in b};
var Vb=function(a,b,c){var d=Wb(c).span;c=Sb(c);"number"==typeof b?d[a]=b:b in c&&(d[a]=(0,m.G)()-c[b])};
m.Xb=function(a){var b=Sb(a),c=Wb(a).span,d=(0,m.Yb)(a),e=(0,m.p)("yt.timing.reportbuilder_");if(e){if(e=e.apply(null,[b,c,d,a]))Zb(e),(0,m.$b)(a)}else{var e={v:2,s:"youtube",action:(0,m.x)("TIMING_ACTION")},g=(0,m.x)("TIMING_INFO")||{},h;for(h in g)d[h]=g[h];h=d.srt;delete d.srt;var k;h||0===h||(k=m.ac.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=h;b.aft||(b.aft=b.pbs?b.pbs:b.vr&&b.cl&&b.cl>b.vr?b.cl:b.vr?b.vr:b.ol);b.vr&&b.gv&&
(c.vl=Math.round(b.vr-b.gv));h=b._start;if(!bc){k||(k=m.ac.timing||{});t:if(g=k,g.msFirstPaint)g=Math.max(0,g.msFirstPaint);else{var n=window.chrome;if(n&&(n=n.loadTimes,(0,m.ka)(n))){var n=n(),u=1E3*Math.min(n.requestTime||window.Infinity,n.startLoadTime||window.Infinity),u=window.Infinity===u?0:g.navigationStart-u,g=Math.max(0,Math.round(1E3*n.firstPaintTime+u)||0);break t}g=0}0<g&&g>h&&(b.fpt=g);g=k.redirectEnd-k.redirectStart;0<g&&(c.rtime_=g);g=k.domainLookupEnd-k.domainLookupStart;0<g&&(c.dns_=
g);g=k.connectEnd-k.connectStart;0<g&&(c.tcp_=g);g=k.connectEnd-k.secureConnectionStart;k.secureConnectionStart&&0<g&&(c.stcp_=g);g=k.responseStart-k.requestStart;0<g&&(c.req_=g);g=k.responseEnd-k.responseStart;0<g&&(c.rcv_=g);bc=!0}for(var y in d)"_"!=y.charAt(0)&&(e[y]=d[y]);d={};y=[];for(var F in b)"_"!=F.charAt(0)&&(g=Math.max(Math.round(b[F]-h),0),d[F]=g,y.push(F+"."+g));e.rt=y.join(",");b={};F=[];for(var N in c)"_"!=N.charAt(0)&&(b[N]=c[N],F.push(N+"."+c[N]));e.it=F.join(",");Zb(e);(c=(0,m.p)("ytdebug.logTiming"))&&
c(e,d,b);(0,m.$b)(a)}};var cc=function(a){var b=(0,m.x)("TIMING_ACTION"),c=!!(0,m.x)("TIMING_WFF"),d=Sb(a);b&&d._start&&(c&&d.vr?(0,m.Xb)(a):c||!d.ol&&!d.aft||(0,m.Xb)(a))};m.dc=function(a,b,c){c={v:2,s:"youtube",action:c?"watch7ad_html5":"watch7ad"};var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var g in b)"_"!=g.charAt(0)&&(c[g]=b[g]);a=(0,m.x)("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Zb(c)};
var Zb=function(a){var b="https:"==window.location.protocol?"https://web.archive.org/web/20140301001026/https://gg.google.com/csi":"https://web.archive.org/web/20140301001026/http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];(0,m.Nb)(b+"?"+c.substring(1))};var Sb=function(a){return Wb(a).tick};m.Yb=function(a){return Wb(a).info};var Wb=function(a){return(0,m.p)("ytcsi."+(a||"")+"data_")||(0,m.$b)(a)};m.$b=function(a){var b={tick:{},span:{},info:{}};(0,m.l)("ytcsi."+(a||"")+"data_",b,void 0);return b};m.ec=function(a,b,c){return Math.min(Math.max(a,b),c)};
m.fc=function(a,b){this.x=(0,m.q)(a)?a:0;this.y=(0,m.q)(b)?b:0};m.gc=function(){return m.da.navigator?m.da.navigator.userAgent:null};var hc=function(){return m.da.navigator};var ic=function(){var a=m.da.document;return a?a.documentMode:void 0};m.jc=function(a){return kc[a]||(kc[a]=0<=(0,m.va)(lc,a))};m.mc=function(a){return m.nc&&oc>=a};m.pc=function(a){a=a.className;return(0,m.r)(a)&&a.match(/\S+/g)||[]};m.qc=function(a,b){return(0,m.Ba)((0,m.pc)(a),b)};
m.H=function(a){return(0,m.r)(a)?window.document.getElementById(a):a};m.I=function(a,b){var c=b||window.document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):(0,m.rc)("*",a,b)};m.J=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=(0,m.rc)("*",a,b)[0];return d||null};
m.rc=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,g=0,h;h=c[g];g++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(g=e=0;h=c[g];g++)a=h.className,"function"==typeof a.split&&(0,m.Ba)(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.sc=function(a,b,c,d){function e(c){c&&b.appendChild((0,m.r)(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!(0,m.ia)(g)||(0,m.la)(g)&&0<g.nodeType?e(g):(0,m.C)(tc(g)?(0,m.Ga)(g):g,e)}};m.uc=function(a,b){(0,m.sc)((0,m.vc)(a),a,arguments,1)};m.wc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.xc=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};m.yc=function(a){return zc&&void 0!=a.children?a.children:(0,m.Ac)(a.childNodes,function(a){return 1==a.nodeType})};
var Bc=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};var Cc=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
m.Dc=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};m.vc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var tc=function(a){if(a&&"number"==typeof a.length){if((0,m.la)(a))return"function"==typeof a.item||"string"==typeof a.item;if((0,m.ka)(a))return"function"==typeof a.item}return!1};
m.Ec=function(a,b,c){if(!b&&!c)return null;var d=b?b.toUpperCase():null;return(0,m.Fc)(a,function(a){return(!d||a.nodeName==d)&&(!c||(0,m.qc)(a,c))},!0)};m.K=function(a,b){return(0,m.Ec)(a,null,b)};m.Fc=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};m.Gc=function(a){this.b=a||m.da.document||window.document};
m.Hc=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||(0,m.Db)(Ic);this.assets=a.assets||{};this.attrs=a.attrs||(0,m.Db)(Jc);this.params=a.params||(0,m.Db)(Kc);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded};m.Lc=function(a){a instanceof m.Hc||(a=new m.Hc(a));return a};
m.Mc=function(a){if(a.classList)return a.classList;a=a.className;return(0,m.r)(a)&&a.match(/\S+/g)||[]};m.L=function(a,b){return a.classList?a.classList.contains(b):(0,m.Ba)((0,m.Mc)(a),b)};m.M=function(a,b){a.classList?a.classList.add(b):(0,m.L)(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.O=function(a,b){a.classList?a.classList.remove(b):(0,m.L)(a,b)&&(a.className=(0,m.Ac)((0,m.Mc)(a),function(a){return a!=b}).join(" "))};m.P=function(a,b,c){c?(0,m.M)(a,b):(0,m.O)(a,b)};
m.Nc=function(a,b){var c=!(0,m.L)(a,b);(0,m.P)(a,b,c);return c};var Oc=function(){return m.Pc?"Webkit":m.Qc?"Moz":m.nc?"ms":m.Rc?"O":null};m.Sc=function(){return m.Pc?"-webkit":m.Qc?"-moz":m.nc?"-ms":m.Rc?"-o":null};m.Tc=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};m.Uc=function(a,b){return a&&b?b instanceof m.Tc?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
m.Vc=function(a,b){var c=xa(b);if(void 0===a.style[c]){var d=Oc()+ya(b);if(void 0!==a.style[d])return d}return c};m.Wc=function(a,b){var c=(0,m.vc)(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""};m.Xc=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.Yc=function(a,b){a.style.height=(0,m.Xc)(b,!0)};m.Zc=function(a,b){a.style.width=(0,m.Xc)(b,!0)};
m.$c=function(a,b){a.style.display=b?"":"none"};m.ad=function(a){this.b=a};m.bd=function(a){a=(a.b.cookie||"").split(m.cd);for(var b=[],c=[],d,e,g=0;e=a[g];g++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,Qu:c}};m.dd=function(a,b,c){m.ed.set(""+a,b,c,"/","youtube.com")};m.fd=function(a,b){return m.ed.get(""+a,b)};
m.gd=function(){var a=(0,m.fd)("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.hd[d]=c.toString())}};var id=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var jd=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.kd=function(a){a=void 0!==m.hd[a]?m.hd[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
m.ld=function(a,b){return!!(((0,m.kd)("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};m.md=function(){if(!(0,m.q)(nd))if(m.nc)nd=(0,m.jc)("10.0");else{var a=window.document.createElement("div"),b=(0,m.Sc)();a.innerHTML='<div style="'+(b?b+"-transition:opacity 1s linear;":"")+'transition:opacity 1s linear;">';a=a.firstChild;b=a.style[xa("transition")];nd=""!=("undefined"!==typeof b?b:a.style[(0,m.Vc)(a,"transition")]||"")}return nd};
m.od=function(a,b,c,d,e,g,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);g&&(k+="?"+g);h&&(k+="#"+h);return k};m.pd=function(a){if(qd){qd=!1;var b=m.da.location;if(b){var c=b.href;if(c&&(c=(0,m.rd)(c))&&c!=b.hostname)throw qd=!0,Error();}}return a.match(sd)};m.rd=function(a){return(a=(0,m.pd)(a)[3]||null)&&(0,window.decodeURIComponent)(a)};m.td=function(a){a=(0,m.pd)(a);return(0,m.od)(null,null,null,null,a[5],a[6],a[7])};
m.ud=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};m.vd=function(a,b,c){if((0,m.ha)(b))for(var d=0;d<b.length;d++)(0,m.vd)(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",(0,m.ua)(b))};var wd=function(a,b){for(var c in b)(0,m.vd)(c,b[c],a);return a};m.xd=function(a,b){return(0,m.ud)(wd([a],b))};m.yd=function(a){a=wd([],a);a[0]="";return a.join("")};
var zd=function(a){a=(0,m.Ad)(a);a=null===a?null:a.split(".").reverse();return(null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
var Bd=function(){this.i=this.g=this.b=0;this.j="";var a=(0,m.p)("window.navigator.plugins"),b=(0,m.p)("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,g=c.length;e<g;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==
a.charAt(0)||"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.j=b;b=a;this.b=b[0];this.g=b[1];this.i=b[2];if(0>=this.b){var h,k,n,u;if(m.Cd)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(y){h=null}else n=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),h=n.appendChild(u);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(F){k=""}n&&u&&n.removeChild(u);(h=k||
"")?(h=h.split(" ")[1].split(","),h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.b=h[0];this.g=h[1];this.i=h[2]}};var Dd=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.b>b[0]||a.b==b[0]&&a.g>b[1]||a.b==b[0]&&a.g==b[1]&&a.i>=b[2]};
var Ed=function(a){return-1<a.j.indexOf("Gnash")&&-1==a.j.indexOf("AVM2")||9==a.b&&1==a.g||9==a.b&&0==a.g&&1==a.i?!1:9<=a.b};var Fd=function(a){return m.Gd?!Dd(a,11,2):m.Hd?!Dd(a,11,3):!Ed(a)};
var Id=function(a,b,c){if((a=(0,m.H)(a))&&b&&c){c=(0,m.Lc)(c);var d=(0,m.Db)(c.attrs);d.tabindex=0;var e=(0,m.Db)(c.params);e.flashvars=(0,m.yd)(c.args);if(m.Cd){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var g in d)b.setAttribute(g,d[g]);for(g in e)d=window.document.createElement("param"),d.setAttribute("name",g),d.setAttribute("value",e[g]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(g in d)b.setAttribute(g,d[g]);for(g in e)b.setAttribute(g,e[g])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Jd=function(a,b){a=(0,m.H)(a);b=(0,m.Lc)(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Kd();Dd(c,b.minVersion)?(c=Ld(b,c),Id(a,c,b)):Md(a,b,c)};
var Nd=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=(0,m.Lc)(a);var d=!!b,e=(0,m.H)(a.attrs.id),g=e?e.parentNode:null;if(e&&g){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);zd(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Kd();if(Dd(h,a.minVersion)){var k=Ld(a,h),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=k||d)&&Id(g,k,a);Fd(h)&&Od()}else Md(g,a,h);c&&c()}else(0,m.z)(function(){Nd(a,
b,c)},50)}};var Md=function(a,b,c){0==c.b&&b.fallback?b.fallback():0==c.b&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+(0,m.Wa)("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="https://web.archive.org/web/20140301001026/http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Ld=function(a,b){return Ed(b)&&a.url||(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Dd(b,9,1,58)?!1:!0)&&a.urlV9As2||a.urlV8||a.url};
var Kd=function(){var a=Bd.getInstance(),b=m.gd.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Od=function(){var a=(0,m.H)("flash10-promo-div"),b=(0,m.ld)(m.gd.getInstance(),107);a&&!b&&m.Q.show(a)};m.Pd=function(a){var b=a.match(Qd);window.spf.styles.load(a,void 0,b?b[1]:"")};m.Rd=function(){var a=(0,m.p)("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),(0,m.l)("yt.player.utils.videoElement_",a,void 0));return a};
m.Sd=function(){if(2.2==m.Td)return!0;var a=(0,m.Rd)();try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};m.Ud=function(){};var Vd=function(a){if(a instanceof m.Ud)return a;if("function"==typeof a.nc)return a.nc(!1);if((0,m.ia)(a)){var b=0,c=new m.Ud;c.next=function(){for(;;){if(b>=a.length)throw m.Wd;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};
m.Xd=function(a,b,c){if((0,m.ia)(a))try{(0,m.C)(a,b,c)}catch(d){if(d!==m.Wd)throw d;}else{a=Vd(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.Wd)throw e;}}};var Yd=function(a){if((0,m.ia)(a))return(0,m.Ga)(a);a=Vd(a);var b=[];(0,m.Xd)(a,function(a){b.push(a)});return b};var Zd=function(){};m.$d=function(){};m.ae=function(a){this.b=a};m.be=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.b=a};
var ce=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.b=a};m.de=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.ee=function(a){return(0,m.fe)(new m.ge(void 0),a)};
m.ge=function(a){this.b=a};m.fe=function(a,b){var c=[];he(a,b,c);return c.join("")};
var he=function(a,b,c){switch(typeof b){case "string":ie(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if((0,m.ha)(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],he(a,a.b?a.b.call(b,String(g),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=
typeof e&&(c.push(d),ie(g,c),c.push(":"),he(a,a.b?a.b.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var ie=function(a,b){b.push('"',a.replace(je,function(a){if(a in ke)return ke[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ke[a]=e+b.toString(16)}),'"')};m.le=function(a){this.b=a};var me=function(a){this.b=a};var ne=function(a){this.data=a};
var oe=function(a){return!(0,m.q)(a)||a instanceof ne?a:new ne(a)};m.pe=function(a){a=a.data;if(!(0,m.q)(a))throw"Storage: Invalid value was encountered";return a};var qe=function(a){this.b=a};m.re=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.G)()||!!b&&b>(0,m.G)()};m.se=function(a){this.b=a};m.te=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.G)()+1E3*d:0;if((d=d?m.ue:m.ve)&&window.JSON){(0,m.r)(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};
m.we=function(a){if(!m.ve&&!m.ue||!window.JSON)return null;var b;try{b=m.ve.get(a),b=(0,m.r)(b)?b:m.ue.get(a)}catch(c){return null}if(!(0,m.r)(b))return null;try{b=JSON.parse(b,void 0)}catch(d){}return b};m.xe=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?(0,m.ye)().volume:(0,m.ec)(a.volume,0,100);b.nonNormalized=a.nonNormalized;b.muted=void 0==a.muted?(0,m.ye)().muted:a.muted;(0,m.te)("yt-player-volume",b,2592E3)};
m.ye=function(){var a={volume:100,muted:!1,nonNormalized:100},b=(0,m.we)("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:(0,m.ec)(b.volume,0,100);a.nonNormalized=(0,window.isNaN)(b.nonNormalized)?a.volume:b.nonNormalized;a.muted=void 0==b.muted?!1:b.muted;return a};
var ze=function(a,b){this.Le=a;this.C=b;this.A=!1;this.g={};this.L=this.B=null;this.H=new m.La;(0,m.w)(this,this.H);this.j={};this.k=this.P=this.i=this.U=this.b=null;this.S=!1;this.R=this.F=null;this.M={};this.$=["onReady"];this.X=0;Ae(this);this.rj("onVolumeChange",(0,m.s)(this.ux,this));this.rj("onError",(0,m.s)(this.vx,this));this.rj("onTabOrderChange",(0,m.s)(this.tx,this))};
var Be=function(a,b){a.U=b;a.b=b.clone();a.i=a.b.attrs.id||a.i;"video-player"==a.i&&(a.i=a.C,a.b.attrs.id=a.C);a.Le.id==a.i&&(a.i=a.i+"-player",a.b.attrs.id=a.i);var c;(c=a.b.args.eurl)||(c=window.document.location.toString(),c=-1!=c.indexOf("/embed/")?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":c);a.b.args.eurl=c;a.b.args.enablejsapi="1";a.b.args.playerapiid=a.C;a.P||(a.P=Ce(a,a.b.args.jsapicallback||"onYouTubePlayerReady"));a.b.args.jsapicallback=null;(c=a.b.attrs.width)&&
(0,m.Zc)(a.Le,Number(c)||c);(c=a.b.attrs.height)&&(0,m.Yc)(a.Le,Number(c)||c);a.Le.style.overflow="hidden"};var De=function(a){a.b.loaded||(a.b.loaded=!0,"0"!=a.b.args.autoplay?a.g.loadVideoByPlayerVars(a.b.args):a.g.cueVideoByPlayerVars(a.b.args))};var Ee=function(a){if(!(0,m.q)(a.b.disable.flash)){var b=a.b.disable,c;c=Dd(Kd(),a.b.minVersion);b.flash=!c}return!a.b.disable.flash};
var Fe=function(a){var b=(0,m.H)(a.i);b&&b.stopVideo&&b.stopVideo();b&&b.logFallback&&b.logFallback();if(Ee(a)){var c=a.b;b&&b.getUpdatedConfigurationData&&(b=(0,m.Lc)(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";Be(a,c);Ge(a,"flash")}};
var Ge=function(a,b){if(!a.ka()){if(!b){var c;(c=!a.b.html5&&Ee(a))||((0,m.q)(a.b.disable.html5)||(c=(0,m.Sd)()&&(He()||a.b.assets.js),a.b.disable.html5=!c,c||(a.b.args.html5_unavailable="1")),c=!!a.b.disable.html5);b=c?Ee(a)?"flash":"unsupported":"html5"}("flash"==b?a.$F:"html5"==b?a.aG:a.bG).call(a)}};var He=function(){return(0,m.p)("yt.player.Application")};var Ie=function(a,b){var c=a[b];return function(){try{return c.apply(a,arguments)}catch(d){d.message+=" ("+b+")",(0,m.Sa)(d,"WARNING")}}};
var Ae=function(a){a.A=!1;if(a.L)for(var b in a.j)a.L(b,a.j[b]);a.B=null;a.L=null;for(var c in a.g)a.g[c]=null;a.g.addEventListener=(0,m.s)(a.rj,a);a.g.removeEventListener=(0,m.s)(a.cF,a);a.g.destroy=(0,m.s)(a.dispose,a);a.g.getPlayerType=(0,m.s)(a.bF,a);a.g.getCurrentVideoConfig=(0,m.s)(a.aF,a);a.g.loadNewVideoConfig=(0,m.s)(a.Go,a);a.g.isReady=(0,m.s)(a.dF,a)};
var Ce=function(a,b){var c=b;if("string"==typeof b){if(a.M[b])return a.M[b];c=function(){var a=(0,m.p)(b);a&&a.apply(m.da,arguments)};a.M[b]=c}return c?c:null};var Je=function(a,b){var c="ytPlayer"+b+a.C;a.j[b]=c;m.da[c]=function(c){(0,m.z)(function(){a.ka()||a.H.J(b,c)},0)};return c};var Ke=function(a){return(a=(0,m.H)(a.i))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Le=function(a){a.cancel();Ae(a);a.k=null;a.b.loaded=!1;var b=(0,m.H)(a.i);"html5"==Ke(a)?a.R=b:b&&b.destroy&&b.destroy();(0,m.wc)(a.Le)};m.Me=function(a,b){a=(0,m.H)(a);if(!a)return null;b=(0,m.Lc)(b);var c="player"+(0,m.ma)(a),d=Ne[c];if(d)return d.Go(b),d.g;d||(d=new ze(a,c),Ne[c]=d,(0,m.D)("player-added",d.g),(0,m.Ja)(d,(0,m.t)(Oe,d)));(0,m.z)(function(){d.Go(b)},0);return d.g};var Pe=function(){for(var a in Ne){var b=Ne[a];b&&b.cancel()}};
m.Qe=function(a){if(a=(0,m.H)(a))a="player"+(0,m.ma)(a),(a=Ne[a])&&a.dispose()};var Oe=function(a){Ne[a.getId()]=null};m.Re=function(a){a=(0,m.H)(a);if(!a)return null;a="player"+(0,m.ma)(a);return(a=Ne[a])?a.g:null};var Se=function(){(0,m.Rb)("ol");(0,m.D)("init");var a=(0,m.x)("PAGE_NAME");a&&(0,m.D)("init-"+a);cc()};var Te=function(){var a=(0,m.x)("PAGE_NAME");a&&gb("dispose-"+a);gb("dispose")};var Ue=function(){Se()};var Ve=function(){Te()};
var We=function(a,b,c){for(var d=window.document.getElementsByTagName("script"),e=!1,g=0,h=d.length;g<h;g++)if(0<d[g].src.indexOf("/debug-")){e=!0;break}e&&(d=Error(),d.message=a,d.fileName=b,d.lineNumber=c,(0,m.Sa)(d))};var Xe=function(){Ye=1;(0,m.$b)(void 0);Tb("mark_navigation_requested");Ze($e);gb("navigate")};var af=function(a,b){var c=1==Ye;Ye=2;c?(Ze(bf),cf()):Ze(df);b.swfcfg&&ef(b.swfcfg)};var ff=function(){};
var gf=function(a,b){var c=1==Ye;Ye=3;(0,m.Rb)("_start",b.timing.responseStart);var d=b.timing,d=Math.max(0,d.responseStart-d.navigationStart);(0,m.Yb)(void 0).srt=d;Vb("req",b.timing.responseStart-b.timing.fetchStart);c&&(Ze(hf),cf());b.swfcfg&&ef(b.swfcfg)};var jf=function(a){Ze(kf);if(a.timing){var b={spfProcessCss:"cl",spfProcessHtml:"hr",spfProcessJs:"jl"},c;for(c in b)a.timing[c]&&(0,m.Rb)(b[c],a.timing[c])}Se();Ye=0};var lf=function(a,b){(0,m.Sa)(b)};var mf=function(){nf()};var of=function(){};
var cf=function(){var a=(0,m.p)("ytbin.qoe.getInstance");a&&(a=a(),a.reset(),a.start());window.scroll(0,0);Te();for(var b in m.Oa)delete m.Oa[b];(b=(0,m.p)("yt.www.watch.player.dispose"))?b():(b=(0,m.H)("movie_player"))&&b.stopVideo&&b.stopVideo()};var ef=function(a){(0,m.Ub)("cfg")||(0,m.Rb)("cfg");(0,m.l)("ytplayer.config",null,void 0);Pe();if(a=a||null)(0,m.Me)("player-api",a),a=(0,m.Lc)(a),a.loaded=!0;(0,m.l)("ytplayer.config",a,void 0)};
var Ze=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.innerHTML="<dt><dd>",window.document.body.appendChild(b));(0,m.z)(function(){var c=a[0],d=a[1],e=a[2];b.className="";var g=b.style;g.transitionDuration=g.webkitTransitionDuration=c+"ms";g.width=d+"%";(0,m.A)(pf);pf=(0,m.z)(function(){b.className=e},c)},0)};
var nf=function(){var a=kf[0]+50;(0,m.A)(pf);pf=(0,m.z)(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};m.qf=function(a,b){var c=(0,m.rd)(a);if(c==(0,m.rd)(window.location.href)||!c&&0==a.lastIndexOf("/",0)){var c=(0,m.td)(a),d=c.indexOf("#");if(c=0>d?c:c.substr(0,d)){for(var e=d=0;e<c.length;++e)d=31*d+c.charCodeAt(e),d%=4294967296;c="s_tempdata-"+d;d=b?(0,m.yd)(b):"";(0,m.dd)(c,d,5)}}};
m.rf=function(a,b,c){c=c||"";window.location=(0,m.xd)(a,b||{})+c};m.sf=function(a){(window.ytspf||{}).enabled?window.spf.navigate(a):(0,m.rf)(a)};var tf=function(a,b,c){var d=(0,m.x)("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&(0,m.qf)(a,b);if(c)return!1;(0,m.sf)(a);return!0};
m.uf=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||m.da;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//web.archive.org/web/20140301001026/http://www.google.com/tools/feedback",g=d.GOOGLE_FEEDBACK_START;if(g)g.apply(d,arguments);else{var e=e+"/load.js?",h;for(h in a)g=a[h],null!=g&&!(0,m.la)(g)&&(e+=(0,window.encodeURIComponent)(h)+"="+(0,window.encodeURIComponent)(g)+"&");h=d.document;d=h.createElement("script");d.src=e;h.body.appendChild(d)}};
m.vf=function(){var a=window.GOOGLE_FEEDBACK_DESTROY_FUNCTION;a&&a()};var wf=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var xf=function(a){return(a=a.exec((0,m.gc)()))?a[1]:""};m.yf=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.C)(a.childNodes,function(a){b.appendChild((0,m.yf)(a))}):b.innerHTML=a.innerHTML;return b};
m.zf=function(a){if(a=a||window.event){for(var b in a)b in Af||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.Za=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName&&b}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;
this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Gp=a.pageX;this.Hp=a.pageY}};m.Bf=function(a,b,c,d){return(0,m.Cb)(m.Cf,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.R=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=(0,m.Bf)(a,b,c,d);if(e)return e;var e=++Df.count+"",g=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=g?function(d){d=new m.zf(d);if(!(0,m.Fc)(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.zf(b);b.currentTarget=a;return c.call(a,b)};h=(0,m.Ra)(h);m.Cf[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&
g?a.addEventListener("mouseover",h,d):"mouseleave"==b&&g?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.Ef=function(a,b,c){var d;switch(a){case "mouseover":case "mouseout":d=3;break;case "mouseenter":case "mouseleave":d=9}return(0,m.Fc)(c,function(a){return(0,m.L)(a,b)},!0,d)};
var Ff=function(a){var b="mouseover"==a.type&&"mouseenter"in m.Gf||"mouseout"==a.type&&"mouseleave"in m.Gf,c=a.type in m.Gf||b;if("HTML"!=a.target.tagName&&c){if(b){var b="mouseover"==a.type?"mouseenter":"mouseleave",c=m.Gf[b],d;for(d in c.Nc){var e=(0,m.Ef)(b,d,a.target);e&&!(0,m.Fc)(a.relatedTarget,function(a){return a==e},!0)&&c.J(d,e,b,a)}}if(b=m.Gf[a.type])for(d in b.Nc)(e=(0,m.Ef)(a.type,d,a.target))&&b.J(d,e,a.type,a)}};m.Hf=function(){this.b={}};
m.S=function(a,b){return"yt-uix"+(a.Ka?"-"+a.Ka:"")+(b?"-"+b:"")};m.If=function(){this.b={};this.j=[];this.g={}};m.Jf=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.kg=!1;this.qt=!0};var Kf=function(a){Kf[" "](a);return a};
m.Lf=function(a,b){m.Jf.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.Za=this.state=null;a&&this.init(a,b)};m.Mf=function(a){try{return!(!a||!a[m.Nf])}catch(b){return!1}};
var Of=function(a,b,c,d,e){this.Xf=a;this.proxy=null;this.src=b;this.type=c;this.g=!!d;this.i=e;this.key=++Pf;this.b=this.xk=!1};var Qf=function(a){a.b=!0;a.Xf=null;a.proxy=null;a.src=null;a.i=null};var Rf=function(a){this.src=a;this.b={};this.g=0};m.Sf=function(a,b){var c=b.type;if(!(c in a.b))return!1;var d=(0,m.Da)(a.b[c],b);d&&(Qf(b),0==a.b[c].length&&(delete a.b[c],a.g--));return d};m.Tf=function(a,b,c,d,e){a=a.b[b.toString()];b=-1;a&&(b=Uf(a,c,d,e));return-1<b?a[b]:null};
var Uf=function(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.b&&g.Xf==b&&g.g==!!c&&g.i==d)return e}return-1};m.Vf=function(a,b,c,d,e){if((0,m.ha)(b)){for(var g=0;g<b.length;g++)(0,m.Vf)(a,b[g],c,d,e);return null}c=(0,m.Wf)(c);return(0,m.Mf)(a)?a.listen(b,c,d,e):(0,m.Xf)(a,b,c,!1,d,e)};
m.Xf=function(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=!!e,k=(0,m.Yf)(a);k||(a[Zf]=k=new Rf(a));c=k.add(b,c,d,e,g);if(c.proxy)return c;d=$f();c.proxy=d;d.src=a;d.Xf=c;a.addEventListener?a.addEventListener(b,d,h):a.attachEvent(b in ag?ag[b]:ag[b]="on"+b,d);bg++;return c};var $f=function(){var a=cg,b=dg?function(c){return a.call(b.src,b.Xf,c)}:function(c){c=a.call(b.src,b.Xf,c);if(!c)return c};return b};
m.eg=function(a,b,c,d,e){if((0,m.ha)(b))for(var g=0;g<b.length;g++)(0,m.eg)(a,b[g],c,d,e);else c=(0,m.Wf)(c),(0,m.Mf)(a)?a.ab(b,c,d,e):a&&(a=(0,m.Yf)(a))&&(b=(0,m.Tf)(a,b,c,!!d,e))&&(0,m.fg)(b)};
m.fg=function(a){if((0,m.ja)(a)||!a||a.b)return!1;var b=a.src;if((0,m.Mf)(b))return(0,m.Sf)(b.ve,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.g):b.detachEvent&&b.detachEvent(c in ag?ag[c]:ag[c]="on"+c,d);bg--;(c=(0,m.Yf)(b))?((0,m.Sf)(c,a),0==c.g&&(c.src=null,b[Zf]=null)):Qf(a);return!0};var gg=function(a,b,c,d){var e=1;if(a=(0,m.Yf)(a))if(b=a.b[b])for(b=(0,m.Ga)(b),a=0;a<b.length;a++){var g=b[a];g&&g.g==c&&!g.b&&(e&=!1!==hg(g,d))}return Boolean(e)};
var hg=function(a,b){var c=a.Xf,d=a.i||a.src;a.xk&&(0,m.fg)(a);return c.call(d,b)};
var cg=function(a,b){if(a.b)return!0;if(!dg){var c=b||(0,m.p)("window.event"),d=new m.Lf(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){t:{var g=!1;if(0==c.keyCode)try{c.keyCode=-1;break t}catch(h){g=!0}if(g||void 0==c.returnValue)c.returnValue=!0}c=[];for(g=d.currentTarget;g;g=g.parentNode)c.push(g);for(var g=a.type,k=c.length-1;!d.kg&&0<=k;k--)d.currentTarget=c[k],e&=gg(c[k],g,!0,d);for(k=0;!d.kg&&k<c.length;k++)d.currentTarget=c[k],e&=gg(c[k],g,!1,d)}return e}return hg(a,new m.Lf(b,this))};
m.Yf=function(a){a=a[Zf];return a instanceof Rf?a:null};m.Wf=function(a){return(0,m.ka)(a)?a:a[ig]||(a[ig]=function(b){return a.handleEvent(b)})};m.jg=function(){this.ve=new Rf(this);this.X=this};m.kg=function(){this.b={};this.Ka="tdl";this.g=[]};m.lg=function(){this.b={};this.g={}};m.mg=function(a){if(m.ng&&m.og&&!(m.pg>=m.qg||a>=m.og.length)){var b=m.og[a];b&&b.href?(window.spf.prefetch(b.href,{onSuccess:(0,m.t)(rg,a),onError:(0,m.t)(sg,a)}),m.pg++):sg(a)}};
var rg=function(a,b,c){(0,m.D)("prefetch",b,c);m.tg=(0,m.z)((0,m.t)(m.mg,a+1),500)};var sg=function(a){m.tg=(0,m.z)((0,m.t)(m.mg,a+1),500)};m.ug=function(){if(-2==m.vg){m.vg=(0,window.parseInt)((0,m.fd)("ACTIVITY","-1"),10);(0,m.R)(window.document,"keypress",m.wg);(0,m.R)(window.document,"click",m.xg);var a=(0,m.x)("LIST_AUTO_PLAY_VALUE");a&&1<a||(0,m.yg)()}};m.wg=function(){(0,m.yg)()};m.xg=function(){(0,m.yg)()};
m.yg=function(){(0,m.ug)();var a=(0,m.G)();1E3>a-m.vg||(m.vg=a,(0,m.dd)("ACTIVITY",""+a))};m.zg=function(){return-1==m.vg||-2==m.vg?-1:Math.max((0,m.G)()-m.vg,0)};m.Ag=function(a,b){var c;if(b){if(!m.Bg||m.Cg)return;var d=m.Dg;d&&(c=(0,m.E)(d,"autoplay-clicktracking")||"")}d=m.Eg;(0,m.Fg)(d.href,a||"bf_next",c,b);(0,m.sf)(d.href)};
m.Gg=function(a,b){var c=b||"mr_meh";m.Hg||(0,m.Ig)();m.Jg?m.Kg=(0,m.z)(function(){(0,m.Gg)(a,c)},1E3):((0,m.Lg)(a),0==a?(0,m.Ag)(c,!0):m.Kg=(0,m.z)(function(){(0,m.Gg)(a-1,c)},1E3))};m.Mg=function(a){m.Ng&&(a.y>m.Og?(0,m.M)(m.Pg,"scrolled"):a.y<m.Og-50&&(0,m.O)(m.Pg,"scrolled"))};
m.Fg=function(a,b,c,d){var e=(0,m.x)("EVENT_ID");e&&(e={ei:e},b&&(e.feature=b),c&&(e.ved=c),(b=(0,m.x)("SHUFFLE_VALUE"))&&(e.shuffle=b),d&&(e.playnext=(0,m.x)("LIST_AUTO_PLAY_VALUE"),d=(0,m.zg)(),0<d&&(e.lact=d)),(0,m.qf)(a,e))};m.Lg=function(a){m.Pg&&(0,m.Gb)(m.Pg,"autoplay-countdown",a)};m.Ig=function(){if(!0!=m.Ng&&m.Bg){m.Ng=!0;(0,m.P)(m.Pg,"playlist-floating",!0);var a=window.document,b=a.body,a=a.documentElement;(0,m.Mg)(new m.fc(b.scrollLeft||a.scrollLeft,b.scrollTop||a.scrollTop))}};
m.Qg=function(){return(0,m.x)("PLAYER_REFERENCE")};m.Rg=function(a){var b=m.Sg,c=(0,m.x)("FEEDBACK_LOCALE_EXTRAS",{});a?(0,m.Eb)(b,a):(0,m.Eb)(b,c);return b};m.Tg=function(a){var b=(0,m.x)("SESSION_INDEX"),c=(0,m.x)("FEEDBACK_BUCKET_ID");a={abuseLink:"https://web.archive.org/web/20140301001026/https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005",locale:(0,m.x)("FEEDBACK_LOCALE_LANGUAGE"),productId:(a||"59")+""};b&&(a.authuser=b+"");c&&(a.bucket=c);return a};
m.Ug=function(a,b){try{var c=(0,m.Rg)(b);try{var d=(0,m.Qg)();d&&d.pauseVideo&&d.pauseVideo();var e=Bd.getInstance();c.flashVersion=e.getVersion().join(".");d&&(c.playback_id=d.getVideoData().cpn)}catch(g){}var h=(0,m.Tg)(a);(0,m.vf)();(0,m.uf)(h,c);return!1}catch(k){return!0}};m.Vg=function(){var a=(0,m.p)("ytplayer.config");a&&!a.loaded&&((0,m.Me)("player-api",a),a.loaded=!0)};var Wg=function(){m.hb.call(this,"www/base");this.b=0};
var Xg=function(a,b){var c;(c=(c=b.match(Yg))?c[1]+"/"+c[2]:"")&&kb(c)};var Zg=function(){(0,m.ib)(new Wg);var a=(0,m.p)("yt.actionQueue");if(a){var b=window.yt;(0,m.C)(a,function(a){b[a[0]].apply(b,a[1])});delete b.actionQueue}};var $g=function(){var a=ah.readyState;a&&"complete"!==a&&"loaded"!==a||(ah.removeEventListener?ah.removeEventListener("load",$g,!1):ah.detachEvent&&ah.detachEvent("onreadystatechange",$g),window.spf?Zg():(0,window.setTimeout)($g,0))};m.ba=[];m.bh=m.bh||{};m.da=this;
na="closure_uid_"+(1E9*Math.random()>>>0);oa=0;m.G=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.s.apply(null,c)}return(0,m.s)(this,a)};m.Fa=Array.prototype;m.Ca=m.Fa.indexOf?function(a,b,c){return m.Fa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if((0,m.r)(a))return(0,m.r)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};m.C=m.Fa.forEach?function(a,b,c){m.Fa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
m.Ac=m.Fa.filter?function(a,b,c){return m.Fa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,h=(0,m.r)(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[g++]=n)}return e};m.ch=m.Fa.map?function(a,b,c){return m.Fa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=(0,m.r)(a)?a.split(""):a,h=0;h<d;h++)h in g&&(e[h]=b.call(c,g[h],h,a));return e};
m.dh=m.Fa.reduce?function(a,b,c,d){d&&(b=(0,m.s)(b,d));return m.Fa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.C)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.eh=m.Fa.some?function(a,b,c){return m.Fa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return!0;return!1};
m.fh=m.Fa.every?function(a,b,c){return m.Fa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,m.r)(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&!b.call(c,e[g],g,a))return!1;return!0};m.Ia.prototype.Ee=!1;m.Ia.prototype.ka=function(){return this.Ee};m.Ia.prototype.dispose=function(){this.Ee||(this.Ee=!0,this.K())};m.Ia.prototype.K=function(){if(this.Pd)for(;this.Pd.length;)this.Pd.shift()()};(0,m.v)(m.La,m.Ia);m.f=m.La.prototype;m.f.Iu=1;m.f.Tk=0;m.f.N=function(a,b,c){var d=this.Nc[a];d||(d=this.Nc[a]=[]);var e=this.Iu;this.b[e]=a;this.b[e+1]=b;this.b[e+2]=c;this.Iu=e+3;d.push(e);return e};m.f.oa=function(a,b,c){if(a=this.Nc[a]){var d=this.b;if(a=(0,m.za)(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Gc(a)}return!1};
m.f.Gc=function(a){if(0!=this.Tk)return this.g||(this.g=[]),this.g.push(a),!1;var b=this.b[a];if(b){var c=this.Nc[b];c&&(0,m.Da)(c,a);delete this.b[a];delete this.b[a+1];delete this.b[a+2]}return!!b};m.f.J=function(a,b){var c=this.Nc[a];if(c){this.Tk++;for(var d=(0,m.Ha)(arguments,1),e=0,g=c.length;e<g;e++){var h=c[e];this.b[h+1].apply(this.b[h+2],d)}this.Tk--;if(this.g&&0==this.Tk)for(;c=this.g.pop();)this.Gc(c);return 0!=e}return!1};
m.f.clear=function(a){if(a){var b=this.Nc[a];b&&((0,m.C)(b,this.Gc,this),delete this.Nc[a])}else this.b.length=0,this.Nc={}};m.f.Ua=(0,m.aa)(13);m.f.K=function(){m.La.D.K.call(this);delete this.b;delete this.Nc;delete this.g};m.Oa=window.yt&&window.yt.config_||{};(0,m.l)("yt.config_",m.Oa,void 0);m.Qa=window.yt&&window.yt.tokens_||{};(0,m.l)("yt.tokens_",m.Qa,void 0);m.Ua=window.yt&&window.yt.msgs_||{};(0,m.l)("yt.msgs_",m.Ua,void 0);m.Cd="Microsoft Internet Explorer"==window.navigator.appName;m.gh=(0,m.p)("yt.scheduler.instance.cancelJob")||m.ea;var hh=(0,m.p)("yt.pubsub.instance_")||new m.La;m.La.prototype.subscribe=m.La.prototype.N;m.La.prototype.unsubscribeByKey=m.La.prototype.Gc;m.La.prototype.publish=m.La.prototype.J;m.La.prototype.clear=m.La.prototype.clear;(0,m.l)("yt.pubsub.instance_",hh,void 0);var cb=(0,m.p)("yt.pubsub.subscribedKeys_")||{};(0,m.l)("yt.pubsub.subscribedKeys_",cb,void 0);var eb=(0,m.p)("yt.pubsub.topicToKeys_")||{};(0,m.l)("yt.pubsub.topicToKeys_",eb,void 0);var db=(0,m.p)("yt.pubsub.isSynchronous_")||{};
(0,m.l)("yt.pubsub.isSynchronous_",db,void 0);m.bb=(0,m.p)("yt.pubsub.skipSubId_")||null;(0,m.l)("yt.pubsub.skipSubId_",m.bb,void 0);m.f=m.hb.prototype;m.f.enable=function(){(0,m.C)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.N("init-"+a,this.init,this),this.N("dispose-"+a,this.dispose,this),(0,m.x)("PAGE_NAME")==a&&this.init())},this)};m.f.init=function(){this.j&&this.j()};m.f.dispose=function(){this.i&&this.i()};m.f.disable=function(){this.dispose();this.clear()};m.f.N=function(a,b,c){a=(0,m.B)(a,b,c);this.g.push(a);return a};m.f.clear=function(){(0,m.fb)(this.g);this.g=[]};var jb=(0,m.p)("yt.modules.registry_")||{};(0,m.l)("yt.modules.registry_",jb,void 0);m.ih=null;"undefined"!=typeof window.XMLHttpRequest?m.ih=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(m.ih=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var nb,ob,pb,qb,wb,zb=0,xb=0,vb=[];var Fb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var Jb={};var Lb=/jsbin\/(?:[a-zA-Z0-9_-]+\/)*(?:debug-)?([a-zA-Z0-9_-]+?)(?:-vfl|.js)/,Yg=/^([a-z]+)_(\w+)_mod$/;var Qb={},Pb=0,jh=(0,m.p)("yt.net.ping.workerUrl_")||null;(0,m.l)("yt.net.ping.workerUrl_",jh,void 0);var Tb;var bc;m.ac=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};Tb=m.ac.mark?function(a){m.ac.mark(a)}:m.ea;m.f=m.fc.prototype;m.f.clone=function(){return new m.fc(this.x,this.y)};m.f.ceil=(0,m.aa)(58);m.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};m.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};m.f.scale=function(a,b){var c=(0,m.ja)(b)?b:a;this.x*=a;this.y*=c;return this};var wh;var uh;var th;var oh;var nh;var mh;var lh;var kh;oh=nh=mh=lh=kh=!1;var qh;if(qh=(0,m.gc)()){var rh=hc();kh=0==qh.lastIndexOf("Opera",0);lh=!kh&&(-1!=qh.indexOf("MSIE")||-1!=qh.indexOf("Trident"));nh=(mh=!kh&&-1!=qh.indexOf("WebKit"))&&-1!=qh.indexOf("Mobile");oh=!kh&&!mh&&!lh&&"Gecko"==rh.product}m.Rc=kh;m.nc=lh;m.Qc=oh;m.Pc=mh;m.sh=nh;th=hc();uh=th&&th.platform||"";m.Hd=-1!=uh.indexOf("Mac");m.Gd=-1!=uh.indexOf("Win");m.ph=-1!=uh.indexOf("Linux");m.vh=!!hc()&&-1!=(hc().appVersion||"").indexOf("X11");
t:{var xh="",yh;if(m.Rc&&m.da.opera)var zh=m.da.opera.version,xh="function"==typeof zh?zh():zh;else if(m.Qc?yh=/rv\:([^\);]+)(\)|;)/:m.nc?yh=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.Pc&&(yh=/WebKit\/(\S+)/),yh)var Ah=yh.exec((0,m.gc)()),xh=Ah?Ah[1]:"";if(m.nc){var Bh=ic();if(Bh>(0,window.parseFloat)(xh)){wh=String(Bh);break t}}wh=xh}var lc=wh,kc={},Ch=m.da.document,oc=Ch&&m.nc?ic()||("CSS1Compat"==Ch.compatMode?(0,window.parseInt)(lc,10):5):void 0;var zc;m.Dh=!m.nc||(0,m.mc)(9);zc=!m.Qc&&!m.nc||m.nc&&(0,m.mc)(9)||m.Qc&&(0,m.jc)("1.9.1");m.Eh=m.nc&&!(0,m.jc)("9");m.Fh=m.nc||m.Rc||m.Pc;m.f=m.Gc.prototype;m.f.G=(0,m.aa)(40);m.f.ud=(0,m.aa)(33);m.f.Q=(0,m.aa)(0);m.f.jc=(0,m.aa)(59);m.f.createElement=function(a){return this.b.createElement(a)};m.f.appendChild=function(a,b){a.appendChild(b)};m.f.append=m.uc;m.f.Wk=m.xc;m.f.getChildren=m.yc;m.f.contains=m.Dc;m.f.ZE=m.K;var Ic={enablejsapi:1},Jc={},Kc={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};m.Hc.prototype.clone=function(){var a=new m.Hc,b;for(b in this){var c=this[b];"object"==(0,m.ga)(c)?a[b]=(0,m.Db)(c):a[b]=c}return a};m.f=m.Tc.prototype;m.f.clone=function(){return new m.Tc(this.top,this.right,this.bottom,this.left)};m.f.contains=function(a){return(0,m.Uc)(this,a)};m.f.ceil=(0,m.aa)(56);m.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.f.scale=function(a,b){var c=(0,m.ja)(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};m.cd=/\s*;\s*/;m.f=m.ad.prototype;m.f.isEnabled=(0,m.aa)(27);m.f.set=function(a,b,c,d,e,g){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');(0,m.q)(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.G)()+1E3*c)).toUTCString();this.b.cookie=a+"="+b+e+d+c+g};
m.f.get=function(a,b){for(var c=a+"=",d=(this.b.cookie||"").split(m.cd),e=0,g;g=d[e];e++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};m.f.remove=function(a,b,c){var d=(0,m.q)(this.get(a));this.set(a,"",0,b,c);return d};m.f.Ec=(0,m.aa)(60);m.f.Bb=(0,m.aa)(47);m.f.isEmpty=(0,m.aa)(22);m.f.Ua=(0,m.aa)(12);m.f.mh=(0,m.aa)(39);m.f.clear=function(){for(var a=(0,m.bd)(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.ed=new m.ad(window.document);m.ed.g=3950;(0,m.fa)(m.gd);m.hd=(0,m.p)("yt.prefs.UserPrefs.prefs_")||{};(0,m.l)("yt.prefs.UserPrefs.prefs_",m.hd,void 0);m.f=m.gd.prototype;m.f.get=function(a,b){jd(a);id(a);var c=void 0!==m.hd[a]?m.hd[a].toString():null;return null!=c?c:b?b:""};m.f.set=function(a,b){jd(a);id(a);if(null==b)throw"ExpectedNotNull";m.hd[a]=b.toString()};m.f.remove=function(a){jd(a);id(a);delete m.hd[a]};m.f.save=function(){var a;a=[];for(var b in m.hd)a.push(b+"="+(0,window.escape)(m.hd[b]));a=a.join("&");(0,m.dd)("PREF",a,63072E3)};
m.f.clear=function(){m.hd={}};var nd;m.Q={xb:function(a,b){(a=(0,m.H)(a))&&a.style&&((0,m.$c)(a,b),(0,m.P)(a,"hid",!b))},nb:function(a){return(a=(0,m.H)(a))?!("none"==a.style.display||(0,m.L)(a,"hid")):!1},$w:function(a){if(a=(0,m.H)(a))m.Q.nb(a)?((0,m.$c)(a,!1),(0,m.M)(a,"hid")):((0,m.$c)(a,!0),(0,m.O)(a,"hid"))},setVisible:function(a,b){if(a=(0,m.H)(a))a.style.visibility=b?"visible":"hidden"},Zi:function(a){a=(0,m.H)(a);if(!a)return null;var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return new m.fc(b,
c)},show:function(a){(0,m.C)(arguments,function(a){m.Q.xb(a,!0)})},hide:function(a){(0,m.C)(arguments,function(a){m.Q.xb(a,!1)})},toggle:function(a){(0,m.C)(arguments,m.Q.$w)},hu:function(){return"rtl"==window.document.body.getAttribute("dir")},Rp:{},Ql:function(a){if(a in m.Q.Rp)return m.Q.Rp[a];var b;if((b=window.document.body.style)&&a in b)b=a;else{var c=Oc();c?(c=c.toLowerCase(),c+=ya(a),b=!(0,m.q)(b)||c in b?c:null):b=null}return m.Q.Rp[a]=b},PF:function(a){return null!=m.Q.Ql(a)},setProperty:function(a,
b,c){(a=(0,m.H)(a))&&a.style&&(b=m.Q.Ql(b))&&(a.style[b]=c)},MJ:function(a){if(!(0,m.md)())return null;var b=m.Q.Ql("transitionProperty"),b=(0,m.Wc)(a,b),c=m.Q.Ql("transitionDuration");a=(0,m.Wc)(a,c);if(!b||!a)return null;var d={},e=b.split(",");(0,m.C)(a.split(","),function(a,b){var c=e[b].trim();if(c){var n;n=-1<a.indexOf("ms")?(0,window.parseInt)(a,10):Math.round(1E3*(0,window.parseFloat)(a));d[c]=n}});return d}};var sd=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),qd=m.Pc;m.Ad=m.rd;(0,m.fa)(Bd);Bd.prototype.getVersion=function(){return[this.b,this.g,this.i]};var Qd=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Ph;var Gh,Hh,Ih,Jh,Kh,Lh,Mh;Mh=Lh=Kh=Jh=Ih=Hh=Gh=!1;var Nh=(0,m.gc)();Nh&&(-1!=Nh.indexOf("Firefox")?Gh=!0:-1!=Nh.indexOf("Camino")?Hh=!0:-1!=Nh.indexOf("iPhone")||-1!=Nh.indexOf("iPod")?Ih=!0:-1!=Nh.indexOf("iPad")?Jh=!0:-1!=Nh.indexOf("Chrome")?Lh=!0:-1!=Nh.indexOf("Android")?Kh=!0:-1!=Nh.indexOf("Safari")&&(Mh=!0));m.Oh=Gh;Ph=Hh;m.Qh=Ih;m.Rh=Jh;m.Sh=Kh;m.Th=Lh;m.Uh=Mh;var Vh=(0,m.gc)(),Vh=Vh.toLowerCase();if(-1!=Vh.indexOf("android")){var Wh=Vh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Wh)m.Td=Number(Wh[1]);else{var Xh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Yh=Vh.match("("+(0,m.Bb)(Xh).join("|")+")");m.Td=Yh?Xh[Yh[0]]:0}}else m.Td=void 0;m.Wd="StopIteration"in m.da?m.da.StopIteration:Error("StopIteration");m.Ud.prototype.next=function(){throw m.Wd;};m.Ud.prototype.nc=function(){return this};(0,m.v)(m.$d,Zd);m.$d.prototype.Ua=(0,m.aa)(11);m.$d.prototype.clear=function(){var a=Yd(this.nc(!0)),b=this;(0,m.C)(a,function(a){b.remove(a)})};(0,m.v)(m.ae,m.$d);m.f=m.ae.prototype;m.f.isAvailable=function(){if(!this.b)return!1;try{return this.b.setItem("__sak","1"),this.b.removeItem("__sak"),!0}catch(a){return!1}};m.f.set=function(a,b){try{this.b.setItem(a,b)}catch(c){if(0==this.b.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.f.get=function(a){a=this.b.getItem(a);if(!(0,m.r)(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.f.remove=function(a){this.b.removeItem(a)};
m.f.Ua=(0,m.aa)(10);m.f.nc=function(a){var b=0,c=this.b,d=new m.Ud;d.next=function(){if(b>=c.length)throw m.Wd;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!(0,m.r)(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.f.clear=function(){this.b.clear()};m.f.key=function(a){return this.b.key(a)};(0,m.v)(m.be,m.ae);(0,m.v)(ce,m.ae);var ke={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},je=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.le.prototype.set=function(a,b){(0,m.q)(b)?this.b.set(a,(0,m.ee)(b)):this.b.remove(a)};m.le.prototype.get=function(a){var b;try{b=this.b.get(a)}catch(c){return}if(null!==b)try{return(0,m.de)(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.le.prototype.remove=function(a){this.b.remove(a)};(0,m.v)(me,m.le);me.prototype.set=function(a,b){me.D.set.call(this,a,oe(b))};me.prototype.dh=function(a){a=me.D.get.call(this,a);if(!(0,m.q)(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};me.prototype.get=function(a){return(a=this.dh(a))?(0,m.pe)(a):void 0};(0,m.v)(qe,me);qe.prototype.set=function(a,b,c){if(b=oe(b)){if(c){if(c<(0,m.G)()){qe.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.G)()}qe.D.set.call(this,a,b)};qe.prototype.dh=function(a,b){var c=qe.D.dh.call(this,a);if(c)if(!b&&(0,m.re)(c))qe.prototype.remove.call(this,a);else return c};(0,m.v)(m.se,qe);m.se.prototype.g=(0,m.aa)(19);var $h;var Zh;Zh=new m.be;m.ue=Zh.isAvailable()?new m.se(Zh):null;$h=new ce;m.ve=$h.isAvailable()?new m.se($h):null;(0,m.v)(ze,m.Ia);m.f=ze.prototype;m.f.getId=function(){return this.C};m.f.Go=function(a,b){this.ka()||(Be(this,a),Ge(this,b),this.A&&De(this))};m.f.aF=function(){return this.U};m.f.aG=function(){if(!this.S){var a=this.b.clone();"html5"==Ke(this)?(this.k="html5",this.A||this.zg(!0)):(Le(this),this.k="html5",this.R?(this.Le.appendChild(this.R),this.zg()):(this.b.loaded=!0,this.F=(0,m.s)(function(){new (He())(this.Le,a);this.zg()},this),this.S=!0,He()?this.F():((0,m.Kb)(this.b.assets.js,this.F),(0,m.Pd)(this.b.assets.css))))}};
m.f.$F=function(){var a=this.b.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Ke(this)?(this.k="flash",this.A||Nd(a,!1,(0,m.s)(this.zg,this))):(Le(this),this.k="flash",this.b.loaded=!0,(0,m.Jd)(this.Le,a),this.zg())};
m.f.zg=function(a){var b=(0,m.H)(this.i),c=!1;try{b&&b.getApiInterface&&b.getApiInterface()&&(c=!0)}catch(d){}if(c)if(this.S=!1,a&&b.isNotServable&&b.isNotServable())Fe(this);else{Ae(this);this.A=!0;a=(0,m.H)(this.i);a.addEventListener&&(this.B=Ie(a,"addEventListener"));a.removeEventListener&&(this.L=Ie(a,"removeEventListener"));b=a.getApiInterface();b=b.concat(a.getInternalApiInterface());for(c=0;c<b.length;c++){var e=b[c];this.g[e]||(this.g[e]=Ie(a,e))}for(var g in this.j)this.B(g,this.j[g]);De(this);
this.P&&this.P(this.g);this.H.J("onReady",this.g)}else this.X=(0,m.z)((0,m.s)(this.zg,this),50)};m.f.dF=function(){return this.A};m.f.rj=function(a,b){if(!this.ka()){var c=Ce(this,b);if(c){if(!(0,m.Ba)(this.$,a)&&!this.j[a]){var d=Je(this,a);this.B&&this.B(a,d)}this.H.N(a,c);"onReady"==a&&this.A&&(0,m.z)((0,m.t)(c,this.g),0)}}};m.f.cF=function(a,b){if(!this.ka()){var c=Ce(this,b);c&&this.H.oa(a,c)}};
m.f.tx=function(a){a=a?Cc:Bc;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.f.ux=function(a){(0,m.xe)(a)};m.f.vx=function(a){5==a&&Fe(this)};
m.f.bG=function(){Le(this);this.k="unsupported";var a=(0,m.Wa)("PLAYER_FALLBACK",void 0,'The Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="https://web.archive.org/web/20140301001026/http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>'),b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a=(0,m.Wa)("QUICKTIME_FALLBACK",void 0,'The Adobe Flash Player or QuickTime is required for video playback. <br> <a href="https://web.archive.org/web/20140301001026/http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="https://web.archive.org/web/20140301001026/http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>'));
b=(0,m.H)("player-unavailable");(0,m.H)("unavailable-submessage")&&b&&((0,m.H)("unavailable-submessage").innerHTML=a,(a=(0,m.J)("icon",b))&&(0,m.Ib)(a,"icon")&&(a.src=(0,m.E)(a,"icon")),(0,m.O)(b,"hid"),(0,m.M)((0,m.H)("player"),"off-screen-trigger"))};m.f.bF=function(){return this.k||Ke(this)};m.f.cancel=function(){window.spf.scripts.ignore(this.b.assets.js,this.F);(0,m.A)(this.X)};
m.f.K=function(){Le(this);this.M=null;for(var a in this.j)m.da[this.j[a]]=null;this.g=null;this.b&&(this.U=this.b=this.b.fallback=null);ze.D.K.call(this)};var Ne={};var Ye,pf,$e=[900,60,"waiting"],hf=[500,99,"waiting"],bf=[300,60,"waiting"],df=[400,99,"waiting"],kf=[300,101,"done"];var ai=!1,bi="";
if(window.navigator.plugins&&window.navigator.plugins.length){var ci=window.navigator.plugins["Shockwave Flash"];ci&&(ai=!0,ci.description&&(bi=wf(ci.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(ai=!0,bi="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var di=window.navigator.mimeTypes["application/x-shockwave-flash"];(ai=di&&di.enabledPlugin)&&(bi=wf(di.enabledPlugin.description))}else try{var ei=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),ai=
!0,bi=wf(ei.GetVariable("$version"))}catch(aaa){try{ei=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),ai=!0,bi="6.0.21"}catch(baa){try{ei=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),ai=!0,bi=wf(ei.GetVariable("$version"))}catch(caa){}}}m.fi=bi;m.gi=function(){if(m.Oh)return xf(/Firefox\/([0-9.]+)/);if(m.nc||m.Rc)return lc;if(m.Th)return xf(/Chrome\/([0-9.]+)/);if(m.Uh)return xf(/Version\/([0-9.]+)/);if(m.Qh||m.Rh){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec((0,m.gc)()))return a[1]+"."+a[2]}else{if(m.Sh)return(a=xf(/Android\s+([0-9.]+)/))?a:xf(/Version\/([0-9.]+)/);if(Ph)return xf(/Camino\/([0-9.]+)/)}return""}();m.hi=(0,m.p)("yt.dom.getNextId_");if(!m.hi){m.hi=function(){return++ii};(0,m.l)("yt.dom.getNextId_",m.hi,void 0);var ii=0};m.f=m.zf.prototype;m.f.Za=null;m.f.type="";m.f.target=null;m.f.relatedTarget=null;m.f.currentTarget=null;m.f.data=null;m.f.source=null;m.f.state=null;m.f.keyCode=0;m.f.charCode=0;m.f.altKey=!1;m.f.ctrlKey=!1;m.f.shiftKey=!1;m.f.clientX=0;m.f.clientY=0;m.f.wheelDeltaX=0;m.f.wheelDeltaY=0;m.f.rotation=0;m.f.scale=1;m.f.touches=null;m.f.changedTouches=null;m.f.preventDefault=function(){this.Za.returnValue=!1;this.Za.preventDefault&&this.Za.preventDefault()};m.f.stopPropagation=(0,m.aa)(36);
m.f.stopImmediatePropagation=(0,m.aa)(3);var Af={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.Cf=(0,m.p)("yt.events.listeners_")||{};(0,m.l)("yt.events.listeners_",m.Cf,void 0);var Df=(0,m.p)("yt.events.counter_")||{count:0};(0,m.l)("yt.events.counter_",Df,void 0);var ji;m.Gf={};ji="ontouchstart"in window.document;(0,m.R)(window.document,"blur",Ff,!0);(0,m.R)(window.document,"change",Ff,!0);(0,m.R)(window.document,"click",Ff);(0,m.R)(window.document,"focus",Ff,!0);(0,m.R)(window.document,"mouseover",Ff);(0,m.R)(window.document,"mouseout",Ff);(0,m.R)(window.document,"mousedown",Ff);(0,m.R)(window.document,"keydown",Ff);(0,m.R)(window.document,"keyup",Ff);(0,m.R)(window.document,"keypress",Ff);(0,m.R)(window.document,"cut",Ff);
(0,m.R)(window.document,"paste",Ff);ji&&((0,m.R)(window.document,"touchstart",Ff),(0,m.R)(window.document,"touchend",Ff),(0,m.R)(window.document,"touchcancel",Ff));m.ki=window.yt&&window.yt.uix&&window.yt.uix.widgets_||{};(0,m.l)("yt.uix.widgets_",m.ki,void 0);m.Hf.prototype.i=(0,m.aa)(18);m.Hf.prototype.Z=function(a,b){return(0,m.E)(a,b)};m.Hf.prototype.removeData=(0,m.aa)(24);m.Hf.prototype.Da=(0,m.aa)(7);(0,m.v)(m.If,m.Hf);(0,m.fa)(m.If);m.f=m.If.prototype;m.f.Ka="button";m.f.Te=null;m.f.register=(0,m.aa)(43);m.f.unregister=(0,m.aa)(52);m.f.hp=(0,m.aa)(15);m.f.gp=(0,m.aa)(54);m.f.Bw=(0,m.aa)(38);m.f.ip=(0,m.aa)(1);m.f.Tw=(0,m.aa)(9);m.f.Uw=(0,m.aa)(16);m.f.qp=(0,m.aa)(4);m.f.Bo=(0,m.aa)(26);
m.f.toggle=function(a){if(this.Z(a,"button-toggle")){var b=(0,m.K)(a,(0,m.S)(this,"group"));if(b&&this.Z(b,"button-toggle-group")){var c=this.Z(b,"button-toggle-group"),b=(0,m.I)((0,m.S)(this),b),d=(0,m.S)(this,"toggled"),e=(0,m.L)(a,d);(0,m.C)(b,function(b){b!=a||"optional"==c&&e?(0,m.O)(b,d):(0,m.M)(a,d)})}else(0,m.Nc)(a,(0,m.S)(this,"toggled"))}};m.f.click=(0,m.aa)(20);m.Jf.prototype.K=function(){};m.Jf.prototype.dispose=function(){};m.Jf.prototype.stopPropagation=(0,m.aa)(35);m.Jf.prototype.preventDefault=function(){this.defaultPrevented=!0;this.qt=!1};Kf[" "]=m.ea;var mi;var dg;m.li=!m.nc||(0,m.mc)(9);dg=!m.nc||(0,m.mc)(9);mi=m.nc&&!(0,m.jc)("9");!m.Pc||(0,m.jc)("528");m.Qc&&(0,m.jc)("1.9b")||m.nc&&(0,m.jc)("8")||m.Rc&&(0,m.jc)("9.5")||m.Pc&&(0,m.jc)("528");m.Qc&&!(0,m.jc)("8")||m.nc&&(0,m.jc)("9");m.ni=m.Pc?"webkitTransitionEnd":m.Rc?"otransitionend":"transitionend";(0,m.v)(m.Lf,m.Jf);m.f=m.Lf.prototype;
m.f.init=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(m.Qc){var e;t:{try{Kf(d.nodeName);e=!0;break t}catch(g){}e=!1}e||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=m.Pc||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=m.Pc||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Za=a;a.defaultPrevented&&this.preventDefault()};m.f.stopPropagation=(0,m.aa)(34);
m.f.preventDefault=function(){m.Lf.D.preventDefault.call(this);var a=this.Za;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,mi)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};m.f.rw=(0,m.aa)(5);m.f.K=function(){};var Pf;m.Nf="closure_listenable_"+(1E6*Math.random()|0);Pf=0;Rf.prototype.add=function(a,b,c,d,e){var g=a.toString();a=this.b[g];a||(a=this.b[g]=[],this.g++);var h=Uf(a,b,d,e);-1<h?(b=a[h],c||(b.xk=!1)):(b=new Of(b,this.src,g,!!d,e),b.xk=c,a.push(b));return b};Rf.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.b))return!1;var e=this.b[a];b=Uf(e,b,c,d);return-1<b?(Qf(e[b]),(0,m.Ea)(e,b),0==e.length&&(delete this.b[a],this.g--),!0):!1};
Rf.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.b)if(!a||c==a){for(var d=this.b[c],e=0;e<d.length;e++)++b,Qf(d[e]);delete this.b[c];this.g--}return b};var Zf="closure_lm_"+(1E6*Math.random()|0),ag={},bg=0,ig="__closure_events_fn_"+(1E9*Math.random()>>>0);(0,m.v)(m.jg,m.Ia);m.jg.prototype[m.Nf]=!0;m.f=m.jg.prototype;m.f.wl=null;m.f.Bl=(0,m.aa)(45);m.f.addEventListener=function(a,b,c,d){(0,m.Vf)(this,a,b,c,d)};m.f.removeEventListener=function(a,b,c,d){(0,m.eg)(this,a,b,c,d)};m.f.K=function(){m.jg.D.K.call(this);this.removeAllListeners();this.wl=null};m.f.listen=function(a,b,c,d){return this.ve.add(String(a),b,!1,c,d)};m.f.ab=function(a,b,c,d){return this.ve.remove(String(a),b,c,d)};
m.f.removeAllListeners=function(a){return this.ve?this.ve.removeAll(a):0};(0,m.v)(m.kg,m.Hf);(0,m.fa)(m.kg);m.kg.prototype.register=(0,m.aa)(42);m.kg.prototype.unregister=(0,m.aa)(51);m.kg.prototype.j=(0,m.aa)(8);m.kg.prototype.k=(0,m.aa)(44);(0,m.v)(m.lg,m.Hf);(0,m.fa)(m.lg);m.f=m.lg.prototype;m.f.Ka="scroller";m.f.register=(0,m.aa)(41);m.f.unregister=(0,m.aa)(50);m.f.jp=(0,m.aa)(17);m.f.rl=(0,m.aa)(46);m.f.qv=(0,m.aa)(53);m.f.rv=(0,m.aa)(14);m.vg=-2;m.Hg=!1;m.Ng=!1;m.Jg=!1;m.Cg=!1;m.Og=null;m.Pg=null;m.Eg=null;m.Dg=null;m.Kg=null;m.Bg=!1;m.Sg={};var oi=(0,m.p)("yt.player.exports.navigate")||tf;(0,m.l)("yt.player.exports.navigate",oi,void 0);var pi=(0,m.p)("yt.player.embed")||m.Me;(0,m.l)("yt.player.embed",pi,void 0);var qi=(0,m.p)("yt.player.destroy")||m.Qe;(0,m.l)("yt.player.destroy",qi,void 0);var ri=(0,m.p)("yt.player.cancelAll")||Pe;(0,m.l)("yt.player.cancelAll",ri,void 0);var si=(0,m.p)("yt.player.getPlayerByElement")||m.Re;(0,m.l)("yt.player.getPlayerByElement",si,void 0);var ti=(0,m.p)("yt.player.exports.feedbackStart")||m.Ug;
(0,m.l)("yt.player.exports.feedbackStart",ti,void 0);window.yt=window.yt||{};(0,m.l)("yt.setConfig",m.Ma,void 0);(0,m.l)("yt.getConfig",m.x,void 0);(0,m.l)("yt.hasMsg",m.Va,void 0);(0,m.l)("yt.pubsub.publish",m.D,void 0);(0,m.l)("yt.pubsub.subscribe",m.B,void 0);(0,m.l)("yt.setMsg",m.Ta,void 0);(0,m.l)("yt.setGoogMsg",function(a){Na(m.Ua,arguments)},void 0);(0,m.l)("yt.setAjaxToken",m.Pa,void 0);
(0,m.l)("reportTimingMaps",function(a,b,c,d){if(a)for(var e in a)(0,m.Rb)(e,a[e],d);if(c)for(var g in c)Vb(g,c[g],d);if(b)for(var h in b)a=h,c=b[h],(0,m.Yb)(d)[a]=c;cc(d)},void 0);(0,m.l)("yt.timing.reportAdToVideo",m.dc,void 0);(0,m.v)(Wg,m.hb);
Wg.prototype.enable=function(){window.onload=Ue;window.onunload=Ve;window.onerror=We;var a=window.ytspf||{};a.enabled?(a.config=a.config||{},(0,m.sa)(a.config,{"navigate-requested-callback":Xe,"navigate-part-received-callback":af,"navigate-part-processed-callback":ff,"navigate-received-callback":gf,"navigate-processed-callback":jf,"navigate-error-callback":lf,"script-loading-callback":Xg}),a.enabled=window.spf.init(a.config),this.N("init",mf),this.N("dispose",of)):window.spf.dispose();this.N("init",
this.init,this);this.N("dispose",this.dispose,this)};
Wg.prototype.init=function(){(window.ytspf||{}).enabled||window.spf.dispose();mb();var a,b;!window.ytPageFrameLoaded&&(0,m.x)("PAGEFRAME_JS")&&(a=(0,m.x)("PAGEFRAME_JS"),b=function(){(0,m.p)("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0});var c={};c[(0,m.x)("JS_COMMON_MODULE")]=(0,m.x)("JS_PAGE_MODULES");var d=(0,m.x)("JS_DELAY_LOAD");0<d?((0,m.A)(this.b),this.b=(0,m.z)(function(){a&&(0,m.Kb)(a,b);(0,m.Mb)(c)},d)):(a&&(0,m.Kb)(a,b),(0,m.Mb)(c));(0,m.x)("PLAYER_PERSISTENCE_REFACTOR")&&
(0,m.Vg)()};Wg.prototype.dispose=function(){(0,m.A)(this.b);var a=(0,m.p)("ytbin.www.pageframe.cancelSetup");a&&a()};Wg.prototype.disable=function(){Wg.D.disable.call(this);window.onload=null;window.onunload=null;window.onerror=null};if(window.spf)Zg();else{var ah=(0,m.rc)("script","spf",void 0)[0];ah&&(ah.addEventListener?ah.addEventListener("load",$g,!1):ah.attachEvent&&ah.attachEvent("onreadystatechange",$g))};})(_yt_www);


}
/*
     FILE ARCHIVED ON 00:10:26 Mar 01, 2014 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:48:46 Dec 07, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 170.215
  exclusion.robots: 0.075
  exclusion.robots.policy: 0.064
  cdx.remote: 0.062
  esindex: 0.01
  LoadShardBlock: 107.356 (3)
  PetaboxLoader3.datanode: 65.513 (4)
  PetaboxLoader3.resolve: 455.189 (2)
  load_resource: 436.733
*/